In [ ]:
!pip install peft

In [ ]:
!pip install datasets==3.3.2

In [ ]:
#!pip install transformers==4.49.0

In [ ]:
!pip install trl

In [ ]:
!pip install -U Pillow

In [ ]:
!pip install numpy==1.26.0

In [ ]:
!pip install jinja2==3.1.0

In [1]:
# Warning control
import warnings
warnings.filterwarnings('ignore')

In [2]:
import torch
import pandas as pd
from datasets import load_dataset, Dataset
from transformers import TrainingArguments, AutoTokenizer, AutoModelForCausalLM
from trl import SFTTrainer, SFTConfig

In [3]:
import numpy
numpy.__version__

'1.26.0'

In [64]:
def generate_responses(model, tokenizer, user_message, system_message=None, max_new_tokens=100):
    messages = []
    if system_message:
        messages.append({'role':'system', 'content': system_message})
    messages.append({'role':'user', 'content': user_message})
    prompt = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
    enable_thinking=False
    )
    inputs = tokenizer(prompt, return_tensors='pt').to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id
        )
    input_len = inputs['input_ids'].shape[1]
    generated_ids = outputs[0][input_len:]
    response = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()
    return response

In [65]:
def test_model_with_questions(model, tokenizer, questions, system_message=None,
                              title='Model Output'):
    print(f"\n=== {title} ===")
    for i, question in enumerate(questions, 1):
        response = generate_responses(model, tokenizer, question, 
                                      system_message)
        print(f"\nModel Input {i}:\n{question}\nModel Output {i}:\n{response}\n")

In [6]:
def load_model_and_tokenizer(model_name, use_gpu = False):
    
    # Load base model and tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name)
    
    if use_gpu:
        model.to("cuda")
    
    if not tokenizer.chat_template:
        tokenizer.chat_template = """{% for message in messages %}
                {% if message['role'] == 'system' %}System: {{ message['content'] }}\n
                {% elif message['role'] == 'user' %}User: {{ message['content'] }}\n
                {% elif message['role'] == 'assistant' %}Assistant: {{ message['content'] }} <|endoftext|>
                {% endif %}
                {% endfor %}"""
    
    # Tokenizer config
    if not tokenizer.pad_token:
        tokenizer.pad_token = tokenizer.eos_token
        
    return model, tokenizer

In [7]:
def display_dataset(dataset):
    # Visualize the dataset 
    rows = []
    for i in range(3):
        example = dataset[i]
        user_msg = next(m['content'] for m in example['messages']
                        if m['role'] == 'user')
        assistant_msg = next(m['content'] for m in example['messages']
                             if m['role'] == 'assistant')
        rows.append({
            'User Prompt': user_msg,
            'Assistant Response': assistant_msg
        })
    
    # Display as table
    df = pd.DataFrame(rows)
    pd.set_option('display.max_colwidth', None)  # Avoid truncating long strings
    display(df)

### Load base model & test on simple questions

In [66]:
USE_GPU = True

questions = [
    "Give me an 1-sentence introduction of LLM.",
    "Calculate 1+1-1",
    "What's the difference between thread and process?"
]

In [9]:
model_id = 'Qwen/Qwen3-0.6B-Base'
model, tokenizer = load_model_and_tokenizer(model_id, USE_GPU)

test_model_with_questions(model, tokenizer, questions, 
                          title="Base Model (Before SFT) Output")

del model, tokenizer

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 310/310 [00:00<00:00, 8794.28it/s]

=== Base Model (Before SFT) Output ===

Model Input 1:
Give me an 1-sentence introduction of LLM.
Model Output 1:
⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ �


Model Input 2:
Calculate 1+1-1
Model Output 2:
⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ �


Model Input 3:
What's the difference between thread and process?
Model Output 3:
⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ ⚇ �

In [10]:
model_id = "HuggingFaceTB/SmolLM2-135M"
model, tokenizer = load_model_and_tokenizer(model_id, USE_GPU)

Loading weights: 100%|██████████| 272/272 [00:00<00:00, 8410.07it/s]

In [11]:
train_dataset = load_dataset("banghua/DL-SFT-Dataset")["train"]
train_dataset

Generating train split: 100%|██████████| 2961/2961 [00:00<00:00, 281592.01 examples/s]

Dataset({
    features: ['messages'],
    num_rows: 2961
})

In [12]:
train_dataset[1]

{'messages': [{'content': 'To pass three levels must be the plan.\nThen tackle Two, when that is done.\nOf 100 that start, at the end will be 20.\nFinQuiz is a website that helps you prepare.\nUse it to be stress-free, and not lose your hair.\nThen, take the exam with a smile on your face.\nBe confident that you will gain your place.\nSo make this the goal to which you aspire. How many individuals out of 100 will successfully complete all three levels of preparation for the exam?',
   'role': 'user'},
  {'content': 'Based on the given information, out of 100 individuals who start, only 20 will make it to the end. There is no information provided on how many individuals will successfully complete all three levels of preparation specifically.',
   'role': 'assistant'}]}

In [13]:
train_dataset[11]

{'messages': [{'content': 'What is a dish that this sauce can be used on, and do you have any recommendations for serving it?: In a small saucepan, heat packed brown sugar and butter until butter melts. Carefully add light-colored corn syrup and half-and-half or light cream. Cook, stirring constantly, over medium-low heat for 1 to 2 minutes or until sugar is dissolved and mixture is smooth.\nMy family loves this bread pudding and it is a hit where ever I take it.',
   'role': 'user'},
  {'content': 'This sauce would pair perfectly with bread pudding! I recommend serving the sauce warm on top of individual servings of bread pudding, along with a scoop of ice cream for a decadent dessert. You could also try using the sauce as a topping for pancakes or waffles, or as a dipping sauce for fresh fruit or cookies. Yum!',
   'role': 'assistant'}]}

In [14]:
if not USE_GPU:
    train_dataset=train_dataset.select(range(1000))
display_dataset(train_dataset)

,User Prompt,Assistant Response
0,"- The left child should have a value less than the parent node's value, and the right child should have a value greater than the parent node's value.","This statement is correct. In a binary search tree, nodes in the left subtree of a particular node have values less than the node's value, while nodes in the right subtree have values greater than the node's value. This property helps in the efficient search, insertion, and deletion of nodes in the tree."
1,"To pass three levels must be the plan.\nThen tackle Two, when that is done.\nOf 100 that start, at the end will be 20.\nFinQuiz is a website that helps you prepare.\nUse it to be stress-free, and not lose your hair.\nThen, take the exam with a smile on your face.\nBe confident that you will gain your place.\nSo make this the goal to which you aspire. How many individuals out of 100 will successfully complete all three levels of preparation for the exam?","Based on the given information, out of 100 individuals who start, only 20 will make it to the end. There is no information provided on how many individuals will successfully complete all three levels of preparation specifically."
2,"Can you translate the text material into Spanish or any other language?: He really is, you know.\nThings a hero should show.\nHe loves me more than a zillion things.\nHe loves me when I sing my jolly folktale rhymes.\nHe's good, not just good, in fact he's great!\nBut because he's my best mate!\nWOW !!! I love it!!!!","¿Puede traducir el texto a español o a cualquier otro idioma?: \nRealmente lo es, ya sabes.\nCosas que un héroe debería demostrar.\nMe quiere más que un millón de cosas.\nMe quiere cuando canto mis alegres rimas de cuentos populares.\nEs bueno, no solo bueno, ¡de hecho es genial!\n¡Pero porque es mi mejor amigo!\n¡WOW! ¡Me encanta!"

In [15]:
train_dataset

Dataset({
    features: ['messages'],
    num_rows: 2961
})

In [21]:
# SFTTrainer config 
sft_config = SFTConfig(
    learning_rate=8e-5, # Learning rate for training. 
    num_train_epochs=50, #  Set the number of epochs to train the model.
    per_device_train_batch_size=8, # Batch size for each device (e.g., GPU) during training. 
    gradient_accumulation_steps=8, # Number of steps before performing a backward/update pass to accumulate gradients.
    gradient_checkpointing=False, # Enable gradient checkpointing to reduce memory usage during training at the cost of slower training speed.
    logging_steps=100,  # Frequency of logging training progress (log every 2 steps).

)

In [22]:
sft_trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=train_dataset, 
    processing_class=tokenizer,
)

In [23]:
train_dataset

Dataset({
    features: ['messages'],
    num_rows: 2961
})

In [24]:
sft_trainer.__dict__

{'_tokenizer': GPT2Tokenizer(name_or_path='HuggingFaceTB/SmolLM2-135M', vocab_size=49152, model_max_length=8192, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, added_tokens_decoder={
 	0: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	1: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	2: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	3: AddedToken("<repo_name>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	4: AddedToken("<reponame>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	5: AddedToken("<file_sep>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	6: AddedToken("<filename>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	7: AddedToken("<gh_stars>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	8: AddedToken("<issue_start>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	9: AddedToken("<issue_comment>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	10: AddedToken("<issue_closed>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	11: AddedToken("<jupyter_start>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	12: AddedToken("<jupyter_text>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	13: AddedToken("<jupyter_code>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	14: AddedToken("<jupyter_output>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	15: AddedToken("<jupyter_script>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	16: AddedToken("<empty_output>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 }),
 '_is_vlm': False,
 'num_virtual_tokens': 0,
 'padding_free': False,
 'completion_only_loss': False,
 '_is_vision_dataset': False,
 'chat_template': None,
 'args': SFTConfig(output_dir='trainer_output', per_device_train_batch_size=8, num_train_epochs=50, max_steps=-1, learning_rate=8e-05, lr_scheduler_type=<SchedulerType.LINEAR: 'linear'>, lr_scheduler_kwargs=None, warmup_steps=0, optim=<OptimizerNames.ADAMW_TORCH: 'adamw_torch'>, optim_args=None, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, adam_epsilon=1e-08, optim_target_modules=None, gradient_accumulation_steps=8, average_tokens_across_devices=True, max_grad_norm=1.0, label_smoothing_factor=0.0, bf16=True, fp16=False, bf16_full_eval=False, fp16_full_eval=False, tf32=None, gradient_checkpointing=False, gradient_checkpointing_kwargs=None, torch_compile=False, torch_compile_backend=None, torch_compile_mode=None, use_liger_kernel=False, liger_kernel_config=None, use_cache=False, neftune_noise_alpha=None, torch_empty_cache_steps=None, auto_find_batch_size=False, logging_strategy=<IntervalStrategy.STEPS: 'steps'>, logging_steps=100, logging_first_step=False, log_on_each_node=True, logging_nan_inf_filter=True, include_num_input_tokens_seen='no', log_level='passive', log_level_replica='warning', disable_tqdm=False, report_to=[], run_name=None, project='huggingface', trackio_space_id=None, trackio_bucket_id=None, trackio_static_space_id=None, eval_strategy=<IntervalStrategy.NO: 'no'>, eval_steps=None, eval_delay=0, per_device_eval_batch_size=8, prediction_loss_only=False, eval_on_start=False, eval_do_concat_batches=True, eval_use_gather_object=False, eval_accumulation_steps=None, include_for_metrics=[], batch_eval_metrics=False, save_only_model=False, save_strategy=<SaveStrategy.STEPS: 'steps'>, save_steps=500, save_on_each_node=False, save_total_limit=None, enable_jit_checkpoint=False, push_to_hub=False, hub_token=None, hub_private_repo=None, hub_model_id=None, hub_strategy=<HubStrategy.EVERY_SAVE: 'every_save'>, hub_always_push=False, hub_revision=None, load_best_model_at_end=False, metric_for_best_model=None, greater_is_better=None, ignore_data_skip=False, restore_callback_states_from_checkpoint=False, full_determinism=False, seed=42, data_seed=None, use_cpu=False, accelerator_config=AcceleratorConfig(split_batches=False, dispatch_batches=None, even_batches=True, use_seedable_sampler=True, non_blocking=False, gradient_accumulation_kwargs=None, use_configured_state=False), parallelism_config=None, dataloader_drop_last=False, dataloader_num_workers=0, dataloader_pin_memory=True, dataloader_persistent_workers=False, dataloader_prefetch_factor=None, remove_unused_columns=True, label_names=None, train_sampling_strategy='random', length_column_name='length', ddp_find_unused_parameters=None, ddp_bucket_cap_mb=None, ddp_broadcast_buffers=None, ddp_static_graph=None, ddp_backend=None, ddp_timeout=1800, fsdp=[], fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False}, deepspeed=None, debug=[], skip_memory_metrics=True, do_train=False, do_eval=False, do_predict=False, resume_from_checkpoint=None, warmup_ratio=None, logging_dir=None, local_rank=-1, model_init_kwargs=None, chat_template_path=None, dataset_text_field='text', dataset_kwargs=None, dataset_num_proc=None, eos_token=None, max_length=1024, truncation_mode='keep_start', shuffle_dataset=False, packing=False, packing_strategy='bfd', padding_free=False, pad_to_multiple_of=None, eval_packing=None, completion_only_loss=None, assistant_only_loss=False, loss_type='nll', activation_offloading=False, pad_token=None),
 'deepspeed': None,
 'model': LlamaForCausalLM(
   (model): LlamaModel(
     (embed_tokens): Embedding(49152, 576)
     (layers): ModuleList(
       (0-29): 30 x LlamaDecoderLayer(
         (self_attn): LlamaAttention(
           (q_proj): Linear(in_features=576, out_features=576, bias=False)
           (k_proj): Linear(in_features=576, out_features=192, bias=False)
           (v_proj): Linear(in_features=576, out_features=192, bias=False)
           (o_proj): Linear(in_features=576, out_features=576, bias=False)
         )
         (mlp): LlamaMLP(
           (gate_proj): Linear(in_features=576, out_features=1536, bias=False)
           (up_proj): Linear(in_features=576, out_features=1536, bias=False)
           (down_proj): Linear(in_features=1536, out_features=576, bias=False)
           (act_fn): SiLUActivation()
         )
         (input_layernorm): LlamaRMSNorm((576,), eps=1e-05)
         (post_attention_layernorm): LlamaRMSNorm((576,), eps=1e-05)
       )
     )
     (norm): LlamaRMSNorm((576,), eps=1e-05)
     (rotary_emb): LlamaRotaryEmbedding()
   )
   (lm_head): Linear(in_features=576, out_features=49152, bias=False)
 ),
 'accelerator': <accelerate.accelerator.Accelerator at 0x76a994c14370>,
 'gather_function': functools.partial(<bound method Accelerator.gather_for_metrics of <accelerate.accelerator.Accelerator object at 0x76a994c14370>>, use_gather_object=False),
 'is_deepspeed_enabled': False,
 'is_fsdp_enabled': False,
 '_memory_tracker': <transformers.trainer_utils.TrainerMemoryTracker at 0x76a93cf73eb0>,
 'model_init': None,
 'is_model_parallel': False,
 'is_fsdp_xla_enabled': False,
 'place_model_on_device': True,
 'model_wrapped': LlamaForCausalLM(
   (model): LlamaModel(
     (embed_tokens): Embedding(49152, 576)
     (layers): ModuleList(
       (0-29): 30 x LlamaDecoderLayer(
         (self_attn): LlamaAttention(
           (q_proj): Linear(in_features=576, out_features=576, bias=False)
           (k_proj): Linear(in_features=576, out_features=192, bias=False)
           (v_proj): Linear(in_features=576, out_features=192, bias=False)
           (o_proj): Linear(in_features=576, out_features=576, bias=False)
         )
         (mlp): LlamaMLP(
           (gate_proj): Linear(in_features=576, out_features=1536, bias=False)
           (up_proj): Linear(in_features=576, out_features=1536, bias=False)
           (down_proj): Linear(in_features=1536, out_features=576, bias=False)
           (act_fn): SiLUActivation()
         )
         (input_layernorm): LlamaRMSNorm((576,), eps=1e-05)
         (post_attention_layernorm): LlamaRMSNorm((576,), eps=1e-05)
       )
     )
     (norm): LlamaRMSNorm((576,), eps=1e-05)
     (rotary_emb): LlamaRotaryEmbedding()
   )
   (lm_head): Linear(in_features=576, out_features=49152, bias=False)
 ),
 'model_accepts_loss_kwargs': True,
 'label_names': ['labels'],
 'can_return_loss': False,
 'label_smoother': None,
 'data_collator': DataCollatorForLanguageModeling(pad_token_id=0, max_length=1024, truncation_mode='keep_start', completion_only_loss=False, padding_free=False, pad_to_multiple_of=None, return_tensors='pt'),
 'train_dataset': Dataset({
     features: ['messages', 'input_ids'],
     num_rows: 2961
 }),
 'eval_dataset': None,
 'processing_class': GPT2Tokenizer(name_or_path='HuggingFaceTB/SmolLM2-135M', vocab_size=49152, model_max_length=8192, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, added_tokens_decoder={
 	0: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	1: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	2: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	3: AddedToken("<repo_name>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	4: AddedToken("<reponame>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	5: AddedToken("<file_sep>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	6: AddedToken("<filename>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	7: AddedToken("<gh_stars>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	8: AddedToken("<issue_start>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	9: AddedToken("<issue_comment>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	10: AddedToken("<issue_closed>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	11: AddedToken("<jupyter_start>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	12: AddedToken("<jupyter_text>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	13: AddedToken("<jupyter_code>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	14: AddedToken("<jupyter_output>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	15: AddedToken("<jupyter_script>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	16: AddedToken("<empty_output>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 }),
 'neftune_noise_alpha': None,
 'compute_loss_func': None,
 'compute_metrics': None,
 'preprocess_logits_for_metrics': None,
 'optimizer': None,
 'lr_scheduler': None,
 'optimizer_cls_and_kwargs': None,
 'callback_handler': <transformers.trainer_callback.CallbackHandler at 0x76a994c15c90>,
 'hub_model_id': None,
 'control': TrainerControl(should_training_stop=False, should_epoch_stop=False, should_save=False, should_evaluate=False, should_log=False),
 'state': TrainerState(epoch=0, global_step=0, max_steps=0, logging_steps=500, eval_steps=500, save_steps=500, train_batch_size=None, num_train_epochs=0, num_input_tokens_seen=0, total_flos=0, log_history=[], best_metric=None, best_global_step=None, best_model_checkpoint=None, is_local_process_zero=True, is_world_process_zero=True, is_hyper_param_search=False, trial_name=None, trial_params=None, stateful_callbacks={'TrainerControl': {'args': {'should_training_stop': False, 'should_epoch_stop': False, 'should_save': False, 'should_evaluate': False, 'should_log': False}, 'attributes': {}}}),
 'is_in_train': False,
 'hp_name': None,
 'hp_search_backend': None,
 'current_flos': 0,
 '_loggers_initialized': False,
 '_signature_columns': None,
 '_train_batch_size': 8,
 '_created_lr_scheduler': False,
 'is_fsdp_xla_v2_enabled': False,
 'is_fsdp_xla_v1_enabled': False,
 'maybe_activation_offload_context': <contextlib.nullcontext at 0x76ac19707d60>,
 'aux_loss_enabled': False,
 '_metrics': {'train': defaultdict(list, {}), 'eval': defaultdict(list, {})},
 '_total_train_tokens': 0}

In [25]:
sft_trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.28it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.14it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.18it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.40it/s]

TrainOutput(global_step=2350, training_loss=1.8341243565336187, metrics={'train_runtime': 2040.2483, 'train_samples_per_second': 72.565, 'train_steps_per_second': 1.152, 'total_flos': 2.291835618302285e+16, 'train_loss': 1.8341243565336187})

In [27]:
sft_trainer.model.save_pretrained('smol_sft')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.19it/s]

In [49]:
if not USE_GPU: # move model to CPU when GPU isn’t requested
    sft_trainer.model.to("cpu")
test_model_with_questions(sft_trainer.model, tokenizer, questions, 
                          title="Base Model (After SFT) Output")

=== Base Model (After SFT) Output ===

Model Input 1:
Give me an 1-sentence introduction of LLM.
Model Output 1:
Assistant: LLM is a program for those who want to study in a university and want to work in a research institute. It is a program that allows you to study in a university and work in a research institute. The program is offered by the University of Oxford and is offered for those who are interested in a research career. The program is offered for those who are interested in a research career but not in a university. The program is offered for those who are interested in a research career


Model Input 2:
Calculate 1+1-1
Model Output 2:
1. 1 + 1 = 2
2. 2 - 1 = 1
3. 1 - 1 = 0

Assistant: 1 + 1 - 1 = 0.


Model Input 3:
What's the difference between thread and process?
Model Output 3:
Assistant: Thread is a single-threaded process that runs in the background. It can be used to execute a single function or a set of functions. Process is a multithreaded process that can be started and stopped independently.

### SFT on Qwen/Qwen3-0.6B-Base

In [55]:
!pip install bitsandbytes==0.46.1

Defaulting to user installation because normal site-packages is not writeable
Collecting bitsandbytes==0.46.1
  Downloading bitsandbytes-0.46.1-py3-none-manylinux_2_24_x86_64.whl (72.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 MB 26.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: torch<3,>=2.2 in /usr/lib/python3/dist-packages (from bitsandbytes==0.46.1) (2.7.0)
Requirement already satisfied: numpy>=1.17 in ./.local/lib/python3.10/site-packages (from bitsandbytes==0.46.1) (1.26.0)
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.46.1

In [1]:
import copy
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline
from datasets import load_dataset
from transformers import DataCollatorForLanguageModeling
from torch.utils.data import DataLoader
from peft import  LoraConfig, get_peft_model
from transformers import TrainingArguments
from trl import SFTTrainer
from peft import PeftModel

/home/ubuntu/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
config_8bit = BitsAndBytesConfig(load_in_8bit=True)

In [3]:
model_name = 'Qwen/Qwen3-0.6B-Base'

In [4]:
model_8bit = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=config_8bit,
    device_map= "auto",
    trust_remote_code =True
    )
model_8bit

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 310/310 [00:00<00:00, 441.32it/s]

Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 1024)
    (layers): ModuleList(
      (0-27): 28 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear8bitLt(in_features=1024, out_features=2048, bias=False)
          (k_proj): Linear8bitLt(in_features=1024, out_features=1024, bias=False)
          (v_proj): Linear8bitLt(in_features=1024, out_features=1024, bias=False)
          (o_proj): Linear8bitLt(in_features=2048, out_features=1024, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear8bitLt(in_features=1024, out_features=3072, bias=False)
          (up_proj): Linear8bitLt(in_features=1024, out_features=3072, bias=False)
          (down_proj): Linear8bitLt(in_features=3072, out_features=1024, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((1024,), eps=1e-06)
    (rotary_emb): Qwen3RotaryEmbedding()
  )
  (lm_head): Linear(in_features=1024, out_features=151936, bias=False)
)

In [7]:
model_8bit_clone = copy.deepcopy(model_8bit)

lora_config = LoraConfig(
    r= 32,
    lora_alpha = 64,
    target_modules = ["q_proj","k_proj","v_proj","o_proj",
                      "gate_proj","up_proj","down_proj"],
    lora_dropout = 0.05,
    bias = "none",
    task_type = "CAUSAL_LM"
)

model_8bit_lora = get_peft_model(model_8bit_clone,lora_config)
model_8bit_lora.print_trainable_parameters()

trainable params: 20,185,088 || all params: 616,235,008 || trainable%: 3.2756

In [8]:
model_8bit_lora

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen3ForCausalLM(
      (model): Qwen3Model(
        (embed_tokens): Embedding(151936, 1024)
        (layers): ModuleList(
          (0-27): 28 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=1024, out_features=2048, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=2048, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=1024, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=1024, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=2048, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=1024, out_features=3072, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=3072, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=1024, out_features=3072, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=3072, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=3072, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3072, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
          )
        )
        (norm): Qwen3RMSNorm((1024,), eps=1e-06)
        (rotary_emb): Qwen3RotaryEmbedding()
      )
      (lm_head): Linear(in_features=1024, out_features=151936, bias=False)
    )
  )
)

In [9]:
tokenizer = AutoTokenizer.from_pretrained(model_name,padding_side="left",trust_remote_code= True)

In [10]:
train_dataset = load_dataset("banghua/DL-SFT-Dataset")["train"]
train_dataset

Dataset({
    features: ['messages'],
    num_rows: 2961
})

In [11]:
train_dataset[0]

{'messages': [{'content': "- The left child should have a value less than the parent node's value, and the right child should have a value greater than the parent node's value.",
   'role': 'user'},
  {'content': "This statement is correct. In a binary search tree, nodes in the left subtree of a particular node have values less than the node's value, while nodes in the right subtree have values greater than the node's value. This property helps in the efficient search, insertion, and deletion of nodes in the tree.",
   'role': 'assistant'}]}

'{%- if tools %}\n    {{- \'<|im_start|>system\\n\' }}\n    {%- if messages[0].role == \'system\' %}\n        {{- messages[0].content + \'\\n\\n\' }}\n    {%- endif %}\n    {{- "# Tools\\n\\nYou may call one or more functions to assist with the user query.\\n\\nYou are provided with function signatures within <tools></tools> XML tags:\\n<tools>" }}\n    {%- for tool in tools %}\n        {{- "\\n" }}\n        {{- tool | tojson }}\n    {%- endfor %}\n    {{- "\\n</tools>\\n\\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\\n<tool_call>\\n{\\"name\\": <function-name>, \\"arguments\\": <args-json-object>}\\n</tool_call><|im_end|>\\n" }}\n{%- else %}\n    {%- if messages[0].role == \'system\' %}\n        {{- \'<|im_start|>system\\n\' + messages[0].content + \'<|im_end|>\\n\' }}\n    {%- endif %}\n{%- endif %}\n{%- set ns = namespace(multi_step_tool=true, last_query_index=messages|length - 1) %}\n{%- for message in messages[::-1] %}\n    {%- set index = (messages|length - 1) - loop.index0 %}\n    {%- if ns.multi_step_tool and message.role == "user" and not(message.content.startswith(\'<tool_response>\') and message.content.endswith(\'</tool_response>\')) %}\n        {%- set ns.multi_step_tool = false %}\n        {%- set ns.last_query_index = index %}\n    {%- endif %}\n{%- endfor %}\n{%- for message in messages %}\n    {%- if (message.role == "user") or (message.role == "system" and not loop.first) %}\n        {{- \'<|im_start|>\' + message.role + \'\\n\' + message.content + \'<|im_end|>\' + \'\\n\' }}\n    {%- elif message.role == "assistant" %}\n        {%- set content = message.content %}\n        {%- set reasoning_content = \'\' %}\n        {%- if message.reasoning_content is defined and message.reasoning_content is not none %}\n            {%- set reasoning_content = message.reasoning_content %}\n        {%- else %}\n            {%- if \'</think>\' in message.content %}\n                {%- set content = message.content.split(\'</think>\')[-1].lstrip(\'\\n\') %}\n                {%- set reasoning_content = message.content.split(\'</think>\')[0].rstrip(\'\\n\').split(\'<think>\')[-1].lstrip(\'\\n\') %}\n            {%- endif %}\n        {%- endif %}\n        {%- if loop.index0 > ns.last_query_index %}\n            {%- if loop.last or (not loop.last and reasoning_content) %}\n                {{- \'<|im_start|>\' + message.role + \'\\n<think>\\n\' + reasoning_content.strip(\'\\n\') + \'\\n</think>\\n\\n\' + content.lstrip(\'\\n\') }}\n            {%- else %}\n                {{- \'<|im_start|>\' + message.role + \'\\n\' + content }}\n            {%- endif %}\n        {%- else %}\n            {{- \'<|im_start|>\' + message.role + \'\\n\' + content }}\n        {%- endif %}\n        {%- if message.tool_calls %}\n            {%- for tool_call in message.tool_calls %}\n                {%- if (loop.first and content) or (not loop.first) %}\n                    {{- \'\\n\' }}\n                {%- endif %}\n                {%- if tool_call.function %}\n                    {%- set tool_call = tool_call.function %}\n                {%- endif %}\n                {{- \'<tool_call>\\n{"name": "\' }}\n                {{- tool_call.name }}\n                {{- \'", "arguments": \' }}\n                {%- if tool_call.arguments is string %}\n                    {{- tool_call.arguments }}\n                {%- else %}\n                    {{- tool_call.arguments | tojson }}\n                {%- endif %}\n                {{- \'}\\n</tool_call>\' }}\n            {%- endfor %}\n        {%- endif %}\n        {{- \'<|im_end|>\\n\' }}\n    {%- elif message.role == "tool" %}\n        {%- if loop.first or (messages[loop.index0 - 1].role != "tool") %}\n            {{- \'<|im_start|>user\' }}\n        {%- endif %}\n        {{- \'\\n<tool_response>\\n\' }}\n        {{- message.content }}\n        {{- \'\\n</tool_response>\' }}\n        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}\n            {{- \'<|im_end|>\\n\' }}\n        {%- endif %}\n    {%- endif %}\n{%- endfor %}\n{%- if add_generation_prompt %}\n    {{- \'<|im_start|>assistant\\n\' }}\n    {%- if enable_thinking is defined and enable_thinking is false %}\n        {{- \'<think>\\n\\n</think>\\n\\n\' }}\n    {%- endif %}\n{%- endif %}'

In [15]:
def apply_chat_temp(example):
    new_text = tokenizer.apply_chat_template(example['messages'],tokenize=False)
    return {'text':new_text}

In [16]:
dataset = train_dataset.map(apply_chat_temp)
dataset

Map: 100%|██████████| 2961/2961 [00:00<00:00, 6810.73 examples/s]

Dataset({
    features: ['messages', 'text'],
    num_rows: 2961
})

In [17]:
dataset[0]

{'messages': [{'content': "- The left child should have a value less than the parent node's value, and the right child should have a value greater than the parent node's value.",
   'role': 'user'},
  {'content': "This statement is correct. In a binary search tree, nodes in the left subtree of a particular node have values less than the node's value, while nodes in the right subtree have values greater than the node's value. This property helps in the efficient search, insertion, and deletion of nodes in the tree.",
   'role': 'assistant'}],
 'text': "<|im_start|>user\n- The left child should have a value less than the parent node's value, and the right child should have a value greater than the parent node's value.<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\nThis statement is correct. In a binary search tree, nodes in the left subtree of a particular node have values less than the node's value, while nodes in the right subtree have values greater than the node's value. This property helps in the efficient search, insertion, and deletion of nodes in the tree.<|im_end|>\n"}

In [18]:
def tokenize_fn(example):
    return tokenizer(example['text'])

In [20]:
tokenized_dataset = dataset.map(tokenize_fn,batched=True,remove_columns=['messages', 'text'])
tokenized_dataset

Map: 100%|██████████| 2961/2961 [00:00<00:00, 11422.60 examples/s]

Dataset({
    features: ['input_ids', 'attention_mask'],
    num_rows: 2961
})

In [22]:
len(tokenized_dataset['input_ids'][1])

170

In [23]:
data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False,return_tensors="pt")

In [24]:
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token

'<|endoftext|>'

In [25]:
data_loader = DataLoader(
    tokenized_dataset,
    batch_size=2,
    collate_fn=data_collator
)

In [26]:
for step, batch in enumerate(data_loader):
    print(f"Batch {step}")
    print(batch.keys())
    print("input_ids.shape:", batch["input_ids"].shape)
    print("attention_mask.shape:", batch["attention_mask"].shape)
    print("labels.shape:", batch["labels"].shape)
    break

Batch 0
KeysView({'input_ids': tensor([[151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643,
         151643, 151643, 151643, 151643, 151643, 151643, 151643, 151643, 151644,
            872,    198,     12,    576,   2115,   1682,   1265,    614,    264,
            897,   2686,   1091,    279,   2681,   2436,    594,    897,     11,
            323,    279,   1290,   1682,   1265,    614,    264,    897,   7046,
           1091,    279,   2681,   2436,    594,    897,     13, 151645,    198,
         151644,  77091,    198, 151667,    271, 151668,    271,   1986,   5114,
            374,   4396,     13,    758,    264,   7868,   2711,   4916,     11,
           7798,    304,    279,   2115,  53464,    315,    264,   3953,   2436,
            614,   2750,   2686,   1091,    279,   2436,    594,    897,     11,
           1393,   7798,    304,    279,   1290,  53464,    614,   2750,   7046,
           1091,    279,   2436,    594,    897,     13,   1096,   3343,   8609,
            304,    279,  11050,   2711,     11,  35927,     11,    323,  36066,
            315,   7798,    304,    279,   4916,     13, 151645,    198],
        [151644,    872,    198,   1249,   1494,   2326,   5866,   1969,    387,
            279,   3119,    624,  12209,  21403,   9043,     11,    979,    429,
            374,   2814,    624,   2124,    220,     16,     15,     15,    429,
           1191,     11,    518,    279,    835,    686,    387,    220,     17,
             15,    624,   9134,  53886,    374,    264,   3910,    429,   8609,
            498,  10549,    624,  10253,    432,    311,    387,   8464,  12577,
             11,    323,    537,   9052,    697,   6869,    624,  12209,     11,
           1896,    279,   7006,    448,    264,  15289,    389,    697,   3579,
            624,   3430,  16506,    429,    498,    686,   8722,    697,   1992,
            624,   4416,   1281,    419,    279,   5795,    311,    892,    498,
          83511,     13,   2585,   1657,   7775,    700,    315,    220,     16,
             15,     15,    686,   7790,   4583,    678,   2326,   5866,    315,
          17975,    369,    279,   7006,     30, 151645,    198, 151644,  77091,
            198, 151667,    271, 151668,    271,  28715,    389,    279,   2661,
           1995,     11,    700,    315,    220,     16,     15,     15,   7775,
            879,   1191,     11,   1172,    220,     17,     15,    686,   1281,
            432,    311,    279,    835,     13,   2619,    374,    902,   1995,
           3897,    389,   1246,   1657,   7775,    686,   7790,   4583,    678,
           2326,   5866,    315,  17975,  11689,     13, 151645,    198]]), 'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1]]), 'labels': tensor([[  -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100, 151644,
            872,    198,     12,    576,   2115,   1682,   1265,    614,    264,
            897,   2686,   1091,    279,   2681,   2436,    594,    897,     11,
            323,    279,   1290,   1682,   1265,    614,    264,    897,   7046,
           1091,    279,   2681,   2436,    594,    897,     13, 151645,    198,
         151644,  77091,    198, 151667,    271, 151668,    271,   1986,   5114,
            374,   4396,     13,    758,    264,   7868,   2711,   4916,     11,
           7798,    304,    279,   2115,  53464,    315,    264,   3953,   2436,
            614,   2750,   2686,   1091,    279,   2436,    594,    897,     11,
           1393,   7798,    304,    279,   1290,  53464,    614,   2750,   7046,
           1091,    279,   2436,    594,    897,     13,   1096,   3343,   8609,
            304,    279,  11050,   2711,     11,  35927,     11,    323,  36066,
            315,   7798,    304,    279,   4916,     13, 151645,    198],
        [151644,    872,    198,   1249,   1494,   2326,   5866,   1969,    387,
            279,   3119,    624,  12209,  21403,   9043,     11,    979,    429,
            374,   2814,    624,   2124,    220,     16,     15,     15,    429,
           1191,     11,    518,    279,    835,    686,    387,    220,     17,
             15,    624,   9134,  53886,    374,    264,   3910,    429,   8609,
            498,  10549,    624,  10253,    432,    311,    387,   8464,  12577,
             11,    323,    537,   9052,    697,   6869,    624,  12209,     11,
           1896,    279,   7006,    448,    264,  15289,    389,    697,   3579,
            624,   3430,  16506,    429,    498,    686,   8722,    697,   1992,
            624,   4416,   1281,    419,    279,   5795,    311,    892,    498,
          83511,     13,   2585,   1657,   7775,    700,    315,    220,     16,
             15,     15,    686,   7790,   4583,    678,   2326,   5866,    315,
          17975,    369,    279,   7006,     30, 151645,    198, 151644,  77091,
            198, 151667,    271, 151668,    271,  28715,    389,    279,   2661,
           1995,     11,    700,    315,    220,     16,     15,     15,   7775,
            879,   1191,     11,   1172,    220,     17,     15,    686,   1281,
            432,    311,    279,    835,     13,   2619,    374,    902,   1995,
           3897,    389,   1246,   1657,   7775,    686,   7790,   4583,    678,
           2326,   5866,    315,  17975,  11689,     13, 151645,    198]])})
input_ids.shape: torch.Size([2, 170])
attention_mask.shape: torch.Size([2, 170])
labels.shape: torch.Size([2, 170])

In [30]:
training_args = TrainingArguments(
    output_dir = "./results",
    per_device_train_batch_size = 2,
    per_device_eval_batch_size = 2,
    eval_steps = 50,
    eval_strategy = "no",
    save_steps = 100,
    save_strategy = "steps",
    # num_train_epochs = 1,
    max_steps = 1000,
    learning_rate = 3e-5,
    weight_decay = 0.01,
    warmup_steps = 5,
    fp16 = False,
    bf16 = True,
    gradient_accumulation_steps = 4,
    optim = "adamw_torch",
    logging_steps = 50,
    report_to = "none"
)

In [31]:
training_args

TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=True,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_static_graph=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=50,
eval_strategy=no,
eval_use_gather_object=False,
fp16=False,
fp16_full_eval=False,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
full_determinism=False,
gradient_accumulation_steps=4,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_num_input_tokens_seen=no,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=3e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=None,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=50,
logging_strategy=steps,
lr_scheduler_kwargs=None,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=1000,
metric_for_best_model=None,
neftune_noise_alpha=None,
num_train_epochs=3.0,
optim=adamw_torch,
optim_args=None,
optim_target_modules=None,
output_dir=./results,
parallelism_config=None,
per_device_eval_batch_size=2,
per_device_train_batch_size=2,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_steps=100,
save_strategy=steps,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
trackio_bucket_id=None,
trackio_space_id=None,
trackio_static_space_id=None,
train_sampling_strategy=random,
use_cache=False,
use_cpu=False,
use_liger_kernel=False,
warmup_ratio=None,
warmup_steps=5,
weight_decay=0.01,
)

In [32]:
trainer = SFTTrainer(
    model =model_8bit_lora,
    train_dataset =tokenized_dataset,
    #eval_dataset = tokenized_dataset['test'],
    args = training_args,
    data_collator= data_collator,
    processing_class = tokenizer, # in tne new version
)

In [33]:
trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.
/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")

/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:185: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")

TrainOutput(global_step=1000, training_loss=1.9621775741577148, metrics={'train_runtime': 1113.5653, 'train_samples_per_second': 7.184, 'train_steps_per_second': 0.898, 'total_flos': 4211855845097472.0, 'train_loss': 1.9621775741577148})

In [34]:
trainer.model.save_pretrained('qwen_sft')

In [67]:
if not USE_GPU: # move model to CPU when GPU isn’t requested
    sft_trainer.model.to("cpu")
test_model_with_questions(trainer.model, tokenizer, questions, 
                          title="Base Model (After SFT) Output")

=== Base Model (After SFT) Output ===

Model Input 1:
Give me an 1-sentence introduction of LLM.
Model Output 1:
LLM is a large language model that can generate human-like text based on input prompts. It is used in various applications such as chatbots, content generation, and language translation. It is powered by deep learning algorithms and has been trained on vast amounts of text data. It can understand and generate natural language, making it a valuable tool for businesses and individuals alike. However, it is important to note that LLMs are not perfect and can sometimes produce inaccurate or inappropriate responses. Therefore, it is


Model Input 2:
Calculate 1+1-1
Model Output 2:
The answer is 1. The expression 1+1-1 simplifies to 2-1, which further simplifies to 1. Therefore, the result of the expression is 1.即时发生问题，请问您需要我继续计算吗？如果没有，请告诉我您需要我做什么。即时发生问题，请告诉我您需要我做什么。即时发生问题，请告诉我您需要我做什么。即时发生问题，请告诉我您需要我做什么。即时发生问题，请告诉我您需要我做什么。即时发生问题，请告诉我


Model Input 3:
What's the difference between thread and process?
Model Output 3:
Thread and process are both types of threads in a multi-threaded programming environment, but they have different characteristics and purposes.

A thread is a lightweight process that is created by the operating system to execute a specific task or function. Threads share the same memory space as the program they are running in, which means that changes made to one thread can be immediately reflected in the other threads. Threads are typically used to execute different tasks concurrently, such as reading from a file or performing calculations.

A process, on

In this notebook we used two different models to perform SFT. At the start both models were giving absurd answers.
Post SFT both SmolLM and Qwen/Qwen3-0.6B-Base gave quite sensible answers with Qwen/Qwen3-0.6B-Base appears to give better answer that SmolLM specifically in maths exercise. Plus we also used PEFT to train Qwen/Qwen3-0.6B-Base model.