In [1]:
try:
    import transformers
    import datasets
    from transformers import BitsAndBytesConfig
    from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model
except:
    print("all or at least one of the package not installed. Installing now. Please remember to restart kernel once done")
    !pip install transformers bitsandbytes accelerate datasets peft

In [2]:
from datasets import load_dataset
from transformers import AutoTokenizer
from transformers import AutoModelForCausalLM
import torch
from torch.utils.data import DataLoader, Dataset
from functools import partial
from peft import AutoPeftModelForCausalLM

In [3]:
#importing the "King" library :P
import sagemaker
import boto3
from sagemaker.inputs import TrainingInput

#sagemaker pytorch container estimator related libraries
from sagemaker.pytorch import PyTorch
from sagemaker.pytorch import PyTorchModel


from sagemaker.estimator import Estimator
from sagemaker.model import Model
from sagemaker.predictor import Predictor

#general utility imports
import os
import glob
import pandas as pd
import numpy as np
import random

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "json" in "MonitoringDatasetFormat" shadows an attribute in parent "Base"
  warnings.warn(

[03/06/25 08:11:30] INFO     Found credentials from IAM Role:                                   ]8;id=910595;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=197134;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py#1132\1132]8;;\
                             BaseNotebookInstanceEc2InstanceRole

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/ec2-user/.config/sagemaker/config.yaml

In [16]:
ds = load_dataset("Abirate/english_quotes")

README.md:   0%|          | 0.00/5.55k [00:00<?, ?B/s]

quotes.jsonl:   0%|          | 0.00/647k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2508 [00:00<?, ? examples/s]

In [17]:
ds

DatasetDict({
    train: Dataset({
        features: ['quote', 'author', 'tags'],
        num_rows: 2508
    })
})

In [18]:
ds['train'][:10]

{'quote': ['“Be yourself; everyone else is already taken.”',
  "“I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.”",
  "“Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.”",
  '“So many books, so little time.”',
  '“A room without books is like a body without a soul.”',
  "“Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.”",
  "“You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth.”",
  "“You know you're in love when you can't fall asleep because reality is finally better than your dreams.”",
  '“You only live once, but if you do it right, once is enough.”',
  '“Be the change that you wish to see in the world.”'],
 'author': ['Oscar Wilde',
  'Marilyn Monroe',
  'Albert Einstein',
  'Frank Zappa',
  'Marcus Tullius Cicero',
  'Bernard M. Baruch',
  'William W. Purkey',
  'Dr. Seuss',
  'Mae West',
  'Mahatma Gandhi'],
 'tags': [['be-yourself',
   'gilbert-perreira',
   'honesty',
   'inspirational',
   'misattributed-oscar-wilde',
   'quote-investigator'],
  ['best', 'life', 'love', 'mistakes', 'out-of-control', 'truth', 'worst'],
  ['human-nature',
   'humor',
   'infinity',
   'philosophy',
   'science',
   'stupidity',
   'universe'],
  ['books', 'humor'],
  ['books', 'simile', 'soul'],
  ['ataraxy',
   'be-yourself',
   'confidence',
   'fitting-in',
   'individuality',
   'misattributed-dr-seuss',
   'those-who-matter'],
  ['dance', 'heaven', 'hurt', 'inspirational', 'life', 'love', 'sing'],
  ['dreams', 'love', 'reality', 'sleep'],
  ['humor', 'life'],
  ['action', 'change', 'inspirational', 'philosophy', 'wish']]}

In [19]:
df = ds['train'].to_pandas()

In [20]:
df

,quote,author,tags
0,“Be yourself; everyone else is already taken.”,Oscar Wilde,"[be-yourself, gilbert-perreira, honesty, inspi..."
1,"“I'm selfish, impatient and a little insecure....",Marilyn Monroe,"[best, life, love, mistakes, out-of-control, t..."
2,“Two things are infinite: the universe and hum...,Albert Einstein,"[human-nature, humor, infinity, philosophy, sc..."
3,"“So many books, so little time.”",Frank Zappa,"[books, humor]"
4,“A room without books is like a body without a...,Marcus Tullius Cicero,"[books, simile, soul]"
...,...,...,...
2503,“Morality is simply the attitude we adopt towa...,"Oscar Wilde,","[morality, philosophy]"
2504,“Don't aim at success. The more you aim at it ...,"Viktor E. Frankl,","[happiness, success]"
2505,"“In life, finding a voice is speaking and livi...",John Grisham,[inspirational-life]
2506,"“Winter is the time for comfort, for good food...",Edith Sitwell,"[comfort, home, winter]"
2507,“Silence is so freaking loud”,"Sarah Dessen,","[just-listen, loud, owen, sara-dessen, silence]"

In [22]:
df.author.value_counts()

author
Cassandra Clare,               99
J.K. Rowling,                  74
John Green,                    53
Roy T. Bennett,                46
Mark Twain                     42
                               ..
Thich Nhat Hanh,                1
Bertrand Russell,               1
Ø£Ø­Ù„Ø§Ù… Ù…Ø³ØªØºØ§Ù†Ù…ÙŠ     1
James Patterson,                1
G.K. Chesterton,                1
Name: count, Length: 880, dtype: int64

In [23]:
class dset(Dataset):
    def __init__(self, ds, start_prompt, end_prompt):
        super().__init__()
        self.data = ds
        self.start_prompt = start_prompt
        self.end_prompt = end_prompt

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        author = self.data.iloc[idx]['author']
        quote = self.data.iloc[idx]['quote']
        x = self.start_prompt + author
        y = self.end_prompt + quote
        return x, y

In [24]:
start_prompt = f'Please generate a quote written by author name given below:\n\nauthor: '
end_prompt = f'quote: '
print(start_prompt)
print("#########################")
print(end_prompt)

Please generate a quote written by author name given below:

author:
#########################
quote:

In [25]:
train_ds = dset(df, start_prompt, end_prompt)

In [31]:
print(f'{train_ds[3][0]}\n\n')
print(train_ds[3][1])

Please generate a quote written by author name given below:

author: Frank Zappa


quote: “So many books, so little time.”

In [54]:
ckpt = 'facebook/opt-350m'
tokenizer = AutoTokenizer.from_pretrained(ckpt)
tokenizer

GPT2TokenizerFast(name_or_path='facebook/opt-350m', vocab_size=50265, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '</s>', 'unk_token': '</s>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [93]:
def collate_fn(batch, tokenizer):
    eos_tokenid = [tokenizer.vocab[tokenizer.eos_token]]
    pad_tokenid = [tokenizer.vocab[tokenizer.pad_token]]
    ignore_loss_id = [-100]
    ignore_token_id = [0]
    inp_list, att_list, y_list = [],  [], []

    for x, y in batch:
        x_mod = x + "\n"  # f'{x}\n\n'
        print(x_mod)
        x_tok = tokenizer(x_mod, truncation=True).input_ids
        y_tok = tokenizer(y, truncation=True).input_ids
        print(f'X: {x_tok}\nY: {y_tok}')

        prompt = x_mod + y
        input_prompt = tokenizer(prompt, truncation=True)

        x_tok_len = len(x_tok)
        label_prompt = ignore_loss_id*(x_tok_len - 1) + y_tok[1:] + eos_tokenid
        #to remove extra start of sentence token from y_tok

        inp_list.append(input_prompt['input_ids'])
        att_list.append(input_prompt['attention_mask'])
        print(f"{len(input_prompt['input_ids'])}\n{len(input_prompt['attention_mask'])}\n{input_prompt}")

        y_list.append(label_prompt)
        print(f'{len(label_prompt)}\n{label_prompt}')

    len_labs = [len(l) for l in y_list]
    max_len = max(len_labs)

    def pad_tokens_stack(in_list, max_len, padding):
        list_tensor = []
        for item in in_list:
            len_item = len(item)
            deficit = max_len - len_item
            if deficit > 0:
                item = item + padding*deficit
            list_tensor.append(torch.tensor(item))
        item_ids = torch.vstack(list_tensor)
        return item_ids

    #print(inp_list, max_len, pad_tokenid)
    input_ids = pad_tokens_stack(inp_list, max_len, pad_tokenid)
    attention_mask = pad_tokens_stack(att_list, max_len, ignore_token_id)
    labels = pad_tokens_stack(y_list, max_len, ignore_loss_id)

    return {'input_ids': input_ids, 'attention_mask': attention_mask}, labels

In [94]:
cpu_cores = os.cpu_count()
wrapper_collate_fn = partial(
        collate_fn,
        tokenizer=tokenizer
        )
train_dl = DataLoader(train_ds, shuffle=False, batch_size=3,
                      num_workers=cpu_cores, collate_fn=wrapper_collate_fn)

In [96]:
iter_dl = iter(train_dl)

Please generate a quote written by author name given below:

author: Frank Zappa

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 3848, 525, 22181, 50118]
Y: [2, 43948, 35, 44, 48, 2847, 171, 2799, 6, 98, 410, 86, 4, 17, 46]
34
34
{'input_ids': [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 3848, 525, 22181, 50118, 43948, 35, 44, 48, 2847, 171, 2799, 6, 98, 410, 86, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
34
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 2847, 171, 2799, 6, 98, 410, 86, 4, 17, 46, 2]
Please generate a quote written by author name given below:

author: Marcus Tullius Cicero

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 7380, 255, 5023, 6125, 31547, 5160, 50118]
Y: [2, 43948, 35, 44, 48, 250, 929, 396, 2799, 16, 101, 10, 809, 396, 10, 7047, 4, 17, 46]
41
41
{'input_ids': [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 7380, 255, 5023, 6125, 31547, 5160, 50118, 43948, 35, 44, 48, 250, 929, 396, 2799, 16, 101, 10, 809, 396, 10, 7047, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
41
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 250, 929, 396, 2799, 16, 101, 10, 809, 396, 10, 7047, 4, 17, 46, 2]
Please generate a quote written by author name given below:

author: Bernard M. Baruch

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 11364, 256, 4, 1731, 4272, 50118]
Y: [2, 43948, 35, 44, 48, 9325, 54, 47, 32, 8, 224, 99, 47, 619, 6, 142, 167, 54, 1508, 218, 75, 948, 6, 8, 167, 54, 948, 218, 75, 1508, 4, 17, 46]
54
54
{'input_ids': [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 11364, 256, 4, 1731, 4272, 50118, 43948, 35, 44, 48, 9325, 54, 47, 32, 8, 224, 99, 47, 619, 6, 142, 167, 54, 1508, 218, 75, 948, 6, 8, 167, 54, 948, 218, 75, 1508, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
54
Please generate a quote written by author name given below:, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 9325, 54, 47, 32, 8, 224, 99, 47, 619, 6, 142, 167, 54, 1508, 218, 75, 948, 6, 8, 167, 54, 948, 218, 75, 1508, 4, 17, 46, 2]

author: Oscar Wilde

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 5887, 33941, 50118]
Y: [2, 43948, 35, 44, 48, 9325, 2512, 131, 961, 1493, 16, 416, 551, 4, 17, 46]
34
34
{'input_ids': [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 5887, 33941, 50118, 43948, 35, 44, 48, 9325, 2512, 131, 961, 1493, 16, 416, 551, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
34
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 9325, 2512, 131, 961, 1493, 16, 416, 551, 4, 17, 46, 2]
Please generate a quote written by author name given below:

author: Marilyn Monroe

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 23542, 12885, 50118]
Y: [2, 43948, 35, 44, 48, 100, 437, 20462, 6, 32601, 8, 10, 410, 27810, 4, 38, 146, 6160, 6, 38, 524, 66, 9, 797, 8, 23, 498, 543, 7, 3679, 4, 125, 114, 47, 64, 75, 3679, 162, 23, 127, 2373, 6, 172, 47, 686, 25, 7105, 218, 75, 6565, 162, 23, 127, 275, 4, 17, 46]
75
75
{'input_ids': [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 23542, 12885, 50118, 43948, 35, 44, 48, 100, 437, 20462, 6, 32601, 8, 10, 410, 27810, 4, 38, 146, 6160, 6, 38, 524, 66, 9, 797, 8, 23, 498, 543, 7, 3679, 4, 125, 114, 47, 64, 75, 3679, 162, 23, 127, 2373, 6, 172, 47, 686, 25, 7105, 218, 75, 6565, 162, 23, 127, 275, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
75
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 100, 437, 20462, 6, 32601, 8, 10, 410, 27810, 4, 38, 146, 6160, 6, 38, 524, 66, 9, 797, 8, 23, 498, 543, 7, 3679, 4, 125, 114, 47, 64, 75, 3679, 162, 23, 127, 2373, 6, 172, 47, 686, 25, 7105, 218, 75, 6565, 162, 23, 127, 275, 4, 17, 46, 2]
Please generate a quote written by author name given below:

author: Albert Einstein

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 8098, 27648, 50118]
Y: [2, 43948, 35, 44, 48, 9058, 383, 32, 32952, 35, 5, 9468, 8, 1050, 38821, 131, 8, 38, 437, 45, 686, 59, 5, 9468, 4, 17, 46]
45
45
{'input_ids': [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 8098, 27648, 50118, 43948, 35, 44, 48, 9058, 383, 32, 32952, 35, 5, 9468, 8, 1050, 38821, 131, 8, 38, 437, 45, 686, 59, 5, 9468, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
45
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 9058, 383, 32, 32952, 35, 5, 9468, 8, 1050, 38821, 131, 8, 38, 437, 45, 686, 59, 5, 9468, 4, 17, 46, 2]
Please generate a quote written by author name given below:

author: Mahatma Gandhi

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 3634, 415, 1916, 9277, 50118]
Y: [2, 43948, 35, 44, 48, 9325, 5, 464, 14, 47, 2813, 7, 192, 11, 5, 232, 4, 17, 46]
39
39
{'input_ids': [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 3634, 415, 1916, 9277, 50118, 43948, 35, 44, 48, 9325, 5, 464, 14, 47, 2813, 7, 192, 11, 5, 232, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
39
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 9325, 5, 464, 14, 47, 2813, 7, 192, 11, 5, 232, 4, 17, 46, 2]
Please generate a quote written by author name given below:

author: William W. Purkey

Please generate a quote written by author name given below:

author: Robert Frost

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 2897, 305, 4, 11834, 5282, 50118]
Y: [2, 43948, 35, 44, 48, 1185, 348, 16112, 3836, 101, 89, 18, 5907, 2494, 6, 16587, 101, 47, 581, 393, 28, 2581, 6, 26292, 101, 89, 18, 5907, 6288, 6, 2409, 697, 101, 24, 18, 18478, 15, 6872, 4, 17, 46]
62
62
X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 1738, 16334, 50118]5, 4, 11834, 5282, 50118, 43948, 35, 44, 48, 1185, 348, 16112, 3836, 101, 89, 18, 5907, 2494, 6, 16587, 101, 47, 581, 393, 28, 2581, 6, 26292, 101, 89, 18, 5907, 6288, 6, 2409, 697, 101, 24, 18, 18478, 15, 6872, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
Y: [2, 43948, 35, 44, 48, 1121, 130, 1617, 38, 64, 6797, 62, 960, 38, 348, 2435, 59, 301, 35, 24, 1411, 15, 4, 17, 46]
62
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 1185, 348, 16112, 3836, 101, 89, 18, 5907, 2494, 6, 16587, 101, 47, 581, 393, 28, 2581, 6, 26292, 101, 89, 18, 5907, 6288, 6, 2409, 697, 101, 24, 18, 18478, 15, 6872, 4, 17, 46, 2]
Please generate a quote written by author name given below:

author: Dr. Seuss


43
43
X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 925, 4, 1608, 4781, 50118]118, 43948, 35, 44, 48, 1121, 130, 1617, 38, 64, 6797, 62, 960, 38, 348, 2435, 59, 301, 35, 24, 1411, 15, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
Y: [2, 43948, 35, 44, 48, 1185, 216, 47, 214, 11, 657, 77, 47, 64, 75, 1136, 15028, 142, 2015, 16, 1747, 357, 87, 110, 7416, 4, 17, 46]

48
48
43input_ids': [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 925, 4, 1608, 4781, 50118, 43948, 35, 44, 48, 1185, 216, 47, 214, 11, 657, 77, 47, 64, 75, 1136, 15028, 142, 2015, 16, 1747, 357, 87, 110, 7416, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 1121, 130, 1617, 38, 64, 6797, 62, 960, 38, 348, 2435, 59, 301, 35, 24, 1411, 15, 4, 17, 46, 2]
Please generate a quote written by author name given below:

author: J.K. Rowling,

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 344, 4, 530, 4, 32290, 6, 50118]
Y: [2, 43948, 35, 44, 48, 1106, 47, 236, 7, 216, 99, 10, 313, 18, 101, 6, 185, 10, 205, 356, 23, 141, 37, 12419, 39, 40182, 10327, 6, 45, 39, 27601, 4, 17, 46]

48
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 1185, 216, 47, 214, 11, 657, 77, 47, 64, 75, 1136, 15028, 142, 2015, 16, 1747, 357, 87, 110, 7416, 4, 17, 46, 2]
56
56
Please generate a quote written by author name given below:, 576, 874, 35, 50118, 50118, 11515, 35, 344, 4, 530, 4, 32290, 6, 50118, 43948, 35, 44, 48, 1106, 47, 236, 7, 216, 99, 10, 313, 18, 101, 6, 185, 10, 205, 356, 23, 141, 37, 12419, 39, 40182, 10327, 6, 45, 39, 27601, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

author: Mae West

X: [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 13427, 580, 50118]
Y: [2, 43948, 35, 44, 48, 1185, 129, 697, 683, 6, 53, 114, 47, 109, 24, 235, 6, 683, 16, 615, 4, 17, 46]

41
41
56input_ids': [2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 13427, 580, 50118, 43948, 35, 44, 48, 1185, 129, 697, 683, 6, 53, 114, 47, 109, 24, 235, 6, 683, 16, 615, 4, 17, 46], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 1106, 47, 236, 7, 216, 99, 10, 313, 18, 101, 6, 185, 10, 205, 356, 23, 141, 37, 12419, 39, 40182, 10327, 6, 45, 39, 27601, 4, 17, 46, 2]

41
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 43948, 35, 44, 48, 1185, 129, 697, 683, 6, 53, 114, 47, 109, 24, 235, 6, 683, 16, 615, 4, 17, 46, 2]

In [83]:
print(tokenizer.decode([2, 6715, 5368, 10, 9740, 1982, 30, 2730, 766, 576, 874, 35, 50118, 50118, 11515, 35, 5887, 33941, 50140]))

</s>Please generate a quote written by author name given below:

author: Oscar Wilde

In [85]:
print(tokenizer.decode([2, 43948, 35, 44, 48, 9325, 2512, 131, 961, 1493, 16, 416, 551, 4, 17, 46]))

</s>quote: “Be yourself; everyone else is already taken.”

In [86]:
tokenizer.decode(50140)

'\n\n'

In [68]:
tokenizer.decode([43948, 35, 44, 48, 9325, 2512, 131, 961, 1493, 16, 416, 551, 4, 17, 46, 2])

'quote: “Be yourself; everyone else is already taken.”</s>'

In [70]:
tokenizer.decode([43948, 35, 44, 48, 100, 437, 20462, 6, 32601, 8, 10, 410, 27810, 4, 38, 146, 6160, 6, 38, 524, 66, 9, 797, 8, 23, 498, 543, 7, 3679, 4, 125, 114, 47, 64, 75, 3679, 162, 23, 127, 2373, 6, 172, 47, 686, 25, 7105, 218, 75, 6565, 162, 23, 127, 275, 4, 17, 46, 2])

"quote: “I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.”</s>"

In [67]:
x, y = next(iter_dl)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 x, y = next(iter_dl)                                                                         │
│   2                                                                                              │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/utils/data/dataloa │
│ der.py:631 in __next__                                                                           │
│                                                                                                  │
│    628 │   │   │   if self._sampler_iter is None:                                                │
│    629 │   │   │   │   # TODO(https://github.com/pytorch/pytorch/issues/76750)                   │
│    630 │   │   │   │   self._reset()  # type: ignore[call-arg]                                   │
│ ❱  631 │   │   │   data = self._next_data()                                                      │
│    632 │   │   │   self._num_yielded += 1                                                        │
│    633 │   │   │   if self._dataset_kind == _DatasetKind.Iterable and \                          │
│    634 │   │   │   │   │   self._IterableDataset_len_called is not None and \                    │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/utils/data/dataloa │
│ der.py:1346 in _next_data                                                                        │
│                                                                                                  │
│   1343 │   │   │   │   self._task_info[idx] += (data,)                                           │
│   1344 │   │   │   else:                                                                         │
│   1345 │   │   │   │   del self._task_info[idx]                                                  │
│ ❱ 1346 │   │   │   │   return self._process_data(data)                                           │
│   1347 │                                                                                         │
│   1348 │   def _try_put_index(self):                                                             │
│   1349 │   │   assert self._tasks_outstanding < self._prefetch_factor * self._num_workers        │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/utils/data/dataloa │
│ der.py:1372 in _process_data                                                                     │
│                                                                                                  │
│   1369 │   │   self._rcvd_idx += 1                                                               │
│   1370 │   │   self._try_put_index()                                                             │
│   1371 │   │   if isinstance(data, ExceptionWrapper):                                            │
│ ❱ 1372 │   │   │   data.reraise()                                                                │
│   1373 │   │   return data                                                                       │
│   1374 │                                                                                         │
│   1375 │   def _mark_worker_as_unavailable(self, worker_id, shutdown=False):                     │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/_utils.py:722 in   │
│ reraise                                                                                          │
│                                                                                                  │
│   719 │   │   │   # If the exception takes multiple arguments, don't try to                      │
│   720 │   │   │   # instantiate since we don't know how to                                       │
│   721 │   │   │   raise RuntimeError(msg) from None                                              │
│ ❱ 722 │   │   raise exception                                                                    │
│   723                                                                                            │
│   724                                                                                            │
│   725 def _get_available_device_type():                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py",
line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py",
line 54, in fetch
    return self.collate_fn(data)
  File "/tmp/ipykernel_14323/1959449237.py", line 42, in collate_fn
    input_ids = pad_tokens_stack(inp_list, max_len, pad_tokenid)
  File "/tmp/ipykernel_14323/1959449237.py", line 38, in pad_tokens_stack
    item_ids = torch.vstack(list_tensor)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 75 but got size 76 for tensor number
1 in the list.

In [10]:
df['full_text'] = df.apply(lambda x: f'author: {x["author"]}\nquote:{x["quote"]}', axis=1)

In [11]:
print(df['full_text'].iloc[9])

author: Mahatma Gandhi
quote:“Be the change that you wish to see in the world.”

In [12]:
start_prompt = f'Please generate a quote written by author name given below:\n\nauthor: '
end_prompt = f'\n\nquote: '
print(start_prompt, end_prompt)

Please generate a quote written by author name given below:

author:

quote:

In [13]:
df['prompt'] = df.apply(lambda x: f'{start_prompt}{x["author"]}{end_prompt}{x["quote"]}', axis=1)

In [14]:
print(df['full_text'].iloc[9])
print("################")
print(df['prompt'].iloc[9])

author: Mahatma Gandhi
quote:“Be the change that you wish to see in the world.”
################
Please generate a quote written by author name given below:

author: Mahatma Gandhi

quote: “Be the change that you wish to see in the world.”

We will be treating this in two different problem sets. First we will finetune model for text generation
Next we will do it in QA format like given the author below, generate a quote

In [16]:
df['input_ids_len'] = df['full_text'].apply(lambda x: len(tokenizer(x, truncation=True).input_ids))
df = df.sort_values(by=['input_ids_len'], ascending=True)
df

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

,quote,author,tags,full_text,prompt,input_ids_len
62,“,"Kent M. Keith,","[forgiveness, goodness, happiness, honesty, ki...","author: Kent M. Keith,\nquote:“",Please generate a quote written by author name...,13
1050,“Don't Panic.”,"Douglas Adams,","[h2g2, hitchhiker-s-guide, humor, panic]","author: Douglas Adams,\nquote:“Don't Panic.”",Please generate a quote written by author name...,17
2141,“Hope is a waking dream.”,Aristotle,"[dreams, hope]",author: Aristotle\nquote:“Hope is a waking dre...,Please generate a quote written by author name...,17
562,“I cannot live without books.”,Thomas Jefferson,[books],author: Thomas Jefferson\nquote:“I cannot live...,Please generate a quote written by author name...,18
327,“Peace begins with a smile..”,Mother Teresa,"[inspirational, peace, smile, smiling]",author: Mother Teresa\nquote:“Peace begins wit...,Please generate a quote written by author name...,18
...,...,...,...,...,...,...
411,“I can believe things that are true and things...,"Neil Gaiman,",[belief],"author: Neil Gaiman,\nquote:“I can believe thi...",Please generate a quote written by author name...,655
1878,"“Once upon a midnight dreary, while I pondered...","Edgar Allan Poe,","[hopelessness, pain]","author: Edgar Allan Poe,\nquote:“Once upon a m...",Please generate a quote written by author name...,819
1051,"“For me, trees have always been the most penet...","Herman Hesse,","[eternity, fear, forests, history, holiness, h...","author: Herman Hesse,\nquote:“For me, trees ha...",Please generate a quote written by author name...,838
2418,“I will love you as a thief loves a gallery an...,Lemony Snicket,[the-beatrice-letters],author: Lemony Snicket\nquote:“I will love you...,Please generate a quote written by author name...,867
2393,“If I should have a daughterâ€¦â€œInstead of â...,Sarah Kay,"[inspirational, poem]",author: Sarah Kay\nquote:“If I should have a d...,Please generate a quote written by author name...,965

In [17]:
df.describe()

       input_ids_len
count    2508.000000
mean       53.240431
std        61.133405
min        13.000000
25%        29.000000
50%        37.000000
75%        53.250000
max       965.000000

In [18]:
df['input_ids_len'].quantile(0.98)

213.0

In [19]:
df_1 = df[df['input_ids_len'] < 512].copy()
df_1.reset_index(inplace=True, drop=True)
df_1['id'] = range(len(df_1))

In [20]:
df_1

,quote,author,tags,full_text,prompt,input_ids_len,id
0,“,"Kent M. Keith,","[forgiveness, goodness, happiness, honesty, ki...","author: Kent M. Keith,\nquote:“",Please generate a quote written by author name...,13,0
1,“Don't Panic.”,"Douglas Adams,","[h2g2, hitchhiker-s-guide, humor, panic]","author: Douglas Adams,\nquote:“Don't Panic.”",Please generate a quote written by author name...,17,1
2,“Hope is a waking dream.”,Aristotle,"[dreams, hope]",author: Aristotle\nquote:“Hope is a waking dre...,Please generate a quote written by author name...,17,2
3,“I cannot live without books.”,Thomas Jefferson,[books],author: Thomas Jefferson\nquote:“I cannot live...,Please generate a quote written by author name...,18,3
4,“Peace begins with a smile..”,Mother Teresa,"[inspirational, peace, smile, smiling]",author: Mother Teresa\nquote:“Peace begins wit...,Please generate a quote written by author name...,18,4
...,...,...,...,...,...,...,...
2492,"“Tess, Tess, Tessa. Was there ever a more beau...","Cassandra Clare,","[cassandra-clare, clockwork-prince, tessa-gray...","author: Cassandra Clare,\nquote:“Tess, Tess, T...",Please generate a quote written by author name...,352,2492
2493,"“To be, or not to be: that is the question:Whe...","William Shakespeare,","[death, existence, life]","author: William Shakespeare,\nquote:“To be, or...",Please generate a quote written by author name...,377,2493
2494,“Ø¥Ù† Ø§Ù„Ù…Ø±Ø£Ø© ØªØ­Ø¨ Ø±Ø¬Ù„Ù‡Ø§ Ù„ÙŠØ³ Ù„...,Ø£Ø­Ù…Ø¯ Ø®Ø§Ù„Ø¯ ØªÙˆÙ�ÙŠÙ‚,[life],author: Ø£Ø­Ù…Ø¯ Ø®Ø§Ù„Ø¯ ØªÙˆÙ�ÙŠÙ‚\nquote:“Ø...,Please generate a quote written by author name...,455,2494
2495,“Look again at that dot. That's here. That's h...,"Carl Sagan,","[earth, perspective, space]","author: Carl Sagan,\nquote:“Look again at that...",Please generate a quote written by author name...,468,2495
2496,“It doesn't interest me what you do for a livi...,Oriah Mountain Dreamer,[inspirational],author: Oriah Mountain Dreamer\nquote:“It does...,Please generate a quote written by author name...,504,2496

In [21]:
df.to_csv('./quotes.csv', index=False)

In [22]:
tokenizer.pad_token, tokenizer.eos_token

('<pad>', '</s>')

In [23]:
!pip install torchinfo

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [24]:
from torchinfo import summary

In [25]:
model = AutoModelForCausalLM.from_pretrained('facebook/opt-350m')

pytorch_model.bin:   0%|          | 0.00/663M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/662M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [26]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [27]:
summary(model)

===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
OPTForCausalLM                                     --
├─OPTModel: 1-1                                    --
│    └─OPTDecoder: 2-1                             --
│    │    └─Embedding: 3-1                         25,739,264
│    │    └─OPTLearnedPositionalEmbedding: 3-2     2,099,200
│    │    └─Linear: 3-3                            524,288
│    │    └─Linear: 3-4                            524,288
│    │    └─ModuleList: 3-5                        302,309,376
├─Linear: 1-2                                      25,739,264
===========================================================================
Total params: 356,935,680
Trainable params: 356,935,680
Non-trainable params: 0
===========================================================================

In [28]:
model

OPTForCausalLM(
  (model): OPTModel(
    (decoder): OPTDecoder(
      (embed_tokens): Embedding(50272, 512, padding_idx=1)
      (embed_positions): OPTLearnedPositionalEmbedding(2050, 1024)
      (project_out): Linear(in_features=1024, out_features=512, bias=False)
      (project_in): Linear(in_features=512, out_features=1024, bias=False)
      (layers): ModuleList(
        (0-23): 24 x OPTDecoderLayer(
          (self_attn): OPTSdpaAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): ReLU()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
  )
  (lm_head): Linear(in_features=512, out_features=50272, bias=False)
)

In [29]:
model.config

OPTConfig {
  "_attn_implementation_autoset": true,
  "_name_or_path": "facebook/opt-350m",
  "_remove_final_layer_norm": false,
  "activation_dropout": 0.0,
  "activation_function": "relu",
  "architectures": [
    "OPTForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 2,
  "do_layer_norm_before": false,
  "dropout": 0.1,
  "enable_bias": true,
  "eos_token_id": 2,
  "ffn_dim": 4096,
  "hidden_size": 1024,
  "init_std": 0.02,
  "layer_norm_elementwise_affine": true,
  "layerdrop": 0.0,
  "max_position_embeddings": 2048,
  "model_type": "opt",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 1,
  "prefix": "</s>",
  "torch_dtype": "float32",
  "transformers_version": "4.49.0",
  "use_cache": true,
  "vocab_size": 50272,
  "word_embed_proj_dim": 512
}

In [30]:
tokenizer.decode([1,2,3])

'<pad></s><unk>'

In [32]:
vocab_size =  model.config.vocab_size
vocab_size

50272

In [33]:
tokenizer.encode(tokenizer.eos_token), tokenizer.encode(tokenizer.bos_token), tokenizer.encode(tokenizer.pad_token)

([2, 2], [2, 2], [2, 1])

##### First we wil fine tune the model in text generation model and next we will do it in QA mode

In [4]:
#Sagemaker related commands
sess = sagemaker.Session()
role = sagemaker.get_execution_role()
region = sess.boto_region_name
bucket = sess.default_bucket()
sess, role, region, bucket

[03/06/25 08:11:36] INFO     Found credentials from IAM Role:                                   ]8;id=112658;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=967895;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py#1132\1132]8;;\
                             BaseNotebookInstanceEc2InstanceRole

                    INFO     Found credentials from IAM Role:                                   ]8;id=326508;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=400561;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py#1132\1132]8;;\
                             BaseNotebookInstanceEc2InstanceRole

(<sagemaker.session.Session at 0x7fb5671ccd60>,
 'arn:aws:iam::191013407134:role/service-role/AmazonSageMaker-ExecutionRole-20250124T222384',
 'us-east-1',
 'sagemaker-us-east-1-191013407134')

In [5]:
%pwd

'/home/ec2-user/SageMaker/transformersfromscratch/NLP_tasks/FineTuneDecoder'

In [6]:
S3_LOC = f's3://{bucket}/dataset/abirate_quotes/'
S3_LOC

's3://sagemaker-us-east-1-191013407134/dataset/abirate_quotes/'

In [7]:
#!aws s3 cp ./quotes.csv {S3_LOC}

In [8]:
!aws s3 ls --recursive {S3_LOC}

2025-03-05 12:57:56    4146715 dataset/abirate_quotes/model_data/model.tar.gz
2025-03-04 05:39:55    1763910 dataset/abirate_quotes/quotes.csv

In [9]:
# let us get image uri
training_image_uri = sagemaker.image_uris.retrieve(
    framework='pytorch', 
    version='2.0',
    instance_type='ml.g4dn.xlarge',
    region=region,
    py_version='py310',
    image_scope='training'
)
print(training_image_uri)

763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.0-gpu-py310

In [10]:
train_uri = f'{S3_LOC}'
train_uri

's3://sagemaker-us-east-1-191013407134/dataset/abirate_quotes/'

In [11]:
s3_inp_tr = TrainingInput(
    s3_data = train_uri
    )
s3_inp_tr

In [12]:
data_channels = {
    'train': s3_inp_tr
    }
data_channels

{'train': <sagemaker.inputs.TrainingInput at 0x7fb56093a740>}

In [13]:
objective_metric_name = "average training loss"
objective_type = "Minimize"
metric_definitions = [{"Name": "average training loss", "Regex": "Average loss: ([0-9\\.]+)"},
                      {"Name": "Perplexity", "Regex": "Perplexity: ([0-9\\.]+)"}]
objective_metric_name, objective_type, metric_definitions

('average training loss',
 'Minimize',
 [{'Name': 'average training loss', 'Regex': 'Average loss: ([0-9\\.]+)'},
  {'Name': 'Perplexity', 'Regex': 'Perplexity: ([0-9\\.]+)'}])

In [14]:
ic=1
i_type = "ml.g4dn.xlarge"
ic, i_type

(1, 'ml.g4dn.xlarge')

In [15]:
%pwd

'/home/ec2-user/SageMaker/transformersfromscratch/NLP_tasks/FineTuneDecoder'

# let us get image uri
training_image_uri = sagemaker.image_uris.retrieve(
    framework='pytorch', 
    version='2.0',
    instance_type='ml.g6.xlarge',
    region=region,
    py_version='py310',
    image_scope='training'
)
print(training_image_uri)

ic=1
i_type = "ml.g6.xlarge"
ic, i_type

In [81]:
hparams = {
    'bs': 16,
    'lrate': 0.0008,
    'num_epochs': 20,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'facebook/opt-350m',
    'quant_bits': 4,
    'peft': "lora",
    'grad_accum_steps': 4 #set to 4 if cuda errors out
}
hparams

{'bs': 16,
 'lrate': 0.0008,
 'num_epochs': 20,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'facebook/opt-350m',
 'quant_bits': 4,
 'peft': 'lora',
 'grad_accum_steps': 4}

In [82]:
%pwd

'/home/ec2-user/SageMaker/transformersfromscratch/NLP_tasks/FineTuneDecoder'

In [83]:
est_qoutes_textgen_4bit = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-quotes-textgen.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='quotes-text-gen-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_qoutes_textgen_4bit.fit(
    inputs=data_channels,
    wait=True
)

[03/04/25 11:03:49] INFO     SageMaker Python SDK will collect telemetry to help us better  ]8;id=536567;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/telemetry/telemetry_logging.py\telemetry_logging.py]8;;\:]8;id=602602;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/telemetry/telemetry_logging.py#91\91]8;;\
                             understand our user's needs, diagnose issues, and deliver
                             additional features.
                             To opt out of telemetry, please disable via TelemetryOptOut
                             parameter in SDK defaults config. For more information, refer
                             to
                             https://sagemaker.readthedocs.io/en/stable/overview.html#confi
                             guring-and-using-defaults-with-the-sagemaker-python-sdk.

[03/04/25 11:03:50] INFO     Creating training-job with name:                                       ]8;id=659786;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/session.py\session.py]8;;\:]8;id=435271;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/session.py#1042\1042]8;;\
                             quotes-text-gen-train-2025-03-04-11-03-49-977

2025-03-04 11:03:50 Starting - Starting the training job......
..25-03-04 11:04:28 Starting - Preparing the instances for training.
....................Downloading - Downloading the training image.
bash: cannot set terminal process group (-1): Inappropriate ioctl for devices..
bash: no job control in this shell
2025-03-04 11:08:58,405 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2025-03-04 11:08:58,424 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-04 11:08:58,434 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2025-03-04 11:08:58,441 sagemaker_pytorch_container.training INFO     Invoking user training script.
2025-03-04 11:09:00,423 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 6.1 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.29.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-19.0.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 8.4 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.8.61-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.1 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 155.0 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 45.9 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 62.3 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 82.2 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 75.1 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.6 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 126.0 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 98.0 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 91.9 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 31.7 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 55.1 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 22.0 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 13.9 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 17.1 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 25.4 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 19.4 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.29.1-py3-none-any.whl (468 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.0/468.0 kB 72.5 MB/s eta 0:00:00
Downloading pyarrow-19.0.1-cp310-cp310-manylinux_2_28_x86_64.whl (42.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 MB 71.1 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 18.7 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 77.3 MB/s eta 0:00:00
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 137.2 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 23.0 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 48.1 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.8.61-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.2/39.2 MB 70.2 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 huggingface-hub-0.29.1 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.8.61 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-19.0.1 requests-2.32.3 safetensors-0.5.3 tokenizers-0.21.0 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.1 transformers-4.49.0 triton-2.2.0 xxhash-3.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
2025-03-04 11:11:23,446 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2025-03-04 11:11:23,446 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2025-03-04 11:11:23,524 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-04 11:11:23,579 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-04 11:11:23,609 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-04 11:11:23,620 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 16,
        "ckpt": "facebook/opt-350m",
        "environ": "aws",
        "grad_accum_steps": 4,
        "lrate": 0.0008,
        "num_epochs": 20,
        "peft": "lora",
        "quant_bits": 4
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "train": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "instance_groups": [
        "homogeneousCluster"
    ],
    "instance_groups_dict": {
        "homogeneousCluster": {

In [46]:
est_qoutes_textgen_4bit = Estimator.attach('quotes-text-gen-train-2025-03-04-11-03-49-977')

[03/05/25 05:09:08] INFO     Found credentials from IAM Role:                                   ]8;id=438435;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=888281;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py#1132\1132]8;;\
                             BaseNotebookInstanceEc2InstanceRole

[03/05/25 05:09:09] INFO     Found credentials from IAM Role:                                   ]8;id=421767;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=448455;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/credentials.py#1132\1132]8;;\
                             BaseNotebookInstanceEc2InstanceRole

2025-03-04 11:28:21 Starting - Preparing the instances for training
2025-03-04 11:28:21 Downloading - Downloading the training image
2025-03-04 11:28:21 Training - Training image download completed. Training in progress.
2025-03-04 11:28:21 Uploading - Uploading generated training model
2025-03-04 11:28:21 Completed - Training job completed

In [47]:
!aws s3 ls --recursive {est_qoutes_textgen_4bit.model_data}
!aws s3 cp {est_qoutes_textgen_4bit.model_data} ./est_qoutes_textgen_4bit/
%cd est_qoutes_textgen_4bit
!ls -ltrh
!gunzip -dc model.tar.gz |tar xvf -
!ls -ltrh


%cd ..
%pwd

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

2025-03-04 11:28:14    4148146 quotes-text-gen-train-2025-03-04-11-03-49-977/output/model.tar.gz

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

download: s3://sagemaker-us-east-1-191013407134/quotes-text-gen-train-2025-03-04-11-03-49-977/output/model.tar.gz to est_qoutes_textgen_4bit/model.tar.gz
/home/ec2-user/SageMaker/DecoderTasks/est_qoutes_textgen_4bit
total 4.0M
-rw-rw-r-- 1 ec2-user ec2-user 4.0M Mar  4 11:28 model.tar.gz

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/adapter_model.safetensors
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/training_args.bin
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/vocab.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/special_tokens_map.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/adapter_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/tokenizer_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/merges.txt
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/README.md
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_20_Prplxty_4.906924388591055/tokenizer.json
total 4.0M
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4 11:27 ckpt_Epoch_20_Prplxty_4.906924388591055
-rw-rw-r-- 1 ec2-user ec2-user 4.0M Mar  4 11:28 model.tar.gz
/home/ec2-user/SageMaker/DecoderTasks

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

'/home/ec2-user/SageMaker/DecoderTasks'

In [48]:
%pwd

'/home/ec2-user/SageMaker/DecoderTasks'

In [49]:
%cd est_qoutes_textgen_4bit/ckpt_Epoch_20_Prplxty_4.906924388591055/
%pwd

/home/ec2-user/SageMaker/DecoderTasks/est_qoutes_textgen_4bit/ckpt_Epoch_20_Prplxty_4.906924388591055

'/home/ec2-user/SageMaker/DecoderTasks/est_qoutes_textgen_4bit/ckpt_Epoch_20_Prplxty_4.906924388591055'

In [50]:
!ls -ltrh

total 7.7M
-rw-r--r-- 1 ec2-user ec2-user 5.0K Mar  4 11:27 README.md
-rw-r--r-- 1 ec2-user ec2-user  700 Mar  4 11:27 tokenizer_config.json
-rw-r--r-- 1 ec2-user ec2-user  548 Mar  4 11:27 special_tokens_map.json
-rw-r--r-- 1 ec2-user ec2-user 3.1M Mar  4 11:27 adapter_model.safetensors
-rw-r--r-- 1 ec2-user ec2-user  712 Mar  4 11:27 adapter_config.json
-rw-r--r-- 1 ec2-user ec2-user 780K Mar  4 11:27 vocab.json
-rw-r--r-- 1 ec2-user ec2-user 446K Mar  4 11:27 merges.txt
-rw-r--r-- 1 ec2-user ec2-user 3.4M Mar  4 11:27 tokenizer.json
-rw-r--r-- 1 ec2-user ec2-user 5.2K Mar  4 11:27 training_args.bin

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [52]:
from peft import AutoPeftModelForCausalLM

In [53]:
loaded_model = AutoPeftModelForCausalLM.from_pretrained('./', is_trainable=False)

In [54]:
loaded_model

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): OPTForCausalLM(
      (model): OPTModel(
        (decoder): OPTDecoder(
          (embed_tokens): Embedding(50265, 512, padding_idx=1)
          (embed_positions): OPTLearnedPositionalEmbedding(2050, 1024)
          (project_out): Linear(in_features=1024, out_features=512, bias=False)
          (project_in): Linear(in_features=512, out_features=1024, bias=False)
          (layers): ModuleList(
            (0-23): 24 x OPTDecoderLayer(
              (self_attn): OPTSdpaAttention(
                (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
              )
              (activation_fn): ReLU()
              (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              (fc1): Linear(in_features=1024, out_features=4096, bias=True)
              (fc2): Linear(in_features=4096, out_features=1024, bias=True)
              (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            )
          )
        )
      )
      (lm_head): Linear(in_features=512, out_features=50265, bias=False)
    )
  )
)

In [55]:
summary(loaded_model)

===============================================================================================
Layer (type:depth-idx)                                                 Param #
===============================================================================================
PeftModelForCausalLM                                                   --
├─LoraModel: 1-1                                                       --
│    └─OPTForCausalLM: 2-1                                             --
│    │    └─OPTModel: 3-1                                              (331,979,264)
│    │    └─Linear: 3-2                                                (25,735,680)
===============================================================================================
Total params: 357,714,944
Trainable params: 0
Non-trainable params: 357,714,944
===============================================================================================

In [144]:
def generate(prompt):
    tokenized_text = tokenizer(prompt, return_tensors="pt").to("cuda")
    output = loaded_model.generate(**tokenized_text,
                                   do_sample=True,
                                   top_k=3,
                                   temperature=0.8,
                                   max_new_tokens=50)
    result = tokenizer.batch_decode(output,  skip_special_tokens=True)[0]
    return result

In [145]:
full_text = '''author: Mahatma Gandhi
quote:"Be the change that you wish to see in the world."
'''

print(full_text)

author: Mahatma Gandhi
quote:"Be the change that you wish to see in the world."

In [146]:
prompt = '''author: Mahatma Gandhi
quote:"Be the change '''
print(prompt)

author: Mahatma Gandhi
quote:"Be the change

In [149]:
generate(prompt)

'author: Mahatma Gandhi\nquote:"Be the change  you want to see in the world. But don\'t make yourself a part of it. Be a part of your own change. Be a part of the transformation that is coming. But don\'t be a part of the process that is coming for you'

In [137]:
#So the model is generating correct text and some blabber lol!

In [150]:
prompt = '''author: Mahatma Gandhi
quote:"'''
print(prompt)
print(generate(prompt))

author: Mahatma Gandhi
quote:"
author: Mahatma Gandhi
quote:"I do not want to be the only one who has seen the world. I am sure that there are many who have not, and will never see it. But I want to be able to give a little of my wisdom to those who have not

In [141]:
#when we let model choose it wanders around..expected

In [155]:
prompt = '''author: Mahatma Gandhi
quote:"Nobody can hurt'''
print(prompt)
print(generate(prompt))

author: Mahatma Gandhi
quote:"Nobody can hurt
author: Mahatma Gandhi
quote:"Nobody can hurt me without my consent. I have to give up my own power to help others."

In [156]:
prompt = '''author: Mahatma Gandhi
quote:"An eye for an eye'''
print(prompt)
print(generate(prompt))

author: Mahatma Gandhi
quote:"An eye for an eye
author: Mahatma Gandhi
quote:"An eye for an eye will make the whole world blind, but an eye for an eye will make everything light.”

In [182]:
prompt = '''author: Mahatma Gandhi
quote:"Each night, when I go to sleep'''
print(prompt)
print(generate(prompt))

author: Mahatma Gandhi
quote:"Each night, when I go to sleep
author: Mahatma Gandhi
quote:"Each night, when I go to sleep, I tell myself that the universe is a complex system of which I have no control. But, I am not alone. I am not alone. I am here. And I will continue to live here. And I will continue to be here.

In [89]:
hparams = {
    'bs': 16,
    'lrate': 0.0009,
    'num_epochs': 30,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'facebook/opt-350m',
    'quant_bits': 0,
    'peft': "lora",
    'grad_accum_steps': 4 #set to 4 if cuda errors out
}
hparams

{'bs': 16,
 'lrate': 0.0009,
 'num_epochs': 30,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'facebook/opt-350m',
 'quant_bits': 0,
 'peft': 'lora',
 'grad_accum_steps': 4}

In [90]:
est_qoutes_textgen_loraonly = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-quotes-textgen.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='quotes-text-gen-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_qoutes_textgen_loraonly.fit(
    inputs=data_channels,
    wait=True
)

[03/04/25 11:44:35] INFO     SageMaker Python SDK will collect telemetry to help us better  ]8;id=529250;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/telemetry/telemetry_logging.py\telemetry_logging.py]8;;\:]8;id=690276;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/telemetry/telemetry_logging.py#91\91]8;;\
                             understand our user's needs, diagnose issues, and deliver
                             additional features.
                             To opt out of telemetry, please disable via TelemetryOptOut
                             parameter in SDK defaults config. For more information, refer
                             to
                             https://sagemaker.readthedocs.io/en/stable/overview.html#confi
                             guring-and-using-defaults-with-the-sagemaker-python-sdk.

                    INFO     Creating training-job with name:                                       ]8;id=473683;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/session.py\session.py]8;;\:]8;id=817213;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/session.py#1042\1042]8;;\
                             quotes-text-gen-train-2025-03-04-11-44-35-554

2025-03-04 11:44:36 Starting - Starting the training job......
..25-03-04 11:45:12 Starting - Preparing the instances for training.
..25-03-04 11:45:57 Downloading - Downloading input data.
....................Downloading - Downloading the training image.
2025-03-04 11:49:44 Training - Training image download completed. Training in progress.bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2025-03-04 11:49:59,416 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2025-03-04 11:49:59,435 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-04 11:49:59,446 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2025-03-04 11:49:59,452 sagemaker_pytorch_container.training INFO     Invoking user training script.
2025-03-04 11:50:01,418 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.6 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.29.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-19.0.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 7.5 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.8.61-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.1 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 129.2 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 36.8 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 39.6 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 56.2 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 48.8 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.5 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 109.0 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 83.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 59.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.9 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 22.4 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 39.7 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 22.1 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 14.9 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 18.9 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 16.3 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 18.2 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.29.1-py3-none-any.whl (468 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.0/468.0 kB 49.2 MB/s eta 0:00:00
Downloading pyarrow-19.0.1-cp310-cp310-manylinux_2_28_x86_64.whl (42.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 MB 55.4 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 12.1 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 56.5 MB/s eta 0:00:00
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 106.4 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 16.2 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 27.2 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.8.61-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.2/39.2 MB 63.3 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 huggingface-hub-0.29.1 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.8.61 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-19.0.1 requests-2.32.3 safetensors-0.5.3 tokenizers-0.21.0 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.1 transformers-4.49.0 triton-2.2.0 xxhash-3.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
2025-03-04 11:52:24,429 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2025-03-04 11:52:24,429 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2025-03-04 11:52:24,495 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-04 11:52:24,530 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-04 11:52:24,561 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-04 11:52:24,573 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 16,
        "ckpt": "facebook/opt-350m",
        "environ": "aws",
        "grad_accum_steps": 4,
        "lrate": 0.0009,
        "num_epochs": 30,
        "peft": "lora",
        "quant_bits": 0
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "train": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",

In [183]:
est_qoutes_textgen_loraonly = Estimator.attach('quotes-text-gen-train-2025-03-04-11-44-35-554')

2025-03-04 12:15:33 Starting - Preparing the instances for training
2025-03-04 12:15:33 Downloading - Downloading the training image
2025-03-04 12:15:33 Training - Training image download completed. Training in progress.
2025-03-04 12:15:33 Uploading - Uploading generated training model
2025-03-04 12:15:33 Completed - Training job completed

In [185]:
%cd ../..
%pwd

/home/ec2-user/SageMaker/DecoderTasks

'/home/ec2-user/SageMaker/DecoderTasks'

In [186]:
!aws s3 ls --recursive {est_qoutes_textgen_loraonly.model_data}
!aws s3 cp {est_qoutes_textgen_loraonly.model_data} ./est_qoutes_textgen_loraonly/
%cd est_qoutes_textgen_loraonly
!ls -ltrh
!gunzip -dc model.tar.gz |tar xvf -
!ls -ltrh

%cd ..
%pwd

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

2025-03-04 12:15:26    4146715 quotes-text-gen-train-2025-03-04-11-44-35-554/output/model.tar.gz

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

download: s3://sagemaker-us-east-1-191013407134/quotes-text-gen-train-2025-03-04-11-44-35-554/output/model.tar.gz to est_qoutes_textgen_loraonly/model.tar.gz
/home/ec2-user/SageMaker/DecoderTasks/est_qoutes_textgen_loraonly
total 4.0M
-rw-rw-r-- 1 ec2-user ec2-user 4.0M Mar  4 12:15 model.tar.gz

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/adapter_model.safetensors
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/merges.txt
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/README.md
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/adapter_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/vocab.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/tokenizer.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/special_tokens_map.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/tokenizer_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_30_Prplxty_3.6311811785448933/training_args.bin
total 4.0M
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4 12:15 ckpt_Epoch_30_Prplxty_3.6311811785448933
-rw-rw-r-- 1 ec2-user ec2-user 4.0M Mar  4 12:15 model.tar.gz
/home/ec2-user/SageMaker/DecoderTasks

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

'/home/ec2-user/SageMaker/DecoderTasks'

In [188]:
loaded_model_peftonly = AutoPeftModelForCausalLM.from_pretrained('./est_qoutes_textgen_loraonly/ckpt_Epoch_30_Prplxty_3.6311811785448933', is_trainable=False)

In [189]:
loaded_model_peftonly

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): OPTForCausalLM(
      (model): OPTModel(
        (decoder): OPTDecoder(
          (embed_tokens): Embedding(50265, 512, padding_idx=1)
          (embed_positions): OPTLearnedPositionalEmbedding(2050, 1024)
          (project_out): Linear(in_features=1024, out_features=512, bias=False)
          (project_in): Linear(in_features=512, out_features=1024, bias=False)
          (layers): ModuleList(
            (0-23): 24 x OPTDecoderLayer(
              (self_attn): OPTSdpaAttention(
                (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
              )
              (activation_fn): ReLU()
              (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              (fc1): Linear(in_features=1024, out_features=4096, bias=True)
              (fc2): Linear(in_features=4096, out_features=1024, bias=True)
              (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            )
          )
        )
      )
      (lm_head): Linear(in_features=512, out_features=50265, bias=False)
    )
  )
)

In [190]:
summary(loaded_model_peftonly)

===============================================================================================
Layer (type:depth-idx)                                                 Param #
===============================================================================================
PeftModelForCausalLM                                                   --
├─LoraModel: 1-1                                                       --
│    └─OPTForCausalLM: 2-1                                             --
│    │    └─OPTModel: 3-1                                              (331,979,264)
│    │    └─Linear: 3-2                                                (25,735,680)
===============================================================================================
Total params: 357,714,944
Trainable params: 0
Non-trainable params: 357,714,944
===============================================================================================

In [195]:
loaded_model_peftonly.to(device)

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): OPTForCausalLM(
      (model): OPTModel(
        (decoder): OPTDecoder(
          (embed_tokens): Embedding(50265, 512, padding_idx=1)
          (embed_positions): OPTLearnedPositionalEmbedding(2050, 1024)
          (project_out): Linear(in_features=1024, out_features=512, bias=False)
          (project_in): Linear(in_features=512, out_features=1024, bias=False)
          (layers): ModuleList(
            (0-23): 24 x OPTDecoderLayer(
              (self_attn): OPTSdpaAttention(
                (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
              )
              (activation_fn): ReLU()
              (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              (fc1): Linear(in_features=1024, out_features=4096, bias=True)
              (fc2): Linear(in_features=4096, out_features=1024, bias=True)
              (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            )
          )
        )
      )
      (lm_head): Linear(in_features=512, out_features=50265, bias=False)
    )
  )
)

In [216]:
def generate(prompt, loaded_model):
    tokenized_text = tokenizer(prompt, return_tensors="pt").to("cuda")
    output = loaded_model.generate(**tokenized_text,
                                   do_sample=True,
                                   top_k=3,
                                   temperature=0.9,
                                   max_new_tokens=30)
    result = tokenizer.batch_decode(output,  skip_special_tokens=True)[0]
    return result

In [217]:
prompt = '''author: Mahatma Gandhi
quote:"Each night, when I go to sleep'''
print(prompt)
print(generate(prompt, loaded_model_peftonly))

author: Mahatma Gandhi
quote:"Each night, when I go to sleep
author: Mahatma Gandhi
quote:"Each night, when I go to sleep, I sleep for only a second. Then I wake up and it's all over. The other night, when I woke up, it was just

In [218]:
prompt = '''author: Mahatma Gandhi
quote:"Be the change'''
print(prompt)
print(generate(prompt, loaded_model_peftonly))

author: Mahatma Gandhi
quote:"Be the change
author: Mahatma Gandhi
quote:"Be the change that you want to see in the world. And don't expect people to give up anything. They have worked hard for it. If you can't

In [219]:
prompt = '''author: Mahatma Gandhi
quote:"Nobody can hurt'''
print(prompt)
print(generate(prompt, loaded_model_peftonly))

author: Mahatma Gandhi
quote:"Nobody can hurt
author: Mahatma Gandhi
quote:"Nobody can hurt me without my permission. I will not be hurt by anybody other than my own self. This is the way it has been for thousands of years.

In [228]:
prompt = '''author: Mahatma Gandhi
quote:"Freedom is not worth'''
print(prompt)
print(generate(prompt, loaded_model_peftonly))

author: Mahatma Gandhi
quote:"Freedom is not worth
author: Mahatma Gandhi
quote:"Freedom is not worth having if it doesn't include the ability to be treated with dignity and respect."

In [229]:
prompt = '''author: Mahatma Gandhi
quote:"Hate the sin'''
print(prompt)
print(generate(prompt, loaded_model_peftonly))

author: Mahatma Gandhi
quote:"Hate the sin
author: Mahatma Gandhi
quote:"Hate the sin, love the sinner. This is why, when a child is found in an open field, they say, "I was here before you."

In [230]:
#it seems it does better when the target quote is short

In [240]:
prompt = '''author: Mark Twain
quote:"Sanity and happiness'''
print(prompt)
print(generate(prompt, loaded_model_peftonly))

author: Mark Twain
quote:"Sanity and happiness
author: Mark Twain
quote:"Sanity and happiness are not the only possibilities, but they are the only two possibilities that exist.”

In [247]:
prompt = '''author: Mark Twain
quote:"Kindness is a language'''
print(prompt)
print(generate(prompt, loaded_model_peftonly))

author: Mark Twain
quote:"Kindness is a language
author: Mark Twain
quote:"Kindness is a language that can be heard, seen, and felt in the hearts of many peoples. It is a language that can be heard, seen, and felt in

In [248]:
loaded_model_peftonly_test = AutoPeftModelForCausalLM.from_pretrained('./est_qoutes_textgen_loraonly/ckpt_Epoch_30_Prplxty_3.6311811785448933', is_trainable=True)

In [249]:
summary(loaded_model_peftonly_test)

===============================================================================================
Layer (type:depth-idx)                                                 Param #
===============================================================================================
PeftModelForCausalLM                                                   --
├─LoraModel: 1-1                                                       --
│    └─OPTForCausalLM: 2-1                                             --
│    │    └─OPTModel: 3-1                                              331,979,264
│    │    └─Linear: 3-2                                                (25,735,680)
===============================================================================================
Total params: 357,714,944
Trainable params: 786,432
Non-trainable params: 356,928,512
===============================================================================================

In [261]:
prompt = 'Be the change'
print(prompt)
print(generate(prompt, loaded_model_peftonly))

Be the change
Be the change you want to see in the world.

I don't want to be a good woman. I want to be the kind who can make the

### Prompt Tuning

In [278]:
model_name = "bigscience/bloomz-560m"

In [279]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
foundation_model = AutoModelForCausalLM.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/222 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/14.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/715 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

In [280]:
input1 = tokenizer("Two things are infinite: ", return_tensors="pt")

foundation_outputs = foundation_model.generate(
    input_ids=input1["input_ids"], 
    attention_mask=input1["attention_mask"], 
    max_new_tokens=7, 
    eos_token_id=tokenizer.eos_token_id
    )
print(tokenizer.batch_decode(foundation_outputs, skip_special_tokens=True))

['Two things are infinite:  the number of people and the number']

In [281]:
from datasets import load_dataset

data = load_dataset("Abirate/english_quotes")

data = data.map(lambda samples: tokenizer(samples["quote"]), batched=True)
train_sample = data["train"].select(range(1500))
display(train_sample)

Map:   0%|          | 0/2508 [00:00<?, ? examples/s]

Dataset({
    features: ['quote', 'author', 'tags', 'input_ids', 'attention_mask'],
    num_rows: 1500
})

In [282]:
from peft import  get_peft_model, PromptTuningConfig, TaskType, PromptTuningInit

peft_config = PromptTuningConfig(
    task_type=TaskType.CAUSAL_LM,
    prompt_tuning_init=PromptTuningInit.RANDOM,
    num_virtual_tokens=6,
    tokenizer_name_or_path=model_name
)
peft_model = get_peft_model(foundation_model, peft_config)
print(peft_model.print_trainable_parameters())

trainable params: 6,144 || all params: 559,220,736 || trainable%: 0.0011
None

In [283]:
summary(peft_model)

===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
PeftModelForCausalLM                               --
├─BloomForCausalLM: 1-1                            --
│    └─BloomModel: 2-1                             --
│    │    └─Embedding: 3-1                         (256,901,120)
│    │    └─LayerNorm: 3-2                         (2,048)
│    │    └─ModuleList: 3-3                        (302,309,376)
│    │    └─LayerNorm: 3-4                         (2,048)
│    └─Linear: 2-2                                 (256,901,120)
├─ModuleDict: 1-2                                  --
│    └─PromptEmbedding: 2-3                        --
│    │    └─Embedding: 3-5                         6,144
├─Embedding: 1-3                                   (recursive)
===========================================================================
Total params: 816,121,856
Trainable params: 6,144
Non-trainable params: 816,115,712
===========================================================================

In [284]:
from transformers import TrainingArguments
import os

output_directory = os.path.join("./peft_outputs")

os.makedirs(output_directory, exist_ok=True)

In [285]:
training_args = TrainingArguments(
    output_dir=output_directory, # Where the model predictions and checkpoints will be written
    auto_find_batch_size=True, # Find a suitable batch size that will fit into memory automatically 
    learning_rate= 3e-2, # Higher learning rate than full fine-tuning
    num_train_epochs=20 # Number of passes to go through the entire fine-tuning dataset 
)

In [286]:
from transformers import Trainer, DataCollatorForLanguageModeling

In [287]:
trainer = Trainer(
    model=peft_model, # We pass in the PEFT version of the foundation model, bloomz-560M
    args=training_args,
    train_dataset=train_sample,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False) # mlm=False indicates not to use masked language modeling
)

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [288]:
trainer.train()

TrainOutput(global_step=30000, training_loss=3.083267822265625, metrics={'train_runtime': 1854.7488, 'train_samples_per_second': 16.175, 'train_steps_per_second': 16.175, 'total_flos': 2151980963561472.0, 'train_loss': 3.083267822265625, 'epoch': 20.0})

In [289]:
import time

time_now = time.time()
peft_model_path = os.path.join(output_directory, f"peft_model_{time_now}")
trainer.model.save_pretrained(peft_model_path)

In [292]:
!ls -ltrh {peft_model_path}

total 40K
-rw-rw-r-- 1 ec2-user ec2-user 5.0K Mar  5 07:06 README.md
-rw-rw-r-- 1 ec2-user ec2-user  25K Mar  5 07:06 adapter_model.safetensors
-rw-rw-r-- 1 ec2-user ec2-user  470 Mar  5 07:06 adapter_config.json

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [293]:
from peft import PeftModel

loaded_model = PeftModel.from_pretrained(foundation_model.to(device), 
                                         peft_model_path, 
                                         is_trainable=False)

In [310]:
loaded_model_outputs = loaded_model.generate(
    input_ids=input1["input_ids"].to(device), 
    attention_mask=input1["attention_mask"].to(device), 
    max_new_tokens=7, 
    eos_token_id=tokenizer.eos_token_id,
    #temperature=0.8,
    #do_sample=True,
    #top_k=3
    )
print(tokenizer.batch_decode(loaded_model_outputs, skip_special_tokens=True))

['Two things are infinite:  the number of people who love you']

##### Retraining LORA Only peft model that we fine tuned for text generation as supeervised fine tuning task .. kind of QA task

In [43]:
hparams = {
    'bs': 8,
    'lrate': 0.0009,
    'num_epochs': 30,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'facebook/opt-350m',
    'quant_bits': 0,
    'peft': "peft_retrain",
    'grad_accum_steps': 1 #set to 4 if cuda errors out
}
hparams

{'bs': 8,
 'lrate': 0.0009,
 'num_epochs': 30,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'facebook/opt-350m',
 'quant_bits': 0,
 'peft': 'peft_retrain',
 'grad_accum_steps': 1}

In [44]:
est_qoutes_QA_loraretrain = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-quotes-textgen-QA.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='quotes-text-gen-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_qoutes_QA_loraretrain.fit(
    inputs=data_channels,
    wait=True
)

[03/06/25 09:15:34] INFO     SageMaker Python SDK will collect telemetry to help us better  ]8;id=911180;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/telemetry/telemetry_logging.py\telemetry_logging.py]8;;\:]8;id=304821;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/telemetry/telemetry_logging.py#91\91]8;;\
                             understand our user's needs, diagnose issues, and deliver
                             additional features.
                             To opt out of telemetry, please disable via TelemetryOptOut
                             parameter in SDK defaults config. For more information, refer
                             to
                             https://sagemaker.readthedocs.io/en/stable/overview.html#confi
                             guring-and-using-defaults-with-the-sagemaker-python-sdk.

                    INFO     Creating training-job with name:                                       ]8;id=86716;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/session.py\session.py]8;;\:]8;id=597608;file:///home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/sagemaker/session.py#1042\1042]8;;\
                             quotes-text-gen-train-2025-03-06-09-15-34-558

2025-03-06 09:15:35 Starting - Starting the training job...
..25-03-06 09:15:55 Starting - Preparing the instances for training.
..25-03-06 09:16:23 Downloading - Downloading input data.
....................Downloading - Downloading the training image.
.bash: cannot set terminal process group (-1): Inappropriate ioctl for device..
bash: no job control in this shell
2025-03-06 09:20:49,885 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2025-03-06 09:20:49,905 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-06 09:20:49,916 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2025-03-06 09:20:49,923 sagemaker_pytorch_container.training INFO     Invoking user training script.
2025-03-06 09:20:51,850 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 6.3 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.29.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-19.0.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 8.4 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.8.61-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.1 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 133.9 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 46.2 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 59.9 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 79.8 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 65.6 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.2 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 114.7 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 95.7 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 95.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 35.4 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 63.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 23.7 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 14.1 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 23.8 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 24.7 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 20.7 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.29.2-py3-none-any.whl (468 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.1/468.1 kB 67.5 MB/s eta 0:00:00
Downloading pyarrow-19.0.1-cp310-cp310-manylinux_2_28_x86_64.whl (42.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 MB 70.1 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 16.1 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 71.7 MB/s eta 0:00:00
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 124.8 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 20.9 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 42.2 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.8.61-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.2/39.2 MB 75.4 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 huggingface-hub-0.29.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.8.61 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-19.0.1 requests-2.32.3 safetensors-0.5.3 tokenizers-0.21.0 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.1 transformers-4.49.0 triton-2.2.0 xxhash-3.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
2025-03-06 09:23:19,050 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2025-03-06 09:23:19,050 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2025-03-06 09:23:19,092 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-06 09:23:19,125 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-06 09:23:19,158 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2025-03-06 09:23:19,170 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 8,
        "ckpt": "facebook/opt-350m",
        "environ": "aws",
        "grad_accum_steps": 1,
        "lrate": 0.0009,
        "num_epochs": 30,
        "peft": "peft_retrain",
        "quant_bits": 0
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "train": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "instance_groups": [
        "homogeneousCluster"
    ],
    "instance_groups_dict": {