In [1]:
try:
    import transformers
    import datasets
    from transformers import BitsAndBytesConfig
    from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model
    from peft import TaskType, PeftConfig, PeftModel 
except:
    print("all or at least one of the package not installed. Installing now. Please remember to restart kernel once done")
    !pip install transformers bitsandbytes accelerate peft
    !pip install datasets==3.3.2

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

In [2]:
from datasets import load_dataset
from transformers import AutoTokenizer
from transformers import AutoModelForCausalLM

In [3]:
import torch
from torch.utils.data import DataLoader, Dataset

from functools import partial

# TODO: Import any packages that you might need
#importing the "King" library :P
import sagemaker
import boto3
from sagemaker.inputs import TrainingInput

#sagemaker pytorch container estimator related libraries
from sagemaker.pytorch import PyTorch
from sagemaker.pytorch import PyTorchModel


from sagemaker.estimator import Estimator
from sagemaker.model import Model
from sagemaker.predictor import Predictor

#general utility imports
import os
import glob
import pandas as pd
import numpy as np
import random

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/ec2-user/.config/sagemaker/config.yaml

In [4]:
ds = load_dataset("ingeniumacademy/reuters_articles")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/698 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/8.13M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/1.12M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/827k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/17262 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2158 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2158 [00:00<?, ? examples/s]

In [5]:
ds

DatasetDict({
    train: Dataset({
        features: ['title', 'body'],
        num_rows: 17262
    })
    validation: Dataset({
        features: ['title', 'body'],
        num_rows: 2158
    })
    test: Dataset({
        features: ['title', 'body'],
        num_rows: 2158
    })
})

In [6]:
def create_full_article_col(row):
    full_article = f'TITLE: {row["title"]}\n\nBODY: {row["body"]}'
    return {'full_article': full_article}

In [7]:
ds_1 = ds.map(create_full_article_col)
ds_1

Map:   0%|          | 0/17262 [00:00<?, ? examples/s]

Map:   0%|          | 0/2158 [00:00<?, ? examples/s]

Map:   0%|          | 0/2158 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'body', 'full_article'],
        num_rows: 17262
    })
    validation: Dataset({
        features: ['title', 'body', 'full_article'],
        num_rows: 2158
    })
    test: Dataset({
        features: ['title', 'body', 'full_article'],
        num_rows: 2158
    })
})

In [8]:
print(ds_1['train'][1]['full_article'])

TITLE: STANDARD OIL <SRD> TO FORM FINANCIAL UNIT

BODY: Standard Oil Co and BP North America
Inc said they plan to form a venture to manage the money market
borrowing and investment activities of both companies.
    BP North America is a subsidiary of British Petroleum Co
Plc <BP>, which also owns a 55 pct interest in Standard Oil.
    The venture will be called BP/Standard Financial Trading
and will be operated by Standard Oil under the oversight of a
joint management committee.

 Reuter


In [9]:
print(ds_1['train'][3]['full_article'])

TITLE: TALKING POINT/BANKAMERICA <BAC> EQUITY OFFER

BODY: BankAmerica Corp is not under
pressure to act quickly on its proposed equity offering and
would do well to delay it because of the stock's recent poor
performance, banking analysts said.
    Some analysts said they have recommended BankAmerica delay
its up to one-billion-dlr equity offering, which has yet to be
approved by the Securities and Exchange Commission.
    BankAmerica stock fell this week, along with other banking
issues, on the news that Brazil has suspended interest payments
on a large portion of its foreign debt.
    The stock traded around 12, down 1/8, this afternoon,
after falling to 11-1/2 earlier this week on the news.
    Banking analysts said that with the immediate threat of the
First Interstate Bancorp <I> takeover bid gone, BankAmerica is
under no pressure to sell the securities into a market that
will be nervous on bank stocks in the near term.
    BankAmerica filed the offer on January 26. It was seen as
one of the major factors leading the First Interstate
withdrawing its takeover bid on February 9.
    A BankAmerica spokesman said SEC approval is taking longer
than expected and market conditions must now be re-evaluated.
    "The circumstances at the time will determine what we do,"
said Arthur Miller, BankAmerica's Vice President for Financial
Communications, when asked if BankAmerica would proceed with
the offer immediately after it receives SEC approval.
    "I'd put it off as long as they conceivably could," said
Lawrence Cohn, analyst with Merrill Lynch, Pierce, Fenner and
Smith.
    Cohn said the longer BankAmerica waits, the longer they
have to show the market an improved financial outlook.
    Although BankAmerica has yet to specify the types of
equities it would offer, most analysts believed a convertible
preferred stock would encompass at least part of it.
    Such an offering at a depressed stock price would mean a
lower conversion price and more dilution to BankAmerica stock
holders, noted Daniel Williams, analyst with Sutro Group.
    Several analysts said that while they believe the Brazilian
debt problem will continue to hang over the banking industry
through the quarter, the initial shock reaction is likely to
ease over the coming weeks.
    Nevertheless, BankAmerica, which holds about 2.70 billion
dlrs in Brazilian loans, stands to lose 15-20 mln dlrs if the
interest rate is reduced on the debt, and as much as 200 mln
dlrs if Brazil pays no interest for a year, said Joseph
Arsenio, analyst with Birr, Wilson and Co.
    He noted, however, that any potential losses would not show
up in the current quarter.
    With other major banks standing to lose even more than
BankAmerica if Brazil fails to service its debt, the analysts
said they expect the debt will be restructured, similar to way
Mexico's debt was, minimizing losses to the creditor banks.
 Reuter


In [10]:
ckpt = 'gpt2-medium'
tokenizer = AutoTokenizer.from_pretrained(ckpt)
tokenizer

config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

GPT2Tokenizer(name_or_path='gpt2-medium', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
})

In [11]:
tokenizer.pad_token, tokenizer.eos_token

(None, '<|endoftext|>')

In [12]:
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token, tokenizer.eos_token

('<|endoftext|>', '<|endoftext|>')

In [13]:
tokenizer.encode('<|endoftext|>')

[50256]

In [14]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [15]:
from torchinfo import summary

In [16]:
config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16
)

In [17]:
quantization_config = BitsAndBytesConfig(
                load_in_8bit=True,
                )

In [18]:
gpt2_med_model_4bit = AutoModelForCausalLM.from_pretrained(ckpt, quantization_config=config)
gp2_med_model_8bit = AutoModelForCausalLM.from_pretrained(ckpt, quantization_config=quantization_config)

#this ran successfully in gpu instance so should be ok

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

model.safetensors:   0%|          | 0.00/1.52G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

In [19]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [20]:
def net(args, ckpt, quant_bits, device):
    config = None
    lora_config = LoraConfig(
        lora_alpha=32,
        lora_dropout=0.1,
        r=16,
        task_type="CAUSAL_LM" # TaskType.CAUSAL_LM",
        )
    config_4bit = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.float16
        )
    config_8bit = BitsAndBytesConfig(
        load_in_8bit=True,
        )
    orig_model = AutoModelForCausalLM.from_pretrained(ckpt)
    orig_model.config.pad_token_id = orig_model.config.eos_token_id
    if args == "lora":
        if quant_bits == 4:
            config = config_4bit
        elif quant_bits == 8:
            config = config_8bit
        else:
            config = None

    if config:
        print("Model Quantization requested")
        quant_model = AutoModelForCausalLM.from_pretrained(
            ckpt, 
            quantization_config=config
            )
        quant_model.config.pad_token_id = quant_model.config.eos_token_id
        quant_model.gradient_checkpointing_enable()
        quant_model = prepare_model_for_kbit_training(quant_model)
        model = get_peft_model(quant_model, lora_config)
    elif args == "lora":
        print("Only PEFT. No Model Quantization requested")
        model = get_peft_model(orig_model, lora_config)
    else:
        print("NO PEFT. No Model Quantization requested")
        model = orig_model

    s = summary(model)
    print(f"Total number of trainable parameters: {s.__dict__['trainable_params']}")
    model.to(device)
    return model

s=summary(model)
print(s.__dict__['total_params']) #: 406286336,
print(s.__dict__['trainable_params']) #: 406286336,
print(s.__dict__['total_param_bytes']) #: 1625145344,

s.__dic

In [21]:
args = "lora"
ckpt = "gpt2-medium"
quant_bits = 4

In [22]:
model = net(args, ckpt, quant_bits, device)

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Model Quantization requested

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Total number of trainable parameters: 1572864

In [23]:
model

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): GPT2LMHeadModel(
      (transformer): GPT2Model(
        (wte): Embedding(50257, 1024)
        (wpe): Embedding(1024, 1024)
        (drop): Dropout(p=0.1, inplace=False)
        (h): ModuleList(
          (0-23): 24 x GPT2Block(
            (ln_1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): GPT2Attention(
              (c_attn): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1024, out_features=3072, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=3072, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (c_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
              (attn_dropout): Dropout(p=0.1, inplace=False)
              (resid_dropout): Dropout(p=0.1, inplace=False)
            )
            (ln_2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): GPT2MLP(
              (c_fc): Linear4bit(in_features=1024, out_features=4096, bias=True)
              (c_proj): Linear4bit(in_features=4096, out_features=1024, bias=True)
              (act): NewGELUActivation()
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
        )
        (ln_f): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
      (lm_head): Linear(in_features=1024, out_features=50257, bias=False)
    )
  )
)

In [24]:
args = "lora"
ckpt = "gpt2-medium"
quant_bits = 8

In [25]:
del model
model = net(args, ckpt, quant_bits, device)

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Model Quantization requested

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Total number of trainable parameters: 1572864

In [26]:
model

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): GPT2LMHeadModel(
      (transformer): GPT2Model(
        (wte): Embedding(50257, 1024)
        (wpe): Embedding(1024, 1024)
        (drop): Dropout(p=0.1, inplace=False)
        (h): ModuleList(
          (0-23): 24 x GPT2Block(
            (ln_1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): GPT2Attention(
              (c_attn): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=1024, out_features=3072, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=3072, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (c_proj): Linear8bitLt(in_features=1024, out_features=1024, bias=True)
              (attn_dropout): Dropout(p=0.1, inplace=False)
              (resid_dropout): Dropout(p=0.1, inplace=False)
            )
            (ln_2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): GPT2MLP(
              (c_fc): Linear8bitLt(in_features=1024, out_features=4096, bias=True)
              (c_proj): Linear8bitLt(in_features=4096, out_features=1024, bias=True)
              (act): NewGELUActivation()
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
        )
        (ln_f): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
      (lm_head): Linear(in_features=1024, out_features=50257, bias=False)
    )
  )
)

In [27]:
args = "lora"
ckpt = "gpt2-medium"
quant_bits = 0

In [28]:
del model
model = net(args, ckpt, quant_bits, device)

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Only PEFT. No Model Quantization requested
Total number of trainable parameters: 1572864

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/peft/tuners/lora/layer.py:2504: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

In [29]:
model

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): GPT2LMHeadModel(
      (transformer): GPT2Model(
        (wte): Embedding(50257, 1024)
        (wpe): Embedding(1024, 1024)
        (drop): Dropout(p=0.1, inplace=False)
        (h): ModuleList(
          (0-23): 24 x GPT2Block(
            (ln_1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (attn): GPT2Attention(
              (c_attn): lora.Linear(
                (base_layer): Conv1D(nf=3072, nx=1024)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=3072, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (c_proj): Conv1D(nf=1024, nx=1024)
              (attn_dropout): Dropout(p=0.1, inplace=False)
              (resid_dropout): Dropout(p=0.1, inplace=False)
            )
            (ln_2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): GPT2MLP(
              (c_fc): Conv1D(nf=4096, nx=1024)
              (c_proj): Conv1D(nf=1024, nx=4096)
              (act): NewGELUActivation()
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
        )
        (ln_f): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
      (lm_head): Linear(in_features=1024, out_features=50257, bias=False)
    )
  )
)

In [30]:
args = None
ckpt = "gpt2-medium"
quant_bits = 0

In [31]:
del model
model = net(args, ckpt, quant_bits, device)

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

NO PEFT. No Model Quantization requested
Total number of trainable parameters: 406286336

In [32]:
args = "lora"
ckpt = "gpt2"
quant_bits = 4

In [33]:
del model
model = net(args, ckpt, quant_bits, device)

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Model Quantization requested

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Total number of trainable parameters: 589824

In [34]:
args = "lora"
ckpt = "gpt2"
quant_bits = 8

In [35]:
del model
model = net(args, ckpt, quant_bits, device)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Model Quantization requested

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Total number of trainable parameters: 589824

In [36]:
args = "lora"
ckpt = "gpt2"
quant_bits = 0

In [37]:
del model
model = net(args, ckpt, quant_bits, device)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Only PEFT. No Model Quantization requested
Total number of trainable parameters: 589824

In [38]:
args = None
ckpt = "gpt2"
quant_bits = 0

In [39]:
del model
model = net(args, ckpt, quant_bits, device)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

NO PEFT. No Model Quantization requested
Total number of trainable parameters: 163037184

In [40]:
df = ds_1['train'].to_pandas()

In [41]:
df['full_article'].describe()

count                 17262
unique                16338
top       TITLE: \n\nBODY:
freq                    718
Name: full_article, dtype: object

In [42]:
len(df)

17262

In [43]:
df

,title,body,full_article
0,BAHIA COCOA REVIEW,Showers continued throughout the week in\nthe ...,TITLE: BAHIA COCOA REVIEW\n\nBODY: Showers con...
1,STANDARD OIL <SRD> TO FORM FINANCIAL UNIT,Standard Oil Co and BP North America\nInc said...,TITLE: STANDARD OIL <SRD> TO FORM FINANCIAL UN...
2,TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN,Texas Commerce Bancshares Inc's Texas\nCommerc...,TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES P...
3,TALKING POINT/BANKAMERICA <BAC> EQUITY OFFER,BankAmerica Corp is not under\npressure to act...,TITLE: TALKING POINT/BANKAMERICA <BAC> EQUITY ...
4,NATIONAL AVERAGE PRICES FOR FARMER-OWNED RESERVE,The U.S. Agriculture Department\nreported the ...,TITLE: NATIONAL AVERAGE PRICES FOR FARMER-OWNE...
...,...,...,...
17257,BANK OF JAPAN TO SELL 600 BILLION YEN IN BILLS,The Bank of Japan will sell 600 billion\nyen i...,TITLE: BANK OF JAPAN TO SELL 600 BILLION YEN I...
17258,"FURTHER TERM FOR POEHL LIKELY, BONN SOURCES SAY",Karl Otto Poehl is likely to be re-elected\nPr...,"TITLE: FURTHER TERM FOR POEHL LIKELY, BONN SOU..."
17259,TAIWAN ISSUES MORE CDS TO CURB MONEY SUPPLY GR...,The central bank issued 7.53 billion\nTaiwan d...,TITLE: TAIWAN ISSUES MORE CDS TO CURB MONEY SU...
17260,JAPAN HOLDS OUT PROMISE OF FUNDS FOR ASIAN BANK,Japanese Finance Minister Kiichi\nMiyazawa ope...,TITLE: JAPAN HOLDS OUT PROMISE OF FUNDS FOR AS...
17261,NIPPON STEEL NOMINATES NEW PRESIDENT,Nippon Steel Corp <NSTC.T> nominated\nHiroshi ...,TITLE: NIPPON STEEL NOMINATES NEW PRESIDENT\n\...

In [44]:
df.columns

Index(['title', 'body', 'full_article'], dtype='object')

In [45]:
tokenizer.encode(tokenizer.eos_token)

[50256]

In [46]:
class dset(Dataset):
    def __init__(self, df, tokenizer, max_length):
        super().__init__()
        self.data = df['full_article']
        self.tokenizer = tokenizer
        self.eos_tokid = tokenizer.encode(tokenizer.eos_token)
        self.max_length = max_length

    
    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        x = self.data.iloc[idx]
        x = self.tokenizer(x, max_length=self.max_length, truncation=True)
        y = x['input_ids'][1:] + self.eos_tokid
        return x, y

In [47]:
ds = dset(df, tokenizer, 512)

In [48]:
len(ds)

17262

In [49]:
ds[0][0]

{'input_ids': [49560, 2538, 25, 347, 18429, 3539, 327, 4503, 23621, 4526, 28206, 198, 198, 33, 33076, 25, 911, 3618, 3767, 3690, 262, 1285, 287, 198, 1169, 13081, 544, 35845, 6516, 11, 23863, 26336, 262, 18393, 1201, 1903, 198, 21339, 290, 10068, 13285, 329, 262, 2406, 10042, 5488, 11, 198, 16670, 3487, 27716, 2974, 423, 407, 587, 15032, 11, 198, 5377, 747, 10312, 4176, 531, 287, 663, 10273, 2423, 13, 198, 220, 220, 220, 383, 5894, 2278, 1724, 262, 10042, 5488, 481, 307, 2739, 428, 614, 13, 198, 220, 220, 220, 27350, 12786, 329, 262, 1285, 4444, 3945, 2534, 547, 20708, 11, 26115, 11668, 198, 1659, 3126, 8769, 418, 1642, 257, 23818, 2472, 329, 262, 1622, 286, 642, 13, 6052, 198, 4029, 77, 1028, 642, 13, 6659, 379, 262, 976, 3800, 938, 614, 13, 6521, 340, 2331, 198, 5562, 35845, 6793, 2961, 319, 762, 16747, 373, 3017, 287, 262, 198, 283, 380, 12786, 5538, 13, 198, 220, 220, 220, 955, 747, 10312, 4176, 531, 612, 318, 991, 617, 4719, 355, 284, 703, 198, 29482, 1468, 13833, 35845, 318, 991, 1695, 355, 34102, 468, 198, 29152, 1146, 1282, 284, 281, 886, 13, 2080, 2472, 13081, 544, 13833, 7746, 198, 14145, 718, 13, 19, 285, 18755, 11668, 290, 4200, 5055, 379, 2048, 718, 13, 17, 285, 18755, 612, 198, 533, 257, 1178, 3470, 7319, 11668, 991, 287, 262, 2832, 286, 9818, 11, 198, 27171, 3653, 11, 1033, 3816, 290, 20399, 13, 198, 220, 220, 220, 1318, 389, 17188, 355, 284, 703, 881, 286, 428, 35845, 561, 307, 4197, 198, 1640, 10784, 355, 427, 16415, 389, 783, 13456, 288, 811, 586, 444, 287, 198, 672, 7339, 1343, 47514, 544, 9098, 10, 20835, 13, 198, 220, 220, 220, 554, 1570, 286, 262, 2793, 3081, 625, 2274, 2745, 9818, 423, 198, 24120, 257, 922, 636, 286, 511, 35845, 2714, 319, 762, 16747, 13, 198, 220, 220, 220, 955, 747, 10312, 4176, 531, 4136, 26394, 4536, 8278, 284, 28560, 284, 13803, 198, 32838, 89, 22484, 583, 610, 305, 7012, 286, 1315, 8769, 418, 13, 198, 220, 220, 220, 26510, 427, 16415, 547, 18416, 284, 2897, 6716, 28652, 290, 198, 8807, 3614, 4200, 547, 21765, 329, 2805, 28652, 379, 352, 11, 15426, 284, 198, 16, 11, 40873, 288, 75, 3808, 583, 5680, 710, 284, 14090, 284, 307, 3706, 13, 198, 220, 220, 220, 968, 13833, 4200, 547, 635, 1657, 290, 477, 284, 1280, 14090, 351, 198, 15749, 14, 16157, 1016, 379, 352, 11, 25764, 290, 352, 11, 41655, 288, 75, 3808, 290, 379, 3439, 290, 4153, 288, 75, 3808, 198, 4625, 968, 1971, 474, 2062, 11, 2447, 14, 14635, 379, 352, 11, 46951, 11, 352, 11, 31360, 290, 352, 11, 41655, 288, 75, 3808, 198, 525, 5680, 710, 376, 9864, 13, 198, 220, 220, 220, 371, 28399, 4200, 286, 9215, 547, 925, 13, 2805, 14, 16784, 2702, 379, 198, 19, 11, 23601, 11, 604, 11, 27712, 290, 604, 11, 14877, 288, 75, 3808, 13, 198, 220, 220, 220, 3035, 14, 6747, 9215, 1816, 379, 362, 13, 1983, 1661, 968, 1971, 1737, 11, 2795, 14, 16157, 198, 265, 604, 11, 7029, 290], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [50]:
ds[0][1]

[2538,
 25,
 347,
 18429,
 3539,
 327,
 4503,
 23621,
 4526,
 28206,
 198,
 198,
 33,
 33076,
 25,
 911,
 3618,
 3767,
 3690,
 262,
 1285,
 287,
 198,
 1169,
 13081,
 544,
 35845,
 6516,
 11,
 23863,
 26336,
 262,
 18393,
 1201,
 1903,
 198,
 21339,
 290,
 10068,
 13285,
 329,
 262,
 2406,
 10042,
 5488,
 11,
 198,
 16670,
 3487,
 27716,
 2974,
 423,
 407,
 587,
 15032,
 11,
 198,
 5377,
 747,
 10312,
 4176,
 531,
 287,
 663,
 10273,
 2423,
 13,
 198,
 220,
 220,
 220,
 383,
 5894,
 2278,
 1724,
 262,
 10042,
 5488,
 481,
 307,
 2739,
 428,
 614,
 13,
 198,
 220,
 220,
 220,
 27350,
 12786,
 329,
 262,
 1285,
 4444,
 3945,
 2534,
 547,
 20708,
 11,
 26115,
 11668,
 198,
 1659,
 3126,
 8769,
 418,
 1642,
 257,
 23818,
 2472,
 329,
 262,
 1622,
 286,
 642,
 13,
 6052,
 198,
 4029,
 77,
 1028,
 642,
 13,
 6659,
 379,
 262,
 976,
 3800,
 938,
 614,
 13,
 6521,
 340,
 2331,
 198,
 5562,
 35845,
 6793,
 2961,
 319,
 762,
 16747,
 373,
 3017,
 287,
 262,
 198,
 283,
 380,
 12786,
 5538,
 13,
 198,
 220,
 220,
 220,
 955,
 747,
 10312,
 4176,
 531,
 612,
 318,
 991,
 617,
 4719,
 355,
 284,
 703,
 198,
 29482,
 1468,
 13833,
 35845,
 318,
 991,
 1695,
 355,
 34102,
 468,
 198,
 29152,
 1146,
 1282,
 284,
 281,
 886,
 13,
 2080,
 2472,
 13081,
 544,
 13833,
 7746,
 198,
 14145,
 718,
 13,
 19,
 285,
 18755,
 11668,
 290,
 4200,
 5055,
 379,
 2048,
 718,
 13,
 17,
 285,
 18755,
 612,
 198,
 533,
 257,
 1178,
 3470,
 7319,
 11668,
 991,
 287,
 262,
 2832,
 286,
 9818,
 11,
 198,
 27171,
 3653,
 11,
 1033,
 3816,
 290,
 20399,
 13,
 198,
 220,
 220,
 220,
 1318,
 389,
 17188,
 355,
 284,
 703,
 881,
 286,
 428,
 35845,
 561,
 307,
 4197,
 198,
 1640,
 10784,
 355,
 427,
 16415,
 389,
 783,
 13456,
 288,
 811,
 586,
 444,
 287,
 198,
 672,
 7339,
 1343,
 47514,
 544,
 9098,
 10,
 20835,
 13,
 198,
 220,
 220,
 220,
 554,
 1570,
 286,
 262,
 2793,
 3081,
 625,
 2274,
 2745,
 9818,
 423,
 198,
 24120,
 257,
 922,
 636,
 286,
 511,
 35845,
 2714,
 319,
 762,
 16747,
 13,
 198,
 220,
 220,
 220,
 955,
 747,
 10312,
 4176,
 531,
 4136,
 26394,
 4536,
 8278,
 284,
 28560,
 284,
 13803,
 198,
 32838,
 89,
 22484,
 583,
 610,
 305,
 7012,
 286,
 1315,
 8769,
 418,
 13,
 198,
 220,
 220,
 220,
 26510,
 427,
 16415,
 547,
 18416,
 284,
 2897,
 6716,
 28652,
 290,
 198,
 8807,
 3614,
 4200,
 547,
 21765,
 329,
 2805,
 28652,
 379,
 352,
 11,
 15426,
 284,
 198,
 16,
 11,
 40873,
 288,
 75,
 3808,
 583,
 5680,
 710,
 284,
 14090,
 284,
 307,
 3706,
 13,
 198,
 220,
 220,
 220,
 968,
 13833,
 4200,
 547,
 635,
 1657,
 290,
 477,
 284,
 1280,
 14090,
 351,
 198,
 15749,
 14,
 16157,
 1016,
 379,
 352,
 11,
 25764,
 290,
 352,
 11,
 41655,
 288,
 75,
 3808,
 290,
 379,
 3439,
 290,
 4153,
 288,
 75,
 3808,
 198,
 4625,
 968,
 1971,
 474,
 2062,
 11,
 2447,
 14,
 14635,
 379,
 352,
 11,
 46951,
 11,
 352,
 11,
 31360,
 290,
 352,
 11,
 41655,
 288,
 75,
 3808,
 198,
 525,
 5680,
 710,
 376,
 9864,
 13,
 198,
 220,
 220,
 220,
 371,
 28399,
 4200,
 286,
 9215,
 547,
 925,
 13,
 2805,
 14,
 16784,
 2702,
 379,
 198,
 19,
 11,
 23601,
 11,
 604,
 11,
 27712,
 290,
 604,
 11,
 14877,
 288,
 75,
 3808,
 13,
 198,
 220,
 220,
 220,
 3035,
 14,
 6747,
 9215,
 1816,
 379,
 362,
 13,
 1983,
 1661,
 968,
 1971,
 1737,
 11,
 2795,
 14,
 16157,
 198,
 265,
 604,
 11,
 7029,
 290,
 50256]

In [51]:
ds[1][0]['input_ids'][1:] == ds[1][1][:-1]

True

In [52]:
type(ds[1][0]['input_ids'])

list

In [53]:
type(ds[1][1])

list

In [54]:
len(ds[0])

2

In [55]:
def collate_fn(batch, device, tokenizer):
    pad_tokenid = tokenizer.encode(tokenizer.eos_token)
    inp_list, att_list, y_list = [],  [], []
    print(batch)
    len_labs =  [len(l) for i, l in batch]
    print(len_labs)
    max_len = max(len_labs)
    print(f'Max Length is {max_len}')
    for _text, _label in batch:
        inp_ids = _text['input_ids']
        am = _text['attention_mask']
        label = _label
        if len(inp_ids) < max_len:
            deficit = max_len - len(inp_ids)
            inp_ids = inp_ids + pad_tokenid*deficit
            am = am + [0]*deficit
            label = label + [-100]*deficit
        inp_list.append(torch.tensor(inp_ids))
        att_list.append(torch.tensor(am))
        y_list.append(torch.tensor(label))
    input_ids = torch.vstack(inp_list)
    input_ids = input_ids.to(device)
    attention_mask = torch.vstack(att_list)
    attention_mask = attention_mask.to(device)
    labels = torch.vstack(y_list)
    labels = labels.to(device)
    return {'input_ids': input_ids, 'attention_mask': attention_mask}, labels

In [56]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [57]:
wrapper_collate_fn = partial(
    collate_fn,
    device=device,
    tokenizer=tokenizer
)

In [58]:
tokenizer

GPT2Tokenizer(name_or_path='gpt2-medium', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
})

In [59]:
dl = DataLoader(ds, shuffle=False, batch_size=2, collate_fn=wrapper_collate_fn)

In [60]:
iter_dl = iter(dl)

In [61]:
i,l = next(iter_dl)

[({'input_ids': [49560, 2538, 25, 347, 18429, 3539, 327, 4503, 23621, 4526, 28206, 198, 198, 33, 33076, 25, 911, 3618, 3767, 3690, 262, 1285, 287, 198, 1169, 13081, 544, 35845, 6516, 11, 23863, 26336, 262, 18393, 1201, 1903, 198, 21339, 290, 10068, 13285, 329, 262, 2406, 10042, 5488, 11, 198, 16670, 3487, 27716, 2974, 423, 407, 587, 15032, 11, 198, 5377, 747, 10312, 4176, 531, 287, 663, 10273, 2423, 13, 198, 220, 220, 220, 383, 5894, 2278, 1724, 262, 10042, 5488, 481, 307, 2739, 428, 614, 13, 198, 220, 220, 220, 27350, 12786, 329, 262, 1285, 4444, 3945, 2534, 547, 20708, 11, 26115, 11668, 198, 1659, 3126, 8769, 418, 1642, 257, 23818, 2472, 329, 262, 1622, 286, 642, 13, 6052, 198, 4029, 77, 1028, 642, 13, 6659, 379, 262, 976, 3800, 938, 614, 13, 6521, 340, 2331, 198, 5562, 35845, 6793, 2961, 319, 762, 16747, 373, 3017, 287, 262, 198, 283, 380, 12786, 5538, 13, 198, 220, 220, 220, 955, 747, 10312, 4176, 531, 612, 318, 991, 617, 4719, 355, 284, 703, 198, 29482, 1468, 13833, 35845, 318, 991, 1695, 355, 34102, 468, 198, 29152, 1146, 1282, 284, 281, 886, 13, 2080, 2472, 13081, 544, 13833, 7746, 198, 14145, 718, 13, 19, 285, 18755, 11668, 290, 4200, 5055, 379, 2048, 718, 13, 17, 285, 18755, 612, 198, 533, 257, 1178, 3470, 7319, 11668, 991, 287, 262, 2832, 286, 9818, 11, 198, 27171, 3653, 11, 1033, 3816, 290, 20399, 13, 198, 220, 220, 220, 1318, 389, 17188, 355, 284, 703, 881, 286, 428, 35845, 561, 307, 4197, 198, 1640, 10784, 355, 427, 16415, 389, 783, 13456, 288, 811, 586, 444, 287, 198, 672, 7339, 1343, 47514, 544, 9098, 10, 20835, 13, 198, 220, 220, 220, 554, 1570, 286, 262, 2793, 3081, 625, 2274, 2745, 9818, 423, 198, 24120, 257, 922, 636, 286, 511, 35845, 2714, 319, 762, 16747, 13, 198, 220, 220, 220, 955, 747, 10312, 4176, 531, 4136, 26394, 4536, 8278, 284, 28560, 284, 13803, 198, 32838, 89, 22484, 583, 610, 305, 7012, 286, 1315, 8769, 418, 13, 198, 220, 220, 220, 26510, 427, 16415, 547, 18416, 284, 2897, 6716, 28652, 290, 198, 8807, 3614, 4200, 547, 21765, 329, 2805, 28652, 379, 352, 11, 15426, 284, 198, 16, 11, 40873, 288, 75, 3808, 583, 5680, 710, 284, 14090, 284, 307, 3706, 13, 198, 220, 220, 220, 968, 13833, 4200, 547, 635, 1657, 290, 477, 284, 1280, 14090, 351, 198, 15749, 14, 16157, 1016, 379, 352, 11, 25764, 290, 352, 11, 41655, 288, 75, 3808, 290, 379, 3439, 290, 4153, 288, 75, 3808, 198, 4625, 968, 1971, 474, 2062, 11, 2447, 14, 14635, 379, 352, 11, 46951, 11, 352, 11, 31360, 290, 352, 11, 41655, 288, 75, 3808, 198, 525, 5680, 710, 376, 9864, 13, 198, 220, 220, 220, 371, 28399, 4200, 286, 9215, 547, 925, 13, 2805, 14, 16784, 2702, 379, 198, 19, 11, 23601, 11, 604, 11, 27712, 290, 604, 11, 14877, 288, 75, 3808, 13, 198, 220, 220, 220, 3035, 14, 6747, 9215, 1816, 379, 362, 13, 1983, 1661, 968, 1971, 1737, 11, 2795, 14, 16157, 198, 265, 604, 11, 7029, 290], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}, [2538, 25, 347, 18429, 3539, 327, 4503, 23621, 4526, 28206, 198, 198, 33, 33076, 25, 911, 3618, 3767, 3690, 262, 1285, 287, 198, 1169, 13081, 544, 35845, 6516, 11, 23863, 26336, 262, 18393, 1201, 1903, 198, 21339, 290, 10068, 13285, 329, 262, 2406, 10042, 5488, 11, 198, 16670, 3487, 27716, 2974, 423, 407, 587, 15032, 11, 198, 5377, 747, 10312, 4176, 531, 287, 663, 10273, 2423, 13, 198, 220, 220, 220, 383, 5894, 2278, 1724, 262, 10042, 5488, 481, 307, 2739, 428, 614, 13, 198, 220, 220, 220, 27350, 12786, 329, 262, 1285, 4444, 3945, 2534, 547, 20708, 11, 26115, 11668, 198, 1659, 3126, 8769, 418, 1642, 257, 23818, 2472, 329, 262, 1622, 286, 642, 13, 6052, 198, 4029, 77, 1028, 642, 13, 6659, 379, 262, 976, 3800, 938, 614, 13, 6521, 340, 2331, 198, 5562, 35845, 6793, 2961, 319, 762, 16747, 373, 3017, 287, 262, 198, 283, 380, 12786, 5538, 13, 198, 220, 220, 220, 955, 747, 10312, 4176, 531, 612, 318, 991, 617, 4719, 355, 284, 703, 198, 29482, 1468, 13833, 35845, 318, 991, 1695, 355, 34102, 468, 198, 29152, 1146, 1282, 284, 281, 886, 13, 2080, 2472, 13081, 544, 13833, 7746, 198, 14145, 718, 13, 19, 285, 18755, 11668, 290, 4200, 5055, 379, 2048, 718, 13, 17, 285, 18755, 612, 198, 533, 257, 1178, 3470, 7319, 11668, 991, 287, 262, 2832, 286, 9818, 11, 198, 27171, 3653, 11, 1033, 3816, 290, 20399, 13, 198, 220, 220, 220, 1318, 389, 17188, 355, 284, 703, 881, 286, 428, 35845, 561, 307, 4197, 198, 1640, 10784, 355, 427, 16415, 389, 783, 13456, 288, 811, 586, 444, 287, 198, 672, 7339, 1343, 47514, 544, 9098, 10, 20835, 13, 198, 220, 220, 220, 554, 1570, 286, 262, 2793, 3081, 625, 2274, 2745, 9818, 423, 198, 24120, 257, 922, 636, 286, 511, 35845, 2714, 319, 762, 16747, 13, 198, 220, 220, 220, 955, 747, 10312, 4176, 531, 4136, 26394, 4536, 8278, 284, 28560, 284, 13803, 198, 32838, 89, 22484, 583, 610, 305, 7012, 286, 1315, 8769, 418, 13, 198, 220, 220, 220, 26510, 427, 16415, 547, 18416, 284, 2897, 6716, 28652, 290, 198, 8807, 3614, 4200, 547, 21765, 329, 2805, 28652, 379, 352, 11, 15426, 284, 198, 16, 11, 40873, 288, 75, 3808, 583, 5680, 710, 284, 14090, 284, 307, 3706, 13, 198, 220, 220, 220, 968, 13833, 4200, 547, 635, 1657, 290, 477, 284, 1280, 14090, 351, 198, 15749, 14, 16157, 1016, 379, 352, 11, 25764, 290, 352, 11, 41655, 288, 75, 3808, 290, 379, 3439, 290, 4153, 288, 75, 3808, 198, 4625, 968, 1971, 474, 2062, 11, 2447, 14, 14635, 379, 352, 11, 46951, 11, 352, 11, 31360, 290, 352, 11, 41655, 288, 75, 3808, 198, 525, 5680, 710, 376, 9864, 13, 198, 220, 220, 220, 371, 28399, 4200, 286, 9215, 547, 925, 13, 2805, 14, 16784, 2702, 379, 198, 19, 11, 23601, 11, 604, 11, 27712, 290, 604, 11, 14877, 288, 75, 3808, 13, 198, 220, 220, 220, 3035, 14, 6747, 9215, 1816, 379, 362, 13, 1983, 1661, 968, 1971, 1737, 11, 2795, 14, 16157, 198, 265, 604, 11, 7029, 290, 50256]), ({'input_ids': [49560, 2538, 25, 49053, 9795, 440, 4146, 1279, 12562, 35, 29, 5390, 49144, 33642, 20940, 12576, 4725, 2043, 198, 198, 33, 33076, 25, 8997, 11474, 1766, 290, 20997, 2258, 2253, 198, 25517, 531, 484, 1410, 284, 1296, 257, 13189, 284, 6687, 262, 1637, 1910, 198, 2865, 11577, 290, 4896, 4568, 286, 1111, 2706, 13, 198, 220, 220, 220, 20997, 2258, 2253, 318, 257, 22347, 286, 3517, 39970, 1766, 198, 3646, 66, 1279, 20866, 22330, 543, 635, 12216, 257, 5996, 279, 310, 1393, 287, 8997, 11474, 13, 198, 220, 220, 220, 383, 13189, 481, 307, 1444, 20997, 14, 23615, 11302, 25469, 198, 392, 481, 307, 12228, 416, 8997, 11474, 739, 262, 15662, 286, 257, 198, 73, 1563, 4542, 5583, 13, 628, 797, 11894, 198, 191], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}, [2538, 25, 49053, 9795, 440, 4146, 1279, 12562, 35, 29, 5390, 49144, 33642, 20940, 12576, 4725, 2043, 198, 198, 33, 33076, 25, 8997, 11474, 1766, 290, 20997, 2258, 2253, 198, 25517, 531, 484, 1410, 284, 1296, 257, 13189, 284, 6687, 262, 1637, 1910, 198, 2865, 11577, 290, 4896, 4568, 286, 1111, 2706, 13, 198, 220, 220, 220, 20997, 2258, 2253, 318, 257, 22347, 286, 3517, 39970, 1766, 198, 3646, 66, 1279, 20866, 22330, 543, 635, 12216, 257, 5996, 279, 310, 1393, 287, 8997, 11474, 13, 198, 220, 220, 220, 383, 13189, 481, 307, 1444, 20997, 14, 23615, 11302, 25469, 198, 392, 481, 307, 12228, 416, 8997, 11474, 739, 262, 15662, 286, 257, 198, 73, 1563, 4542, 5583, 13, 628, 797, 11894, 198, 191, 50256])]
[512, 124]
Max Length is 512

In [62]:
i['input_ids'].shape, i['attention_mask'].shape, l.shape

(torch.Size([2, 512]), torch.Size([2, 512]), torch.Size([2, 512]))

In [63]:
i['input_ids']

tensor([[49560,  2538,    25,  ...,    11,  7029,   290],
        [49560,  2538,    25,  ..., 50256, 50256, 50256]], device='cuda:0')

In [64]:
i['attention_mask']

tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0')

In [65]:
i['input_ids'] = i['input_ids'].to(device)
i['attention_mask'] = i['attention_mask'].to(device)

In [66]:
out = model(**i)

In [67]:
out.logits.shape, out

(torch.Size([2, 512, 50257]),
 CausalLMOutputWithCrossAttentions(loss=None, logits=tensor([[[ -32.5351,  -31.3880,  -33.9832,  ...,  -42.8560,  -42.2166,
            -33.0416],
          [ -91.4329,  -90.0395,  -91.3562,  ..., -102.3688, -100.5219,
            -92.0736],
          [ -69.2479,  -68.6931,  -68.9566,  ...,  -76.6611,  -75.7209,
            -66.8522],
          ...,
          [-101.0089,  -99.4432,  -99.8513,  ..., -107.8896, -108.4641,
            -97.9067],
          [ -50.4815,  -52.6545,  -53.9596,  ...,  -59.7929,  -60.0427,
            -49.6024],
          [ -77.5360,  -78.3590,  -79.1278,  ...,  -85.0720,  -82.5483,
            -74.6692]],

         [[ -32.5351,  -31.3880,  -33.9832,  ...,  -42.8560,  -42.2166,
            -33.0416],
          [ -91.4329,  -90.0395,  -91.3562,  ..., -102.3688, -100.5219,
            -92.0736],
          [ -69.2479,  -68.6931,  -68.9566,  ...,  -76.6611,  -75.7209,
            -66.8522],
          ...,
          [ -95.4947,  -88.2352,  -90.9241,  ..., -109.3591, -109.8787,
            -95.8424],
          [ -95.4578,  -88.2001,  -90.8870,  ..., -109.3105, -109.8292,
            -95.7959],
          [ -95.4004,  -88.1450,  -90.8289,  ..., -109.2500, -109.7739,
            -95.7464]]], device='cuda:0', grad_fn=<UnsafeViewBackward0>), past_key_values=DynamicCache(layers=[DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer]), hidden_states=None, attentions=None, cross_attentions=None))

In [68]:
tokenizer.decode([49560,  2538,    25])

'TITLE:'

In [69]:
tokenizer.decode([797, 11894,   198,   191])

' Reuter\n\x03'

In [70]:
#df.to_csv('./reuters_ds.csv', index=False)

In [71]:
vocab_size =  tokenizer.vocab_size
vocab_size

50257

#### TILL THIS POINT EXECUTE IN GPU NOTEBOOK REST EXECUTE IN T3.MEDIUM. RUN INFERENCES IN T3.XLARGE

Strategy for training experiments:
1) We have already executed full fine tuning of gpt2 model for 4 epochs
2) Next, we do 4 bit fine-tuning for gpt2 for 4 epochs and measure run times. if lesser then execute for more epochs. Max time limit : 1 hour --> 2 experiments: 1-2 hours
3) Next we do 8 bit fine-tuning for 4 epochs. Same procedure as above 1 hour
4) Next we do 4 bit for gpt2-medium followed by 8 bit. 2-3 hours
5) Next we run inference and check the quality of the outputs produced by different models- total 4 experiments

Next we do QA and summarization fine tuning from another udemy course --> instruction fine tuning
We can use karthick dataset from AWS LLM course as well

In [10]:
#Sagemaker related commands
sess = sagemaker.Session()
role = sagemaker.get_execution_role()
region = sess.boto_region_name
bucket = sess.default_bucket()
sess, role, region, bucket

(<sagemaker.session.Session at 0x7f8c8904fc10>,
 'arn:aws:iam::191013407134:role/service-role/AmazonSageMaker-ExecutionRole-20250124T222384',
 'us-east-1',
 'sagemaker-us-east-1-191013407134')

In [11]:
%pwd

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder'

In [12]:
S3_LOC = f's3://{bucket}/gpt_train/dataset/reuters/'
S3_LOC

's3://sagemaker-us-east-1-191013407134/gpt_train/dataset/reuters/'

In [13]:
#!aws s3 cp ./reuters_ds.csv {S3_LOC}

In [14]:
!aws s3 ls --recursive {S3_LOC}

2025-02-26 05:00:50   27728622 gpt_train/dataset/reuters/reuters_ds.csv

In [15]:
# let us get image uri
training_image_uri = sagemaker.image_uris.retrieve(
    framework='pytorch', 
    version='2.0',
    instance_type='ml.g4dn.xlarge',
    region=region,
    py_version='py310',
    image_scope='training'
)
print(training_image_uri)

763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.0-gpu-py310

In [16]:
train_uri = f'{S3_LOC}'
train_uri

's3://sagemaker-us-east-1-191013407134/gpt_train/dataset/reuters/'

In [17]:
s3_inp_tr = TrainingInput(
    s3_data = train_uri
    )
s3_inp_tr

In [18]:
data_channels = {
    'train': s3_inp_tr
    }
data_channels

{'train': <sagemaker.inputs.TrainingInput at 0x7f8c62049270>}

In [19]:
objective_metric_name = "average training loss"
objective_type = "Minimize"
metric_definitions = [{"Name": "average training loss", "Regex": "Average loss: ([0-9\\.]+)"},
                      {"Name": "Perplexity", "Regex": "Perplexity: ([0-9\\.]+)"}]
objective_metric_name, objective_type, metric_definitions

('average training loss',
 'Minimize',
 [{'Name': 'average training loss', 'Regex': 'Average loss: ([0-9\\.]+)'},
  {'Name': 'Perplexity', 'Regex': 'Perplexity: ([0-9\\.]+)'}])

In [20]:
ic=1
i_type = "ml.g4dn.xlarge"
ic, i_type

(1, 'ml.g4dn.xlarge')

In [21]:
%pwd

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder'

In [22]:
hparams = {
    'bs': 16,
    'lrate': 0.0006,
    'num_epochs': 4,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'gpt2',
    'quant_bits': 4,
    'peft': 'lora'
}
hparams

{'bs': 16,
 'lrate': 0.0006,
 'num_epochs': 4,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'gpt2',
 'quant_bits': 4,
 'peft': 'lora'}

In [23]:
est = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-gpt2-reuters.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='reutersgpt-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est.fit(
    inputs=data_channels,
    wait=True
)

INFO:sagemaker:Creating training-job with name: reutersgpt-train-2026-04-26-03-52-17-073

2026-04-26 03:52:17 Starting - Starting the training job...
2026-04-26 03:52:43 Starting - Preparing the instances for training...
2026-04-26 03:53:07 Downloading - Downloading input data...
2026-04-26 03:53:38 Downloading - Downloading the training image..................
2026-04-26 03:56:50 Training - Training image download completed. Training in progress...bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2026-04-26 03:57:01,940 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2026-04-26 03:57:01,958 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 03:57:01,973 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2026-04-26 03:57:01,982 sagemaker_pytorch_container.training INFO     Invoking user training script.
2026-04-26 03:57:03,948 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 6.4 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 8.9 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.26.0->transformers==4.49.0->-r requirements.txt (line 2))
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.0 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 147.3 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 39.2 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 54.6 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 60.2 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 64.5 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.2 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 113.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 97.8 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 52.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 37.3 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 54.9 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 32.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 15.3 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 21.9 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 19.6 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 21.8 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 76.9 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (48.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.8/48.8 MB 69.0 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 14.0 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 57.3 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 133.6 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 17.9 MB/s eta 0:00:00
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.3/193.3 kB 41.1 MB/s eta 0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 150.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 62.0 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 hf-xet-1.4.3 huggingface-hub-0.36.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.9.86 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-24.0.0 requests-2.33.1 safetensors-0.7.0 tokenizers-0.21.4 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.3 transformers-4.49.0 triton-2.2.0 xxhash-3.7.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
2026-04-26 03:59:37,120 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2026-04-26 03:59:37,120 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2026-04-26 03:59:37,164 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 03:59:37,197 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 03:59:37,227 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 03:59:37,239 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 16,
        "ckpt": "gpt2",

In [24]:
est.latest_training_job.describe()['FinalMetricDataList']

[{'MetricName': 'Perplexity',
  'Value': 10.314106941223145,
  'Timestamp': datetime.datetime(2026, 4, 26, 4, 50, 59, tzinfo=tzlocal())},
 {'MetricName': 'average training loss',
  'Value': 2.333512544631958,
  'Timestamp': datetime.datetime(2026, 4, 26, 4, 50, 59, tzinfo=tzlocal())}]

In [25]:
!aws s3 ls --recursive {est.model_data}

2026-04-26 04:51:17    3425537 reutersgpt-train-2026-04-26-03-52-17-073/output/model.tar.gz

In [26]:
!aws s3 cp {est.model_data} ./temp/gpt2-lora-4-bit-quant.tar.gz

download: s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-03-52-17-073/output/model.tar.gz to temp/gpt2-lora-4-bit-quant.tar.gz

In [27]:
%cd temp

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder/temp

In [28]:
!ls -ltrh

total 4.9M
-rw-rw-r-- 1 ec2-user ec2-user 756K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (2).ipynb
-rw-rw-r-- 1 ec2-user ec2-user 840K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (1).ipynb
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0384616768394737
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0191842654468437
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.00977148872375
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_2_Prplxty_9.256776574458915
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.363786833972586
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.29573556990836
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_20_Prplxty_4.906924388591055
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_30_Prplxty_3.6311811785448933
drwxrwxr-x 3 ec2-user ec2-user 4.0K Mar  5  2025 train
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz

In [29]:
#!gunzip -dc model.tar.gz |tar xvf -

In [30]:
#!ls -ltrh

##### We have some observations:
- Training run time was lower than full fine tuning --> can be attributed to gradient accumulation
- Differential model is very small (less than 4 MB)

### Experiment 2: Run GPT2 with 8 bits. We will try to use 8 steps in gradient accumulation and slightly higher learning rate

In [31]:
%cd ..
%pwd

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder'

In [32]:
hparams = {
    'bs': 16,
    'lrate': 0.0008,
    'num_epochs': 4,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'gpt2',
    'quant_bits': 8,
    'peft': 'lora',
    'grad_accum_steps': 8
}
hparams

{'bs': 16,
 'lrate': 0.0008,
 'num_epochs': 4,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'gpt2',
 'quant_bits': 8,
 'peft': 'lora',
 'grad_accum_steps': 8}

In [33]:
est_gpt2_8bit = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-gpt2-reuters.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='reutersgpt-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_gpt2_8bit.fit(
    inputs=data_channels,
    wait=True
)

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: reutersgpt-train-2026-04-26-05-01-11-367

2026-04-26 05:01:11 Starting - Starting the training job...
2026-04-26 05:01:35 Starting - Preparing the instances for training...
2026-04-26 05:02:02 Downloading - Downloading input data...
2026-04-26 05:02:33 Downloading - Downloading the training image....................
2026-04-26 05:05:50 Training - Training image download completed. Training in progress.bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2026-04-26 05:05:59,536 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2026-04-26 05:05:59,557 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 05:05:59,567 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2026-04-26 05:05:59,574 sagemaker_pytorch_container.training INFO     Invoking user training script.
2026-04-26 05:06:01,576 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 6.3 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 8.5 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.26.0->transformers==4.49.0->-r requirements.txt (line 2))
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.0 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 136.0 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 36.0 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 63.6 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 79.5 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 64.5 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.3 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 113.6 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 115.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 75.6 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 34.8 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 56.8 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 29.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 9.7 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 25.1 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 22.8 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 21.4 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 81.9 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (48.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.8/48.8 MB 70.6 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 16.6 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 77.1 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 92.1 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 18.3 MB/s eta 0:00:00
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.3/193.3 kB 38.4 MB/s eta 0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 134.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 79.2 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 hf-xet-1.4.3 huggingface-hub-0.36.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.9.86 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-24.0.0 requests-2.33.1 safetensors-0.7.0 tokenizers-0.21.4 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.3 transformers-4.49.0 triton-2.2.0 xxhash-3.7.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
2026-04-26 05:08:29,850 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2026-04-26 05:08:29,850 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2026-04-26 05:08:29,910 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 05:08:29,964 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 05:08:29,996 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 05:08:30,008 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 16,
        "ckpt": "gpt2",

In [34]:
est_gpt2_8bit.latest_training_job.describe()['FinalMetricDataList']

[{'MetricName': 'Perplexity',
  'Value': 11.32615852355957,
  'Timestamp': datetime.datetime(2026, 4, 26, 5, 57, 9, tzinfo=tzlocal())},
 {'MetricName': 'average training loss',
  'Value': 2.427114963531494,
  'Timestamp': datetime.datetime(2026, 4, 26, 5, 57, 9, tzinfo=tzlocal())}]

In [35]:
!aws s3 ls --recursive {est_gpt2_8bit.model_data}

2026-04-26 05:57:25    3425806 reutersgpt-train-2026-04-26-05-01-11-367/output/model.tar.gz

In [36]:
!aws s3 cp {est_gpt2_8bit.model_data} ./temp/gpt2-lora-8-bit-quant.tar.gz

download: s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-05-01-11-367/output/model.tar.gz to temp/gpt2-lora-8-bit-quant.tar.gz

In [37]:
%cd temp
!ls -ltrh

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder/temp
total 8.2M
-rw-rw-r-- 1 ec2-user ec2-user 756K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (2).ipynb
-rw-rw-r-- 1 ec2-user ec2-user 840K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (1).ipynb
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0384616768394737
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0191842654468437
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.00977148872375
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_2_Prplxty_9.256776574458915
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.363786833972586
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.29573556990836
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_20_Prplxty_4.906924388591055
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_30_Prplxty_3.6311811785448933
drwxrwxr-x 3 ec2-user ec2-user 4.0K Mar  5  2025 train
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 05:57 gpt2-lora-8-bit-quant.tar.gz

In [38]:
#!gunzip -dc model.tar.gz |tar xvf -
#!ls -ltrh

###### We have some observations:
- Training run time was lower than even with 4bit fine tuning --> can be attributed to gradient accumulation -8
- -Differential model is very small (less than 4 MB)
- further there is a scope for increasing gradient accumulation steps. we will explore that in peft only training

In [39]:
%cd ..
%pwd

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder'

In [40]:
hparams = {
    'bs': 16,
    'lrate': 0.0008,
    'num_epochs': 4,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'gpt2',
    'quant_bits': 0,
    'peft': 'lora',
    'grad_accum_steps': 16
    }
hparams

{'bs': 16,
 'lrate': 0.0008,
 'num_epochs': 4,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'gpt2',
 'quant_bits': 0,
 'peft': 'lora',
 'grad_accum_steps': 16}

In [41]:
est_gpt2_loraonly = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-gpt2-reuters.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='reutersgpt-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_gpt2_loraonly.fit(
    inputs=data_channels,
    wait=True
)

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: reutersgpt-train-2026-04-26-06-05-23-370

2026-04-26 06:05:27 Starting - Starting the training job...
2026-04-26 06:05:42 Starting - Preparing the instances for training...
2026-04-26 06:06:06 Downloading - Downloading input data...
2026-04-26 06:06:37 Downloading - Downloading the training image..................
2026-04-26 06:09:54 Training - Training image download completed. Training in progress..bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2026-04-26 06:10:01,602 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2026-04-26 06:10:01,624 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 06:10:01,634 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2026-04-26 06:10:01,642 sagemaker_pytorch_container.training INFO     Invoking user training script.
2026-04-26 06:10:03,465 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 5.7 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 8.6 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.26.0->transformers==4.49.0->-r requirements.txt (line 2))
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 1.9 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 152.8 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 53.4 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 46.0 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 71.8 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 64.6 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.3 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 113.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 54.6 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 103.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 38.1 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 54.7 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 27.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 14.9 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 20.1 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 23.2 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 14.2 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 83.5 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (48.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.8/48.8 MB 68.4 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 17.4 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 73.0 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 93.6 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 22.5 MB/s eta 0:00:00
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.3/193.3 kB 46.9 MB/s eta 0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 152.4 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 66.7 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 hf-xet-1.4.3 huggingface-hub-0.36.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.9.86 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-24.0.0 requests-2.33.1 safetensors-0.7.0 tokenizers-0.21.4 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.3 transformers-4.49.0 triton-2.2.0 xxhash-3.7.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
2026-04-26 06:12:24,978 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2026-04-26 06:12:24,978 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2026-04-26 06:12:25,039 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 06:12:25,071 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 06:12:25,099 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 06:12:25,110 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 16,
        "ckpt": "gpt2",

In [42]:
est_gpt2_loraonly.latest_training_job.describe()['FinalMetricDataList']

[{'MetricName': 'Perplexity',
  'Value': 12.134512901306152,
  'Timestamp': datetime.datetime(2026, 4, 26, 7, 8, 30, tzinfo=tzlocal())},
 {'MetricName': 'average training loss',
  'Value': 2.496053695678711,
  'Timestamp': datetime.datetime(2026, 4, 26, 7, 8, 30, tzinfo=tzlocal())}]

In [43]:
!aws s3 ls --recursive {est_gpt2_loraonly.model_data}

2026-04-26 07:08:47    3426530 reutersgpt-train-2026-04-26-06-05-23-370/output/model.tar.gz

In [44]:
!aws s3 cp {est_gpt2_loraonly.model_data} ./temp/gpt2-lora-noquant.tar.gz

download: s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-06-05-23-370/output/model.tar.gz to temp/gpt2-lora-noquant.tar.gz

In [45]:
%cd temp
!ls -ltrh

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder/temp
total 12M
-rw-rw-r-- 1 ec2-user ec2-user 756K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (2).ipynb
-rw-rw-r-- 1 ec2-user ec2-user 840K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (1).ipynb
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0384616768394737
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0191842654468437
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.00977148872375
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_2_Prplxty_9.256776574458915
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.363786833972586
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.29573556990836
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_20_Prplxty_4.906924388591055
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_30_Prplxty_3.6311811785448933
drwxrwxr-x 3 ec2-user ec2-user 4.0K Mar  5  2025 train
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 05:57 gpt2-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 07:08 gpt2-lora-noquant.tar.gz

In [46]:
#!gunzip -dc model.tar.gz |tar xvf -
#!ls -ltrh

###### We have some observations:
- Training run time was higher than previous runs --> can be attributed to non-quantization
- Differential model is very small (less than 4 MB) as in previous runs

next we move with gpt2-medium. we will run only quantized runs and prhaps peft only rnus

In [47]:
%cd ..
%pwd

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder'

In [49]:
hparams = {
    'bs': 16,
    'lrate': 0.0008,
    'num_epochs': 2,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'gpt2-medium',
    'quant_bits': 4,
    'peft': 'lora',
    'grad_accum_steps': 8
}
hparams

{'bs': 16,
 'lrate': 0.0008,
 'num_epochs': 2,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'gpt2-medium',
 'quant_bits': 4,
 'peft': 'lora',
 'grad_accum_steps': 8}

In [50]:
est_gpt2_medium_4bit = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-gpt2-reuters.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='reutersgpt-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_gpt2_medium_4bit.fit(
    inputs=data_channels,
    wait=True
)

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: reutersgpt-train-2026-04-26-07-14-52-226

2026-04-26 07:14:54 Starting - Starting the training job...
2026-04-26 07:15:10 Starting - Preparing the instances for training...
2026-04-26 07:15:33 Downloading - Downloading input data...
2026-04-26 07:15:59 Downloading - Downloading the training image..................
2026-04-26 07:19:16 Training - Training image download completed. Training in progress..bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2026-04-26 07:19:28,039 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2026-04-26 07:19:28,057 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 07:19:28,067 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2026-04-26 07:19:28,074 sagemaker_pytorch_container.training INFO     Invoking user training script.
2026-04-26 07:19:29,945 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 6.3 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 8.7 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.26.0->transformers==4.49.0->-r requirements.txt (line 2))
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.0 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 139.7 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 40.9 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 57.9 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 44.2 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 64.1 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.3 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 125.6 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 82.9 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 105.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 33.9 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 52.2 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 21.5 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 15.6 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 18.4 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 22.8 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 17.2 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 80.6 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (48.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.8/48.8 MB 62.2 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 15.5 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 38.1 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 56.3 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 14.8 MB/s eta 0:00:00
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.3/193.3 kB 22.0 MB/s eta 0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 104.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 53.0 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 hf-xet-1.4.3 huggingface-hub-0.36.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.9.86 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-24.0.0 requests-2.33.1 safetensors-0.7.0 tokenizers-0.21.4 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.3 transformers-4.49.0 triton-2.2.0 xxhash-3.7.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
2026-04-26 07:22:00,205 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2026-04-26 07:22:00,205 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2026-04-26 07:22:00,245 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 07:22:00,277 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 07:22:00,305 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 07:22:00,316 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 16,

In [51]:
est_gpt2_medium_4bit.latest_training_job.describe()['FinalMetricDataList']

[{'MetricName': 'Perplexity',
  'Value': 9.246621131896973,
  'Timestamp': datetime.datetime(2026, 4, 26, 8, 29, 24, tzinfo=tzlocal())},
 {'MetricName': 'average training loss',
  'Value': 2.2242581844329834,
  'Timestamp': datetime.datetime(2026, 4, 26, 8, 29, 24, tzinfo=tzlocal())}]

In [52]:
!aws s3 ls --recursive {est_gpt2_medium_4bit.model_data}

2026-04-26 08:29:39    7077043 reutersgpt-train-2026-04-26-07-14-52-226/output/model.tar.gz

In [53]:
!aws s3 cp {est_gpt2_medium_4bit.model_data} ./temp/gpt2-medium-lora-4-bit-quant.tar.gz

download: s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-07-14-52-226/output/model.tar.gz to temp/gpt2-medium-lora-4-bit-quant.tar.gz

In [54]:
%cd temp
!ls -ltrh

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder/temp
total 19M
-rw-rw-r-- 1 ec2-user ec2-user 756K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (2).ipynb
-rw-rw-r-- 1 ec2-user ec2-user 840K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (1).ipynb
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0384616768394737
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0191842654468437
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.00977148872375
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_2_Prplxty_9.256776574458915
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.363786833972586
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.29573556990836
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_20_Prplxty_4.906924388591055
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_30_Prplxty_3.6311811785448933
drwxrwxr-x 3 ec2-user ec2-user 4.0K Mar  5  2025 train
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 05:57 gpt2-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 07:08 gpt2-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 08:29 gpt2-medium-lora-4-bit-quant.tar.gz

Differential model is very small (about 6 MB). It took 1 hour 12 minutes to complete 2 epochs

In [55]:
%cd ..
%pwd

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder'

In [58]:
hparams = {
    'bs': 8,
    'lrate': 0.0008,
    'num_epochs': 2,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'gpt2-medium',
    'quant_bits': 8,
    'peft': "lora",
    'grad_accum_steps': 4 #set to 4 if cuda errors out
}
hparams

{'bs': 8,
 'lrate': 0.0008,
 'num_epochs': 2,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'gpt2-medium',
 'quant_bits': 8,
 'peft': 'lora',
 'grad_accum_steps': 4}

In [59]:
est_gpt2_medium_8bit = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-gpt2-reuters.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='reutersgpt-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_gpt2_medium_8bit.fit(
    inputs=data_channels,
    wait=True
)

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: reutersgpt-train-2026-04-26-08-36-23-555

2026-04-26 08:36:25 Starting - Starting the training job...
2026-04-26 08:36:40 Starting - Preparing the instances for training...
2026-04-26 08:37:03 Downloading - Downloading input data...
2026-04-26 08:37:33 Downloading - Downloading the training image..................
2026-04-26 08:40:51 Training - Training image download completed. Training in progress..bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2026-04-26 08:41:02,253 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2026-04-26 08:41:02,273 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 08:41:02,283 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2026-04-26 08:41:02,290 sagemaker_pytorch_container.training INFO     Invoking user training script.
2026-04-26 08:41:04,256 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 6.3 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 8.1 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.26.0->transformers==4.49.0->-r requirements.txt (line 2))
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.1 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 156.3 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 44.4 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 59.4 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 77.9 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 62.6 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.2 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 137.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 105.2 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 72.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 36.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 48.9 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 16.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 15.8 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 17.3 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 23.2 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 17.1 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 81.6 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (48.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.8/48.8 MB 68.5 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 14.4 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 71.2 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 127.3 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 19.4 MB/s eta 0:00:00
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.3/193.3 kB 43.6 MB/s eta 0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 128.1 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 86.8 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 hf-xet-1.4.3 huggingface-hub-0.36.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.9.86 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-24.0.0 requests-2.33.1 safetensors-0.7.0 tokenizers-0.21.4 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.3 transformers-4.49.0 triton-2.2.0 xxhash-3.7.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
2026-04-26 08:43:36,585 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2026-04-26 08:43:36,585 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2026-04-26 08:43:36,628 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 08:43:36,662 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 08:43:36,694 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 08:43:36,707 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 8,

In [60]:
est_gpt2_medium_8bit.latest_training_job.describe()['FinalMetricDataList']

[{'MetricName': 'Perplexity',
  'Value': 8.337007522583008,
  'Timestamp': datetime.datetime(2026, 4, 26, 9, 41, 48, tzinfo=tzlocal())},
 {'MetricName': 'average training loss',
  'Value': 2.120704412460327,
  'Timestamp': datetime.datetime(2026, 4, 26, 9, 41, 48, tzinfo=tzlocal())}]

In [61]:
!aws s3 ls --recursive {est_gpt2_medium_8bit.model_data}
!aws s3 cp {est_gpt2_medium_8bit.model_data} ./temp/gpt2-medium-lora-8-bit-quant.tar.gz
%cd temp
!ls -ltrh

2026-04-26 09:42:08    7078966 reutersgpt-train-2026-04-26-08-36-23-555/output/model.tar.gz
download: s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-08-36-23-555/output/model.tar.gz to temp/gpt2-medium-lora-8-bit-quant.tar.gz
/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder/temp
total 25M
-rw-rw-r-- 1 ec2-user ec2-user 756K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (2).ipynb
-rw-rw-r-- 1 ec2-user ec2-user 840K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (1).ipynb
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0384616768394737
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0191842654468437
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.00977148872375
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_2_Prplxty_9.256776574458915
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.363786833972586
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.29573556990836
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_20_Prplxty_4.906924388591055
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_30_Prplxty_3.6311811785448933
drwxrwxr-x 3 ec2-user ec2-user 4.0K Mar  5  2025 train
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 05:57 gpt2-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 07:08 gpt2-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 08:29 gpt2-medium-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 09:42 gpt2-medium-lora-8-bit-quant.tar.gz

In [62]:
%cd ..
%pwd

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder'

In [64]:
hparams = {
    'bs': 8,
    'lrate': 0.0008,
    'num_epochs': 2,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'gpt2-medium',
    'quant_bits': 0,
    'peft': "lora",
    'grad_accum_steps': 4 #set to 4 if cuda errors out
}
hparams

{'bs': 8,
 'lrate': 0.0008,
 'num_epochs': 2,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'gpt2-medium',
 'quant_bits': 0,
 'peft': 'lora',
 'grad_accum_steps': 4}

In [65]:
est_gpt2_medium_peft = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-gpt2-reuters.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='reutersgpt-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_gpt2_medium_peft.fit(
    inputs=data_channels,
    wait=True
)

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: reutersgpt-train-2026-04-26-09-45-38-009

2026-04-26 09:45:40 Starting - Starting the training job...
2026-04-26 09:45:55 Starting - Preparing the instances for training...
2026-04-26 09:46:20 Downloading - Downloading input data...
2026-04-26 09:46:45 Downloading - Downloading the training image..................
2026-04-26 09:50:07 Training - Training image download completed. Training in progress...bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2026-04-26 09:50:18,825 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2026-04-26 09:50:18,844 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 09:50:18,855 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2026-04-26 09:50:18,861 sagemaker_pytorch_container.training INFO     Invoking user training script.
2026-04-26 09:50:20,766 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 5.4 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 8.6 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.26.0->transformers==4.49.0->-r requirements.txt (line 2))
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.0 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 146.1 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 51.1 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 61.4 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 85.3 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 75.6 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.3 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 132.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 103.4 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 83.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 39.1 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 73.1 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 26.2 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 15.9 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 17.6 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 23.4 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 17.6 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 89.7 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (48.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.8/48.8 MB 67.9 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 17.7 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 82.6 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 110.2 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 21.5 MB/s eta 0:00:00
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.3/193.3 kB 44.4 MB/s eta 0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 149.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 85.5 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 hf-xet-1.4.3 huggingface-hub-0.36.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.9.86 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-24.0.0 requests-2.33.1 safetensors-0.7.0 tokenizers-0.21.4 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.3 transformers-4.49.0 triton-2.2.0 xxhash-3.7.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
2026-04-26 09:52:49,668 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2026-04-26 09:52:49,668 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2026-04-26 09:52:49,728 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 09:52:49,768 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 09:52:49,799 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 09:52:49,812 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 8,

In [66]:
est_gpt2_medium_peft.latest_training_job.describe()['FinalMetricDataList']

[{'MetricName': 'Perplexity',
  'Value': 8.287935256958008,
  'Timestamp': datetime.datetime(2026, 4, 26, 10, 58, 52, tzinfo=tzlocal())},
 {'MetricName': 'average training loss',
  'Value': 2.1148009300231934,
  'Timestamp': datetime.datetime(2026, 4, 26, 10, 58, 52, tzinfo=tzlocal())}]

In [67]:
!aws s3 ls --recursive {est_gpt2_medium_peft.model_data}
!aws s3 cp {est_gpt2_medium_peft.model_data} ./temp/gpt2-medium-lora-noquant.tar
%cd temp
!ls -ltrh

2026-04-26 10:59:10    7079477 reutersgpt-train-2026-04-26-09-45-38-009/output/model.tar.gz
download: s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-09-45-38-009/output/model.tar.gz to temp/gpt2-medium-lora-noquant.tar
/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder/temp
total 32M
-rw-rw-r-- 1 ec2-user ec2-user 756K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (2).ipynb
-rw-rw-r-- 1 ec2-user ec2-user 840K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (1).ipynb
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0384616768394737
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0191842654468437
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.00977148872375
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_2_Prplxty_9.256776574458915
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.363786833972586
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.29573556990836
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_20_Prplxty_4.906924388591055
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_30_Prplxty_3.6311811785448933
drwxrwxr-x 3 ec2-user ec2-user 4.0K Mar  5  2025 train
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 05:57 gpt2-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 07:08 gpt2-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 08:29 gpt2-medium-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 09:42 gpt2-medium-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 10:59 gpt2-medium-lora-noquant.tar

In [68]:
%cd ..
%pwd

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/NLP_tasks/FineTuneDecoder'

In [69]:
hparams = {
    'bs': 8,
    'lrate': 0.0008,
    'num_epochs': 2,
    'environ': 'aws',
    'block_size': 256,
    'ckpt': 'gpt2',
    'quant_bits': 0,
    'peft': "nolora",
    'grad_accum_steps': 4 #set to 4 if cuda errors out
}
hparams

{'bs': 8,
 'lrate': 0.0008,
 'num_epochs': 2,
 'environ': 'aws',
 'block_size': 256,
 'ckpt': 'gpt2',
 'quant_bits': 0,
 'peft': 'nolora',
 'grad_accum_steps': 4}

In [70]:
est_gpt2_only = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train-gpt2-reuters.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='reutersgpt-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_gpt2_only.fit(
    inputs=data_channels,
    wait=True
)

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: reutersgpt-train-2026-04-26-11-12-51-336

2026-04-26 11:12:55 Starting - Starting the training job...
2026-04-26 11:13:11 Starting - Preparing the instances for training...
2026-04-26 11:13:35 Downloading - Downloading input data...
2026-04-26 11:14:00 Downloading - Downloading the training image..................
2026-04-26 11:17:17 Training - Training image download completed. Training in progress..bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2026-04-26 11:17:28,854 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2026-04-26 11:17:28,874 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 11:17:28,884 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2026-04-26 11:17:28,891 sagemaker_pytorch_container.training INFO     Invoking user training script.
2026-04-26 11:17:30,812 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:
/opt/conda/bin/python3.10 -m pip install -r requirements.txt
Collecting torch==2.2.2 (from -r requirements.txt (line 1))
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers==4.49.0 (from -r requirements.txt (line 2))
Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 6.1 MB/s eta 0:00:00
Collecting bitsandbytes==0.45.3 (from -r requirements.txt (line 3))
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting accelerate==1.4.0 (from -r requirements.txt (line 4))
Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets==3.3.2 (from -r requirements.txt (line 5))
Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting peft==0.14.0 (from -r requirements.txt (line 6))
Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting torchinfo (from -r requirements.txt (line 7))
Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch==2.2.2->-r requirements.txt (line 1)) (2023.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.2.0 (from torch==2.2.2->-r requirements.txt (line 1))
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (2.31.0)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.49.0->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==1.4.0->-r requirements.txt (line 4)) (5.9.5)
Collecting safetensors>=0.4.1 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting pyarrow>=15.0.0 (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (2.1.3)
Collecting requests (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm>=4.27 (from transformers==4.49.0->-r requirements.txt (line 2))
Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 8.6 MB/s eta 0:00:00
Collecting xxhash (from datasets==3.3.2->-r requirements.txt (line 5))
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (0.70.15)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets==3.3.2->-r requirements.txt (line 5)) (3.9.3)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 1))
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (1.9.3)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets==3.3.2->-r requirements.txt (line 5)) (4.0.3)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.26.0->transformers==4.49.0->-r requirements.txt (line 2))
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.49.0->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->datasets==3.3.2->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.2.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2->-r requirements.txt (line 5)) (1.16.0)
Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl (755.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.1 MB/s eta 0:00:00
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 126.1 MB/s eta 0:00:00
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 42.1 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 61.1 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 78.1 MB/s eta 0:00:00
Downloading peft-0.14.0-py3-none-any.whl (374 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 71.6 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.3 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 152.6 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 108.1 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 81.5 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 35.7 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 54.7 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 23.7 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 15.7 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 24.7 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 26.7 MB/s eta 0:00:00
Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 17.9 MB/s eta 0:00:00
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 81.9 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (48.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.8/48.8 MB 74.4 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 17.0 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 82.5 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 121.6 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 22.3 MB/s eta 0:00:00
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.3/193.3 kB 46.8 MB/s eta 0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 144.3 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 84.8 MB/s eta 0:00:00
Installing collected packages: xxhash, triton, tqdm, torchinfo, safetensors, requests, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, accelerate, peft
Attempting uninstall: triton
Found existing installation: triton 2.0.0.dev20221202
Uninstalling triton-2.0.0.dev20221202:
Successfully uninstalled triton-2.0.0.dev20221202
Attempting uninstall: tqdm
Found existing installation: tqdm 4.65.0
Uninstalling tqdm-4.65.0:
Successfully uninstalled tqdm-4.65.0
Attempting uninstall: safetensors
Found existing installation: safetensors 0.4.1
Uninstalling safetensors-0.4.1:
Successfully uninstalled safetensors-0.4.1
Attempting uninstall: requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
Successfully uninstalled requests-2.31.0
Attempting uninstall: pyarrow
Found existing installation: pyarrow 14.0.1
Uninstalling pyarrow-14.0.1:
Successfully uninstalled pyarrow-14.0.1
Attempting uninstall: huggingface-hub
Found existing installation: huggingface-hub 0.19.4
Uninstalling huggingface-hub-0.19.4:
Successfully uninstalled huggingface-hub-0.19.4
Attempting uninstall: tokenizers
Found existing installation: tokenizers 0.15.0
Uninstalling tokenizers-0.15.0:
Successfully uninstalled tokenizers-0.15.0
Attempting uninstall: transformers
Found existing installation: transformers 4.38.2
Uninstalling transformers-4.38.2:
Successfully uninstalled transformers-4.38.2
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Attempting uninstall: accelerate
Found existing installation: accelerate 0.22.0
Uninstalling accelerate-0.22.0:
Successfully uninstalled accelerate-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.13 requires torch<2.2,>=1.10, but you have torch 2.2.2 which is incompatible.
Successfully installed accelerate-1.4.0 bitsandbytes-0.45.3 datasets-3.3.2 hf-xet-1.4.3 huggingface-hub-0.36.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.9.86 nvidia-nvtx-cu12-12.1.105 peft-0.14.0 pyarrow-24.0.0 requests-2.33.1 safetensors-0.7.0 tokenizers-0.21.4 torch-2.2.2 torchinfo-1.8.0 tqdm-4.67.3 transformers-4.49.0 triton-2.2.0 xxhash-3.7.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
2026-04-26 11:19:57,420 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2026-04-26 11:19:57,420 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2026-04-26 11:19:57,481 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 11:19:57,524 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 11:19:57,556 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-04-26 11:19:57,567 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 8,
        "ckpt": "gpt2",

In [72]:
est_gpt2_only.latest_training_job.describe()['FinalMetricDataList']

[{'MetricName': 'Perplexity',
  'Value': 6.104443550109863,
  'Timestamp': datetime.datetime(2026, 4, 26, 11, 53, 28, tzinfo=tzlocal())},
 {'MetricName': 'average training loss',
  'Value': 1.8090169429779053,
  'Timestamp': datetime.datetime(2026, 4, 26, 11, 53, 28, tzinfo=tzlocal())}]

In [74]:
est_gpt2_only.latest_training_job.describe()

{'TrainingJobName': 'reutersgpt-train-2026-04-26-11-12-51-336',
 'TrainingJobArn': 'arn:aws:sagemaker:us-east-1:191013407134:training-job/reutersgpt-train-2026-04-26-11-12-51-336',
 'ModelArtifacts': {'S3ModelArtifacts': 's3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-11-12-51-336/output/model.tar.gz'},
 'TrainingJobStatus': 'Completed',
 'SecondaryStatus': 'Completed',
 'HyperParameters': {'block_size': '256',
  'bs': '8',
  'ckpt': '"gpt2"',
  'environ': '"aws"',
  'grad_accum_steps': '4',
  'lrate': '0.0008',
  'num_epochs': '2',
  'peft': '"nolora"',
  'quant_bits': '0',
  'sagemaker_container_log_level': '20',
  'sagemaker_job_name': '"reutersgpt-train-2026-04-26-11-12-51-336"',
  'sagemaker_program': '"train-gpt2-reuters.py"',
  'sagemaker_region': '"us-east-1"',
  'sagemaker_submit_directory': '"s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-11-12-51-336/source/sourcedir.tar.gz"'},
 'AlgorithmSpecification': {'TrainingImage': '763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.0-gpu-py310',
  'TrainingInputMode': 'File',
  'MetricDefinitions': [{'Name': 'average training loss',
    'Regex': 'Average loss: ([0-9\\.]+)'},
   {'Name': 'Perplexity', 'Regex': 'Perplexity: ([0-9\\.]+)'}],
  'EnableSageMakerMetricsTimeSeries': False},
 'RoleArn': 'arn:aws:iam::191013407134:role/service-role/AmazonSageMaker-ExecutionRole-20250124T222384',
 'InputDataConfig': [{'ChannelName': 'train',
   'DataSource': {'S3DataSource': {'S3DataType': 'S3Prefix',
     'S3Uri': 's3://sagemaker-us-east-1-191013407134/gpt_train/dataset/reuters/',
     'S3DataDistributionType': 'FullyReplicated'}},
   'CompressionType': 'None',
   'RecordWrapperType': 'None'}],
 'OutputDataConfig': {'KmsKeyId': '',
  'S3OutputPath': 's3://sagemaker-us-east-1-191013407134/',
  'CompressionType': 'GZIP'},
 'ResourceConfig': {'InstanceType': 'ml.g4dn.xlarge',
  'InstanceCount': 1,
  'VolumeSizeInGB': 30},
 'StoppingCondition': {'MaxRuntimeInSeconds': 86400},
 'CreationTime': datetime.datetime(2026, 4, 26, 11, 12, 52, 449000, tzinfo=tzlocal()),
 'TrainingStartTime': datetime.datetime(2026, 4, 26, 11, 13, 35, 278000, tzinfo=tzlocal()),
 'TrainingEndTime': datetime.datetime(2026, 4, 26, 11, 54, 17, 107000, tzinfo=tzlocal()),
 'LastModifiedTime': datetime.datetime(2026, 4, 26, 11, 54, 17, 236000, tzinfo=tzlocal()),
 'SecondaryStatusTransitions': [{'Status': 'Starting',
   'StartTime': datetime.datetime(2026, 4, 26, 11, 12, 52, 449000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 4, 26, 11, 13, 35, 278000, tzinfo=tzlocal()),
   'StatusMessage': 'Preparing the instances for training'},
  {'Status': 'Downloading',
   'StartTime': datetime.datetime(2026, 4, 26, 11, 13, 35, 278000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 4, 26, 11, 17, 17, 643000, tzinfo=tzlocal()),
   'StatusMessage': 'Downloading the training image'},
  {'Status': 'Training',
   'StartTime': datetime.datetime(2026, 4, 26, 11, 17, 17, 643000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 4, 26, 11, 53, 34, 321000, tzinfo=tzlocal()),
   'StatusMessage': 'Training image download completed. Training in progress.'},
  {'Status': 'Uploading',
   'StartTime': datetime.datetime(2026, 4, 26, 11, 53, 34, 321000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 4, 26, 11, 54, 17, 107000, tzinfo=tzlocal()),
   'StatusMessage': 'Uploading generated training model'},
  {'Status': 'Completed',
   'StartTime': datetime.datetime(2026, 4, 26, 11, 54, 17, 107000, tzinfo=tzlocal()),
   'EndTime': datetime.datetime(2026, 4, 26, 11, 54, 17, 107000, tzinfo=tzlocal()),
   'StatusMessage': 'Training job completed'}],
 'FinalMetricDataList': [{'MetricName': 'Perplexity',
   'Value': 6.104443550109863,
   'Timestamp': datetime.datetime(2026, 4, 26, 11, 53, 28, tzinfo=tzlocal())},
  {'MetricName': 'average training loss',
   'Value': 1.8090169429779053,
   'Timestamp': datetime.datetime(2026, 4, 26, 11, 53, 28, tzinfo=tzlocal())}],
 'EnableNetworkIsolation': False,
 'EnableInterContainerTrafficEncryption': False,
 'EnableManagedSpotTraining': False,
 'TrainingTimeInSeconds': 2442,
 'BillableTimeInSeconds': 2442,
 'DebugHookConfig': {'S3OutputPath': 's3://sagemaker-us-east-1-191013407134/',
  'CollectionConfigurations': []},
 'ProfilerConfig': {'S3OutputPath': 's3://sagemaker-us-east-1-191013407134/',
  'ProfilingIntervalInMilliseconds': 500,
  'DisableProfiler': False},
 'ProfilingStatus': 'Enabled',
 'ResponseMetadata': {'RequestId': 'e7b15905-8754-43d9-adc3-43ecfe21b9f4',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'e7b15905-8754-43d9-adc3-43ecfe21b9f4',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '3641',
   'date': 'Sun, 26 Apr 2026 12:22:15 GMT'},
  'RetryAttempts': 0}}

In [82]:
est_gpt2_only.latest_training_job.describe()['FinalMetricDataList'][0]['Value']

6.104443550109863

In [79]:
est_gpt2_only.latest_training_job.describe()['HyperParameters']

{'block_size': '256',
 'bs': '8',
 'ckpt': '"gpt2"',
 'environ': '"aws"',
 'grad_accum_steps': '4',
 'lrate': '0.0008',
 'num_epochs': '2',
 'peft': '"nolora"',
 'quant_bits': '0',
 'sagemaker_container_log_level': '20',
 'sagemaker_job_name': '"reutersgpt-train-2026-04-26-11-12-51-336"',
 'sagemaker_program': '"train-gpt2-reuters.py"',
 'sagemaker_region': '"us-east-1"',
 'sagemaker_submit_directory': '"s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-11-12-51-336/source/sourcedir.tar.gz"'}

In [100]:
!aws s3 ls --recursive {est_gpt2_only.model_data}
!aws s3 cp {est_gpt2_only.model_data} ./temp/gpt2-nolora-noquant.tar

2026-04-26 11:54:07 1376083371 reutersgpt-train-2026-04-26-11-12-51-336/output/model.tar.gz
download: s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-11-12-51-336/output/model.tar.gz to temp/gpt2-nolora-noquant.tar
total 1.4G
-rw-rw-r-- 1 ec2-user ec2-user 756K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (2).ipynb
-rw-rw-r-- 1 ec2-user ec2-user 840K Feb 28  2025 Quant_ReuterSDSgpt2fine-tuning (1).ipynb
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0384616768394737
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.0191842654468437
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_4_Prplxty_1.00977148872375
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  1  2025 ckpt_Epoch_2_Prplxty_9.256776574458915
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.363786833972586
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  2  2025 ckpt_Epoch_2_Prplxty_8.29573556990836
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_20_Prplxty_4.906924388591055
drwxr-xr-x 2 ec2-user ec2-user 4.0K Mar  4  2025 ckpt_Epoch_30_Prplxty_3.6311811785448933
drwxrwxr-x 3 ec2-user ec2-user 4.0K Mar  5  2025 train
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 05:57 gpt2-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 07:08 gpt2-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 08:29 gpt2-medium-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 09:42 gpt2-medium-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 10:59 gpt2-medium-lora-noquant.tar
-rw-rw-r-- 1 ec2-user ec2-user 1.3G Apr 26 11:54 gpt2-nolora-noquant.tar

In [103]:
!ls -ltrh ./temp|grep 'gpt2-'

-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 05:57 gpt2-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 07:08 gpt2-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 08:29 gpt2-medium-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 09:42 gpt2-medium-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 10:59 gpt2-medium-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 1.3G Apr 26 11:54 gpt2-nolora-noquant.tar.gz

In [71]:
#Collect loss and perplexity for all 7 experiments
#create a pandas dataframe with following fields: Experiment name, loss value truncated to 3 places, perplexity
#truncated to 3 places

#next create a function that will load peft model with main model and then perform sample generation.
#Measure Bleu score and put it in a pandas dataframe
#DO this for all 7 experiments

In [78]:
!aws sagemaker list-training-jobs --creation-time-after 2026-04-25

{
    "TrainingJobSummaries": [
        {
            "TrainingJobName": "reutersgpt-train-2026-04-26-11-12-51-336",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/reutersgpt-train-2026-04-26-11-12-51-336",
            "CreationTime": 1777201972.449,
            "TrainingEndTime": 1777204457.107,
            "LastModifiedTime": 1777204457.236,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        },
        {
            "TrainingJobName": "reutersgpt-train-2026-04-26-09-45-38-009",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/reutersgpt-train-2026-04-26-09-45-38-009",
            "CreationTime": 1777196738.583,
            "TrainingEndTime": 1777201155.355,
            "LastModifiedTime": 1777201155.53,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        },
        {
            "TrainingJobName": "reutersgpt-train-2026-04-26-08-36-23-555",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/reutersgpt-train-2026-04-26-08-36-23-555",
            "CreationTime": 1777192584.093,
            "TrainingEndTime": 1777196532.788,
            "LastModifiedTime": 1777196533.15,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        },
        {
            "TrainingJobName": "reutersgpt-train-2026-04-26-07-14-52-226",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/reutersgpt-train-2026-04-26-07-14-52-226",
            "CreationTime": 1777187692.79,
            "TrainingEndTime": 1777192184.759,
            "LastModifiedTime": 1777192185.34,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        },
        {
            "TrainingJobName": "reutersgpt-train-2026-04-26-06-05-23-370",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/reutersgpt-train-2026-04-26-06-05-23-370",
            "CreationTime": 1777183523.98,
            "TrainingEndTime": 1777187330.985,
            "LastModifiedTime": 1777187331.094,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        },
        {
            "TrainingJobName": "reutersgpt-train-2026-04-26-05-01-11-367",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/reutersgpt-train-2026-04-26-05-01-11-367",
            "CreationTime": 1777179671.942,
            "TrainingEndTime": 1777183049.322,
            "LastModifiedTime": 1777183049.888,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        },
        {
            "TrainingJobName": "reutersgpt-train-2026-04-26-03-52-17-073",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/reutersgpt-train-2026-04-26-03-52-17-073",
            "CreationTime": 1777175537.665,
            "TrainingEndTime": 1777179084.036,
            "LastModifiedTime": 1777179084.325,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        },
        {
            "TrainingJobName": "brogpt-train-2026-04-25-07-40-25-286",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/brogpt-train-2026-04-25-07-40-25-286",
            "CreationTime": 1777102825.961,
            "TrainingEndTime": 1777104846.191,
            "LastModifiedTime": 1777104846.356,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        },
        {
            "TrainingJobName": "brogpt-train-2026-04-25-06-59-20-750",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/brogpt-train-2026-04-25-06-59-20-750",
            "CreationTime": 1777100361.849,
            "TrainingEndTime": 1777101527.13,
            "LastModifiedTime": 1777101527.727,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        },
        {
            "TrainingJobName": "brogpt-train-2026-04-25-05-47-14-463",
            "TrainingJobArn": "arn:aws:sagemaker:us-east-1:191013407134:training-job/brogpt-train-2026-04-25-05-47-14-463",
            "CreationTime": 1777096035.554,
            "TrainingEndTime": 1777098698.54,
            "LastModifiedTime": 1777098698.645,
            "TrainingJobStatus": "Completed",
            "SecondaryStatus": "Completed"
        }
    ]
}

In [84]:
joblist = [est, est_gpt2_8bit, est_gpt2_loraonly, est_gpt2_medium_4bit, 
           est_gpt2_medium_8bit, est_gpt2_medium_peft, est_gpt2_only]

In [85]:
joblist

[<sagemaker.estimator.Estimator at 0x7f8c6204ba00>,
 <sagemaker.estimator.Estimator at 0x7f8c6204b5e0>,
 <sagemaker.estimator.Estimator at 0x7f8c6282a020>,
 <sagemaker.estimator.Estimator at 0x7f8c60c39480>,
 <sagemaker.estimator.Estimator at 0x7f8c60d26c80>,
 <sagemaker.estimator.Estimator at 0x7f8c62048160>,
 <sagemaker.estimator.Estimator at 0x7f8c67866350>]

In [92]:
exp_hp = []
exp_loss = []
exp_perp = []
for job in joblist:
    exp_hp.append(job.latest_training_job.describe()['HyperParameters'])
    exp_perp.append(round(job.latest_training_job.describe()['FinalMetricDataList'][0]['Value'], 3))
    exp_loss.append(round(job.latest_training_job.describe()['FinalMetricDataList'][1]['Value'], 3))

In [93]:
exp_perp

[10.314, 11.326, 12.135, 9.247, 8.337, 8.288, 6.104]

In [96]:
exp_hp[0]

{'block_size': '256',
 'bs': '16',
 'ckpt': '"gpt2"',
 'environ': '"aws"',
 'lrate': '0.0006',
 'num_epochs': '4',
 'peft': '"lora"',
 'quant_bits': '4',
 'sagemaker_container_log_level': '20',
 'sagemaker_job_name': '"reutersgpt-train-2026-04-26-03-52-17-073"',
 'sagemaker_program': '"train-gpt2-reuters.py"',
 'sagemaker_region': '"us-east-1"',
 'sagemaker_submit_directory': '"s3://sagemaker-us-east-1-191013407134/reutersgpt-train-2026-04-26-03-52-17-073/source/sourcedir.tar.gz"'}

In [94]:
df = pd.DataFrame({'exp_hparams': exp_hp, 'loss': exp_loss, 'perplexity': exp_perp})
df

                                         exp_hparams   loss  perplexity
0  {'block_size': '256', 'bs': '16', 'ckpt': '"gp...  2.334      10.314
1  {'block_size': '256', 'bs': '16', 'ckpt': '"gp...  2.427      11.326
2  {'block_size': '256', 'bs': '16', 'ckpt': '"gp...  2.496      12.135
3  {'block_size': '256', 'bs': '16', 'ckpt': '"gp...  2.224       9.247
4  {'block_size': '256', 'bs': '8', 'ckpt': '"gpt...  2.121       8.337
5  {'block_size': '256', 'bs': '8', 'ckpt': '"gpt...  2.115       8.288
6  {'block_size': '256', 'bs': '8', 'ckpt': '"gpt...  1.809       6.104

In [106]:
df['ckpt'] = df['exp_hparams'].apply(lambda x: x['ckpt'])
df['peft'] = df['exp_hparams'].apply(lambda x: x['peft'])
df['quant_bits'] = df['exp_hparams'].apply(lambda x: x['quant_bits'])
df

,exp_hparams,loss,perplexity,ckpt,peft,quant_bits
0,"{'block_size': '256', 'bs': '16', 'ckpt': '""gp...",2.334,10.314,"""gpt2""","""lora""",4
1,"{'block_size': '256', 'bs': '16', 'ckpt': '""gp...",2.427,11.326,"""gpt2""","""lora""",8
2,"{'block_size': '256', 'bs': '16', 'ckpt': '""gp...",2.496,12.135,"""gpt2""","""lora""",0
3,"{'block_size': '256', 'bs': '16', 'ckpt': '""gp...",2.224,9.247,"""gpt2-medium""","""lora""",4
4,"{'block_size': '256', 'bs': '8', 'ckpt': '""gpt...",2.121,8.337,"""gpt2-medium""","""lora""",8
5,"{'block_size': '256', 'bs': '8', 'ckpt': '""gpt...",2.115,8.288,"""gpt2-medium""","""lora""",0
6,"{'block_size': '256', 'bs': '8', 'ckpt': '""gpt...",1.809,6.104,"""gpt2""","""nolora""",0

In [14]:
ds_1['train']['full_article'][2]

"TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN\n\nBODY: Texas Commerce Bancshares Inc's Texas\nCommerce Bank-Houston said it filed an application with the\nComptroller of the Currency in an effort to create the largest\nbanking network in Harris County.\n    The bank said the network would link 31 banks having\n13.5 billion dlrs in assets and 7.5 billion dlrs in deposits.\n       \n Reuter\n\x03"

In [113]:
!ls -ltrh ./temp |grep 'gpt2-'

-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 05:57 gpt2-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 07:08 gpt2-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 08:29 gpt2-medium-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 09:42 gpt2-medium-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 10:59 gpt2-medium-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 1.3G Apr 26 11:54 gpt2-nolora-noquant.tar.gz

In [45]:
def load_model_gen_text(ckpt, lora_ckpt, prompt, num_toks, lora=True):
    model = AutoModelForCausalLM.from_pretrained(ckpt)
    if lora:
        model = PeftModel.from_pretrained(model, lora_ckpt)
    else:
        with open(lora_ckpt, 'rb') as f:
            checkpoint = torch.load(f, map_location=torch.device(device))
            print(f'checkpoint keys: {checkpoint.keys()}')
            model.load_state_dict(checkpoint['model_state_dict'])
            print("completed success")
    tokenizer = AutoTokenizer.from_pretrained(ckpt)
    input_ids = tokenizer.encode(prompt, return_tensors='pt')
    gen_tokens = model.generate(
        input_ids,
        do_sample=True,
        temperature=0.8,
        max_length=num_toks,
    )
    gen_text = tokenizer.batch_decode(gen_tokens)[0]
    print(f'Prompt: {prompt}')
    print(gen_text)
    del model

In [20]:
#Collect loss and perplexity for all 7 experiments
#create a pandas dataframe with following fields: Experiment name, loss value truncated to 3 places, perplexity
#truncated to 3 places

#next create a function that will load peft model with main model and then perform sample generation.
#Measure Bleu score and put it in a pandas dataframe
#DO this for all 7 experiments

In [21]:
prompt = "TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN\n\nBODY:"
prompt

'TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN\n\nBODY:'

In [22]:
num_toks=512
num_toks

512

In [23]:
!ls -ltrh ./temp |grep 'gpt2-'

-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 04:51 gpt2-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 05:57 gpt2-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 3.3M Apr 26 07:08 gpt2-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 08:29 gpt2-medium-lora-4-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 09:42 gpt2-medium-lora-8-bit-quant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 6.8M Apr 26 10:59 gpt2-medium-lora-noquant.tar.gz
-rw-rw-r-- 1 ec2-user ec2-user 1.3G Apr 26 11:54 gpt2-nolora-noquant.tar.gz

In [13]:
!gunzip -dc ./temp/gpt2-lora-4-bit-quant.tar.gz |tar xvf -

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/training_args.bin
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/tokenizer.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/README.md
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/merges.txt
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/adapter_model.safetensors
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/vocab.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/adapter_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/tokenizer_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_10.314107140187565/special_tokens_map.json

In [26]:
load_model_gen_text('gpt2', 'ckpt_Epoch_4_Prplxty_10.314107140187565', prompt, num_toks)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

Prompt: TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY:
TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY: Texas Commuter Bank Holdings Inc said
it filed with the Securities and Exchange Commission a
plan to make deposits and accept cash. The plan will be
filed as part of its initial public offering, the company said.
    It said the Securities and Exchange Commission will begin
to act as a regulatory agency rather than a trading
person.
 Reuter
<|endoftext|>

In [27]:
!gunzip -dc ./temp/gpt2-lora-8-bit-quant.tar.gz |tar xvf -

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/vocab.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/merges.txt
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/adapter_model.safetensors
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/README.md
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/adapter_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/training_args.bin
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/special_tokens_map.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/tokenizer_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_11.326158550842958/tokenizer.json

In [28]:
load_model_gen_text('gpt2', 'ckpt_Epoch_4_Prplxty_11.326158550842958', prompt, num_toks)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY:
TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY: Texas Commerce and Construction Corp
said it filed a proposal to acquire all of Chevron Corp as
a result of an agreement reached in April 2016 between
the three companies.
    The Texas proposal has the approval of the U.S.
Committee on Foreign Investment in the United States.
    The Texas proposal is intended to improve the
construction of the Corpus Christi gas basin and to diversify the
resource resources of the state.
 Reuter
quickShip<|endoftext|>

In [29]:
!gunzip -dc ./temp/gpt2-lora-noquant.tar.gz |tar xvf -

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/tokenizer_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/README.md
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/tokenizer.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/merges.txt
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/adapter_model.safetensors
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/special_tokens_map.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/adapter_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/vocab.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_4_Prplxty_12.134512543935335/training_args.bin

In [30]:
load_model_gen_text('gpt2', 'ckpt_Epoch_4_Prplxty_12.134512543935335', prompt, num_toks)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY:
TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY: The Texas Commerce Commission
approved two securities contracts of the Pacific Southwest Inc
<PWR> and the C.I.P. of Los Angeles Corp <LAD> to cover
$5.2 billion in capital expenses and to raise $1.2 billion
in financing, the commission reported.
    The securities awards and commissions are authorized through
a combination of two third party securities market
agents.
    The commission also approved a memorandum of understanding with the
Pacific Southwest to develop the $5.2 billion securities
contract with C.I.P. of Los Angeles, and C.I.P. of
Los Angeles, to secure a 1.25 billion dlr increase in
capital expenses.
    The commission also approved a 5.8 billion dlr, five-year
comprehensive, three-year capital agreement with the C.I.P.
of Los Angeles, to cover $25.5 billion in capital
increases and $1.3 billion in debt.
    The commission reported the deal<|endoftext|>

In [31]:
!gunzip -dc ./temp/gpt2-medium-lora-4-bit-quant.tar.gz |tar xvf -

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/adapter_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/tokenizer.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/merges.txt
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/training_args.bin
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/adapter_model.safetensors
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/special_tokens_map.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/README.md
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/tokenizer_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_9.246621550015862/vocab.json

In [32]:
load_model_gen_text('gpt2-medium', 'ckpt_Epoch_2_Prplxty_9.246621550015862', prompt, num_toks)

model.safetensors:   0%|          | 0.00/1.52G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

[transformers] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY:
TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY: Texas Commerce Bancshares Inc said
its board has unanimously approved a plan to sell its
business to American Continental Corp <AFS> for an undisclosed
amount of money.
    The company said the transaction would be completed
by the end of the third quarter. It said the sale would
result in a net benefit to the Dallas-based company of
1,000,000 dlrs over five years.
    It said this is a move to address the company's
irrelevance to the Dallas market.
    The company said the board has approved a plan to
sell its stake in American Continental to American
Bancshares Inc, a Delaware-based company that is
associated with Continental and with the Texas-based
Texas-Dominion Bank.
    American Continental has about one mln dlrs of net
profit from the Texas commerce unit in the current year,
its chief executive, Roger Hall, said in a statement.
    This year, Texas Commerce Bancshares reported a net
gain of about 20 mln dlrs from interest and dividends.
    Hall said the business was highly valuable<|endoftext|>

In [33]:
!gunzip -dc ./temp/gpt2-medium-lora-8-bit-quant.tar.gz |tar xvf -

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/special_tokens_map.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/tokenizer.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/merges.txt
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/adapter_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/vocab.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/training_args.bin
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/tokenizer_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/README.md
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.337007894999958/adapter_model.safetensors

In [34]:
load_model_gen_text('gpt2-medium', 'ckpt_Epoch_2_Prplxty_8.337007894999958', prompt, num_toks)

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[transformers] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY:
TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY: Texas Commerce Bancshares Inc
said it has filed with the Federal Trade Commission a
plan by the company to buy all the Texas Bancshares in
Texas and consolidate the companies.
    The company said in a filing that it has a plan to
consolidate the Texas Bancshares into a single company,
Texas Bancshares Texas Corp, with the purpose of selling any
Bancshares that may be acquired.
    The filing said Texas Commerce Bancshares plans to
consolidate the Bancshares into an exchange company, so
the company will not be subject to federal market
control laws.
 Reuter
<|endoftext|>

In [35]:
!gunzip -dc ./temp/gpt2-medium-lora-noquant.tar.gz |tar xvf -

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/vocab.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/tokenizer_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/special_tokens_map.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/tokenizer.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/training_args.bin
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/adapter_model.safetensors
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/README.md
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/adapter_config.json
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_8.287935356408438/merges.txt

In [36]:
load_model_gen_text('gpt2-medium', 'ckpt_Epoch_2_Prplxty_8.287935356408438', prompt, num_toks)

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[transformers] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY:
TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY: Texas Commerce Bancshares Inc
said it filed for a Class B common stock tender offer to raise
350 mln dlrs through a series one subordinated debt offering.
    The company said it will sell Class B common stock at 30
dlrs per share, subject to adjustment for a reduction in
gross senior indebtedness.
 Reuter
<|endoftext|>

In [37]:
!gunzip -dc ./temp/gpt2-nolora-noquant.tar.gz |tar xvf -

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_2_Prplxty_6.104443553348461.pt

In [50]:
device='cuda'
load_model_gen_text('gpt2', 'ckpt_Epoch_2_Prplxty_6.104443553348461.pt',  prompt=prompt, num_toks=num_toks, lora=False)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

checkpoint keys: dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'loss', 'device'])
completed success

[transformers] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY:
TITLE: TEXAS COMMERCE BANCSHARES <TCB> FILES PLAN

BODY: Texas Commerce Bancshares Inc's Dallas
Mortgage and Trust Co said it filed a registration statement
with the Securities and Exchange Commission for the proposed offering of
the securities.
    The company said proceeds of the offering will be used to
buy 2.5 mln shares of its common stock, for working capital,
to repay short-term bank debt, for working capital and
for working on the company's industrial revenue financing.
    Texas Commerce said proceeds of the offering will be used
to reduce short-term bank borrowings, for working capital,
for general corporate purposes and for working
capital.
 Reuter
<|endoftext|>