In [1]:
!pip install datasets bitsandbytes trl transformers peft huggingface-hub accelerate safetensors pandas matplotlib

Collecting datasets
  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.45.5-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting trl
  Downloading trl-0.16.1-py3-none-any.whl.metadata (12 kB)
Collecting transformers
  Downloading transformers-4.51.3-py3-none-any.whl.metadata (38 kB)
Collecting peft
  Downloading peft-0.15.2-py3-none-any.whl.metadata (13 kB)
Collecting huggingface-hub
  Downloading huggingface_hub-0.30.2-py3-none-any.whl.metadata (13 kB)
Collecting accelerate
  Downloading accelerate-1.6.0-py3-none-any.whl.metadata (19 kB)
Collecting safetensors
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: matplotlib in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (3.10.0)
Requirement already satisfied: filelock in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (19.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests>=2.32.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Collecting aiohttp (from datasets)
  Downloading aiohttp-3.11.16-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (21.3)
Requirement already satisfied: pyyaml>=5.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (6.0.2)
Requirement already satisfied: torch<3,>=2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bitsandbytes) (2.2.2)
Requirement already satisfied: rich in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from trl) (13.9.4)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: psutil in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from peft) (6.1.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: pillow>=8 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib) (3.2.1)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->datasets)
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp->datasets)
  Downloading async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: attrs>=17.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets) (23.2.0)
Collecting frozenlist>=1.1.1 (from aiohttp->datasets)
  Downloading frozenlist-1.5.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets)
  Downloading multidict-6.4.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp->datasets)
  Downloading propcache-0.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp->datasets)
  Downloading yarl-1.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (72 kB)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: sympy in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.0->bitsandbytes) (1.13.3)
Requirement already satisfied: networkx in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.0->bitsandbytes) (3.4.2)
Requirement already satisfied: jinja2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.0->bitsandbytes) (3.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rich->trl) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rich->trl) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->trl) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from jinja2->torch<3,>=2.0->bitsandbytes) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sympy->torch<3,>=2.0->bitsandbytes) (1.3.0)
Downloading datasets-3.5.0-py3-none-any.whl (491 kB)
Downloading bitsandbytes-0.45.5-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 202.5 MB/s eta 0:00:00a 0:00:01
Downloading trl-0.16.1-py3-none-any.whl (336 kB)
Downloading transformers-4.51.3-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 201.2 MB/s eta 0:00:00
Downloading peft-0.15.2-py3-none-any.whl (411 kB)
Downloading huggingface_hub-0.30.2-py3-none-any.whl (481 kB)
Downloading accelerate-1.6.0-py3-none-any.whl (354 kB)
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
Downloading aiohttp-3.11.16-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 127.8 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 74.3 MB/s eta 0:00:00
Downloading tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 157.6 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)
Downloading async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Downloading frozenlist-1.5.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (241 kB)
Downloading multidict-6.4.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (219 kB)
Downloading propcache-0.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (206 kB)
Downloading yarl-1.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (333 kB)
Installing collected packages: xxhash, safetensors, regex, propcache, multidict, fsspec, frozenlist, dill, async-timeout, aiohappyeyeballs, yarl, multiprocess, huggingface-hub, aiosignal, tokenizers, bitsandbytes, aiohttp, accelerate, transformers, peft, datasets, trl
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.2.0
    Uninstalling fsspec-2025.2.0:
      Successfully uninstalled fsspec-2025.2.0
  Attempting uninstall: dill
    Found existing installation: dill 0.3.9
    Uninstalling dill-0.3.9:
      Successfully uninstalled dill-0.3.9
  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.17
    Uninstalling multiprocess-0.70.17:
      Successfully uninstalled multiprocess-0.70.17
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pathos 0.3.3 requires dill>=0.3.9, but you have dill 0.3.8 which is incompatible.
pathos 0.3.3 requires multiprocess>=0.70.17, but you have multiprocess 0.70.16 which is incompatible.
Successfully installed accelerate-1.6.0 aiohappyeyeballs-2.6.1 aiohttp-3.11.16 aiosignal-1.3.2 async-timeout-5.0.1 bitsandbytes-0.45.5 datasets-3.5.0 dill-0.3.8 frozenlist-1.5.0 fsspec-2024.12.0 huggingface-hub-0.30.2 multidict-6.4.3 multiprocess-0.70.16 peft-0.15.2 propcache-0.3.1 regex-2024.11.6 safetensors-0.5.3 tokenizers-0.21.1 transformers-4.51.3 trl-0.16.1 xxhash-3.5.0 yarl-1.20.0

In [2]:
!pip install --upgrade evaluate

Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: datasets>=2.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (3.5.0)
Requirement already satisfied: numpy>=1.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (0.30.2)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (21.3)
Requirement already satisfied: filelock in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (19.0.0)
Requirement already satisfied: aiohttp in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.11.16)
Requirement already satisfied: pyyaml>=5.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from packaging->evaluate) (3.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.20.0)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
Installing collected packages: evaluate
Successfully installed evaluate-0.4.3

In [3]:
#!pip install bitsandbytes

In [1]:
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from datasets import load_dataset
import torch
from torch.utils.data import Dataset
from tqdm import tqdm
import evaluate
from trl import SFTConfig, SFTTrainer, DataCollatorForCompletionOnlyLM

from peft import get_peft_model, LoraConfig, TaskType, PeftModel

import pickle
import json
import matplotlib.pyplot as plt

from urllib.request import urlopen
import io

Matplotlib is building the font cache; this may take a moment.

In [2]:
import torch
from peft import prepare_model_for_kbit_training, get_peft_model, LoraConfig
from datasets import load_dataset, Dataset
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig, DataCollatorForLanguageModeling, DataCollatorWithPadding, DataCollatorWithFlattening, BitsAndBytesConfig
from trl import setup_chat_format, DataCollatorForCompletionOnlyLM
from trl.extras.dataset_formatting import FORMAT_MAPPING, instructions_formatting_function, conversations_formatting_function
from trl.trainer import ConstantLengthDataset

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [4]:
device

device(type='cuda')

In [5]:
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/WzOT_CwDALWedTtXjwH7bA/CodeAlpaca-20k.json

--2025-04-17 05:57:46--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/WzOT_CwDALWedTtXjwH7bA/CodeAlpaca-20k.json
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.45.118.108
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.45.118.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6957007 (6.6M) [application/json]
Saving to: ‘CodeAlpaca-20k.json.4’

100%[======================================>] 6,957,007   9.64MB/s   in 0.7s

2025-04-17 05:57:47 (9.64 MB/s) - ‘CodeAlpaca-20k.json.4’ saved [6957007/6957007]

In [6]:
dataset = load_dataset("json", data_files="CodeAlpaca-20k.json", split="train")
dataset

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['output', 'instruction', 'input'],
    num_rows: 20022
})

In [7]:
dataset[0]

{'output': 'arr = [2, 4, 6, 8, 10]',
 'instruction': 'Create an array of length 5 which contains all even numbers between 1 and 10.',
 'input': ''}

In [8]:
dataset = dataset.filter(lambda example: example["input"] == '')

Filter:   0%|          | 0/20022 [00:00<?, ? examples/s]

In [9]:
dataset = dataset.shuffle(seed=42)

In [10]:
dataset[0]

{'output': 'def create_input_string(nums, ops):\n    input_str = ""\n    \n    for i in range(len(nums)):\n        if i == 0:\n            input_str += str(nums[i])\n        else:\n            input_str += ops[i - 1] + str(nums[i])\n    \n    return input_str',
 'instruction': 'Create a function that produces input strings for a calculator.',
 'input': ''}

In [11]:
print(dataset[0]['output'])

def create_input_string(nums, ops):
    input_str = ""

    for i in range(len(nums)):
        if i == 0:
            input_str += str(nums[i])
        else:
            input_str += ops[i - 1] + str(nums[i])

    return input_str

In [12]:
dataset_split = dataset.train_test_split(test_size=0.2, seed=42)
train_dataset = dataset_split['train']
test_dataset = dataset_split['test']
dataset_split

DatasetDict({
    train: Dataset({
        features: ['output', 'instruction', 'input'],
        num_rows: 7811
    })
    test: Dataset({
        features: ['output', 'instruction', 'input'],
        num_rows: 1953
    })
})

In [13]:
# Select a small set of data for the resource limitation
# This dataset will be only used for evaluation parts, not for the training
#tiny_test_dataset=test_dataset.select(range(10))
#tiny_train_dataset=train_dataset.select(range(10))

In [14]:
# Base model
#model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m").to(device)

In [15]:
!pip install torchinfo
from torchinfo import summary

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [16]:
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-350m", padding_side='left')

tokenizer_config.json:   0%|          | 0.00/685 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/644 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/441 [00:00<?, ?B/s]

In [17]:
tokenizer

GPT2TokenizerFast(name_or_path='facebook/opt-350m', vocab_size=50265, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '</s>', 'unk_token': '</s>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [18]:
tokenizer.eos_token

'</s>'

In [19]:
print(tokenizer.chat_template)

None

In [31]:
tokenizer.special_tokens_map

{'bos_token': '</s>',
 'eos_token': '</s>',
 'unk_token': '</s>',
 'pad_token': '<pad>'}

In [32]:
def get_multiple_of(vocab_size):
    return 2**(bin(vocab_size)[::-1].find('1'))

##pad_to_multiple_of = get_multiple_of(model.config.vocab_size)
#pad_to_multiple_of

In [33]:
#model.resize_token_embeddings(len(tokenizer),
#                                  pad_to_multiple_of=pad_to_multiple_of)

In [34]:
tokenizer_phi = AutoTokenizer.from_pretrained("microsoft/phi-3-mini-4k-instruct")
print(tokenizer_phi.chat_template)

{% for message in messages %}{% if message['role'] == 'system' %}{{'<|system|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'user' %}{{'<|user|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'assistant' %}{{'<|assistant|>
' + message['content'] + '<|end|>
'}}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '<|assistant|>
' }}{% else %}{{ eos_token }}{% endif %}

In [35]:
tokenizer_phi

LlamaTokenizerFast(name_or_path='microsoft/phi-3-mini-4k-instruct', vocab_size=32000, model_max_length=4096, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '<|endoftext|>', 'unk_token': '<unk>', 'pad_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("</s>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=False),
	32000: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32001: AddedToken("<|assistant|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32002: AddedToken("<|placeholder1|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32003: AddedToken("<|placeholder2|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32004: AddedToken("<|placeholder3|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32005: AddedToken("<|placeholder4|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32006: AddedToken("<|system|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32007: AddedToken("<|end|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32008: AddedToken("<|placeholder5|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32009: AddedToken("<|placeholder6|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
	32010: AddedToken("<|user|>", rstrip=True, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [36]:
tokenizer

GPT2TokenizerFast(name_or_path='facebook/opt-350m', vocab_size=50265, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '</s>', 'unk_token': '</s>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [37]:
tokenizer.special_tokens_map

{'bos_token': '</s>',
 'eos_token': '</s>',
 'unk_token': '</s>',
 'pad_token': '<pad>'}

In [38]:
tokenizer_phi.special_tokens_map

{'bos_token': '<s>',
 'eos_token': '<|endoftext|>',
 'unk_token': '<unk>',
 'pad_token': '<|endoftext|>'}

In [39]:
tokenizer.vocab['</s>']

2

In [40]:
tokenizer_phi.vocab["<|user|>"]

32010

In [41]:
tokenizer.vocab['<pad>']

1

In [42]:
special_tokens_dict = {'unk_token': '<unk>',
                       'eos_token': '<|endoftext|>',
                       }
special_tokens_dict

{'unk_token': '<unk>', 'eos_token': '<|endoftext|>'}

In [43]:
new_toks  = ['<|system|>', '<|user|>', '<|assistant|>', '<|end|>']

In [44]:
new_toks

['<|system|>', '<|user|>', '<|assistant|>', '<|end|>']

In [45]:
tokenizer.add_special_tokens(special_tokens_dict)

2

In [46]:
tokenizer

GPT2TokenizerFast(name_or_path='facebook/opt-350m', vocab_size=50265, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '<|endoftext|>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50260: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [47]:
tokenizer.add_tokens(new_toks)

4

In [48]:
tokenizer

GPT2TokenizerFast(name_or_path='facebook/opt-350m', vocab_size=50265, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '<|endoftext|>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50260: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50265: AddedToken("<|system|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50266: AddedToken("<|user|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50267: AddedToken("<|assistant|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50268: AddedToken("<|end|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
}
)

In [49]:
len(tokenizer)

50269

In [50]:
tokenizer.chat_template = tokenizer_phi.chat_template
print(tokenizer.chat_template)

{% for message in messages %}{% if message['role'] == 'system' %}{{'<|system|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'user' %}{{'<|user|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'assistant' %}{{'<|assistant|>
' + message['content'] + '<|end|>
'}}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '<|assistant|>
' }}{% else %}{{ eos_token }}{% endif %}

In [51]:
def ds_chat_format(example):
  messages = []
  user_dict = {}
  asst_dict = {}
  for k in example.keys():
    role = k
    content = example[k]
    if k == 'assistant':
      asst_dict = {'role': role, 'content': content}
    else:
      user_dict = {'role': role, 'content': content}
  messages = [user_dict, asst_dict]
  return {'messages': messages}

In [52]:
import os
import torch
from datasets import load_dataset
from peft import get_peft_model, LoraConfig, prepare_model_for_kbit_training
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from trl import SFTConfig, SFTTrainer

In [53]:
bnb_config = BitsAndBytesConfig(
   load_in_4bit=True,
   bnb_4bit_quant_type="nf4",
   bnb_4bit_use_double_quant=True,
   bnb_4bit_compute_dtype=torch.float32
)
repo_id = "facebook/opt-350m"
model = AutoModelForCausalLM.from_pretrained(repo_id,
                                             device_map="cuda:0",
                                             quantization_config=bnb_config
)

pytorch_model.bin:   0%|          | 0.00/663M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/662M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [54]:
summary(model)

===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
OPTForCausalLM                                     --
├─OPTModel: 1-1                                    --
│    └─OPTDecoder: 2-1                             --
│    │    └─Embedding: 3-1                         25,739,264
│    │    └─OPTLearnedPositionalEmbedding: 3-2     2,099,200
│    │    └─Linear4bit: 3-3                        (262,144)
│    │    └─Linear4bit: 3-4                        (262,144)
│    │    └─ModuleList: 3-5                        151,314,432
├─Linear: 1-2                                      25,739,264
===========================================================================
Total params: 205,416,448
Trainable params: 53,676,032
Non-trainable params: 151,740,416
===========================================================================

In [55]:
print(model.get_memory_footprint()/1e6)

207.835136

In [56]:
model = prepare_model_for_kbit_training(model)
print(summary(model))
config = LoraConfig(
    r=8,                   # the rank of the adapter, the lower the fewer parameters you'll need to train
    lora_alpha=16,         # multiplier, usually 2*r
    bias="none",           # BEWARE: training biases *modifies* base model's behavior
    lora_dropout=0.05,
    task_type="CAUSAL_LM",
    # Newer models, such as Phi-3 at time of writing, may require
    # manually setting target modules
    #target_modules=['o_proj', 'qkv_proj', 'gate_up_proj', 'down_proj'],
)

model = get_peft_model(model, config)
model

===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
OPTForCausalLM                                     --
├─OPTModel: 1-1                                    --
│    └─OPTDecoder: 2-1                             --
│    │    └─Embedding: 3-1                         (25,739,264)
│    │    └─OPTLearnedPositionalEmbedding: 3-2     (2,099,200)
│    │    └─Linear4bit: 3-3                        (262,144)
│    │    └─Linear4bit: 3-4                        (262,144)
│    │    └─ModuleList: 3-5                        (151,314,432)
├─Linear: 1-2                                      (25,739,264)
===========================================================================
Total params: 205,416,448
Trainable params: 0
Non-trainable params: 205,416,448
===========================================================================

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): OPTForCausalLM(
      (model): OPTModel(
        (decoder): OPTDecoder(
          (embed_tokens): Embedding(50272, 512, padding_idx=1)
          (embed_positions): OPTLearnedPositionalEmbedding(2050, 1024)
          (project_out): Linear4bit(in_features=1024, out_features=512, bias=False)
          (project_in): Linear4bit(in_features=512, out_features=1024, bias=False)
          (layers): ModuleList(
            (0-23): 24 x OPTDecoderLayer(
              (self_attn): OPTSdpaAttention(
                (k_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
                (v_proj): lora.Linear4bit(
                  (base_layer): Linear4bit(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear4bit(
                  (base_layer): Linear4bit(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
              )
              (activation_fn): ReLU()
              (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              (fc1): Linear4bit(in_features=1024, out_features=4096, bias=True)
              (fc2): Linear4bit(in_features=4096, out_features=1024, bias=True)
              (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            )
          )
        )
      )
      (lm_head): Linear(in_features=512, out_features=50272, bias=False)
    )
  )
)

In [57]:
print(model.get_memory_footprint()/1e6)

267.296768

In [58]:
trainable_parms, tot_parms = model.get_nb_trainable_parameters()
print(f'Trainable parameters:             {trainable_parms/1e6:.2f}M')
print(f'Total parameters:                 {tot_parms/1e6:.2f}M')
print(f'Fraction of trainable parameters: {100*trainable_parms/tot_parms:.2f}%')

Trainable parameters:             0.79M
Total parameters:                 331.98M
Fraction of trainable parameters: 0.24%

In [59]:
train_dataset

Dataset({
    features: ['output', 'instruction', 'input'],
    num_rows: 7811
})

In [60]:
test_dataset

Dataset({
    features: ['output', 'instruction', 'input'],
    num_rows: 1953
})

In [61]:
train_dataset = train_dataset.rename_column("instruction", "user")
train_dataset = train_dataset.rename_column("output", "assistant")
train_dataset

Dataset({
    features: ['assistant', 'user', 'input'],
    num_rows: 7811
})

In [62]:
train_dataset = train_dataset.remove_columns("input")
train_dataset

Dataset({
    features: ['assistant', 'user'],
    num_rows: 7811
})

In [63]:
test_dataset = test_dataset.rename_column("instruction", "user")
test_dataset = test_dataset.rename_column("output", "assistant")
test_dataset = test_dataset.remove_columns("input")
test_dataset

Dataset({
    features: ['assistant', 'user'],
    num_rows: 1953
})

In [64]:
train_dataset[0]

{'assistant': 'db.collection.find( { count: { $gt: 10 } } )',
 'user': 'Write a query in MongoDB to find all documents which have a count greater than 10.'}

In [65]:
train_ds = train_dataset.map(ds_chat_format, batched=False)
test_ds = test_dataset.map(ds_chat_format, batched=False)

Map:   0%|          | 0/7811 [00:00<?, ? examples/s]

Map:   0%|          | 0/1953 [00:00<?, ? examples/s]

In [66]:
train_ds['messages'][0:2]

[[{'content': 'Write a query in MongoDB to find all documents which have a count greater than 10.',
   'role': 'user'},
  {'content': 'db.collection.find( { count: { $gt: 10 } } )',
   'role': 'assistant'}],
 [{'content': 'Determine the fraction of numbers in this list that are multiples of 3: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].',
   'role': 'user'},
  {'content': 'fraction = 3/10 = 0.3', 'role': 'assistant'}]]

In [67]:
test_ds['messages'][0:2]

[[{'content': 'Name the most important benefit of using a database system.',
   'role': 'user'},
  {'content': 'The most important benefit of using a database system is the ability to store and retrieve data quickly and easily. Database systems also provide support for data security, data integrity, and concurrently accessing and modifying data from multiple systems.',
   'role': 'assistant'}],
 [{'content': 'Come up with a Java program that checks if one string is a substring of another.',
   'role': 'user'},
  {'content': 'public static boolean isSubstring(String s, String x) {\n    int i = 0, j = 0;\n    while (i < s.length() && j < x.length()) {\n        if (s.charAt(i) == x.charAt(j)) {\n            i++;\n            j++;\n        } else {\n            i = i - j + 1;\n            j = 0;\n        }\n    }\n    if (j == x.length()) {\n        return true;\n    }\n    return false;\n}',
   'role': 'assistant'}]]

In [68]:
FORMAT_MAPPING['chatml'] == train_ds.features['messages']

True

In [69]:
messages = train_ds["messages"][0]
output_texts = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
print(output_texts)

<|user|>
Write a query in MongoDB to find all documents which have a count greater than 10.<|end|>
<|assistant|>
db.collection.find( { count: { $gt: 10 } } )<|end|>
<|endoftext|>

In [70]:
train_ds, test_ds

(Dataset({
     features: ['assistant', 'user', 'messages'],
     num_rows: 7811
 }),
 Dataset({
     features: ['assistant', 'user', 'messages'],
     num_rows: 1953
 }))

In [71]:
sft_config = SFTConfig(
    ## GROUP 1: Memory usage
    # These arguments will squeeze the most out of your GPU's RAM
    # Checkpointing
    #gradient_checkpointing=True,
    # this saves a LOT of memory
    # Set this to avoid exceptions in newer versions of PyTorch
    #gradient_checkpointing_kwargs={'use_reentrant': False},
    # Gradient Accumulation / Batch size
    # Actual batch (for updating) is same (1x) as micro-batch size
    gradient_accumulation_steps=1,
    # The initial (micro) batch size to start off with
    per_device_train_batch_size=64,
    # If batch size would cause OOM, halves its size until it works
    auto_find_batch_size=True,

    ## GROUP 2: Dataset-related
    max_seq_length=256,
    # Dataset
    # packing a dataset means no padding is needed
    packing=True,

    ## GROUP 3: These are typical training parameters
    num_train_epochs=20,
    learning_rate=3e-4,
    # Optimizer
    # 8-bit Adam optimizer - doesn't help much if you're using LoRA!
    optim='adamw_torch',

    ## GROUP 4: Logging parameters
    logging_steps=50,
    logging_dir='./logs',
    output_dir='./opt350-alpaca-code-adapter',
    report_to='none'
)

In [72]:
trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    args=sft_config,
    train_dataset=train_ds
    )

Converting train dataset to ChatML:   0%|          | 0/7811 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/7811 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/7811 [00:00<?, ? examples/s]

Packing train dataset:   0%|          | 0/7811 [00:00<?, ? examples/s]

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [73]:
trainer.__dict__

{'_metrics': {'train': defaultdict(list, {}), 'eval': defaultdict(list, {})},
 '_total_train_tokens': 0,
 'args': SFTConfig(output_dir='./opt350-alpaca-code-adapter', overwrite_output_dir=False, do_train=False, do_eval=False, do_predict=False, eval_strategy=<IntervalStrategy.NO: 'no'>, prediction_loss_only=False, per_device_train_batch_size=64, per_device_eval_batch_size=8, per_gpu_train_batch_size=None, per_gpu_eval_batch_size=None, gradient_accumulation_steps=1, eval_accumulation_steps=None, eval_delay=0, torch_empty_cache_steps=None, learning_rate=0.0003, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=20, max_steps=-1, lr_scheduler_type=<SchedulerType.LINEAR: 'linear'>, lr_scheduler_kwargs={}, warmup_ratio=0.0, warmup_steps=0, log_level='passive', log_level_replica='warning', log_on_each_node=True, logging_dir='./logs', logging_strategy=<IntervalStrategy.STEPS: 'steps'>, logging_first_step=False, logging_steps=50, logging_nan_inf_filter=True, save_strategy=<SaveStrategy.STEPS: 'steps'>, save_steps=500, save_total_limit=None, save_safetensors=True, save_on_each_node=False, save_only_model=False, restore_callback_states_from_checkpoint=False, no_cuda=False, use_cpu=False, use_mps_device=False, seed=42, data_seed=None, jit_mode_eval=False, use_ipex=False, bf16=False, fp16=False, fp16_opt_level='O1', half_precision_backend='auto', bf16_full_eval=False, fp16_full_eval=False, tf32=None, local_rank=0, ddp_backend=None, tpu_num_cores=None, tpu_metrics_debug=False, debug=[], dataloader_drop_last=False, eval_steps=None, dataloader_num_workers=0, dataloader_prefetch_factor=None, past_index=-1, run_name='./opt350-alpaca-code-adapter', disable_tqdm=False, remove_unused_columns=True, label_names=None, load_best_model_at_end=False, metric_for_best_model=None, greater_is_better=None, ignore_data_skip=False, fsdp=[], fsdp_min_num_params=0, fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False}, tp_size=0, fsdp_transformer_layer_cls_to_wrap=None, accelerator_config=AcceleratorConfig(split_batches=False, dispatch_batches=None, even_batches=True, use_seedable_sampler=True, non_blocking=False, gradient_accumulation_kwargs=None, use_configured_state=False), deepspeed=None, label_smoothing_factor=0.0, optim=<OptimizerNames.ADAMW_TORCH: 'adamw_torch'>, optim_args=None, adafactor=False, group_by_length=False, length_column_name='length', report_to=[], ddp_find_unused_parameters=None, ddp_bucket_cap_mb=None, ddp_broadcast_buffers=None, dataloader_pin_memory=True, dataloader_persistent_workers=False, skip_memory_metrics=True, use_legacy_prediction_loop=False, push_to_hub=False, resume_from_checkpoint=None, hub_model_id=None, hub_strategy=<HubStrategy.EVERY_SAVE: 'every_save'>, hub_token=None, hub_private_repo=None, hub_always_push=False, gradient_checkpointing=False, gradient_checkpointing_kwargs=None, include_inputs_for_metrics=False, include_for_metrics=[], eval_do_concat_batches=True, fp16_backend='auto', push_to_hub_model_id=None, push_to_hub_organization=None, push_to_hub_token=None, mp_parameters='', auto_find_batch_size=True, full_determinism=False, torchdynamo=None, ray_scope='last', ddp_timeout=1800, torch_compile=False, torch_compile_backend=None, torch_compile_mode=None, include_tokens_per_second=False, include_num_input_tokens_seen=False, neftune_noise_alpha=None, optim_target_modules=None, batch_eval_metrics=False, eval_on_start=False, use_liger_kernel=False, eval_use_gather_object=False, average_tokens_across_devices=False, model_init_kwargs=None, dataset_text_field='text', dataset_kwargs=None, dataset_num_proc=None, pad_token=None, max_length=256, packing=True, padding_free=False, eval_packing=None, dataset_batch_size=None, num_of_sequences=None, chars_per_token=None, max_seq_length=256, use_liger=None),
 'compute_loss_func': None,
 'hp_name': None,
 'deepspeed': None,
 'is_in_train': False,
 'accelerator': <accelerate.accelerator.Accelerator at 0x7fa6256ded40>,
 'gather_function': functools.partial(<bound method Accelerator.gather_for_metrics of <accelerate.accelerator.Accelerator object at 0x7fa6256ded40>>, use_gather_object=False),
 'is_deepspeed_enabled': False,
 'is_fsdp_enabled': False,
 'is_tp_enabled': False,
 '_memory_tracker': <transformers.trainer_utils.TrainerMemoryTracker at 0x7fa649c08a90>,
 'model_init': None,
 'is_model_parallel': False,
 'is_fsdp_xla_enabled': False,
 'place_model_on_device': True,
 'data_collator': DataCollatorForLanguageModeling(pad_token_id=1, return_tensors='pt'),
 'train_dataset': Dataset({
     features: ['input_ids'],
     num_rows: 3359
 }),
 'eval_dataset': None,
 'processing_class': GPT2TokenizerFast(name_or_path='facebook/opt-350m', vocab_size=50265, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '<|endoftext|>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
 	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
 	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
 	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	50260: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	50265: AddedToken("<|system|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
 	50266: AddedToken("<|user|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
 	50267: AddedToken("<|assistant|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
 	50268: AddedToken("<|end|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
 }
 ),
 'model_wrapped': PeftModelForCausalLM(
   (base_model): LoraModel(
     (model): OPTForCausalLM(
       (model): OPTModel(
         (decoder): OPTDecoder(
           (embed_tokens): Embedding(50272, 512, padding_idx=1)
           (embed_positions): OPTLearnedPositionalEmbedding(2050, 1024)
           (project_out): Linear4bit(in_features=1024, out_features=512, bias=False)
           (project_in): Linear4bit(in_features=512, out_features=1024, bias=False)
           (layers): ModuleList(
             (0-23): 24 x OPTDecoderLayer(
               (self_attn): OPTSdpaAttention(
                 (k_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
                 (v_proj): lora.Linear4bit(
                   (base_layer): Linear4bit(in_features=1024, out_features=1024, bias=True)
                   (lora_dropout): ModuleDict(
                     (default): Dropout(p=0.05, inplace=False)
                   )
                   (lora_A): ModuleDict(
                     (default): Linear(in_features=1024, out_features=8, bias=False)
                   )
                   (lora_B): ModuleDict(
                     (default): Linear(in_features=8, out_features=1024, bias=False)
                   )
                   (lora_embedding_A): ParameterDict()
                   (lora_embedding_B): ParameterDict()
                   (lora_magnitude_vector): ModuleDict()
                 )
                 (q_proj): lora.Linear4bit(
                   (base_layer): Linear4bit(in_features=1024, out_features=1024, bias=True)
                   (lora_dropout): ModuleDict(
                     (default): Dropout(p=0.05, inplace=False)
                   )
                   (lora_A): ModuleDict(
                     (default): Linear(in_features=1024, out_features=8, bias=False)
                   )
                   (lora_B): ModuleDict(
                     (default): Linear(in_features=8, out_features=1024, bias=False)
                   )
                   (lora_embedding_A): ParameterDict()
                   (lora_embedding_B): ParameterDict()
                   (lora_magnitude_vector): ModuleDict()
                 )
                 (out_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
               )
               (activation_fn): ReLU()
               (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
               (fc1): Linear4bit(in_features=1024, out_features=4096, bias=True)
               (fc2): Linear4bit(in_features=4096, out_features=1024, bias=True)
               (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
             )
           )
         )
       )
       (lm_head): Linear(in_features=512, out_features=50272, bias=False)
     )
   )
 ),
 'model': PeftModelForCausalLM(
   (base_model): LoraModel(
     (model): OPTForCausalLM(
       (model): OPTModel(
         (decoder): OPTDecoder(
           (embed_tokens): Embedding(50272, 512, padding_idx=1)
           (embed_positions): OPTLearnedPositionalEmbedding(2050, 1024)
           (project_out): Linear4bit(in_features=1024, out_features=512, bias=False)
           (project_in): Linear4bit(in_features=512, out_features=1024, bias=False)
           (layers): ModuleList(
             (0-23): 24 x OPTDecoderLayer(
               (self_attn): OPTSdpaAttention(
                 (k_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
                 (v_proj): lora.Linear4bit(
                   (base_layer): Linear4bit(in_features=1024, out_features=1024, bias=True)
                   (lora_dropout): ModuleDict(
                     (default): Dropout(p=0.05, inplace=False)
                   )
                   (lora_A): ModuleDict(
                     (default): Linear(in_features=1024, out_features=8, bias=False)
                   )
                   (lora_B): ModuleDict(
                     (default): Linear(in_features=8, out_features=1024, bias=False)
                   )
                   (lora_embedding_A): ParameterDict()
                   (lora_embedding_B): ParameterDict()
                   (lora_magnitude_vector): ModuleDict()
                 )
                 (q_proj): lora.Linear4bit(
                   (base_layer): Linear4bit(in_features=1024, out_features=1024, bias=True)
                   (lora_dropout): ModuleDict(
                     (default): Dropout(p=0.05, inplace=False)
                   )
                   (lora_A): ModuleDict(
                     (default): Linear(in_features=1024, out_features=8, bias=False)
                   )
                   (lora_B): ModuleDict(
                     (default): Linear(in_features=8, out_features=1024, bias=False)
                   )
                   (lora_embedding_A): ParameterDict()
                   (lora_embedding_B): ParameterDict()
                   (lora_magnitude_vector): ModuleDict()
                 )
                 (out_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
               )
               (activation_fn): ReLU()
               (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
               (fc1): Linear4bit(in_features=1024, out_features=4096, bias=True)
               (fc2): Linear4bit(in_features=4096, out_features=1024, bias=True)
               (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
             )
           )
         )
       )
       (lm_head): Linear(in_features=512, out_features=50272, bias=False)
     )
   )
 ),
 'model_accepts_loss_kwargs': True,
 'neftune_noise_alpha': None,
 'compute_metrics': None,
 'preprocess_logits_for_metrics': None,
 'optimizer': None,
 'lr_scheduler': None,
 'optimizer_cls_and_kwargs': None,
 'callback_handler': <transformers.trainer_callback.CallbackHandler at 0x7fa623710850>,
 '_loggers_initialized': False,
 'hub_model_id': None,
 '_signature_columns': None,
 'use_apex': False,
 'use_cpu_amp': False,
 'label_smoother': None,
 'control': TrainerControl(should_training_stop=False, should_epoch_stop=False, should_save=False, should_evaluate=False, should_log=False),
 'state': TrainerState(epoch=None, global_step=0, max_steps=0, logging_steps=500, eval_steps=500, save_steps=500, train_batch_size=None, num_train_epochs=0, num_input_tokens_seen=0, total_flos=0, log_history=[], best_metric=None, best_global_step=None, best_model_checkpoint=None, is_local_process_zero=True, is_world_process_zero=True, is_hyper_param_search=False, trial_name=None, trial_params=None, stateful_callbacks={'TrainerControl': {'args': {'should_training_stop': False, 'should_epoch_stop': False, 'should_save': False, 'should_evaluate': False, 'should_log': False}, 'attributes': {}}}),
 'current_flos': 0,
 'hp_search_backend': None,
 'label_names': ['labels'],
 'can_return_loss': False,
 '_train_batch_size': 64,
 '_created_lr_scheduler': False,
 'is_fsdp_xla_v2_enabled': False,
 'is_fsdp_xla_v1_enabled': False}

In [74]:
dl = trainer.get_train_dataloader()
batch = next(iter(dl))

In [75]:
tokenizer

GPT2TokenizerFast(name_or_path='facebook/opt-350m', vocab_size=50265, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '<|endoftext|>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50260: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50265: AddedToken("<|system|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50266: AddedToken("<|user|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50267: AddedToken("<|assistant|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50268: AddedToken("<|end|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
}
)

In [76]:
batch['input_ids'][0], batch['labels'][0]

(tensor([  311,    10,  5059,   618,    19,     5,  1270,     6,    22,  2387,
          1234, 21617,  1869,    72, 50268, 50118, 50267, 50118, 41552,   328,
         19174,  7164,   975, 16035, 48445, 15698, 50118, 41552,  6660, 22682,
         40635,   225, 46479, 50118, 41552,  3628, 15698, 50118, 28696, 46876,
         49160,   594, 40635, 44987,    12,   398, 46479, 50118, 28696, 46876,
           766, 40635,  5877,  3427,   113,  1383, 40635, 36097,  5214, 42005,
            12, 36097,     6,  2557,    12,  8056,  5214,   134,     4,   288,
         46479, 50118, 28696, 14691, 15698,  2387,  1234, 21617,  1869, 49138,
         14691, 15698, 50118, 49138,  3628, 15698, 50118, 41552,  9773, 15698,
         50118, 28696,   298,   134, 15698,  2387,  1234, 21617,  1869, 49138,
           298,   134, 15698, 50118, 28696,   642, 15698, 48386,  5059,   618,
          1383,   259, 49803,   642, 15698, 50118, 49138,  9773, 15698, 50118,
         49138,  6660, 15698, 50268, 50118, 50260,     2, 50266, 50118, 44758,
            10,   230, 10431,  1380,    14,  2326,  1294,   335,   215,    25,
           766,     6,  1046,     6,     8,  4050,     4, 50268, 50118, 50267,
         50118, 15110,  1380,  9067,  1437, 50118, 45152,  1437, 50118,  1437,
          1437,  1437,   285,  6755,   766,   131,  1437, 50118,  1437,  1437,
          1437,   285,  6979,  1046,   131,  1437, 50118,  1437,  1437,  1437,
           285,  6755, 48992,  4050,   131,  1437, 50140,  1437,  1437,  1437,
           285,  9067,  1640, 20951,   766,     6,  6979,  1046,     6,  6755,
         48992,  4050,    43,  1437, 50118,  1437,  1437,  1437, 25522,  1437,
         50118,  1437,  1437,  1437,  1437,  1437,  1437,  1437,    42,     4,
         13650,  5457,   766,   131,  1437, 50118,  1437,  1437,  1437,  1437,
          1437,  1437,  1437,    42,     4,  1580,  5457,  1046,   131,  1437,
         50118,  1437,  1437,  1437,  1437,  1437,  1437,  1437,    42,     4,
         44770,  5457,  4050,   131,  1437, 50118], device='cuda:0'),
 tensor([  311,    10,  5059,   618,    19,     5,  1270,     6,    22,  2387,
          1234, 21617,  1869,    72, 50268, 50118, 50267, 50118, 41552,   328,
         19174,  7164,   975, 16035, 48445, 15698, 50118, 41552,  6660, 22682,
         40635,   225, 46479, 50118, 41552,  3628, 15698, 50118, 28696, 46876,
         49160,   594, 40635, 44987,    12,   398, 46479, 50118, 28696, 46876,
           766, 40635,  5877,  3427,   113,  1383, 40635, 36097,  5214, 42005,
            12, 36097,     6,  2557,    12,  8056,  5214,   134,     4,   288,
         46479, 50118, 28696, 14691, 15698,  2387,  1234, 21617,  1869, 49138,
         14691, 15698, 50118, 49138,  3628, 15698, 50118, 41552,  9773, 15698,
         50118, 28696,   298,   134, 15698,  2387,  1234, 21617,  1869, 49138,
           298,   134, 15698, 50118, 28696,   642, 15698, 48386,  5059,   618,
          1383,   259, 49803,   642, 15698, 50118, 49138,  9773, 15698, 50118,
         49138,  6660, 15698, 50268, 50118, 50260,     2, 50266, 50118, 44758,
            10,   230, 10431,  1380,    14,  2326,  1294,   335,   215,    25,
           766,     6,  1046,     6,     8,  4050,     4, 50268, 50118, 50267,
         50118, 15110,  1380,  9067,  1437, 50118, 45152,  1437, 50118,  1437,
          1437,  1437,   285,  6755,   766,   131,  1437, 50118,  1437,  1437,
          1437,   285,  6979,  1046,   131,  1437, 50118,  1437,  1437,  1437,
           285,  6755, 48992,  4050,   131,  1437, 50140,  1437,  1437,  1437,
           285,  9067,  1640, 20951,   766,     6,  6979,  1046,     6,  6755,
         48992,  4050,    43,  1437, 50118,  1437,  1437,  1437, 25522,  1437,
         50118,  1437,  1437,  1437,  1437,  1437,  1437,  1437,    42,     4,
         13650,  5457,   766,   131,  1437, 50118,  1437,  1437,  1437,  1437,
          1437,  1437,  1437,    42,     4,  1580,  5457,  1046,   131,  1437,
         50118,  1437,  1437,  1437,  1437,  1437,  1437,  1437,    42,     4,
         44770,  5457,  4050,   131,  1437, 50118], device='cuda:0'))

In [77]:
#tokenizer.decode(batch['labels'][0][batch['labels'][0]>-100])

In [78]:
#tokenizer.decode(batch['input_ids'][0][batch['input_ids'][0] != 1])

In [79]:
len(batch['input_ids'][0])

256

In [80]:
trainer.train()

`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

TrainOutput(global_step=1060, training_loss=1.6606299274372605, metrics={'train_runtime': 9008.9202, 'train_samples_per_second': 7.457, 'train_steps_per_second': 0.118, 'total_flos': 3.138419668549632e+16, 'train_loss': 1.6606299274372605})

In [81]:
def gen_prompt(tokenizer, sentence):
    converted_sample = [
        {"role": "user", "content": sentence},
    ]
    prompt = tokenizer.apply_chat_template(converted_sample,
                                           tokenize=False,
                                           add_generation_prompt=True)
    return prompt

In [110]:
def generate(model, tokenizer, prompt, orig_completion, max_new_tokens=128, skip_special_tokens=False):
    tokenized_input = tokenizer(prompt, add_special_tokens=False, return_tensors="pt").to(model.device)

    model.eval()
    generation_output = model.generate(**tokenized_input,
                                       eos_token_id=tokenizer.eos_token_id,
                                       max_new_tokens=max_new_tokens)

    output = tokenizer.batch_decode(generation_output,
                                    skip_special_tokens=skip_special_tokens)
    print(output[0])
    print("##############")
    print('orig completion: ', orig_completion)
    #return output[0]

In [114]:
def gen_prompt_exec(model, tokenizer, sentence, orig_completion):
    prompt = gen_prompt(tokenizer, sentence)
    print("##############")
    print(prompt)
    print("##############")
    generate(model, tokenizer, prompt, orig_completion)

In [117]:
sentence = test_dataset[0]['user']
orig_completion = test_dataset[0]['assistant']
gen_prompt_exec(model, tokenizer, sentence, orig_completion)

##############
<|user|>
Name the most important benefit of using a database system.<|end|>
<|assistant|>

##############
<|user|>
Name the most important benefit of using a database system.<|end|>
<|assistant|>
The most important benefit of using a database system is the ability to store and retrieve data in a way that is easy to use and maintain. This is especially true for data that is stored in a database, such as financial data, customer data, and customer information. This is especially true for data that is stored in a database, such as customer data, customer information, and customer information.<|end|>
<|endoftext|>
##############
orig completion:  The most important benefit of using a database system is the ability to store and retrieve data quickly and easily. Database systems also provide support for data security, data integrity, and concurrently accessing and modifying data from multiple systems.

In [118]:
idx = 6
sentence = test_dataset[idx]['user']
orig_completion = test_dataset[idx]['assistant']
gen_prompt_exec(model, tokenizer, sentence, orig_completion)

##############
<|user|>
What is an example of a multi-dimensional array?<|end|>
<|assistant|>

##############
<|user|>
What is an example of a multi-dimensional array?<|end|>
<|assistant|>
A multi-dimensional array is a set of objects that are arranged in a way that is more or less parallel to the original object. It is a set of objects that are arranged in a way that is more or less parallel to the original object. It is a set of objects that are arranged in a way that is more or less parallel to the original object. It is a set of objects that are arranged in a way that is more or less parallel to the original object.<|end|>
<|endoftext|>
##############
orig completion:  An example of a multi-dimensional array is a two-dimensional array, which is an array of arrays. For example:

var array = [[1,2,3], [4,5,6], [7,8,9]];

In [126]:
idx = 77
sentence = train_dataset[idx]['user']
orig_completion = train_dataset[idx]['assistant']
gen_prompt_exec(model, tokenizer, sentence, orig_completion)

##############
<|user|>
Construct a while loop with an if-else statement in Java to print all odd numbers between 1 to 10.<|end|>
<|assistant|>

##############
<|user|>
Construct a while loop with an if-else statement in Java to print all odd numbers between 1 to 10.<|end|>
<|assistant|>
public static int getUnodds(int nums) {
    int num = num;
    for (int i = 0; i < num; i++) {
        int num = num;
        if (num % i == 0) {
             num += i;
        }
    }
    return num;
}<|end|>
<|endoftext|>
##############
orig completion:  int i = 1;
while (i <= 10) {
    if (i % 2 != 0) {
        System.out.print(i + " ");
    }
    i++;
}

In [127]:
trainer.save_model('alpaca-opt-code-adapter_full_text')

In [128]:
#let us continue training the same model but using completiononlyLM collator

In [143]:
sft_config = SFTConfig(
    ## GROUP 1: Memory usage
    # These arguments will squeeze the most out of your GPU's RAM
    # Checkpointing
    #gradient_checkpointing=True,
    # this saves a LOT of memory
    # Set this to avoid exceptions in newer versions of PyTorch
    #gradient_checkpointing_kwargs={'use_reentrant': False},
    # Gradient Accumulation / Batch size
    # Actual batch (for updating) is same (1x) as micro-batch size
    gradient_accumulation_steps=1,
    # The initial (micro) batch size to start off with
    per_device_train_batch_size=64,
    # If batch size would cause OOM, halves its size until it works
    auto_find_batch_size=True,

    ## GROUP 2: Dataset-related
    max_seq_length=128,
    # Dataset
    # packing a dataset means no padding is needed
    packing=False,

    ## GROUP 3: These are typical training parameters
    num_train_epochs=20,
    learning_rate=3e-4,
    # Optimizer
    # 8-bit Adam optimizer - doesn't help much if you're using LoRA!
    optim='adamw_torch',

    ## GROUP 4: Logging parameters
    logging_steps=50,
    logging_dir='./logs',
    output_dir='./opt350-alpaca-code-adapter',
    report_to='none'
)

In [144]:
print(tokenizer.chat_template)

{% for message in messages %}{% if message['role'] == 'system' %}{{'<|system|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'user' %}{{'<|user|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'assistant' %}{{'<|assistant|>
' + message['content'] + '<|end|>
'}}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '<|assistant|>
' }}{% else %}{{ eos_token }}{% endif %}

In [145]:
train_dataset[0]

{'assistant': 'db.collection.find( { count: { $gt: 10 } } )',
 'user': 'Write a query in MongoDB to find all documents which have a count greater than 10.'}

In [146]:
tokenizer

GPT2TokenizerFast(name_or_path='facebook/opt-350m', vocab_size=50265, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '<|endoftext|>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50260: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50265: AddedToken("<|system|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50266: AddedToken("<|user|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50267: AddedToken("<|assistant|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50268: AddedToken("<|end|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
}
)

In [147]:
tokenizer.padding_side='left'
response_template = '<|assistant|>' # according to the tokenizer's chat template
collator_fn=DataCollatorForCompletionOnlyLM(response_template, tokenizer=tokenizer)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    args=sft_config,
    train_dataset=train_ds,
    data_collator=collator_fn
    )

Applying chat template to train dataset:   0%|          | 0/7811 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/7811 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/7811 [00:00<?, ? examples/s]

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    peft_config=peft_config,
    data_collator=collator_fn,
    args=SFTConfig(
        output_dir="./future_name_on_the_hub",
        packing=False,
        max_seq_length=max_seq_length,
    )
)

In [148]:
dl = trainer.get_train_dataloader()
batch = next(iter(dl))
batch['input_ids'][0], batch['labels'][0]

(tensor([    1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     2, 50266, 50118, 45714,    10, 41614,
         25860,     7,  5163,    70,     5, 11693,  1947,    11,     5,   576,
         41616,     4, 50268, 50118, 50267, 50118, 49179,   211, 11595,  2444,
          7164,   412, 11974, 41616,   131, 50268, 50118, 50260],
        device='cuda:0'),
 tensor([ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100, 50118, 49179,   211, 11595,  2444,
          7164,   412, 11974, 41616,   131, 50268, 50118, 50260],
        device='cuda:0'))

In [149]:
len(batch['input_ids'][0])

128

In [ ]:
trainer.train()

TrainOutput(global_step=2460, training_loss=1.2849677585973973, metrics={'train_runtime': 10075.6906, 'train_samples_per_second': 15.505, 'train_steps_per_second': 0.244, 'total_flos': 3.648927294500045e+16, 'train_loss': 1.2849677585973973})

In [159]:
idx = 10
sentence = test_dataset[idx]['user']
orig_completion = test_dataset[idx]['assistant']
gen_prompt_exec(model, tokenizer, sentence, orig_completion)

##############
<|user|>
Write a code snipplet that computes the sum of numbers between 1 and 100.<|end|>
<|assistant|>

##############
<|user|>
Write a code snipplet that computes the sum of numbers between 1 and 100.<|end|>
<|assistant|>
sum_of_numbers = 0
for num in range(1, 100):
    sum_of_numbers += num
print(sum_of_numbers)<|end|>
<|endoftext|>
##############
orig completion:  let sum = 0;
for(let i = 1; i <= 100; i++) {
  sum += i;
}

In [160]:
trainer.save_model('alpaca-opt-code-adapter_full_text_CO')

In [163]:
trainer.args.num_train_epochs = 10

In [164]:
trainer.args.num_train_epochs

10

In [ ]:
trainer.train()

TrainOutput(global_step=1230, training_loss=1.1831197630099164, metrics={'train_runtime': 5037.7143, 'train_samples_per_second': 15.505, 'train_steps_per_second': 0.244, 'total_flos': 1.824474322717901e+16, 'train_loss': 1.1831197630099164})

In [166]:
idx = 10
sentence = test_dataset[idx]['user']
orig_completion = test_dataset[idx]['assistant']
gen_prompt_exec(model, tokenizer, sentence, orig_completion)

##############
<|user|>
Write a code snipplet that computes the sum of numbers between 1 and 100.<|end|>
<|assistant|>

##############
<|user|>
Write a code snipplet that computes the sum of numbers between 1 and 100.<|end|>
<|assistant|>
sum = 0
for i in range(1, 101):
    sum += i
print(sum)<|end|>
<|endoftext|>
##############
orig completion:  let sum = 0;
for(let i = 1; i <= 100; i++) {
  sum += i;
}

In [168]:
idx = 25
sentence = test_dataset[idx]['user']
orig_completion = test_dataset[idx]['assistant']
gen_prompt_exec(model, tokenizer, sentence, orig_completion)

##############
<|user|>
Create a JavaScript object that contains a student's name, age, and courses.<|end|>
<|assistant|>

##############
<|user|>
Create a JavaScript object that contains a student's name, age, and courses.<|end|>
<|assistant|>
const studentName = {
    name: 'John',
    age: 25,
    courses: 'Degree',
    course_id: 'Degree',
    course_description: 'Degree'
};<|end|>
<|endoftext|>
##############
orig completion:  let student = {
    name: "John Doe",
    age: 20,
    courses: ["Math", "Physics", "English"]
};

In [169]:
idx = 5
sentence = test_dataset[idx]['user']
orig_completion = test_dataset[idx]['assistant']
gen_prompt_exec(model, tokenizer, sentence, orig_completion)

##############
<|user|>
Generate a 5x5 array with all its elements equal to 1.<|end|>
<|assistant|>

##############
<|user|>
Generate a 5x5 array with all its elements equal to 1.<|end|>
<|assistant|>
import random

def generate_array():
    array = []
    for i in range(5):
        array.append(random.randint(1, 1))
    return array<|end|>
<|endoftext|>
##############
orig completion:  arr = [[1,1,1,1,1],
       [1,1,1,1,1],
       [1,1,1,1,1],
       [1,1,1,1,1],
       [1,1,1,1,1]]

In [170]:
idx = 30
sentence = test_dataset[idx]['user']
orig_completion = test_dataset[idx]['assistant']
gen_prompt_exec(model, tokenizer, sentence, orig_completion)

##############
<|user|>
Construct a query in MySQL to calculate the total salary of all employees in a given department.<|end|>
<|assistant|>

##############
<|user|>
Construct a query in MySQL to calculate the total salary of all employees in a given department.<|end|>
<|assistant|>
SELECT SUM(salary) FROM employees WHERE department = 'Department1';<|end|>
<|endoftext|>
##############
orig completion:  SELECT SUM(Salary)
FROM Employees
WHERE Department = 'DEPARTMENT-NAME';

In [171]:
trainer.save_model('alpaca-opt-code-adapter_full_text_CO_1')

In [172]:
os.listdir('alpaca-opt-code-adapter_full_text_CO_1')

['vocab.json',
 'adapter_config.json',
 'tokenizer.json',
 'tokenizer_config.json',
 'added_tokens.json',
 'adapter_model.safetensors',
 'special_tokens_map.json',
 'training_args.bin',
 'README.md',
 'merges.txt']

In [173]:
from huggingface_hub import login
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [174]:
trainer.push_to_hub()

adapter_model.safetensors:   0%|          | 0.00/3.16M [00:00<?, ?B/s]

Upload 2 LFS files:   0%|          | 0/2 [00:00<?, ?it/s]

training_args.bin:   0%|          | 0.00/5.56k [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/Fardan/opt350-alpaca-code-adapter/commit/823a3c692e1d93a2b9deb3ed898f77546febbfae', commit_message='End of training', commit_description='', oid='823a3c692e1d93a2b9deb3ed898f77546febbfae', pr_url=None, repo_url=RepoUrl('https://huggingface.co/Fardan/opt350-alpaca-code-adapter', endpoint='https://huggingface.co', repo_type='model', repo_id='Fardan/opt350-alpaca-code-adapter'), pr_revision=None, pr_num=None)