In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from pathlib import Path
import sys
from torch.utils.data import Dataset, DataLoader, RandomSampler
import math
from collections import OrderedDict

In [2]:
!pip install torchinfo
from torchinfo import summary

Requirement already satisfied: torchinfo in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (1.8.0)

In [227]:
!pip install sacrebleu bert-score

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: sacrebleu in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (2.5.1)
Requirement already satisfied: bert-score in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (0.3.13)
Requirement already satisfied: portalocker in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sacrebleu) (3.1.1)
Requirement already satisfied: regex in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sacrebleu) (2024.11.6)
Requirement already satisfied: tabulate>=0.8.9 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sacrebleu) (1.26.4)
Requirement already satisfied: colorama in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sacrebleu) (0.4.6)
Requirement already satisfied: lxml in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sacrebleu) (5.3.1)
Requirement already satisfied: torch>=1.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bert-score) (2.2.2)
Requirement already satisfied: pandas>=1.0.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bert-score) (2.2.3)
Requirement already satisfied: transformers>=3.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bert-score) (4.49.0)
Requirement already satisfied: requests in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bert-score) (2.32.3)
Requirement already satisfied: tqdm>=4.31.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bert-score) (4.67.1)
Requirement already satisfied: matplotlib in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bert-score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bert-score) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from packaging>=20.9->bert-score) (3.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas>=1.0.1->bert-score) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas>=1.0.1->bert-score) (2025.1)
Requirement already satisfied: filelock in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.0.0->bert-score) (3.17.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.0.0->bert-score) (4.12.2)
Requirement already satisfied: sympy in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.0.0->bert-score) (1.13.3)
Requirement already satisfied: networkx in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.0.0->bert-score) (3.4.2)
Requirement already satisfied: jinja2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.0.0->bert-score) (3.1.5)
Requirement already satisfied: fsspec in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.0.0->bert-score) (2024.12.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers>=3.0.0->bert-score) (0.29.3)
Requirement already satisfied: pyyaml>=5.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers>=3.0.0->bert-score) (6.0.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers>=3.0.0->bert-score) (0.21.1)
Requirement already satisfied: safetensors>=0.4.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers>=3.0.0->bert-score) (0.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib->bert-score) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib->bert-score) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib->bert-score) (1.4.7)
Requirement already satisfied: pillow>=8 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from matplotlib->bert-score) (11.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->bert-score) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->bert-score) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->bert-score) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->bert-score) (2025.1.31)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert-score) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sympy->torch>=1.0.0->bert-score) (1.3.0)

In [228]:
!pip install evaluate
import evaluate

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: evaluate in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (0.4.3)
Requirement already satisfied: datasets>=2.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (3.4.0)
Requirement already satisfied: numpy>=1.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (0.29.3)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (21.3)
Requirement already satisfied: filelock in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (19.0.0)
Requirement already satisfied: aiohttp in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.11.13)
Requirement already satisfied: pyyaml>=5.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from packaging->evaluate) (3.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.3)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda

In [4]:
torch.__version__

'2.2.2'

In [5]:
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, dropout, max_len, device):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        pe = torch.zeros(max_len, d_model, device=device)
        position = torch.arange(0., max_len,
                                device=device).unsqueeze(1)
        div_term = torch.exp(torch.arange(0., d_model, 2, device=device) * -(math.log(10000.0) / d_model))
        pe_pos = torch.mul(position, div_term)
        pe[:, 0::2] = torch.sin(pe_pos)
        pe[:, 1::2] = torch.cos(pe_pos)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        out = self.pe[:, :x.size(1)].requires_grad_(False)
        return out

In [6]:
#del pe
pe_e = PositionalEncoding(d_model=768, dropout=0.1, max_len=512, device=device)
inp_tok = torch.tensor([5,8,78, 86, 78, 90, 45]).unsqueeze(0)
inp_tok, inp_tok.shape

(tensor([[ 5,  8, 78, 86, 78, 90, 45]]), torch.Size([1, 7]))

In [7]:
pe_e_e = pe_e(inp_tok)
pe_e_e, pe_e_e.shape

(tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
            0.0000e+00,  1.0000e+00],
          [ 8.4147e-01,  5.4030e-01,  8.2843e-01,  ...,  1.0000e+00,
            1.0243e-04,  1.0000e+00],
          [ 9.0930e-01, -4.1615e-01,  9.2799e-01,  ...,  1.0000e+00,
            2.0486e-04,  1.0000e+00],
          ...,
          [-7.5680e-01, -6.5364e-01, -6.9153e-01,  ...,  1.0000e+00,
            4.0971e-04,  1.0000e+00],
          [-9.5892e-01,  2.8366e-01, -9.8573e-01,  ...,  1.0000e+00,
            5.1214e-04,  1.0000e+00],
          [-2.7942e-01,  9.6017e-01, -4.1267e-01,  ...,  1.0000e+00,
            6.1457e-04,  1.0000e+00]]], device='cuda:0'),
 torch.Size([1, 7, 768]))

In [8]:
class Embed(nn.Module):
    def __init__(self, vocab_size, embed_dim, ctx_len, do, device):
        super().__init__()
        self.tok_layer = nn.Embedding(vocab_size, embed_dim)
        self.pos_layer = PositionalEncoding(embed_dim, do, ctx_len, device)
        self.norm_do = nn.Sequential(
            nn.LayerNorm(embed_dim),
            nn.Dropout(do)
            )
        self.device = device
        self.ctx_len = ctx_len

    def forward(self, inp):
        inp = inp.to(self.device)
        len_inp = inp.shape[-1]
        try:
            assert len_inp <= self.ctx_len
        except:
            print("Err..Errr. Error...Bro..Length of supplied text exceeds context length defined.Exiting the program now")
            sys.exit(1)
        tok_embed = self.tok_layer(inp)
        pos_embed = self.pos_layer(inp)
        embed_tok_pos = tok_embed + pos_embed
        embed_out = self.norm_do(embed_tok_pos)
        return embed_out

In [9]:
inp_tok = torch.tensor([5,8,78, 86, 78, 90, 45]).unsqueeze(0)
inp_tok, inp_tok.shape

(tensor([[ 5,  8, 78, 86, 78, 90, 45]]), torch.Size([1, 7]))

In [10]:
emb = Embed(100, 768, 512, 0.1, device).to(device)

In [11]:
emb_out = emb(inp_tok.to(device))
emb_out.shape, emb_out

(torch.Size([1, 7, 768]),
 tensor([[[-1.5386,  0.3591,  0.8827,  ...,  0.9390,  0.0000,  0.9367],
          [ 1.6824,  0.0000,  1.0312,  ...,  0.0288, -0.0555, -0.2307],
          [-0.0114, -0.0000,  0.9309,  ...,  1.3326, -0.1746,  1.3423],
          ...,
          [-1.6158, -0.7835, -0.6554,  ...,  1.3534, -0.1079,  1.3628],
          [ 0.0432,  1.1828, -0.5430,  ..., -0.9626, -0.7858,  0.6681],
          [ 0.6340, -0.1091, -1.0273,  ...,  0.1483, -2.8837,  1.1835]]],
        device='cuda:0', grad_fn=<NativeDropoutBackward0>))

In [12]:
summary(emb)

=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
Embed                                    --
├─Embedding: 1-1                         76,800
├─PositionalEncoding: 1-2                --
│    └─Dropout: 2-1                      --
├─Sequential: 1-3                        --
│    └─LayerNorm: 2-2                    1,536
│    └─Dropout: 2-3                      --
=================================================================
Total params: 78,336
Trainable params: 78,336
Non-trainable params: 0
=================================================================

In [13]:
def att_mask(attention_mask, lookahead, cross_att, x=None):
    if cross_att:
        batch_dim = x[0]
        repeat = x[1]
    else:
        batch_dim = attention_mask.shape[0]
        repeat = len(attention_mask[0])

    mask =[]
    for i in range(batch_dim):
        am_interim = [attention_mask[i].tolist()] * repeat
        am_interim = torch.tensor(am_interim).unsqueeze(0)
        mask.append(am_interim)
    mask = torch.vstack(mask)
    if lookahead:
        inp_save = mask
        mask = torch.tril(torch.ones(mask.shape))
    mask = torch.where(mask == 0, -torch.inf, 0.0)
    return mask

In [14]:
attention_mask = torch.tensor([[1,1,1,1,0,0], [1,1,1,0,0,0]])
attention_mask.shape

torch.Size([2, 6])

In [15]:
mask  = att_mask(attention_mask, lookahead=False, cross_att=False, x=[2,9,6])

In [16]:
mask, mask.shape

(tensor([[[0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf]],

         [[0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf]]]),
 torch.Size([2, 6, 6]))

In [17]:
mask  = att_mask(attention_mask, lookahead=True, cross_att=False, x=[2,9,6])

In [18]:
mask, mask.shape

(tensor([[[0., -inf, -inf, -inf, -inf, -inf],
          [0., 0., -inf, -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., 0., -inf],
          [0., 0., 0., 0., 0., 0.]],

         [[0., -inf, -inf, -inf, -inf, -inf],
          [0., 0., -inf, -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., 0., -inf],
          [0., 0., 0., 0., 0., 0.]]]),
 torch.Size([2, 6, 6]))

In [19]:
mask  = att_mask(attention_mask, lookahead=False, cross_att=True, x=[2,9,6])

In [20]:
mask, mask.shape

(tensor([[[0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf]],

         [[0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf]]]),
 torch.Size([2, 9, 6]))

In [21]:
attention_mask = torch.tensor([[1,1,1,1,1,1,0,0,0], [1,1,1,1,0,0,0,0,0]])
attention_mask.shape

torch.Size([2, 9])

In [22]:
mask  = att_mask(attention_mask, lookahead=False, cross_att=True, x=[2,6,9])
mask, mask.shape

(tensor([[[0., 0., 0., 0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., 0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., 0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., 0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., 0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., 0., 0., 0., -inf, -inf, -inf]],

         [[0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf],
          [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf],
          [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf],
          [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf],
          [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf],
          [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf]]]),
 torch.Size([2, 6, 9]))

In [23]:
class Attention(nn.Module):
    def __init__(self, embed_dim, k_dim, do, device):
        super().__init__()
        self.embed_dim = embed_dim
        self.k_dim = k_dim
        self.query = nn.Linear(embed_dim, k_dim)
        self.key = nn.Linear(embed_dim, k_dim)
        self.value = nn.Linear(embed_dim, k_dim)
        self.att_do = nn.Dropout(do)
        self.device = device

    def forward(self, qry, ky, vlu, mask):
        q = self.query(qry)
        k = self.key(ky)
        v = self.value(vlu)
        qk = (q@k.transpose(1, 2))/(self.k_dim**0.5)
        mask = mask.to(self.device)
        qk_m = qk + mask
        qk_m_smax = torch.softmax(qk_m, dim=-1)
        qk_m_smax_do = self.att_do(qk_m_smax)
        qkv = qk_m_smax_do@v
        return qkv

In [24]:
class Attention_Block(nn.Module):
    def __init__(self, num_heads, embed_dim, k_dim, do, device):
        super().__init__()
        self.num_heads = num_heads
        self.heads_list = [Attention(embed_dim, k_dim, do, device) for i in range(num_heads)]
        self.heads = nn.ModuleList(self.heads_list)
        self.lin_do = nn.Sequential(
            nn.Linear(embed_dim, embed_dim),
            nn.Dropout(do)
        )

    def forward(self, q, k, v, mask):
        heads_list_out = [head(q, k, v, mask) for head in self.heads]
        att_head = torch.cat(heads_list_out, dim=-1)
        att_head_out = self.lin_do(att_head)
        return att_head_out

In [25]:
class Encoder_Block(nn.Module):
    def __init__(self, num_heads, embed_dim, k_dim, do, device):
        super().__init__()
        self.MHA = Attention_Block(num_heads, embed_dim, k_dim, do, device)
        self.mha_blk_end_layernorm = nn.LayerNorm(embed_dim)
        self.ff = nn.Sequential(
            nn.Linear(embed_dim, embed_dim*4),
            nn.GELU(),
            nn.Linear(embed_dim*4, embed_dim),
            nn.Dropout(do)
            )
        self.enc_blk_end_layernorm = nn.LayerNorm(embed_dim)

    def forward(self, args_list):  #q, k, v, mask):
        x = args_list[0]
        mask = args_list[1]

        inp_start_att_block = x
        x = self.MHA(x, x, x, mask)

        x = x + inp_start_att_block
        x = self.mha_blk_end_layernorm(x)

        inp_start_ff_block = x
        x = self.ff(x)

        x = x + inp_start_ff_block
        x = self.enc_blk_end_layernorm(x)
        return [x, mask]

In [26]:
class Encoder(nn.Module):
    def __init__(self, num_layers, num_heads, vocab_size, embed_dim, k_dim, ctx_len, do, device):
        super().__init__()
        self.emb = Embed(vocab_size, embed_dim, ctx_len, do, device)
        self.layer_list = [Encoder_Block(num_heads, embed_dim, k_dim, do, device) for i in range(num_layers)]
        self.layers = nn.Sequential(*self.layer_list)

    def forward(self, input_ids, attention_mask):
        x = self.emb(input_ids)
        mask = att_mask(attention_mask, lookahead=False, cross_att=False, x=None)
        x = self.layers([x, mask])
        return x[0]

In [27]:
enc = Encoder(3, 6, 100, 768, 128, 100, 0.1, device).to(device)
enc

Encoder(
  (emb): Embed(
    (tok_layer): Embedding(100, 768)
    (pos_layer): PositionalEncoding(
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (norm_do): Sequential(
      (0): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (1): Dropout(p=0.1, inplace=False)
    )
  )
  (layers): Sequential(
    (0): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (1): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (2): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
  )
)

In [28]:
inp = torch.randint(1,100, (4,6))
am = torch.ones(inp.shape)
inp.shape, am.shape

(torch.Size([4, 6]), torch.Size([4, 6]))

In [29]:
out = enc(inp.to(device), am.to(device))
out.shape

torch.Size([4, 6, 768])

In [30]:
class Decoder_Block(nn.Module):
    def __init__(self, num_heads, embed_dim, k_dim, do, device, decoderonly=False):
        super().__init__()
        self.MHA_CAUSAL_ATTN = Attention_Block(num_heads, embed_dim, k_dim, do, device)
        self.mha_causal_end_layernorm = nn.LayerNorm(embed_dim)
        self.decoderonly = decoderonly
        if not decoderonly:
            self.MHA_CROSS_ATTN = Attention_Block(num_heads, embed_dim, k_dim, do, device)
            self.mha_cross_end_layernorm = nn.LayerNorm(embed_dim)
        self.ff = nn.Sequential(
            nn.Linear(embed_dim, embed_dim*4),
            nn.GELU(),
            nn.Linear(embed_dim*4, embed_dim),
            nn.Dropout(do)
            )
        self.dec_blk_end_layernorm = nn.LayerNorm(embed_dim)

    def forward(self, args_list):
        q = args_list[0]
        enc_k = args_list[1] 
        enc_v = args_list[2] 
        causal_mask = args_list[3] 
        padding_mask = args_list[4]
        
        # Causal Attention Block
        #################################################
        inp_start_causal_att_block = q
        x = self.MHA_CAUSAL_ATTN(q, q, q, causal_mask)
        x = x + inp_start_causal_att_block
        x = self.mha_causal_end_layernorm(x)

        # Cross Attention Block
        ###################################################
        if not self.decoderonly:
            inp_end_causal_att_block = x
            x = self.MHA_CROSS_ATTN(x, enc_k, enc_v, padding_mask)
            x = x + inp_end_causal_att_block
            x = self.mha_cross_end_layernorm(x)
        ###################################################

        inp_start_ff_block = x
        x = self.ff(x)
        x = x + inp_start_ff_block
        x = self.dec_blk_end_layernorm(x)
        return [x, enc_k, enc_v, causal_mask, padding_mask]

In [31]:
class Decoder(nn.Module):
    def __init__(self, num_layers, num_heads, vocab_size, embed_dim, 
                 k_dim, ctx_len, do, device):
        super().__init__()
        self.emb = Embed(vocab_size, embed_dim, ctx_len, do, device)
        self.layer_list = [Decoder_Block(num_heads, embed_dim, k_dim, do, device) for i in range(num_layers)]
        self.layers = nn.Sequential(*self.layer_list)


    def forward(self, input_ids, attention_mask, enc_attention_mask, enc_k, enc_v):
        x = self.emb(input_ids)
        q = x
        dim = [x.shape[0], attention_mask.shape[1], enc_attention_mask.shape[1]]
        causal_mask = att_mask(attention_mask, lookahead=True, cross_att=False)
        padding_mask = att_mask(enc_attention_mask, lookahead=False, cross_att=True, x=dim)
        x = self.layers([q, enc_k, enc_v, causal_mask, padding_mask])
        return x[0]

In [32]:
inp = torch.randint(1,100, (3,6))
am = torch.ones(inp.shape)
inp.shape, am.shape

(torch.Size([3, 6]), torch.Size([3, 6]))

In [33]:
dec = Decoder(3, 6, 100, 768, 128, 100, 0.1, device).to(device)
dec

Decoder(
  (emb): Embed(
    (tok_layer): Embedding(100, 768)
    (pos_layer): PositionalEncoding(
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (norm_do): Sequential(
      (0): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (1): Dropout(p=0.1, inplace=False)
    )
  )
  (layers): Sequential(
    (0): Decoder_Block(
      (MHA_CAUSAL_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (MHA_CROSS_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_cross_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (1): Decoder_Block(
      (MHA_CAUSAL_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (MHA_CROSS_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_cross_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (2): Decoder_Block(
      (MHA_CAUSAL_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (MHA_CROSS_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_cross_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
  )
)

In [34]:
inp_e = torch.randint(1,100, (3,7))
am_e = torch.ones(inp_e.shape)
inp_e.shape, am_e.shape, inp_e

(torch.Size([3, 7]),
 torch.Size([3, 7]),
 tensor([[84, 21, 23, 41, 87, 22, 89],
         [28, 60,  8, 19, 95, 18, 16],
         [97, 37, 21, 80, 85, 92, 26]]))

In [35]:
out_e = enc(inp_e.to(device), am_e.to(device))
out_e, out_e.shape

(tensor([[[-1.1520,  0.2251,  0.5948,  ...,  0.4930,  0.7644,  0.3571],
          [ 0.7496, -0.9165,  1.1198,  ...,  1.5222, -0.8834, -0.6800],
          [ 0.5627, -1.3676,  0.5731,  ..., -1.3979,  0.5178, -0.3652],
          ...,
          [-1.1889, -1.6088,  1.2920,  ...,  1.4004, -0.5312,  1.9008],
          [-0.9177, -0.5240, -0.2517,  ..., -0.3394, -0.4634,  1.1644],
          [-1.7263, -0.6355,  0.0976,  ...,  0.4594,  0.2327,  0.0158]],

         [[-1.0290,  0.2047,  0.1248,  ...,  1.7964,  0.2256, -0.4307],
          [-0.2000,  0.8311, -0.5451,  ..., -0.2154, -0.7678, -0.0457],
          [ 1.6650, -1.5256, -0.6958,  ...,  0.5390, -1.2662, -0.2836],
          ...,
          [-1.0518, -0.0831, -0.4581,  ...,  1.4901, -0.4471,  1.1940],
          [-1.8780, -0.3381, -2.4201,  ...,  0.4150, -1.5673,  0.8025],
          [-0.7691, -0.6502,  0.3222,  ...,  1.1360, -0.1747, -0.3013]],

         [[-0.1468,  0.6034, -0.6218,  ..., -0.9832, -0.5701,  1.5235],
          [-0.7410,  0.0383, -0.0392,  ..., -0.7026, -1.1800, -0.1315],
          [ 0.6290, -1.0875,  0.4387,  ...,  1.3222, -0.2898, -0.7210],
          ...,
          [-0.3445, -0.1093, -2.0073,  ..., -1.7991, -0.8440,  1.0624],
          [-2.4483, -0.2717, -1.0804,  ...,  0.0815, -0.2784,  0.5063],
          [-0.0286, -0.0549,  0.1644,  ...,  0.0423,  0.2902,  0.2034]]],
        device='cuda:0', grad_fn=<NativeLayerNormBackward0>),
 torch.Size([3, 7, 768]))

In [36]:
out = dec(inp.to(device), am.to(device), am_e.to(device), out_e, out_e)
out.shape

torch.Size([3, 6, 768])

In [37]:
class Bro_Transformer(nn.Module):

    def __init__(self, num_layers, embed_dim, num_heads,
                 input_vocab_size, target_vocab_size, enc_ctx_len,
                 dec_ctx_len, device, do=0.1):
        super().__init__()
        k_dim = int(embed_dim/num_heads)

        self.encoder = Encoder(num_layers, num_heads, input_vocab_size, embed_dim, k_dim, enc_ctx_len, do, device)
        self.decoder = Decoder(num_layers, num_heads, target_vocab_size, embed_dim, k_dim, dec_ctx_len, do, device)
        self.final_layer = nn.Linear(embed_dim, target_vocab_size)

    def forward(self, enc_input_ids, dec_input_ids, enc_attention_mask, dec_attention_mask):

        enc_output = self.encoder(enc_input_ids, enc_attention_mask)
        dec_output = self.decoder(dec_input_ids, dec_attention_mask,
                                  enc_attention_mask, enc_output, enc_output)
        final_output = self.final_layer(dec_output)
        return final_output

In [38]:
inp_e = torch.randint(1,100, (2,6))
am_e = torch.ones(inp_e.shape)
inp_e.shape, am_e.shape

(torch.Size([2, 6]), torch.Size([2, 6]))

In [39]:
inp_d = torch.randint(1,100, (2,8))
am_d = torch.ones(inp_d.shape)
inp_d.shape, am_d.shape

(torch.Size([2, 8]), torch.Size([2, 8]))

In [40]:
bro_transformer = Bro_Transformer(3, 768, 6, 150, 160, 128, 128, device, 0.1).to(device)

In [41]:
bro_transformer

Bro_Transformer(
  (encoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(150, 768)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (decoder): Decoder(
    (emb): Embed(
      (tok_layer): Embedding(160, 768)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (1): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (2): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (final_layer): Linear(in_features=768, out_features=160, bias=True)
)

In [42]:
out = bro_transformer(inp_e.to(device), inp_d.to(device), am_e.to(device), am_d.to(device))

In [43]:
out.shape

torch.Size([2, 8, 160])

In [44]:
summary(bro_transformer)

===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
Bro_Transformer                                    --
├─Encoder: 1-1                                     --
│    └─Embed: 2-1                                  --
│    │    └─Embedding: 3-1                         115,200
│    │    └─PositionalEncoding: 3-2                --
│    │    └─Sequential: 3-3                        1,536
│    └─Sequential: 2-2                             --
│    │    └─Encoder_Block: 3-4                     7,087,872
│    │    └─Encoder_Block: 3-5                     7,087,872
│    │    └─Encoder_Block: 3-6                     7,087,872
├─Decoder: 1-2                                     --
│    └─Embed: 2-3                                  --
│    │    └─Embedding: 3-7                         122,880
│    │    └─PositionalEncoding: 3-8                --
│    │    └─Sequential: 3-9                        1,536
│    └─Sequential: 2-4                             --
│    │    └─Decoder_Block: 3-10                    9,451,776
│    │    └─Decoder_Block: 3-11                    9,451,776
│    │    └─Decoder_Block: 3-12                    9,451,776
├─Linear: 1-3                                      123,040
===========================================================================
Total params: 49,983,136
Trainable params: 49,983,136
Non-trainable params: 0
===========================================================================

In [45]:
class BroGPT(nn.Module):
    def __init__(self, num_layers, num_heads, vocab_size,
                 embed_dim, ctx_len, do, device):
        super().__init__()
        k_dim = int(embed_dim/num_heads)
        self.emb = Embed(vocab_size, embed_dim, ctx_len, do, device)
        self.layer_list = [Decoder_Block(num_heads, embed_dim, k_dim, do, device, True) for i in range(num_layers)]
        self.layers = nn.Sequential(*self.layer_list)
        self.embed_vocab = nn.Linear(embed_dim, vocab_size)

    def forward(self, input_ids, attention_mask): # , enc_k=None, enc_v=None):
        x = self.emb(input_ids)
        causal_mask = att_mask(attention_mask, lookahead=True, cross_att=False)
        padding_mask = att_mask(attention_mask, lookahead=False, cross_att=False)
        #Let us fuse the two together. This is because causal should not be paying attention when there is a padding
        causal_mask = causal_mask + padding_mask
        padding_mask = None
        x = self.layers([x, x, x, causal_mask, padding_mask])
        x = self.embed_vocab(x[0])
        return x

In [46]:
brogpt = BroGPT(num_layers=4, num_heads=6, vocab_size=11000, embed_dim=768,
                ctx_len=512, do=0.1, device=device).to(device)

In [47]:
brogpt

BroGPT(
  (emb): Embed(
    (tok_layer): Embedding(11000, 768)
    (pos_layer): PositionalEncoding(
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (norm_do): Sequential(
      (0): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (1): Dropout(p=0.1, inplace=False)
    )
  )
  (layers): Sequential(
    (0): Decoder_Block(
      (MHA_CAUSAL_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (1): Decoder_Block(
      (MHA_CAUSAL_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (2): Decoder_Block(
      (MHA_CAUSAL_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (3): Decoder_Block(
      (MHA_CAUSAL_ATTN): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_causal_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (dec_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
  )
  (embed_vocab): Linear(in_features=768, out_features=11000, bias=True)
)

In [48]:
inp_d = torch.randint(1,100, (4,9))
am_d = torch.ones(inp_d.shape)
inp_d.shape, am_d.shape

(torch.Size([4, 9]), torch.Size([4, 9]))

In [49]:
am_d[2]

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
am_d[2] = torch.tensor([1]*6 + [0]*3)
am_d[2], am_d[2].shape

(tensor([1., 1., 1., 1., 1., 1., 0., 0., 0.]), torch.Size([9]))

In [51]:
am_d[3] = torch.tensor([1]*7 + [0]*2)
am_d[3], am_d[3].shape

(tensor([1., 1., 1., 1., 1., 1., 1., 0., 0.]), torch.Size([9]))

In [52]:
am_d

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0.]])

In [53]:
out = brogpt(inp_d.to(device), am_d.to(device))
out.shape

torch.Size([4, 9, 11000])

In [54]:
!pip install transformers datasets sentencepiece sacremoses

Requirement already satisfied: transformers in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (4.49.0)
Requirement already satisfied: datasets in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (3.4.0)
Requirement already satisfied: sentencepiece in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (0.2.0)
Requirement already satisfied: sacremoses in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (0.1.1)
Requirement already satisfied: filelock in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (0.29.3)
Requirement already satisfied: numpy>=1.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (21.3)
Requirement already satisfied: pyyaml>=5.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (19.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (2.2.3)
Requirement already satisfied: xxhash in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.12.0)
Requirement already satisfied: aiohttp in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets) (3.11.13)
Requirement already satisfied: click in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sacremoses) (8.1.8)
Requirement already satisfied: joblib in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sacremoses) (1.4.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.12.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from packaging>=20.0->transformers) (3.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [55]:
from transformers import AutoTokenizer

In [56]:
ckpt = 'gpt2'
tokenizer = AutoTokenizer.from_pretrained(ckpt)
tokenizer

GPT2TokenizerFast(name_or_path='gpt2', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [57]:
%pwd

'/home/ec2-user/SageMaker/MT/brotransformer'

In [58]:
!wget https://gattonweb.uky.edu/faculty/lium/gai/en2fr.zip

--2025-03-15 15:15:39--  https://gattonweb.uky.edu/faculty/lium/gai/en2fr.zip
Resolving gattonweb.uky.edu (gattonweb.uky.edu)... 128.163.2.96
connected. to gattonweb.uky.edu (gattonweb.uky.edu)|128.163.2.96|:443...
HTTP request sent, awaiting response... 200 OK
Length: 1793553 (1.7M) [application/x-zip-compressed]
Saving to: ‘en2fr.zip.2’

100%[======================================>] 1,793,553   2.10MB/s   in 0.8s

2025-03-15 15:15:41 (2.10 MB/s) - ‘en2fr.zip.2’ saved [1793553/1793553]

In [59]:
#!unzip en2fr.zip

In [60]:
#!mkdir files
#!mv en2fr.csv ./files/

In [61]:
import pandas as pd

df=pd.read_csv("files/en2fr.csv")
num_examples=len(df)
print(f"there are {num_examples} examples in the training data")
print(df.iloc[30856]["en"])
print(df.iloc[30856]["fr"])

there are 47173 examples in the training data
How are you?
Comment êtes-vous?

In [62]:
tokenized_en=tokenizer.tokenize("I don't speak French.")
print(tokenized_en)
tokenized_fr=tokenizer.tokenize("Je ne parle pas français.")
print(tokenized_fr)
print(tokenizer.tokenize("How are you?"))
print(tokenizer.tokenize("Comment êtes-vous?"))

['I', 'Ġdon', "'t", 'Ġspeak', 'ĠFrench', '.']
['Je', 'Ġne', 'Ġpar', 'le', 'Ġpas', 'Ġfr', 'an', 'Ã§', 'ais', '.']
['How', 'Ġare', 'Ġyou', '?']
['Comment', 'ĠÃ', 'ª', 'tes', '-', 'vous', '?']

In [63]:
tokenizer.get_vocab()

{'Ġdanger': 3514,
 'Ġmentor': 22387,
 'ĠFil': 7066,
 'Ġkilling': 5170,
 'Ġmigrate': 32492,
 'Ãĥ': 5746,
 'ĠAzerbai': 29830,
 'Ġomega': 37615,
 'bringer': 48046,
 'zon': 26361,
 'Ġdefend': 4404,
 'Ġcourtesy': 12537,
 'Adams': 47462,
 'Ġskeletons': 25612,
 'eding': 8228,
 'index': 9630,
 'Ġbegs': 38609,
 'Ġenh': 5881,
 'ĠKiw': 40011,
 'Ġmixer': 33938,
 'Ġenemies': 5775,
 'Ġrescind': 39091,
 'Ġatoms': 23235,
 'Ġsounds': 5238,
 'urn': 700,
 'Ġdelicate': 19217,
 'Ġidiots': 35838,
 'ove': 659,
 'Lewis': 40330,
 'itional': 1859,
 'would': 19188,
 'ĠBeaut': 13711,
 'ĠBefore': 7413,
 'repair': 49932,
 'ĠCSI': 49911,
 'ĠRemote': 21520,
 'ĠWeld': 45156,
 'ĠTraps': 44110,
 'Ġcalmed': 49566,
 'icycle': 35298,
 'Ġlever': 17124,
 'amba': 31842,
 'Ġempty': 6565,
 'want': 42949,
 'Ġdomestically': 42127,
 'ĠHUN': 41041,
 'ĠCompet': 38558,
 'CON': 10943,
 '1990': 19891,
 'ãĤ¨ãĥ«': 46948,
 'Ġlightsaber': 45282,
 'achusetts': 9770,
 'Ġparts': 3354,
 'layout': 39786,
 'Ġsourcing': 47015,
 'Ġoutlines': 27430,
 'Ġswitches': 18225,
 'adem': 36920,
 'checking': 41004,
 'Ġtent': 11105,
 'Ġtravelers': 23325,
 'Ġissuance': 30145,
 '¶æ': 35050,
 'ĠEAR': 31834,
 'icating': 12364,
 'Ġobstacle': 22007,
 'ĠZhang': 19439,
 'Ġfirms': 9611,
 'Ġpinned': 25711,
 'Ġreviewed': 11765,
 'ĠRU': 46432,
 '704': 32869,
 'ĠFaces': 48463,
 'forming': 15464,
 'Ġchalk': 30860,
 'ĠAuburn': 24579,
 'Journal': 25296,
 'alysis': 8767,
 'ottenham': 21889,
 'sql': 25410,
 'ĠReef': 34151,
 'Ġbible': 41169,
 'Ġneeded': 2622,
 'arthy': 18270,
 'Ale': 37474,
 'ĠFukushima': 34170,
 'Ġpicks': 11103,
 'ĠGrav': 32599,
 'ĠGuests': 46936,
 'ĠHP': 6574,
 'ophone': 38656,
 'Ġprized': 37768,
 'ars': 945,
 'Ġ351': 44417,
 'Ġmeal': 9799,
 'Ġrenewal': 22901,
 'Ġtam': 21885,
 'igate': 10055,
 'ĠChristy': 50058,
 'Ġlions': 31420,
 'Ġexpressly': 27462,
 'Ġindependently': 14799,
 'ĠCong': 2908,
 'ĠKorean': 6983,
 'bish': 31795,
 'timeout': 48678,
 'Ġbrew': 9059,
 'Ġbundled': 34358,
 'Ġsurfing': 36254,
 'basic': 35487,
 'Ġstaging': 29475,
 'ved': 1079,
 'spection': 31308,
 'ils': 4487,
 'ĠCaliforn': 37704,
 'ĠDil': 29328,
 'ĠSebast': 22787,
 'ĠAD': 5984,
 'Ġtorment': 33378,
 'Princ': 42904,
 'Ġneuroscience': 39738,
 'Ġmac': 8352,
 'Ġnationalists': 32442,
 'who': 8727,
 'Event': 9237,
 'ĠBorg': 29004,
 'ĠOEM': 29671,
 'Ġproviding': 4955,
 'Ġdeleg': 8570,
 'Ġcompleted': 5668,
 'entary': 48648,
 'Ġadvisory': 20852,
 'ĠScience': 5800,
 'Ġaffiliation': 26218,
 'edit': 19312,
 'ĠCaucasus': 47990,
 'LEY': 25173,
 'Ġrevisit': 32302,
 'Ġstating': 12316,
 'Ġthee': 17903,
 'Ġtreasure': 14068,
 'Ġuncertainty': 13479,
 'Ġawareness': 9359,
 'ĠSaiyan': 33725,
 'ĠGarrett': 27540,
 'Ġemulation': 47065,
 'Ġwage': 7699,
 'IND': 12115,
 'Ġnotices': 19748,
 'Ġtuber': 35813,
 'ondon': 3391,
 'run': 5143,
 'ĠNathan': 18106,
 'Ġcriteria': 9987,
 'usher': 34055,
 'Ġquasi': 32551,
 'ĠSpecifications': 46271,
 'ĠPROC': 41755,
 'ĠDesigner': 31716,
 'ĠTrigger': 24593,
 'ĠVerb': 49973,
 'Ġdegraded': 41604,
 'multiple': 48101,
 'Ġfalls': 8953,
 'Ġclinical': 8668,
 'ĠNASCAR': 30774,
 'ĠArgentina': 16519,
 'Ġdevelopmental': 23456,
 'arent': 1580,
 'Similarly': 28039,
 'Originally': 22731,
 'okane': 41776,
 'Kenn': 39324,
 'Ġinequ': 11082,
 'Ġjazz': 21274,
 'Ġgeneric': 14276,
 'Ġinvoked': 24399,
 'ĠAires': 44692,
 'Ġanguish': 41210,
 'ĠMog': 30926,
 'Ġnuns': 45805,
 'Ġoperative': 28609,
 'ĠVoices': 40440,
 'Ġseemed': 3947,
 'Ġglyphosate': 38329,
 'Ġwished': 16555,
 'anca': 42124,
 'Ġtorture': 11543,
 'Ġgelatin': 49084,
 'Ġ-------': 35656,
 'L': 43,
 'ermanent': 30312,
 'ĠBauer': 41971,
 'ĠFramework': 25161,
 'Ble': 43413,
 'Ġdeadline': 12508,
 'Ġremed': 20100,
 'claimer': 17111,
 'Ġendorse': 11438,
 'unci': 49652,
 'Ġbosses': 17317,
 'Ġadmiration': 28506,
 'issors': 32555,
 'sec': 2363,
 'ĠEthereum': 20313,
 'Ġprevail': 28615,
 'Ġshit': 7510,
 'Ġultraviolet': 49961,
 'Ġanticipating': 40807,
 '630': 30005,
 'ĠLegions': 48534,
 'idates': 37051,
 'Ġlinguistic': 29929,
 'ĠEvidence': 21259,
 'ĠIndex': 12901,
 'Ġcal': 2386,
 'Ġcracked': 21368,
 'ĠAppears': 31254,
 'Ġillusion': 17878,
 'Ġfandom': 35387,
 'bone': 15992,
 'Ġmelody': 32859,
 'ĠFrances': 27025,
 'Ġmystical': 29746,
 'typically': 48126,
 'conservancy': 41215,
 'ĠDiaz': 26899,
 'ĠQuarterly': 36082,
 'Ġgenerating': 15453,
 'Ġvibr': 12611,
 '");': 15341,
 'atsuki': 40063,
 'HD': 10227,
 'het': 3202,
 'Entity': 32398,
 'ĠCasting': 39285,
 'ĠPOLIT': 32082,
 'Ġbub': 10015,
 'Ġexpressing': 16621,
 '87': 5774,
 'ĠDrake': 18515,
 'ĠGuide': 10005,
 'then': 8524,
 'ĠSI': 25861,
 'ĠReborn': 37612,
 'ĠAmir': 43931,
 'require': 46115,
 'ĠFey': 39775,
 'Ġbear': 6842,
 'Ġleve': 34002,
 'ĠGMO': 35945,
 'Ġling': 18459,
 'Ġconfir': 4322,
 'Ġnotoriously': 29862,
 'ĠFound': 4062,
 'Ġembry': 20748,
 'ĠWizards': 21092,
 'Ġshift': 6482,
 '160': 14198,
 'IRE': 41736,
 '-+': 19529,
 'Ę': 212,
 'earing': 6648,
 'mob': 39949,
 'æĺ': 23626,
 'Tem': 12966,
 'EO': 4720,
 'lect': 801,
 'Henry': 32476,
 'Allah': 48620,
 'supported': 15999,
 'ĠArtificial': 35941,
 "['": 17816,
 'ĠEdge': 13113,
 'ĠVall': 46929,
 'Ġ[|': 49074,
 'Ġclot': 5148,
 'Ġfederally': 33710,
 'Ġspun': 26843,
 'Ġcivilisation': 45605,
 '451': 36330,
 'ament': 3263,
 'Ġbeh': 1372,
 'UI': 10080,
 'DNA': 28886,
 'km': 13276,
 'ĠLEVEL': 49277,
 'ĠLunch': 40514,
 'Ġmouth': 5422,
 'ussia': 31269,
 'Ġresolved': 12939,
 'ĠFall': 7218,
 'amsung': 30136,
 'fashion': 25265,
 'Ġlearners': 46184,
 'istered': 23187,
 'Ġshooting': 4395,
 'idas': 24496,
 'Ġspect': 5444,
 'ouncing': 18155,
 'ilet': 41550,
 'Ġroutine': 8027,
 'val': 2100,
 'ĠScythe': 45227,
 'French': 24111,
 'abase': 5754,
 'zech': 15356,
 'ãĥĺãĥ©': 34473,
 'ĠFirm': 31623,
 'Ġwaiter': 46612,
 'ĠGuidelines': 31072,
 'Ġsignific': 2216,
 'adel': 6959,
 'ĠBren': 20465,
 'wayne': 43932,
 'Ġaccidental': 23221,
 'ĠBean': 26510,
 'ĠCo': 1766,
 'Ġglimps': 41226,
 'ĠSOM': 42121,
 'Ġdistract': 11786,
 'ĠPepper': 24346,
 'Ġfame': 16117,
 'Ġropes': 31001,
 'Ġsooner': 14556,
 'rared': 25122,
 'Ġpackets': 24624,
 'Ġsuccession': 22435,
 'ĠHamilton': 11582,
 'Ġtips': 9040,
 'ĠRoche': 47765,
 'Ġgift': 6979,
 'Ġevolve': 18101,
 'ĠVaults': 21314,
 'Ġcrushing': 24949,
 'Ġalbeit': 18244,
 'Ġcomplicit': 42927,
 'Ġallotted': 44554,
 'Ġindis': 49919,
 'secondary': 38238,
 'Ġopt': 2172,
 'Ġreapp': 24578,
 'Ġãģ': 23294,
 'Ġmeant': 4001,
 'Ġparting': 44823,
 'euro': 44252,
 'ĠTTC': 42662,
 'Ġburdens': 27127,
 'asted': 8992,
 'Ġbye': 33847,
 'Ġconvergence': 40826,
 'Oil': 44142,
 'Ġmars': 48962,
 'Ġsurplus': 18201,
 'Ġbelonging': 16686,
 'FINEST': 40236,
 'ĠAcer': 49606,
 'integ': 18908,
 'Ġboss': 6478,
 'Ġmighty': 18680,
 'Ġpsycho': 30731,
 'Process': 18709,
 'Ġ1500': 20007,
 'è': 164,
 'bub': 46176,
 'vier': 49663,
 'St': 1273,
 'velop': 1091,
 'Ġunwillingness': 47836,
 'ĠPeriod': 18581,
 'Ġbull': 6473,
 'Ġ529': 49888,
 'profits': 31504,
 'ĠPatel': 33110,
 'ĠRamsay': 47959,
 'Ġmisunderstanding': 29789,
 'ĠNeighbor': 28708,
 'Ġassessing': 24171,
 'Ġraise': 5298,
 'ĠRobo': 39702,
 'Ġfixtures': 34609,
 'ĠCary': 47474,
 'Ġrejo': 30668,
 'leasing': 48764,
 'Ġdupl': 14184,
 'Ġgraphs': 28770,
 'ĠShiny': 39657,
 'Ġorphans': 50213,
 'Ġtricks': 15910,
 'Ġnood': 25099,
 'apo': 41817,
 'ott': 1252,
 'ilon': 33576,
 'ĠBahÃ¡': 38218,
 'ĠRacing': 14954,
 'Read': 5569,
 'ĠBabel': 50175,
 'ĠIsaiah': 29756,
 'OVA': 41576,
 'Ġanchor': 18021,
 'Ġinvent': 8067,
 'Ġtidy': 43044,
 '1999': 18946,
 '238': 23721,
 'ahoo': 12992,
 'ĠDogs': 21367,
 'ĠNormally': 29282,
 'ĠRSA': 42319,
 'Mid': 22622,
 'plays': 26024,
 'ĠJolly': 40276,
 'ĠYourself': 42132,
 'Ġcensor': 42081,
 'Ġemphasized': 20047,
 'Ġforest': 8222,
 'ĠPredator': 38871,
 'Ġperish': 42531,
 'Ġpulp': 38341,
 'ĠWinning': 40983,
 'Ġdog': 3290,
 'ĠSTATES': 47023,
 'Ġslides': 19392,
 'ingham': 25875,
 'AK': 10206,
 'andan': 42509,
 'sent': 34086,
 'aintain': 32725,
 'olin': 24910,
 'standard': 20307,
 'vag': 29821,
 '!).': 19588,
 'ĠAncest': 31200,
 'artisan': 19714,
 'Ġassigned': 8686,
 'Ġcream': 8566,
 'tags': 31499,
 'LOD': 38543,
 'ĠObamacare': 12439,
 'ĠCounsel': 21023,
 'ĠMediterranean': 19517,
 'Ġembodiment': 23168,
 'Ġreconc': 19331,
 'Ġrecover': 8551,
 'Ġarrest': 3251,
 'aughed': 13726,
 'icultural': 26823,
 'ĠLCS': 38217,
 'Ā': 188,
 'bda': 43444,
 'Ġbranch': 8478,
 'ancock': 37077,
 'idium': 43523,
 'Ġchase': 15505,
 'ĠSage': 28733,
 'Ġdisciplines': 29861,
 'Ġmoments': 7188,
 'Ġscholarship': 18652,
 'uses': 2664,
 'Ġstumbling': 37829,
 'ĠAlvarez': 36952,
 'Ġwillingly': 30981,
 'Ġproves': 17021,
 'availability': 47274,
 'iola': 30292,
 'Ġdepletion': 42435,
 'fu': 20942,
 'Ġstarved': 47224,
 'acts': 8656,
 'ĠFiorina': 49028,
 'Ġredirected': 45158,
 'Ġwolves': 23214,
 'Ġeyel': 29708,
 'RAFT': 44700,
 'agn': 4660,
 'ealing': 26919,
 'iflower': 42642,
 'tw': 4246,
 'ĠAtmosp': 33276,
 'Ġseventy': 31989,
 'Ġtearing': 24447,
 'Ġvortex': 42726,
 'ĠOwner': 23853,
 'ĠArmenian': 29388,
 'vich': 49547,
 'ĠNora': 32561,
 'ĠDi': 6031,
 'ĠTransportation': 15198,
 'Ġcompelling': 13206,
 'Written': 25354,
 'ĠMondays': 49748,
 'ĠGandhi': 22081,
 'ĠGuatemala': 32183,
 'ĠEc': 14003,
 'ĠSpanish': 7897,
 'Ġdirectories': 29196,
 'ĠMinute': 38573,
 'ĠBarry': 14488,
 'Ġfeasible': 23498,
 'Ġprevents': 15174,
 'ĠRFC': 30978,
 'ĠGuant': 27772,
 'Ġprimed': 46959,
 'advert': 17904,
 'gly': 10853,
 'psy': 13764,
 'ĠInside': 14384,
 'Ġbetrayal': 29355,
 'Ġring': 5858,
 '787': 41019,
 'Ġmats': 46054,
 'ĠPatron': 43315,
 'Ġmentioning': 20862,
 'ĠVintage': 34057,
 'Ġmyths': 22886,
 'Ġpharmac': 25702,
 'Ġsleek': 33143,
 'lems': 46367,
 'Ġviral': 14416,
 'isure': 20609,
 'Ġstrictly': 14084,
 '":': 1298,
 'ĠNikki': 34108,
 'ĠRest': 8324,
 'ĠShel': 15325,
 'oine': 42722,
 'Ġshowc': 21876,
 'ements': 3196,
 'ĠMumbai': 22917,
 'Se': 4653,
 'Ġjihadists': 31395,
 'angled': 22393,
 'ĠEarly': 12556,
 'uting': 15129,
 'ĠWrap': 41028,
 'Ġdominated': 13354,
 'Ġlanding': 9581,
 'Credits': 42855,
 'ĠMecca': 35247,
 'ĠIndependent': 13362,
 'ĠNeedless': 39114,
 'ĠDroid': 46546,
 'Detailed': 32080,
 'kun': 28374,
 'Ġ503': 44541,
 'Berry': 25215,
 'Danny': 45478,
 'ĠPrincess': 8449,
 'ĠVine': 28879,
 'Ġinterior': 11087,
 'Ġlauncher': 24008,
 'Ġstrives': 37873,
 'Ġâĸł': 34252,
 'alli': 36546,
 'WT': 39386,
 'ĠRedmond': 49420,
 'Brien': 20118,
 'ĠHaw': 6091,
 'iege': 14566,
 'ortion': 5817,
 'Ġoutspoken': 27687,
 'Ġabstinence': 40683,
 'Ġclue': 18437,
 'Token': 30642,
 'Ġaren': 3588,
 '544': 47576,
 'thal': 11669,
 'ĠRhythm': 45757,
 'ĠGrizzlies': 40669,
 'adelphia': 8273,
 'icularly': 22585,
 'ishes': 5614,
 'ĠattRot': 35207,
 'Ġ1955': 25325,
 'Ġcommanded': 22419,
 'Ġimplicitly': 31821,
 'Ġmunitions': 39586,
 'Ġwastes': 43739,
 'Ġknocking': 21500,
 'bit': 2545,
 'ĠFell': 21710,
 'wrap': 37150,
 'ĠSent': 11352,
 'gender': 8388,
 '003': 11245,
 'Ġnegativity': 45074,
 'Ġdepressing': 31193,
 'Ġvide': 18784,
 'stories': 50164,
 'adia': 29523,
 'ĠBrendan': 26134,
 'Ġcaveat': 36531,
 'eh': 17231,
 'Ġ(âĪĴ': 35508,
 'olicy': 21424,
 'Ġseismic': 37463,
 'ewitness': 28588,
 'anz': 35410,
 'ĠKut': 40323,
 'Ġfruitful': 44474,
 'Parameters': 48944,
 'ĠAssistant': 15286,
 'ĠFBI': 5349,
 'CAP': 33177,
 'ĠAdministrator': 22998,
 'Ġmilestone': 23554,
 'Ġshove': 38332,
 'Ġsummer': 3931,
 'ĠLocked': 48613,
 'Ġetiquette': 49455,
 'scene': 29734,
 'Ġpointless': 27158,
 'Ġwells': 22571,
 'Cre': 12443,
 'Ap': 25189,
 'enos': 28380,
 'Ġms': 13845,
 'Ġdelightful': 32327,
 'ibe': 32438,
 'ĠIsabel': 41838,
 'boys': 13202,
 'Ġdrink': 4144,
 'Ġdate': 3128,
 'utherford': 46923,
 'games': 19966,
 'Ġfurthermore': 50002,
 'Ġgrotesque': 40505,
 'ĠStealth': 23293,
 'Ġinsecure': 31955,
 'Ġprogressed': 28775,
 'asure': 5015,
 'Ġ512': 22243,
 'Ġmathematician': 48251,
 'emis': 30561,
 'Ġmalls': 43890,
 'gl': 4743,
 'ĠNeigh': 22505,
 'Ġshy': 15800,
 'ĠSingh': 14403,
 'Ġexplanation': 7468,
 'Ġbandwidth': 19484,
 'Ġstimulated': 40216,
 'Ġunrem': 49733,
 'Num': 33111,
 'Ġbreaker': 46408,
 'ĠRPGs': 46697,
 'Ġcog': 43072,
 'oha': 28083,
 'ĠSense': 24956,
 'uda': 15339,
 'Ġbow': 9563,
 'Ġartifacts': 20316,
 'Ġconsistency': 15794,
 'Overview': 29064,
 'Ġexhausting': 39663,
 'Ġconcurrently': 47480,
 'Ġstudent': 3710,
 'Ġagendas': 37611,
 'Ġelectrom': 26629,
 'case': 7442,
 'ĠPiet': 36548,
 'ĠFrequ': 22192,
 'SU': 12564,
 'una': 9613,
 'Experience': 44901,
 'Ġbullshit': 20041,
 'Ġclimb': 12080,
 'Ġdil': 11844,
 'ĠGoddard': 47386,
 'Ġbarrels': 17907,
 'Ġredeem': 26509,
 'Ġresponses': 9109,
 'Ġinco': 44237,
 'etime': 8079,
 'ĠMoon': 6869,
 'Ġoptimal': 16586,
 'Ġlot': 1256,
 'ĠSocialism': 40407,
 'Ġmalware': 18953,
 'ĠO': 440,
 'ĠKnow': 9365,
 'gallery': 24460,
 '21': 2481,
 'Ġmaximal': 40708,
 'Ġtyrann': 44315,
 'puting': 48074,
 'ĠERA': 18802,
 'ĠLIA': 43031,
 '127': 16799,
 'gart': 41651,
 'ĠDer': 9626,
 'ensional': 37176,
 'Ġinflation': 10610,
 'XXXX': 24376,
 'bach': 19496,
 'existing': 25687,
 'organisms': 45165,
 'Ġknowingly': 26526,
 'Usually': 37887,
 'Ġdisbel': 23935,
 'Ġdeliber': 8958,
 'Ġmash': 30407,
 'fell': 23299,
 'ĠUtilities': 41086,
 'ĠBrian': 8403,
 '________________________': 32941,
 'ĠProp': 8772,
 'ĠDial': 21269,
 'esting': 37761,
 'Ġamen': 29448,
 'Ġammon': 34946,
 'Ġcautioned': 34105,
 'Ġtwitter': 17044,
 'Ġmediation': 41077,
 'oler': 13625,
 'bett': 48138,
 'bid': 14065,
 'bsite': 12485,
 'ĠBASE': 49688,
 'Ġgreen': 4077,
 'Ġaud': 2709,
 'ĠACC': 15859,
 'Ġstate': 1181,
 'EEEE': 35039,
 'Ġtremend': 11039,
 'Ġironically': 32532,
 'Ġwa': 2082,
 'Ġdisappointing': 17185,
 'Ġinsisted': 11189,
 'ĠUz': 40919,
 'ALK': 28082,
 'ĠFore': 4558,
 'ĠHeaven': 11225,
 'Ġswayed': 47632,
 'Ġconsists': 10874,
 'Ban': 30457,
 'Ġslight': 3731,
 'Ġser': 1055,
 'earable': 40816,
 'none': 23108,
 'ĠBT': 22205,
 'ĠEnc': 14711,
 'ĠPutin': 8144,
 'ĠSolomon': 22912,
 'Ġauditory': 38949,
 'Ġbulletin': 40813,
 'umbo': 29309,
 'ĠCry': 8152,
 'ĠMellon': 49808,
 'Method': 17410,
 'ĠEighth': 41040,
 'Pain': 38490,
 'Ġloan': 8063,
 'Ġreinforcements': 38578,
 'Ġshocked': 11472,
 'Ġtraveling': 11300,
 'Ġpas': 38836,
 'ĠðŁĻĤ': 32485,
 'Ġ&&': 11405,
 'ĠHandbook': 30579,
 'Ġillustration': 20936,
 'Mer': 13102,
 'Ġ1995': 8735,
 'Ġrocked': 36872,
 'etsk': 29515,
 'ĠDefault': 15161,
 'º': 118,
 'ĠTerror': 14915,
 'Ġmaiden': 34827,
 'Ġrocking': 38059,
 'Ġdraft': 4538,
 'Ġhyp': 5328,
 'Ġneedy': 37278,
 'ĠRohing': 32571,
 'ĠWhere': 6350,
 'Ġsnipers': 50238,
 'Skip': 50232,
 'orry': 5152,
 'Mir': 27453,
 'ĠTacoma': 45132,
 'Ġuphold': 24963,
 'ighton': 42993,
 'vacc': 37839,
 'ĠVT': 32751,
 'Ġflags': 9701,
 'Ġthreads': 14390,
 'Ġinaccessible': 40604,
 'kar': 21070,
 'ĠDam': 5245,
 'Ġpanel': 6103,
 'icit': 3628,
 'arry': 6532,
 'ĠBlades': 34776,
 '478': 29059,
 'Ġfiltering': 25431,
 'Ġlawsuit': 8087,
 'heavy': 23701,
 'Ġfloated': 29742,
 'ĠAlcohol': 21051,
 'ĠMachines': 31182,
 'Ġresolutions': 21811,
 'Boston': 31710,
 'FE': 15112,
 'ylum': 11183,
 'Ġchewing': 36615,
 'custom': 23144,
 'ĠCunning': 30249,
 'operated': 42767,
 'DON': 41173,
 'Ġcompositions': 33543,
 'Ġsectarian': 28005,
 'em': 368,
 'uba': 22013,
 'Ġdunno': 50109,
 'ohyd': 15782,
 'Ġwitty': 45466,
 'ĠApache': 24843,
 'Ġkilometres': 23990,
 'Ġ43': 5946,
 'Ġartillery': 20381,
 'ĠFram': 15183,
 'gio': 27769,
 'ophers': 20856,
 'apan': 2674,
 'ĠAdvocate': 40209,
 'abortion': 32396,
 'itatively': 48668,
 'lor': 4685,
 'No': 2949,
 'respected': 48268,
 'street': 25662,
 'ĠSachs': 25158,
 'ĠLama': 36187,
 'Ġanywhere': 6609,
 'Ġempir': 18097,
 'CN': 44175,
 'Ġdescended': 23667,
 '234': 24409,
 'Far': 21428,
 'ĠSmoking': 39801,
 'Ġhelmets': 28359,
 'Ġlevy': 35783,
 'Ni': 34153,
 '191': 26492,
 'ULE': 24212,
 'Paul': 12041,
 'ĠRanking': 45407,
 'ĠHavana': 40274,
 'depend': 45841,
 'Ġrepeal': 14634,
 'ĠShields': 30512,
 '740': 45598,
 'ARDS': 48294,
 'che': 2395,
 'icum': 39901,
 'ometime': 47056,
 'Ġ234': 34323,
 'ĠMighty': 25532,
 ':#': 43922,
 'ĠTrad': 8397,
 'ĠWyn': 29758,
 'ittered': 36613,
 'emade': 21398,
 'Ġ670': 48136,
 'ĠAnaheim': 31100,
 'youtu': 32594,
 'ĠTerminal': 24523,
 'Ġbut': 475,
 'Ġdevelops': 21126,
 'ĠScheme': 32448,
 'Ġperipheral': 25514,
 'Ġpropaganda': 11613,
 'ĠHG': 48698,
 'Ġsticky': 23408,
 'agements': 38113,
 'express': 42712,
 'atched': 14265,
 'ĠFein': 45711,
 'actory': 9548,
 'Ġbearer': 49508,
 'Examples': 27730,
 'independence': 39894,
 'test': 9288,
 '-(': 30420,
 'ĠIA': 35229,
 'utical': 14224,
 'atted': 16898,
 'ĠWarsaw': 32955,
 'Ġcrack': 8469,
 'Ġes': 1658,
 'Ġrate': 2494,
 'ius': 3754,
 'Ġglob': 15095,
 'aunders': 32818,
 'Ġknife': 9845,
 'Ġmanipulate': 18510,
 'ĠOriginal': 13745,
 'Ġbullpen': 35093,
 'called': 7174,
 'help': 16794,
 'reon': 21833,
 'Mp': 28861,
 'Ġ(?,': 32843,
 'ĠPOST': 24582,
 'Ġcommittee': 5583,
 'Ġgrateful': 14066,
 'Ġmanufactured': 15943,
 'Northern': 40495,
 'ĠMyth': 18900,
 'wings': 48819,
 'Ġincidents': 10207,
 'disk': 39531,
 'igers': 34984,
 'Ġmetal': 6147,
 'idon': 47287,
 'Ġparticipating': 11983,
 'erous': 48411,
 'Ġlubric': 33211,
 'Ġplans': 3352,
 'Ġoldest': 13325,
 'Ġsupports': 6971,
 'Wow': 22017,
 'enabled': 25616,
 'Ġthrilling': 31610,
 'Ġwrote': 2630,
 'ĠPenny': 25965,
 'ãĥ¼ãĥ³': 31708,
 '182': 24294,
 'ĠProgram': 6118,
 'Ġdragon': 10441,
 'ĠPhD': 16394,
 'Ġreprinted': 44362,
 'Ġsoutheast': 26015,
 'ĠUNC': 39151,
 'Ġtechnicians': 33519,
 'ĠEvent': 8558,
 'Bron': 18760,
 'ierra': 16367,
 'Ġdorm': 18586,
 'robat': 40655,
 'Ġvelvet': 47750,
 'anguages': 33213,
 'ĠStand': 5751,
 'Ġmarketers': 41064,
 'ĠBas': 6455,
 'ĠTracks': 42259,
 'qi': 40603,
 '2014': 4967,
 'Ġdetailing': 22976,
 '/+': 28404,
 'Ġpublications': 16125,
 'kept': 45089,
 'robe': 25481,
 'Ġpledges': 31241,
 '10': 940,
 'Ġsellers': 23531,
 'ĠApart': 22596,
 'Ġretreat': 13703,
 'Ġcomplicate': 45058,
 'Ġbruised': 44379,
 '261': 30057,
 'Ġbanners': 31931,
 'ĠGonzalez': 24416,
 'ĠHuang': 31663,
 'Ġadmirable': 37959,
 'HS': 7998,
 'Ġmalt': 26868,
 'shock': 39563,
 'Ġauctions': 48043,
 'ĠDefinitions': 45205,
 'ĠGloria': 38109,
 'ĠClean': 5985,
 'ĠWatergate': 42128,
 'Ġcitation': 27860,
 'ĠKn': 6102,
 'KO': 22328,
 'ĠNot': 1892,
 'Ġinflu': 3057,
 'Ġintestinal': 32031,
 'How': 2437,
 'fet': 34045,
 'ä¸į': 38834,
 'ĠOK': 7477,
 'ĠSupporting': 44188,
 'ĠGlock': 45152,
 'LB': 30501,
 'quant': 40972,
 'ĠThanksgiving': 21494,
 'Ġdeem': 32435,
 'Ġlact': 26222,
 'Ġroster': 9354,
 'ke': 365,
 'ys': 893,
 'Ġpilgrims': 42408,
 '05': 2713,
 'Ġsleeve': 23179,
 'ĠUE': 27595,
 'Ġfrozen': 12912,
 'EEE': 31909,
 'Ġdrainage': 37664,
 'Ġdepressed': 19095,
 ...}

In [64]:
df

,Unnamed: 0,en,fr
0,0,"Two young, White males are outside near many b...",Deux jeunes mâles blancs se trouvent à l’extér...
1,0,Several men in hard hats are operating a giant...,Plusieurs hommes portant un chapeau d'assaut f...
2,0,A little girl climbing into a wooden playhouse.,Une petite fille grimpant dans une maison de j...
3,0,A man in a blue shirt is standing on a ladder ...,Un homme en chemise bleue se tient sur une éch...
4,0,Two men are at the stove preparing food.,Deux hommes sont à la cuisinière pour préparer...
...,...,...,...
47168,0,I'm walking with her.,Je marche avec elle.
47169,0,How are you doing today?,Comment allez-vous aujourd'hui?
47170,0,Today is a great day for hiking!,Aujourd'hui est une belle journée pour la rand...
47171,0,What a wonderful day for fishing!,Quelle merveilleuse journée pour la pêche!
47172,0,Look both ways before you cross the stree!,Regardez les deux côtés avant de traverser la ...

In [65]:
en_list = df['en'].tolist()

In [66]:
en_list[:5], len(en_list)

(['Two young, White males are outside near many bushes.',
  'Several men in hard hats are operating a giant pulley system.',
  'A little girl climbing into a wooden playhouse.',
  'A man in a blue shirt is standing on a ladder cleaning a window.',
  'Two men are at the stove preparing food.'],
 47173)

In [67]:
fr_list = df['fr'].tolist()

In [68]:
fr_list[:5], len(fr_list)

(['Deux jeunes mâles blancs se trouvent à l’extérieur près de nombreux buissons.',
  "Plusieurs hommes portant un chapeau d'assaut font fonctionner un système géant de poulies.",
  'Une petite fille grimpant dans une maison de jeux en bois.',
  'Un homme en chemise bleue se tient sur une échelle pour nettoyer une fenêtre.',
  'Deux hommes sont à la cuisinière pour préparer la nourriture.'],
 47173)

In [69]:
en_train_corpus = (en_list[i:i+1000] for i in range(0, len(en_list), 1000))

In [70]:
en_train_corpus

In [71]:
#len((next(en_train_corpus)))

In [72]:
fr_train_corpus = (fr_list[i:i+1000] for i in range(0, len(fr_list), 1000))

In [73]:
fr_train_corpus

In [74]:
#len(next(fr_train_corpus))

In [75]:
del tokenizer

In [76]:
orig_tokenizer = AutoTokenizer.from_pretrained(ckpt)
orig_tokenizer

GPT2TokenizerFast(name_or_path='gpt2', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [77]:
en_corp = ' '.join(en_list)
print(len(en_corp))
unique_en_word_toks = set(en_corp.split())
len(unique_en_word_toks)

2389158

21725

In [78]:
fr_corp = ' '.join(fr_list)
print(len(fr_corp))
unique_fr_word_toks = set(fr_corp.split())
len(unique_fr_word_toks)

2756011

25656

In [79]:
#We want to restrict the tokenizer size to 11500
#we will create two tokenizers - one for english and another for french

In [80]:
#let us reinitialize the generator object so that their counters are reset
en_train_corpus = (en_list[i:i+1000] for i in range(0, len(en_list), 1000))
fr_train_corpus = (fr_list[i:i+1000] for i in range(0, len(fr_list), 1000))

In [81]:
en_train_corpus, fr_train_corpus

(<generator object <genexpr> at 0x7f42d30cf7d0>,
 <generator object <genexpr> at 0x7f42d30cf5a0>)

In [82]:
en_tokenizer = orig_tokenizer.train_new_from_iterator(en_train_corpus, 11500) #vocab size of 11500

In [83]:
en_tokenizer

GPT2TokenizerFast(name_or_path='gpt2', vocab_size=11500, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [84]:
orig_tokenizer

GPT2TokenizerFast(name_or_path='gpt2', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [85]:
fr_tokenizer = orig_tokenizer.train_new_from_iterator(fr_train_corpus, 11500) #vocab size of 11500

In [86]:
print("###Tokenizing English and French using original tokenizer###")
tokenized_en=orig_tokenizer.tokenize("I don't speak French.")
print(tokenized_en)
tokenized_fr=orig_tokenizer.tokenize("Je ne parle pas français.")
print(tokenized_fr)
print(orig_tokenizer.tokenize("How are you?"))
print(orig_tokenizer.tokenize("Comment êtes-vous?"))

###Tokenizing English and French using original tokenizer###
['I', 'Ġdon', "'t", 'Ġspeak', 'ĠFrench', '.']
['Je', 'Ġne', 'Ġpar', 'le', 'Ġpas', 'Ġfr', 'an', 'Ã§', 'ais', '.']
['How', 'Ġare', 'Ġyou', '?']
['Comment', 'ĠÃ', 'ª', 'tes', '-', 'vous', '?']

In [87]:
print("###Tokenizing English and French using new  tokenizers###")
tokenized_en=en_tokenizer.tokenize("I don't speak French.")
print(tokenized_en)
tokenized_fr=fr_tokenizer.tokenize("Je ne parle pas français.")
print(tokenized_fr)
print(en_tokenizer.tokenize("How are you?"))
print(fr_tokenizer.tokenize("Comment êtes-vous?"))

###Tokenizing English and French using new  tokenizers###
['I', 'Ġdon', "'t", 'Ġspeak', 'ĠFrench', '.']
['Je', 'Ġne', 'Ġparle', 'Ġpas', 'ĠfranÃ§ais', '.']
['How', 'Ġare', 'Ġyou', '?']
['Comment', 'ĠÃªtes', '-', 'vous', '?']

In [88]:
fr_tokenizer.decode(fr_tokenizer.encode("Comment êtes-vous?"))

'Comment êtes-vous?'

In [89]:
fr_tokenizer.decode(fr_tokenizer.encode("Je ne parle pas français."))

'Je ne parle pas français.'

In [90]:
#As we can see new tokenizer is able to tokenize french text better. 
#at the same time we can limit the vocab size which will bring down the model size

In [91]:
#let us try to use en_tokenizer to tokenize french words and see the fun and vice versa

In [92]:
en_tokenizer.tokenize("Je ne parle pas français.") ##oh bro what's this..dont fret. this is expected

['J',
 'e',
 'Ġne',
 'Ġpar',
 'le',
 'Ġp',
 'as',
 'Ġfr',
 'an',
 'Ã',
 '§',
 'a',
 'is',
 '.']

In [93]:
fr_tokenizer.tokenize("I don't speak French.")

['I', 'Ġdon', "'", 't', 'Ġs', 'pe', 'ak', 'ĠFr', 'en', 'ch', '.']

In [94]:
en_tokenizer.tokenize("I don't speak French.")

['I', 'Ġdon', "'t", 'Ġspeak', 'ĠFrench', '.']

In [95]:
#en_tokenizer.save_pretrained('./tokenizers_dir/en_tokenizer')

In [96]:
#fr_tokenizer.save_pretrained('./tokenizers_dir/fr_tokenizer')

In [97]:
#new_en_tokenizer = AutoTokenizer.from_pretrained('./tokenizers_dir/en_tokenizer')
#new_en_tokenizer

In [98]:
#new_fr_tokenizer = AutoTokenizer.from_pretrained('./tokenizers_dir/fr_tokenizer')
#new_fr_tokenizer

In [99]:
#print("###Tokenizing English and French using new  tokenizers initialized from saved config###")
#tokenized_en=new_en_tokenizer.tokenize("I don't speak French.")
#print(tokenized_en)
#tokenized_fr=new_fr_tokenizer.tokenize("Je ne parle pas français.")
#print(tokenized_fr)
#print(new_en_tokenizer.tokenize("How are you?"))
#print(new_fr_tokenizer.tokenize("Comment êtes-vous?"))

In [100]:
#new_en_tokenizer("I don't speak French.")

In [101]:
#new_fr_tokenizer.tokenize("Je ne parle pas français.")

In [102]:
del  fr_tokenizer

In [103]:
en_tokenizer = AutoTokenizer.from_pretrained('./tokenizers_dir/en_tokenizer')
en_tokenizer

GPT2TokenizerFast(name_or_path='./tokenizers_dir/en_tokenizer', vocab_size=11500, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [104]:
fr_tokenizer = AutoTokenizer.from_pretrained('./tokenizers_dir/fr_tokenizer')
fr_tokenizer

GPT2TokenizerFast(name_or_path='./tokenizers_dir/fr_tokenizer', vocab_size=11500, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

What all do we need to train model?

1) Model initialized and moved to GPU
2) Tokenizer initialized
3) Dataset
4) DataLoader
5) Collate_fn
6) loss function
7) optimizer
8) training loop
9) Split dataset into train/validation/test dataset
10) evaluator = loss/accuracy on train and eval dataset
11) Once training is done we need to use Bleu Score and BERT score to assess efficiency

In [105]:
en_vocab_size = en_tokenizer.vocab_size
fr_vocab_size = fr_tokenizer.vocab_size
en_vocab_size, fr_vocab_size

(11500, 11500)

In [106]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [107]:
bro_model = Bro_Transformer(num_layers=6, embed_dim=256, num_heads=8,
                            input_vocab_size=en_vocab_size, target_vocab_size=fr_vocab_size,
                            enc_ctx_len=128, dec_ctx_len=128, device=device, do=0.1)

In [108]:
bro_model

Bro_Transformer(
  (encoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(11500, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (decoder): Decoder(
    (emb): Embed(
      (tok_layer): Embedding(11500, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (final_layer): Linear(in_features=256, out_features=11500, bias=True)
)

In [109]:
summary(bro_model)

===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
Bro_Transformer                                    --
├─Encoder: 1-1                                     --
│    └─Embed: 2-1                                  --
│    │    └─Embedding: 3-1                         2,944,000
│    │    └─PositionalEncoding: 3-2                --
│    │    └─Sequential: 3-3                        512
│    └─Sequential: 2-2                             --
│    │    └─Encoder_Block: 3-4                     789,760
│    │    └─Encoder_Block: 3-5                     789,760
│    │    └─Encoder_Block: 3-6                     789,760
│    │    └─Encoder_Block: 3-7                     789,760
│    │    └─Encoder_Block: 3-8                     789,760
│    │    └─Encoder_Block: 3-9                     789,760
├─Decoder: 1-2                                     --
│    └─Embed: 2-3                                  --
│    │    └─Embedding: 3-10                        2,944,000
│    │    └─PositionalEncoding: 3-11               --
│    │    └─Sequential: 3-12                       512
│    └─Sequential: 2-4                             --
│    │    └─Decoder_Block: 3-13                    1,053,440
│    │    └─Decoder_Block: 3-14                    1,053,440
│    │    └─Decoder_Block: 3-15                    1,053,440
│    │    └─Decoder_Block: 3-16                    1,053,440
│    │    └─Decoder_Block: 3-17                    1,053,440
│    │    └─Decoder_Block: 3-18                    1,053,440
├─Linear: 1-3                                      2,955,500
===========================================================================
Total params: 19,903,724
Trainable params: 19,903,724
Non-trainable params: 0
===========================================================================

In [110]:
bro_model.to(device)

Bro_Transformer(
  (encoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(11500, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (decoder): Decoder(
    (emb): Embed(
      (tok_layer): Embedding(11500, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Decoder_Block(
        (MHA_CAUSAL_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_causal_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (MHA_CROSS_ATTN): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_cross_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (dec_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (final_layer): Linear(in_features=256, out_features=11500, bias=True)
)

In [111]:
df

,Unnamed: 0,en,fr
0,0,"Two young, White males are outside near many b...",Deux jeunes mâles blancs se trouvent à l’extér...
1,0,Several men in hard hats are operating a giant...,Plusieurs hommes portant un chapeau d'assaut f...
2,0,A little girl climbing into a wooden playhouse.,Une petite fille grimpant dans une maison de j...
3,0,A man in a blue shirt is standing on a ladder ...,Un homme en chemise bleue se tient sur une éch...
4,0,Two men are at the stove preparing food.,Deux hommes sont à la cuisinière pour préparer...
...,...,...,...
47168,0,I'm walking with her.,Je marche avec elle.
47169,0,How are you doing today?,Comment allez-vous aujourd'hui?
47170,0,Today is a great day for hiking!,Aujourd'hui est une belle journée pour la rand...
47171,0,What a wonderful day for fishing!,Quelle merveilleuse journée pour la pêche!
47172,0,Look both ways before you cross the stree!,Regardez les deux côtés avant de traverser la ...

In [112]:
df['en_len'] = df['en'].apply(lambda x: len(en_tokenizer(x).input_ids))

In [113]:
df['fr_len'] = df['fr'].apply(lambda x: len(fr_tokenizer(x).input_ids))

In [114]:
df.describe()

       Unnamed: 0        en_len        fr_len
count     47173.0  47173.000000  47173.000000
mean          0.0     11.248447     13.009370
std           0.0      4.563858      5.564908
min           0.0      2.000000      2.000000
25%           0.0      8.000000      9.000000
50%           0.0     10.000000     12.000000
75%           0.0     14.000000     16.000000
max           0.0     44.000000     54.000000

In [115]:
df['en_len'].quantile(0.99), df['fr_len'].quantile(0.99)

(25.0, 30.0)

In [116]:
df_lte32 = df[(df['en_len'] <= 32) & (df['fr_len'] <= 32)]

In [117]:
len(df), len(df_lte32)

(47173, 46883)

In [118]:
len(df) - len(df_lte32)

290

In [119]:
# we do not want to exceed 512 tokens so taking batch size of 16 and 31 tokens
16*31
## We will get rid of data that exceed 31 tokens

496

In [120]:
df_lt32 = df[(df['en_len'] < 32) & (df['fr_len'] < 32)].copy()

In [121]:
df_lt32.reset_index(inplace=True, drop=True)
df_lt32.describe()

       Unnamed: 0        en_len        fr_len
count     46798.0  46798.000000  46798.000000
mean          0.0     11.118082     12.830976
std           0.0      4.321121      5.204432
min           0.0      2.000000      2.000000
25%           0.0      8.000000      9.000000
50%           0.0     10.000000     12.000000
75%           0.0     14.000000     16.000000
max           0.0     31.000000     31.000000

In [122]:
df_lt32.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46798 entries, 0 to 46797
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  46798 non-null  int64
 1   en          46798 non-null  object
 2   fr          46798 non-null  object
 3   en_len      46798 non-null  int64
 4   fr_len      46798 non-null  int64
dtypes: int64(3), object(2)
memory usage: 1.8+ MB

In [123]:
df_lt32

,Unnamed: 0,en,fr,en_len,fr_len
0,0,"Two young, White males are outside near many b...",Deux jeunes mâles blancs se trouvent à l’extér...,11,15
1,0,Several men in hard hats are operating a giant...,Plusieurs hommes portant un chapeau d'assaut f...,12,18
2,0,A little girl climbing into a wooden playhouse.,Une petite fille grimpant dans une maison de j...,9,12
3,0,A man in a blue shirt is standing on a ladder ...,Un homme en chemise bleue se tient sur une éch...,15,15
4,0,Two men are at the stove preparing food.,Deux hommes sont à la cuisinière pour préparer...,9,11
...,...,...,...,...,...
46793,0,I'm walking with her.,Je marche avec elle.,6,5
46794,0,How are you doing today?,Comment allez-vous aujourd'hui?,6,8
46795,0,Today is a great day for hiking!,Aujourd'hui est une belle journée pour la rand...,8,12
46796,0,What a wonderful day for fishing!,Quelle merveilleuse journée pour la pêche!,7,7
46797,0,Look both ways before you cross the stree!,Regardez les deux côtés avant de traverser la ...,10,10

In [135]:
class EN_FR_DS(Dataset):
    def __init__(self, df, en_tokenizer, fr_tokenizer):
        self.data = df
        self.src_tokenizer = en_tokenizer
        self.tgt_tokenizer = fr_tokenizer
        self.EOT = self.tgt_tokenizer.encode('<|endoftext|>')

    def __len__(self):
        return len(df)

    def __getitem__(self, idx):
        en_item = self.data.iloc[idx]['en']
        fr_item = '<|endoftext|>' + self.data.iloc[idx]['fr']
        return en_item, fr_item

In [136]:
ds = EN_FR_DS(df, en_tokenizer, fr_tokenizer)

In [137]:
ds[0], len(ds[0])

(('Two young, White males are outside near many bushes.',
  '<|endoftext|>Deux jeunes mâles blancs se trouvent à l’extérieur près de nombreux buissons.'),
 2)

In [138]:
ds[9], len(ds[9])

(('Boys dancing on poles in the middle of the night.',
  '<|endoftext|>Les garçons dansent sur des mâts au milieu de la nuit.'),
 2)

print(en_tokenizer.decode(ds[0][0]))
print(fr_tokenizer.decode(ds[0][2]))
print(df.iloc[0]['en'])
print(df.iloc[0]['fr'])
print(fr_tokenizer.decode(ds[0][4]))

print(en_tokenizer.decode(ds[1][0]))
print(fr_tokenizer.decode(ds[1][2]))
print(df.iloc[1]['en'])
print(df.iloc[1]['fr'])
print(fr_tokenizer.decode(ds[1][4]))

In [139]:
import os
dl = DataLoader(ds, shuffle=True, batch_size=16, num_workers=os.cpu_count())
dl

In [140]:
dl_iter = iter(dl)
dl_iter

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [141]:
next(dl_iter)

[('He lied to us.',
  "You should follow your teacher's advice.",
  'He does not like being punished.',
  'A youth baseball player rounds third as the outfielders retrieve the ball at the fence.',
  'Mary senses the aliens are watching her.',
  'The ladies in the purple jackets are playing the sax.',
  'I woke up at 2:30.',
  'We go fishing from time to time.',
  'Two older men in coats are standing outside.',
  'A middle-aged man wearing a red hat is fishing.',
  'You or I will be chosen.',
  'Girl in red, with striped tights, playing violin outside of building.',
  'A man with a turquoise vest and black pants sits down in front of a brick monument.',
  'Four dogs jumping over a hurdle.',
  'A blond-hair lady sitting with a kid.',
  'Get away!'),
 ('<|endoftext|>Il nous a menti.',
  '<|endoftext|>Vous devriez suivre les conseils de votre professeur.',
  "<|endoftext|>Il n'aime pas être puni.",
  "<|endoftext|>Un jeune joueur de baseball se classe au troisième rang alors que les joueurs de l'extérieur reprennent la balle à la clôture.",
  "<|endoftext|>Mary a l'impression que les étrangers l'observent.",
  '<|endoftext|>Les femmes dans les vestes pourpre jouent le saxophone.',
  '<|endoftext|>Je me suis réveillée à 12 h 30.',
  '<|endoftext|>Nous pêchons de temps à autre.',
  "<|endoftext|>Deux hommes plus âgés en manteau se trouvent à l'extérieur.",
  "<|endoftext|>Un homme d'âge moyen portant un chapeau rouge pêche.",
  '<|endoftext|>Vous ou moi serez choisis.',
  '<|endoftext|>Girl in red, with striped tights, playing violin outside of building.',
  "<|endoftext|>Un homme muni d'une veste turquoise et de pantalons noirs s'asseoira devant un monument en briques.",
  '<|endoftext|>Quatre chiens sautent sur un obstacle.',
  '<|endoftext|>Une femme à cheveux blond assise avec un enfant.',
  "<|endoftext|>Soyez à l'écart!")]

In [142]:
batch = next(dl_iter)

In [143]:
batch[0]

('All of them are not present.',
 'A man and a woman with feathers on her head dance.',
 'A group of Native Americans sit in a circle chanting and beating a drum.',
 'A group of adults and children are at an amusement park watching over a railing.',
 'Young kids playing soccer on a lush, green field.',
 'Bringing up a baby is hard work.',
 'A young boy taking a picture through the glass and two females chatting.',
 'My aunt made me a new skirt.',
 'Tom seems to hardly ever get his homework done on time.',
 'I envied his new house.',
 'They kept me waiting for an hour.',
 'A man wearing a white shirt is skateboarding downhill on a road.',
 "It's up to you.",
 'A young indian mother is with her child.',
 "He took care of the business after his father's death.",
 'I wish you had come with us.')

In [144]:
batch[1]

('<|endoftext|>Tous ne sont pas présents.',
 '<|endoftext|>Un homme et une femme avec des plumes sur la tête dansent.',
 "<|endoftext|>Un groupe d'Américains autochtones s'asseoir dans un cercle chantant et battant un tambour.",
 "<|endoftext|>Un groupe d'adultes et d'enfants se trouvent dans un parc d'attractions et surveillent un rail.",
 '<|endoftext|>Jeunes enfants jouant au soccer sur un terrain luxuriant et verdoyant.',
 '<|endoftext|>Élever un bébé est un travail ardu.',
 '<|endoftext|>Un jeune garçon prenant une photo à travers le verre et deux femelles chattant.',
 "<|endoftext|>Ma tante m'a fait une nouvelle jupe.",
 '<|endoftext|>Il semble que Tom ne fasse guère ses devoirs à temps.',
 "<|endoftext|>J'envieais sa nouvelle maison.",
 "<|endoftext|>Ils m'ont maintenu en attente pendant une heure.",
 '<|endoftext|>Un homme portant une chemise blanche fait du skateboarding sur une route.',
 "<|endoftext|>C'est à vous de choisir.",
 '<|endoftext|>Une jeune mère indienne est avec son enfant.',
 "<|endoftext|>Il s'occupe de l'entreprise après le décès de son père.",
 '<|endoftext|>Je vous souhaite que vous soyez présent avec nous.')

In [145]:
def collate_fn(batch, en_tokenizer, fr_tokenizer):
    eos_tokenid = fr_tokenizer.encode('<|endoftext|>')
    pad_tokenid = fr_tokenizer.encode('<|endoftext|>')
    ignore_loss_id = [-100]  #ignore loss
    ignore_token_id = [0]   #attention mask filler
    x_input_ids, x_am = [], []
    y_input_ids, y_am, lab_list = [], [], []

    for x, y in batch:
        x_tok = en_tokenizer(x)
        y_tok = fr_tokenizer(y)

        x_tok_input_ids = x_tok.input_ids
        x_tok_am = x_tok.attention_mask

        y_tok_input_ids = y_tok.input_ids
        y_tok_am = y_tok.attention_mask

        labs = y_tok_input_ids[1:] + eos_tokenid

        x_input_ids.append(x_tok_input_ids)
        x_am.append(x_tok_am)

        y_input_ids.append(y_tok_input_ids)
        y_am.append(y_tok_am)

        lab_list.append(labs)

    len_enc = [len(l) for l in x_input_ids]
    max_len_enc = max(len_enc)

    len_labs = [len(l) for l in lab_list]
    max_len_labs = max(len_labs)

    max_len = max([max_len_enc, max_len_labs])

    def pad_tokens_stack(in_list, max_len, padding):
        list_tensor = []
        for item in in_list:
            len_item = len(item)
            deficit = max_len - len_item
            if deficit > 0:
                item = item + padding*deficit
            list_tensor.append(torch.tensor(item))
        item_ids = torch.vstack(list_tensor)
        return item_ids

    enc_input_ids = pad_tokens_stack(x_input_ids, max_len, pad_tokenid)
    enc_am = pad_tokens_stack(x_am, max_len, ignore_token_id)

    dec_input_ids = pad_tokens_stack(y_input_ids, max_len, pad_tokenid)
    dec_am = pad_tokens_stack(y_am, max_len, ignore_token_id)

    labels = pad_tokens_stack(lab_list, max_len, ignore_loss_id)

    return {'enc_input_ids': enc_input_ids, 'dec_input_ids': dec_input_ids,
            'enc_attention_mask': enc_am, 'dec_attention_mask': dec_am}, labels

In [146]:
from functools import partial
wrapper_collate_fn = partial(
    collate_fn,
    en_tokenizer=en_tokenizer,
    fr_tokenizer=fr_tokenizer
    )

dl = DataLoader(ds, shuffle=False, batch_size=3,
                num_workers=os.cpu_count(), collate_fn=wrapper_collate_fn)

In [147]:
iter_dl = iter(dl)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [148]:
batch = next(iter_dl)

In [149]:
len(batch)

2

In [150]:
batch

({'enc_input_ids': tensor([[ 351,  388,   12, 6932, 2799,  320,  541,  609, 1015, 4038,   14,    0,
              0,    0,    0,    0,    0,    0,    0],
          [ 959,  426,  271, 1033, 1353,  320, 3778,  257, 2669, 9013, 4759,   14,
              0,    0,    0,    0,    0,    0,    0],
          [  33,  520,  390, 1175,  566,  257, 1230, 9739,   14,    0,    0,    0,
              0,    0,    0,    0,    0,    0,    0]]),
  'dec_input_ids': tensor([[   0,  369,  654, 5144, 1118,  329,  764,  292,  265,  611,  513,  559,
            271, 1808, 5170,   14,    0,    0,    0],
          [   0,  958,  451,  370,  267,  569,  257,    7,  985,  613, 1155, 6561,
            267, 5512, 5717,  271, 9658, 1528,   14],
          [   0,  327,  672,  437, 4822,  305,  293,  806,  271, 1960,  291,  698,
             14,    0,    0,    0,    0,    0,    0]]),
  'enc_attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
  'dec_attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]])},
 tensor([[ 369,  654, 5144, 1118,  329,  764,  292,  265,  611,  513,  559,  271,
          1808, 5170,   14,    0, -100, -100, -100],
         [ 958,  451,  370,  267,  569,  257,    7,  985,  613, 1155, 6561,  267,
          5512, 5717,  271, 9658, 1528,   14,    0],
         [ 327,  672,  437, 4822,  305,  293,  806,  271, 1960,  291,  698,   14,
             0, -100, -100, -100, -100, -100, -100]]))

In [151]:
print(batch[0]['enc_input_ids'].shape)
print(batch[0]['dec_input_ids'].shape)
print(batch[0]['enc_attention_mask'].shape)
print(batch[0]['dec_attention_mask'].shape)
print(batch[1].shape)

torch.Size([3, 19])
torch.Size([3, 19])
torch.Size([3, 19])
torch.Size([3, 19])
torch.Size([3, 19])

In [152]:
batch = next(iter_dl)

In [153]:
print(batch[0]['enc_input_ids'].shape)
print(batch[0]['dec_input_ids'].shape)
print(batch[0]['enc_attention_mask'].shape)
print(batch[0]['dec_attention_mask'].shape)
print(batch[1].shape)

torch.Size([3, 16])
torch.Size([3, 16])
torch.Size([3, 16])
torch.Size([3, 16])
torch.Size([3, 16])

In [154]:
batch

({'enc_input_ids': tensor([[  33,  298,  271,  257,  405,  378,  290,  433,  289,  257, 2189, 2181,
            257, 1025,   14,    0],
          [ 351,  426,  320,  329,  277, 3607, 1568,  774,   14,    0,    0,    0,
              0,    0,    0,    0],
          [  33,  298,  271,  523,  884,  257,  761,  402,  277,  533,  298, 4937,
            375,  378,   14,    0]]),
  'dec_input_ids': tensor([[   0,  274,  314,  291,  409,  590,  329,  473,  309,  293, 2646,  413,
           3358,  293, 1254,   14],
          [   0,  369,  451,  461,  292,  308, 5701,  413, 3687,  308, 1198,   14,
              0,    0,    0,    0],
          [   0,  274,  314,  745,  473,  293,  844,  624,  377,  265,    7,  769,
           4662,  406,  409,   14]]),
  'enc_attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]]),
  'dec_attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])},
 tensor([[ 274,  314,  291,  409,  590,  329,  473,  309,  293, 2646,  413, 3358,
           293, 1254,   14,    0],
         [ 369,  451,  461,  292,  308, 5701,  413, 3687,  308, 1198,   14,    0,
          -100, -100, -100, -100],
         [ 274,  314,  745,  473,  293,  844,  624,  377,  265,    7,  769, 4662,
           406,  409,   14,    0]]))

In [155]:
batch = next(iter_dl)

In [156]:
print(batch[0]['enc_input_ids'].shape)
print(batch[0]['dec_input_ids'].shape)
print(batch[0]['enc_attention_mask'].shape)
print(batch[0]['dec_attention_mask'].shape)
print(batch[1].shape)

torch.Size([3, 22])
torch.Size([3, 22])
torch.Size([3, 22])
torch.Size([3, 22])
torch.Size([3, 22])

In [157]:
batch

({'enc_input_ids': tensor([[  33,  298,  290,  845,  329,  257, 3117, 5260,    0,    0,    0,    0,
              0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
          [  33, 1049, 9643,  390,  773,  289,  408, 1376,  402, 8064, 3784,  441,
            277,  439,   14,    0,    0,    0,    0,    0,    0,    0],
          [  33,  336,  307,  257,  548, 2293,  290,  455,  460,  257, 3129,   14,
              0,    0,    0,    0,    0,    0,    0,    0,    0,    0]]),
  'dec_input_ids': tensor([[   0,  274,  314, 1250,  292,  267, 6063, 2228,    0,    0,    0,    0,
              0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
          [   0,  327,  441,  437,  292,  308, 3842, 1549,  309,  438,  940, 1428,
            674,  291,  263,    7, 8214, 4331,  305,  308,  459,   14],
          [   0,  327,  343, 6433,  257,    7,  258,  642,  741,  329, 1074,  559,
            257,    7,  331,  565,   14,    0,    0,    0,    0,    0]]),
  'enc_attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
  'dec_attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])},
 tensor([[ 274,  314, 1250,  292,  267, 6063, 2228,    0, -100, -100, -100, -100,
          -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
         [ 327,  441,  437,  292,  308, 3842, 1549,  309,  438,  940, 1428,  674,
           291,  263,    7, 8214, 4331,  305,  308,  459,   14,    0],
         [ 327,  343, 6433,  257,    7,  258,  642,  741,  329, 1074,  559,  257,
             7,  331,  565,   14,    0, -100, -100, -100, -100, -100]]))

In [158]:
batch[0].items()

dict_items([('enc_input_ids', tensor([[  33,  298,  290,  845,  329,  257, 3117, 5260,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
        [  33, 1049, 9643,  390,  773,  289,  408, 1376,  402, 8064, 3784,  441,
          277,  439,   14,    0,    0,    0,    0,    0,    0,    0],
        [  33,  336,  307,  257,  548, 2293,  290,  455,  460,  257, 3129,   14,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])), ('dec_input_ids', tensor([[   0,  274,  314, 1250,  292,  267, 6063, 2228,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   0,  327,  441,  437,  292,  308, 3842, 1549,  309,  438,  940, 1428,
          674,  291,  263,    7, 8214, 4331,  305,  308,  459,   14],
        [   0,  327,  343, 6433,  257,    7,  258,  642,  741,  329, 1074,  559,
          257,    7,  331,  565,   14,    0,    0,    0,    0,    0]])), ('enc_attention_mask', tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])), ('dec_attention_mask', tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]]))])

In [159]:
batch[0].keys()

dict_keys(['enc_input_ids', 'dec_input_ids', 'enc_attention_mask', 'dec_attention_mask'])

In [160]:
from torch.optim import AdamW

In [161]:
def train_model(num_epochs, lrate, brogpt, dl, device, vocab_size):
    epochs = num_epochs
    lr = lrate
    fn_loss = nn.CrossEntropyLoss()
    optimizer = AdamW(brogpt.parameters(), lr=lr)
    grad_accum_steps = 1 #args.grad_accum_steps # 4 - previous static value

    for i in range(epochs):
        loss_epoch = 0
        n_step = 0
        grad_accum_counter = 1

        for inputs in dl:
            data = inputs[0]
            label = inputs[1]
            batch_size = label.shape[0]
            ctx_size = label.shape[1]
            data = {i: k.to(device) for i, k in data.items()}
            label = label.to(device)
            #enc_input_ids, dec_input_ids, enc_attention_mask, dec_attention_mask)
            #dict_keys(['enc_input_ids', 'enc_am', 'dec_input_ids', 'dec_am'])
            out = brogpt(**data)
            #out = out.logits  # Code added for hugging face based transformer models
            out = out.view(batch_size * ctx_size, vocab_size)
            label = label.view(batch_size * ctx_size)
            loss = fn_loss(out, label)
            loss = loss / grad_accum_steps
            loss.backward()
            if grad_accum_counter == grad_accum_steps:
                #logger.info(f'Steps: {grad_accum_counter}, adjusting learnable params now')
                optimizer.step()
                optimizer.zero_grad()
                grad_accum_counter = 0
            loss_epoch = loss_epoch + (loss.item() * batch_size * grad_accum_steps)
            #if n_step % 100 == 0:
            #    print(f'Step: {n_step}, Loss: {loss.item()}')
            grad_accum_counter += 1
            #n_step += 1
            ##update so that if remaining dataloader runs are less than grad accum steps then at the last run i should
            #gradient update
        average_loss = loss_epoch/len(dl.dataset)
        perplexity = math.exp(average_loss) 
        print(f'Epoch: {i} -- Average loss: {average_loss}')
        print(f'Epoch: {i} -- Perplexity: {perplexity}')

    return brogpt, optimizer, average_loss, perplexity

In [162]:
dl = DataLoader(ds, shuffle=False, batch_size=256,
                num_workers=os.cpu_count(), collate_fn=wrapper_collate_fn)

In [163]:
vocab_size = fr_tokenizer.vocab_size
vocab_size

11500

In [167]:
model_dict = torch.load('./MT_bro/ckpt_Epoch_100_Prplxty_1.0323989382902838.pt')

In [168]:
model_dict.keys()

dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'loss', 'device'])

In [169]:
bro_model.load_state_dict(model_dict['model_state_dict'])

In [170]:
torch.cuda.empty_cache()
bro_model, optimizer, average_loss, perplexity = train_model(40, 0.0002, bro_model, dl, device, vocab_size)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 0 -- Average loss: 0.1937053845523891
Epoch: 0 -- Perplexity: 1.2137386441219367

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
TOKENIZERS_PARALLELISM=(true | false)iable
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
TOKENIZERS_PARALLELISM=(true | false)iable
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
TOKENIZERS_PARALLELISM=(true | false)
TOKENIZERS_PARALLELISM=(true | false)
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 1 -- Average loss: 0.08478394283215389
Epoch: 1 -- Perplexity: 1.0884818669815894

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 2 -- Average loss: 0.06423583309410805
Epoch: 2 -- Perplexity: 1.0663438482794036

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 3 -- Average loss: 0.05335885415025967
Epoch: 3 -- Perplexity: 1.0548080994745606

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 4 -- Average loss: 0.04540844180179977
Epoch: 4 -- Perplexity: 1.046455188676076

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 5 -- Average loss: 0.039483153112561994
Epoch: 5 -- Perplexity: 1.040272973375646

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 6 -- Average loss: 0.03533328923553938
Epoch: 6 -- Perplexity: 1.0359649272262756

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
TOKENIZERS_PARALLELISM=(true | false)iable
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
TOKENIZERS_PARALLELISM=(true | false)

Epoch: 7 -- Average loss: 0.0323211762227229
Epoch: 7 -- Perplexity: 1.0328491786373104

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 8 -- Average loss: 0.030012903982249886
Epoch: 8 -- Perplexity: 1.0304678310063247

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 9 -- Average loss: 0.027899863168341275
Epoch: 9 -- Perplexity: 1.0282927092917833

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 10 -- Average loss: 0.026701595095641066
Epoch: 10 -- Perplexity: 1.027061276909248

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 11 -- Average loss: 0.025272284993274465
Epoch: 11 -- Perplexity: 1.025594336456554

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 12 -- Average loss: 0.02381998199185429
Epoch: 12 -- Perplexity: 1.0241059437836595

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
TOKENIZERS_PARALLELISM=(true | false)iable
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
TOKENIZERS_PARALLELISM=(true | false)

Epoch: 13 -- Average loss: 0.023237497962073406
Epoch: 13 -- Perplexity: 1.0235095921261215

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 14 -- Average loss: 0.022026856578093248
Epoch: 14 -- Perplexity: 1.0222712388091293

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 15 -- Average loss: 0.02175533656216514
Epoch: 15 -- Perplexity: 1.021993709385187

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 16 -- Average loss: 0.021082735628217678
Epoch: 16 -- Perplexity: 1.0213065465808435

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 17 -- Average loss: 0.020807168410845647
Epoch: 17 -- Perplexity: 1.021025146751783

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 18 -- Average loss: 0.019909816332907858
Epoch: 18 -- Perplexity: 1.0201093386773117

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 19 -- Average loss: 0.01990067512863847
Epoch: 19 -- Perplexity: 1.0201000136920906

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 20 -- Average loss: 0.01970349502174498
Epoch: 20 -- Perplexity: 1.019898890091787

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 21 -- Average loss: 0.018625100177458036
Epoch: 21 -- Perplexity: 1.0187996292121813

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
TOKENIZERS_PARALLELISM=(true | false)iable
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
TOKENIZERS_PARALLELISM=(true | false)

Epoch: 22 -- Average loss: 0.017867976795856163
Epoch: 22 -- Perplexity: 1.0180285641242743

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
TOKENIZERS_PARALLELISM=(true | false)iable
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
TOKENIZERS_PARALLELISM=(true | false)

Epoch: 23 -- Average loss: 0.019274407550160296
Epoch: 23 -- Perplexity: 1.0194613581322196

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
TOKENIZERS_PARALLELISM=(true | false)iable
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 24 -- Average loss: 0.017470777253054598
Epoch: 24 -- Perplexity: 1.0176242839393128

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 25 -- Average loss: 0.017959310341440587
Epoch: 25 -- Perplexity: 1.0181215485287751

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 26 -- Average loss: 0.01735612581830761
Epoch: 26 -- Perplexity: 1.017507618543181

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 27 -- Average loss: 0.01733842906751691
Epoch: 27 -- Perplexity: 1.0174896121237562

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 28 -- Average loss: 0.01685529905387853
Epoch: 28 -- Perplexity: 1.0169981510829231

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
TOKENIZERS_PARALLELISM=(true | false)iable
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 29 -- Average loss: 0.016218438851772543
Epoch: 29 -- Perplexity: 1.0163506716337136

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 30 -- Average loss: 0.016797553071744253
Epoch: 30 -- Perplexity: 1.0169394252214676

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 31 -- Average loss: 0.016598339964736024
Epoch: 31 -- Perplexity: 1.0167368577366491

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 32 -- Average loss: 0.01609608956318263
Epoch: 32 -- Perplexity: 1.016226329458825

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 33 -- Average loss: 0.016012744338011795
Epoch: 33 -- Perplexity: 1.0161416353760444

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 34 -- Average loss: 0.01631024136283257
Epoch: 34 -- Perplexity: 1.0164439794603681

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 35 -- Average loss: 0.01597264928568836
Epoch: 35 -- Perplexity: 1.0161008939407763

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 36 -- Average loss: 0.01575094147872115
Epoch: 36 -- Perplexity: 1.0158756414109682

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 37 -- Average loss: 0.015134095062999224
Epoch: 37 -- Perplexity: 1.0152491953930987

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 38 -- Average loss: 0.015393329683882451
Epoch: 38 -- Perplexity: 1.0155124172500034

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Epoch: 39 -- Average loss: 0.015740576204905713
Epoch: 39 -- Perplexity: 1.0158651116363546

In [171]:
torch.cuda.empty_cache()

In [172]:
ckpt_name = './MT_bro/' + 'ckpt_' + "Epoch_" + str(140) + "_Prplxty_" + str(perplexity) + '.pt'
ckpt_name

'./MT_bro/ckpt_Epoch_140_Prplxty_1.0158651116363546.pt'

In [173]:
os.makedirs('./MT_bro/', exist_ok=True)

In [174]:
torch.save({
            'epoch': 140,
            'model_state_dict': bro_model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': average_loss,
            'device': device
            }, ckpt_name)

In [175]:
!ls -ltrh {ckpt_name}

-rw-rw-r-- 1 ec2-user ec2-user 230M Mar 15 16:43 ./MT_bro/ckpt_Epoch_140_Prplxty_1.0158651116363546.pt

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [176]:
fr_tokenizer.bos_token

'<|endoftext|>'

In [177]:
fr_tokenizer.vocab[fr_tokenizer.bos_token]

0

In [178]:
fr_tokenizer("Un")

{'input_ids': [274], 'attention_mask': [1]}

In [229]:
bleu_metric = evaluate.load('sacrebleu')
bert_metric = evaluate.load('bertscore')

In [213]:
def translate(en_text, fr_text, fr_start, en_tokenizer, fr_tokenizer, bro_model, compute_metrics=False):
    bro_model.eval()
    tokenized_en = en_tokenizer(en_text)
    tokenized_fr = fr_tokenizer(fr_start)
    enc_input_ids = torch.tensor(tokenized_en.input_ids).unsqueeze(0).to(device)
    dec_input_ids = torch.tensor(tokenized_fr.input_ids).unsqueeze(0).to(device)
    enc_attention_mask = torch.tensor(tokenized_en.attention_mask).unsqueeze(0).to(device)
    dec_attention_mask = torch.tensor(tokenized_fr.attention_mask).unsqueeze(0).to(device)
    pred = 12345678
    while pred!=0:
        with torch.no_grad():
            output = bro_model(enc_input_ids=enc_input_ids, dec_input_ids=dec_input_ids,
                               enc_attention_mask=enc_attention_mask, dec_attention_mask=dec_attention_mask)
        prediction = torch.argmax(output, dim=-1)[0][-1].unsqueeze(0).unsqueeze(0)
        #print(prediction)
        pred = torch.argmax(output, dim=-1).tolist()[0][-1]
        dec_input_ids = torch.cat([dec_input_ids, prediction], dim=1).to(device)
        dec_attention_mask = torch.tensor([1]*len(dec_input_ids[0])).unsqueeze(0).to(device)
        #print(pred)
    pred_text = fr_tokenizer.decode(dec_input_ids[0], skip_special_tokens=True)
    bleu = None
    bert_score = None
    if compute_metrics:
        bleu = bleu_metric.compute(predictions=[pred_text], references=[[fr_text]])
        bert_score = bert_metric.compute(predictions=[pred_text], references=[[fr_text]], lang='fr')
    return pred_text, bleu, bert_score

In [203]:
print(en_list[120])
print(fr_list[120])

Asian man and blond woman holding hands outdoors, man in background watches.
Un homme asiatique et une femme blond tiennent les mains à l'extérieur, l'homme à l'arrière-plan regarde.

In [214]:
en_text = en_list[120]
fr_text = fr_list[120]
fr_start = '<|endoftext|>'
print(en_text, fr_start)
pred_text, bleu, bert_score = translate(en_text, fr_text, fr_start, en_tokenizer, fr_tokenizer, bro_model, True)

Asian man and blond woman holding hands outdoors, man in background watches. <|endoftext|>

In [215]:
print(f'English text: {en_text}')
print(f"Original Text: {fr_text} \nPredicted Text: {pred_text}\n Bleu Score:\n {bleu}\n BertScore:\n  {bert_score}")

English text: Asian man and blond woman holding hands outdoors, man in background watches.
Original Text: Un homme asiatique et une femme blond tiennent les mains à l'extérieur, l'homme à l'arrière-plan regarde.
Predicted Text: Un homme asiatique et une femme blond tiennent les mains à l'extérieur, l'homme à l'arrière-plan regarde.
 Bleu Score:
 {'score': 100.00000000000004, 'counts': [18, 17, 16, 15], 'totals': [18, 17, 16, 15], 'precisions': [100.0, 100.0, 100.0, 100.0], 'bp': 1.0, 'sys_len': 18, 'ref_len': 18}
 BertScore:
  {'precision': [1.0], 'recall': [1.0], 'f1': [1.0], 'hashcode': 'bert-base-multilingual-cased_L9_no-idf_version=0.3.12(hug_trans=4.49.0)'}

In [216]:
en_text = en_list[14500]
fr_text = fr_list[14500]
fr_start = '<|endoftext|>'
print(en_text, fr_start)
pred_text, bleu, bert_score = translate(en_text, fr_text, fr_start, en_tokenizer, fr_tokenizer, bro_model, True)
print(f'English text: {en_text}')
print(f"Original Text: {fr_text} \nPredicted Text: {pred_text}\n Bleu Score:\n {bleu}\n BertScore:\n  {bert_score}")

A woman with a black and white sweater standing on a walkway. <|endoftext|>
English text: A woman with a black and white sweater standing on a walkway.
Original Text: Une femme en chandail noir et blanc se tient sur une passerelle.
Predicted Text: Une femme en chandail noir et blanc se tient sur une passerelle.
 Bleu Score:
 {'score': 100.00000000000004, 'counts': [13, 12, 11, 10], 'totals': [13, 12, 11, 10], 'precisions': [100.0, 100.0, 100.0, 100.0], 'bp': 1.0, 'sys_len': 13, 'ref_len': 13}
 BertScore:
  {'precision': [1.0], 'recall': [1.0], 'f1': [1.0], 'hashcode': 'bert-base-multilingual-cased_L9_no-idf_version=0.3.12(hug_trans=4.49.0)'}

In [217]:
en_text = en_list[3500]
fr_text = fr_list[3500]
fr_start = '<|endoftext|>'
print(en_text, fr_start)
pred_text, bleu, bert_score = translate(en_text, fr_text, fr_start, en_tokenizer, fr_tokenizer, bro_model, True)
print(f'English text: {en_text}')
print(f"Original Text: {fr_text} \nPredicted Text: {pred_text}\n Bleu Score:\n {bleu}\n BertScore:\n  {bert_score}")

A child in a martial arts uniform is jumping in the air with his arms and legs spread. <|endoftext|>
English text: A child in a martial arts uniform is jumping in the air with his arms and legs spread.
Original Text: Un enfant en uniforme d'arts martiaux saute dans l'air avec ses bras et ses jambes étalés.
Predicted Text: Un enfant en uniforme d'arts martiaux saute dans l'air avec ses bras et ses jambes étalés.
 Bleu Score:
 {'score': 100.00000000000004, 'counts': [17, 16, 15, 14], 'totals': [17, 16, 15, 14], 'precisions': [100.0, 100.0, 100.0, 100.0], 'bp': 1.0, 'sys_len': 17, 'ref_len': 17}
 BertScore:
  {'precision': [0.9999999403953552], 'recall': [0.9999999403953552], 'f1': [0.9999999403953552], 'hashcode': 'bert-base-multilingual-cased_L9_no-idf_version=0.3.12(hug_trans=4.49.0)'}

In [218]:
en_text = "I am a good boy"
fr_start = '<|endoftext|>'
print(en_text, fr_start)
translate(en_text,None, fr_start, en_tokenizer, fr_tokenizer, bro_model)

I am a good boy <|endoftext|>

('Je suis un bon garçon', None, None)

In [220]:
en_text = "You know. Today is a hot day"
fr_start = '<|endoftext|>'
print(en_text, fr_start)
translate(en_text, None, fr_start, en_tokenizer, fr_tokenizer, bro_model)

You know. Today is a hot day <|endoftext|>

('Vous savez que la journée (tension est une journée chaude.', None, None)

In [222]:
en_text = "I am a student"
fr_start = '<|endoftext|>'
print(en_text, fr_start)
translate(en_text, None, fr_start, en_tokenizer, fr_tokenizer, bro_model)

I am a student <|endoftext|>

('Je suis un étudiant', None, None)

In [187]:
en_text = "I saw a beautiful girl"
fr_start = '<|endoftext|>'
#fr_start = 'Je'
print(en_text, fr_start)
translate(en_text, fr_start, en_tokenizer, fr_tokenizer, bro_model)

I saw a beautiful girl <|endoftext|>

"J'ai vu une belle fille"

In [223]:
en_text = "A boy is going to school"
fr_start = '<|endoftext|>'
#fr_start = 'Un'
print(en_text, fr_start)
translate(en_text, None, fr_start, en_tokenizer, fr_tokenizer, bro_model)

A boy is going to school <|endoftext|>

("Un garçon va à l'école", None, None)

In [224]:
en_text = "This is my car"
fr_start = '<|endoftext|>'
#fr_start = 'Un'
print(en_text, fr_start)
translate(en_text, None, fr_start, en_tokenizer, fr_tokenizer, bro_model)

This is my car <|endoftext|>

("C'est ma voiture que ma voiture est ma voiture.", None, None)

In [225]:
en_text = "It is a beautiful day and I am loving it"
fr_start = '<|endoftext|>'
#fr_start = 'Un'
print(en_text, fr_start)
translate(en_text, None, fr_start, en_tokenizer, fr_tokenizer, bro_model)

It is a beautiful day and I am loving it <|endoftext|>

("C'est une belle journée et je l'ai aimée.", None, None)

In [226]:
en_text = "The colour of house is yellow"
fr_start = '<|endoftext|>'
#fr_start = 'Un'
print(en_text, fr_start)
translate(en_text, None, fr_start, en_tokenizer, fr_tokenizer, bro_model)

The colour of house is yellow <|endoftext|>

('Le personnel de la maison est jaune', None, None)

In [189]:
## So we our translation system is working good. The first character missing issue has been resolved and it is looking pretty good

In [230]:
##All done. Perform french to english translation using sagemaker script mode . Implement beam search