In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from pathlib import Path
import sys
from torch.utils.data import Dataset, DataLoader, RandomSampler
import math
from collections import OrderedDict
from torch.optim import AdamW

In [2]:
#!pip install torchinfo
from torchinfo import summary

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda

In [4]:
# Set the environment variable TOKENIZERS_PARALLELISM to 'false'
import os
os.environ['TOKENIZERS_PARALLELISM'] = 'false'

In [5]:
#!pip install transformers==4.49.0
#!pip install datasets

In [6]:
from transformers import AutoTokenizer

In [7]:
torch.__version__

'2.2.2'

In [8]:
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, dropout, max_len, device):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        pe = torch.zeros(max_len, d_model, device=device)
        position = torch.arange(0., max_len,
                                device=device).unsqueeze(1)
        div_term = torch.exp(torch.arange(0., d_model, 2, device=device) * -(math.log(10000.0) / d_model))
        pe_pos = torch.mul(position, div_term)
        pe[:, 0::2] = torch.sin(pe_pos)
        pe[:, 1::2] = torch.cos(pe_pos)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        out = self.pe[:, :x.size(1)].requires_grad_(False)
        return out

In [9]:
#del pe
pe_e = PositionalEncoding(d_model=768, dropout=0.1, max_len=512, device=device)
inp_tok = torch.tensor([5,8,78, 86, 78, 90, 45]).unsqueeze(0)
inp_tok, inp_tok.shape

(tensor([[ 5,  8, 78, 86, 78, 90, 45]]), torch.Size([1, 7]))

In [10]:
pe_e_e = pe_e(inp_tok)
pe_e_e, pe_e_e.shape

(tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
            0.0000e+00,  1.0000e+00],
          [ 8.4147e-01,  5.4030e-01,  8.2843e-01,  ...,  1.0000e+00,
            1.0243e-04,  1.0000e+00],
          [ 9.0930e-01, -4.1615e-01,  9.2799e-01,  ...,  1.0000e+00,
            2.0486e-04,  1.0000e+00],
          ...,
          [-7.5680e-01, -6.5364e-01, -6.9153e-01,  ...,  1.0000e+00,
            4.0971e-04,  1.0000e+00],
          [-9.5892e-01,  2.8366e-01, -9.8573e-01,  ...,  1.0000e+00,
            5.1214e-04,  1.0000e+00],
          [-2.7942e-01,  9.6017e-01, -4.1267e-01,  ...,  1.0000e+00,
            6.1457e-04,  1.0000e+00]]], device='cuda:0'),
 torch.Size([1, 7, 768]))

In [11]:
class Embed(nn.Module):
    def __init__(self, vocab_size, embed_dim, ctx_len, do, device):
        super().__init__()
        self.tok_layer = nn.Embedding(vocab_size, embed_dim)
        self.pos_layer = PositionalEncoding(embed_dim, do, ctx_len, device)
        self.norm_do = nn.Sequential(
            nn.LayerNorm(embed_dim),
            nn.Dropout(do)
            )
        self.device = device
        self.ctx_len = ctx_len

    def forward(self, inp):
        inp = inp.to(self.device)
        len_inp = inp.shape[-1]
        try:
            assert len_inp <= self.ctx_len
        except:
            print("Err..Errr. Error...Bro..Length of supplied text exceeds context length defined.Exiting the program now")
            sys.exit(1)
        tok_embed = self.tok_layer(inp)
        pos_embed = self.pos_layer(inp)
        embed_tok_pos = tok_embed + pos_embed
        embed_out = self.norm_do(embed_tok_pos)
        return embed_out

In [12]:
inp_tok = torch.tensor([5,8,78, 86, 78, 90, 45]).unsqueeze(0)
inp_tok, inp_tok.shape

(tensor([[ 5,  8, 78, 86, 78, 90, 45]]), torch.Size([1, 7]))

In [13]:
emb = Embed(100, 768, 512, 0.1, device).to(device)

In [14]:
emb_out = emb(inp_tok.to(device))
emb_out.shape, emb_out

(torch.Size([1, 7, 768]),
 tensor([[[-2.4344, -0.2160, -1.1357,  ...,  0.8146, -1.1258,  0.4370],
          [ 0.4459, -0.0000,  0.6194,  ...,  2.5831,  0.0535, -0.3247],
          [ 1.7692, -2.5958,  1.2576,  ...,  1.5342,  0.4727, -0.7132],
          ...,
          [ 0.1576, -2.7135, -0.2974,  ...,  1.5616,  0.5229, -0.6380],
          [-1.8427, -2.3461, -0.9518,  ...,  0.5105, -0.1308,  0.0000],
          [-0.0000,  1.9962, -1.1940,  ...,  0.2689,  0.2973,  0.8023]]],
        device='cuda:0', grad_fn=<NativeDropoutBackward0>))

In [15]:
summary(emb)

=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
Embed                                    --
├─Embedding: 1-1                         76,800
├─PositionalEncoding: 1-2                --
│    └─Dropout: 2-1                      --
├─Sequential: 1-3                        --
│    └─LayerNorm: 2-2                    1,536
│    └─Dropout: 2-3                      --
=================================================================
Total params: 78,336
Trainable params: 78,336
Non-trainable params: 0
=================================================================

In [16]:
def att_mask(attention_mask, lookahead, cross_att, x=None):
    if cross_att:
        batch_dim = x[0]
        repeat = x[1]
    else:
        batch_dim = attention_mask.shape[0]
        repeat = len(attention_mask[0])

    mask =[]
    for i in range(batch_dim):
        am_interim = [attention_mask[i].tolist()] * repeat
        am_interim = torch.tensor(am_interim).unsqueeze(0)
        mask.append(am_interim)
    mask = torch.vstack(mask)
    if lookahead:
        inp_save = mask
        mask = torch.tril(torch.ones(mask.shape))
    mask = torch.where(mask == 0, -torch.inf, 0.0)
    return mask

In [17]:
attention_mask = torch.tensor([[1,1,1,1,0,0], [1,1,1,0,0,0]])
attention_mask.shape

torch.Size([2, 6])

In [18]:
mask  = att_mask(attention_mask, lookahead=False, cross_att=False, x=[2,9,6])

In [19]:
mask, mask.shape

(tensor([[[0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., -inf, -inf]],

         [[0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf]]]),
 torch.Size([2, 6, 6]))

In [20]:
class Attention(nn.Module):
    def __init__(self, embed_dim, k_dim, do, device):
        super().__init__()
        self.embed_dim = embed_dim
        self.k_dim = k_dim
        self.query = nn.Linear(embed_dim, k_dim)
        self.key = nn.Linear(embed_dim, k_dim)
        self.value = nn.Linear(embed_dim, k_dim)
        self.att_do = nn.Dropout(do)
        self.device = device

    def forward(self, qry, ky, vlu, mask):
        q = self.query(qry)
        k = self.key(ky)
        v = self.value(vlu)
        qk = (q@k.transpose(1, 2))/(self.k_dim**0.5)
        mask = mask.to(self.device)
        qk_m = qk + mask
        qk_m_smax = torch.softmax(qk_m, dim=-1)
        qk_m_smax_do = self.att_do(qk_m_smax)
        qkv = qk_m_smax_do@v
        return qkv

In [21]:
class Attention_Block(nn.Module):
    def __init__(self, num_heads, embed_dim, k_dim, do, device):
        super().__init__()
        self.num_heads = num_heads
        self.heads_list = [Attention(embed_dim, k_dim, do, device) for i in range(num_heads)]
        self.heads = nn.ModuleList(self.heads_list)
        self.lin_do = nn.Sequential(
            nn.Linear(embed_dim, embed_dim),
            nn.Dropout(do)
        )

    def forward(self, q, k, v, mask):
        heads_list_out = [head(q, k, v, mask) for head in self.heads]
        att_head = torch.cat(heads_list_out, dim=-1)
        att_head_out = self.lin_do(att_head)
        return att_head_out

In [22]:
class Encoder_Block(nn.Module):
    def __init__(self, num_heads, embed_dim, k_dim, do, device):
        super().__init__()
        self.MHA = Attention_Block(num_heads, embed_dim, k_dim, do, device)
        self.mha_blk_end_layernorm = nn.LayerNorm(embed_dim)
        self.ff = nn.Sequential(
            nn.Linear(embed_dim, embed_dim*4),
            nn.GELU(),
            nn.Linear(embed_dim*4, embed_dim),
            nn.Dropout(do)
            )
        self.enc_blk_end_layernorm = nn.LayerNorm(embed_dim)

    def forward(self, args_list):  #q, k, v, mask):
        x = args_list[0]
        mask = args_list[1]

        inp_start_att_block = x
        x = self.MHA(x, x, x, mask)

        x = x + inp_start_att_block
        x = self.mha_blk_end_layernorm(x)

        inp_start_ff_block = x
        x = self.ff(x)

        x = x + inp_start_ff_block
        x = self.enc_blk_end_layernorm(x)
        return [x, mask]

In [23]:
class Encoder(nn.Module):
    def __init__(self, num_layers, num_heads, vocab_size, embed_dim, k_dim, ctx_len, do, device):
        super().__init__()
        self.emb = Embed(vocab_size, embed_dim, ctx_len, do, device)
        self.layer_list = [Encoder_Block(num_heads, embed_dim, k_dim, do, device) for i in range(num_layers)]
        self.layers = nn.Sequential(*self.layer_list)

    def forward(self, input_ids, attention_mask):
        x = self.emb(input_ids)
        mask = att_mask(attention_mask, lookahead=False, cross_att=False, x=None)
        x = self.layers([x, mask])
        return x[0]

In [24]:
enc = Encoder(3, 6, 100, 768, 128, 100, 0.1, device)
enc.to(device)

Encoder(
  (emb): Embed(
    (tok_layer): Embedding(100, 768)
    (pos_layer): PositionalEncoding(
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (norm_do): Sequential(
      (0): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (1): Dropout(p=0.1, inplace=False)
    )
  )
  (layers): Sequential(
    (0): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (1): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (2): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-5): 6 x Attention(
            (query): Linear(in_features=768, out_features=128, bias=True)
            (key): Linear(in_features=768, out_features=128, bias=True)
            (value): Linear(in_features=768, out_features=128, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=768, out_features=768, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=768, out_features=3072, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=3072, out_features=768, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
  )
)

In [25]:
summary(enc)

======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
Encoder                                       --
├─Embed: 1-1                                  --
│    └─Embedding: 2-1                         76,800
│    └─PositionalEncoding: 2-2                --
│    │    └─Dropout: 3-1                      --
│    └─Sequential: 2-3                        --
│    │    └─LayerNorm: 3-2                    1,536
│    │    └─Dropout: 3-3                      --
├─Sequential: 1-2                             --
│    └─Encoder_Block: 2-4                     --
│    │    └─Attention_Block: 3-4              2,362,368
│    │    └─LayerNorm: 3-5                    1,536
│    │    └─Sequential: 3-6                   4,722,432
│    │    └─LayerNorm: 3-7                    1,536
│    └─Encoder_Block: 2-5                     --
│    │    └─Attention_Block: 3-8              2,362,368
│    │    └─LayerNorm: 3-9                    1,536
│    │    └─Sequential: 3-10                  4,722,432
│    │    └─LayerNorm: 3-11                   1,536
│    └─Encoder_Block: 2-6                     --
│    │    └─Attention_Block: 3-12             2,362,368
│    │    └─LayerNorm: 3-13                   1,536
│    │    └─Sequential: 3-14                  4,722,432
│    │    └─LayerNorm: 3-15                   1,536
======================================================================
Total params: 21,341,952
Trainable params: 21,341,952
Non-trainable params: 0
======================================================================

In [26]:
inp = torch.randint(1,100, (4,6))
am = torch.ones(inp.shape)
inp.shape, am.shape

(torch.Size([4, 6]), torch.Size([4, 6]))

In [27]:
out = enc(inp.to(device), am.to(device))
out.shape

torch.Size([4, 6, 768])

In [28]:
class MLM(nn.Module):
    def __init__(self, enc, embed_dim, vocab_size):
        super().__init__()

        self.encoder = enc
        self.mlm_layer = nn.Linear(embed_dim, vocab_size)

    def forward(self, input_ids, attention_mask):
        x = self.encoder(input_ids, attention_mask)
        x = self.mlm_layer(x)
        return x

In [29]:
model_mlm = MLM(enc, 768, 36000)
model_mlm.to(device)

MLM(
  (encoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(100, 768)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-5): 6 x Attention(
              (query): Linear(in_features=768, out_features=128, bias=True)
              (key): Linear(in_features=768, out_features=128, bias=True)
              (value): Linear(in_features=768, out_features=128, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=768, out_features=768, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=3072, out_features=768, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (mlm_layer): Linear(in_features=768, out_features=36000, bias=True)
)

In [30]:
summary(model_mlm)

===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
MLM                                                --
├─Encoder: 1-1                                     --
│    └─Embed: 2-1                                  --
│    │    └─Embedding: 3-1                         76,800
│    │    └─PositionalEncoding: 3-2                --
│    │    └─Sequential: 3-3                        1,536
│    └─Sequential: 2-2                             --
│    │    └─Encoder_Block: 3-4                     7,087,872
│    │    └─Encoder_Block: 3-5                     7,087,872
│    │    └─Encoder_Block: 3-6                     7,087,872
├─Linear: 1-2                                      27,684,000
===========================================================================
Total params: 49,025,952
Trainable params: 49,025,952
Non-trainable params: 0
===========================================================================

In [31]:
out = model_mlm(inp.to(device), am.to(device))
out, out.shape

(tensor([[[ 0.8798, -0.3187, -0.1912,  ...,  0.2267, -0.3346,  0.3053],
          [-0.2505, -0.2263, -0.7480,  ...,  0.2541, -0.5820,  0.7315],
          [ 0.5601, -0.4758,  0.4796,  ..., -1.0208,  0.6172, -0.5813],
          [-0.3299, -0.0785,  0.7356,  ..., -0.2092, -0.1876,  0.2377],
          [-0.0550, -0.1602,  0.9643,  ..., -0.9650,  0.4905, -0.6751],
          [ 0.0243,  0.4226, -0.1921,  ...,  0.0827,  0.5370,  0.2664]],

         [[ 0.3910, -0.2775, -0.4450,  ..., -0.4903, -0.1943, -0.5139],
          [ 0.8744,  0.3310, -0.4308,  ..., -1.2726,  0.4207, -0.1840],
          [ 0.3096,  0.5121, -0.0451,  ..., -0.3066, -0.9303,  0.7152],
          [-0.6294, -0.5274,  0.0231,  ..., -0.4083,  0.4094, -1.0037],
          [-0.7904, -0.0071,  0.8717,  ...,  0.4376, -0.9116,  0.5157],
          [ 0.1486, -0.7271,  0.1699,  ..., -0.5983,  0.0058,  0.2841]],

         [[-0.0304, -0.3606, -0.3690,  ..., -0.0623, -0.8899,  0.2064],
          [ 0.4639, -0.7311, -1.0043,  ..., -0.5891,  0.1788, -0.6296],
          [-0.3833, -0.4098,  0.1315,  ...,  0.2764,  0.3729,  0.6662],
          [ 0.1095,  0.2359, -0.3214,  ..., -0.4843,  0.2787, -0.1474],
          [-0.5623, -0.7643, -0.1609,  ..., -0.1699,  0.0491, -1.0519],
          [ 0.0928, -0.2601, -0.1542,  ..., -0.2966, -1.1093,  0.5159]],

         [[-0.0470,  0.5254, -0.0087,  ..., -0.6955, -0.0696, -0.6519],
          [ 0.3547,  0.4989,  0.1766,  ...,  0.5959,  0.1400, -0.3190],
          [ 1.1337, -0.9154,  0.8535,  ...,  0.5831, -0.2767, -1.3673],
          [ 0.7726, -0.5712,  0.0474,  ...,  0.3493, -0.1450,  0.0642],
          [-0.2215,  0.6304,  0.8330,  ..., -0.6482, -0.1871, -1.2870],
          [ 0.5632,  0.4533,  0.0027,  ...,  0.4228, -0.1039, -0.4735]]],
        device='cuda:0', grad_fn=<ViewBackward0>),
 torch.Size([4, 6, 36000]))

In [32]:
from datasets import load_dataset

In [35]:
ds_name = 'fancyzhx/ag_news'
ds = load_dataset(ds_name)

README.md:   0%|          | 0.00/8.07k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/18.6M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/120000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/7600 [00:00<?, ? examples/s]

In [36]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 120000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 7600
    })
})

In [37]:
df_train = ds['train'].to_pandas()

In [38]:
df_test = ds['test'].to_pandas()

In [39]:
df_train.to_csv('./agnews_train', index=False)
df_test.to_csv('./agnews_test', index=False)

In [40]:
%pwd

'/home/ec2-user/SageMaker/EncoderTasks'

In [41]:
!ls -ltrh ./agnews*

-rw-rw-r-- 1 ec2-user ec2-user  28M Mar 23 05:33 ./agnews_train
-rw-rw-r-- 1 ec2-user ec2-user 1.8M Mar 23 05:33 ./agnews_test

In [42]:
tok_ckpt = 'bert-base-uncased'
orig_tokenizer = AutoTokenizer.from_pretrained(tok_ckpt)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [43]:
orig_tokenizer

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [44]:
df_train.columns, df_test.columns

(Index(['text', 'label'], dtype='object'),
 Index(['text', 'label'], dtype='object'))

In [45]:
df = pd.concat([df_train, df_test], axis=0)
df

                                                   text  label
0     Wall St. Bears Claw Back Into the Black (Reute...      2
1     Carlyle Looks Toward Commercial Aerospace (Reu...      2
2     Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3     Iraq Halts Oil Exports from Main Southern Pipe...      2
4     Oil prices soar to all-time record, posing new...      2
...                                                 ...    ...
7595  Around the world Ukrainian presidential candid...      0
7596  Void is filled with Clement With the supply of...      1
7597  Martinez leaves bitter Like Roger Clemens did ...      1
7598  5 of arthritis patients in Singapore take Bext...      2
7599  EBay gets into rentals EBay plans to buy the a...      2

[127600 rows x 2 columns]

In [46]:
text_list = df['text'].tolist()

In [47]:
len(text_list)

127600

In [48]:
text_list[:2]

["Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again.",
 'Carlyle Looks Toward Commercial Aerospace (Reuters) Reuters - Private investment firm Carlyle Group,\\which has a reputation for making well-timed and occasionally\\controversial plays in the defense industry, has quietly placed\\its bets on another part of the market.']

In [49]:
text_list[3]

'Iraq Halts Oil Exports from Main Southern Pipeline (Reuters) Reuters - Authorities have halted oil export\\flows from the main pipeline in southern Iraq after\\intelligence showed a rebel militia could strike\\infrastructure, an oil official said on Saturday.'

In [50]:
unq_words = sorted(list(set([w.lower() for t in text_list for w in t.split()])))

In [51]:
len(unq_words)

163946

In [52]:
text_gen = (text_list[i:i+1000] for i in range(0, len(text_list), 1000))

In [53]:
text_gen

In [54]:
news_tokenizer = orig_tokenizer.train_new_from_iterator(text_gen, 9000) #vocab size of 9000

In [55]:
len(orig_tokenizer.tokenize(text_list[0]))

39

In [56]:
len(news_tokenizer.tokenize(text_list[0]))

42

In [57]:
news_tokenizer

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=9000, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [59]:
news_tokenizer.save_pretrained("./agnews_tokenizer")

('./agnews_tokenizer/tokenizer_config.json',
 './agnews_tokenizer/special_tokens_map.json',
 './agnews_tokenizer/vocab.txt',
 './agnews_tokenizer/added_tokens.json',
 './agnews_tokenizer/tokenizer.json')

In [56]:
#we placed a limit on vocab size to make model size small so that we can train easy peasy

In [57]:
df['text_len'] = df['text'].apply(lambda x: len(x))

In [58]:
df.describe()

               label       text_len
count  127600.000000  127600.000000
mean        1.500000     236.407343
std         1.118038      66.438756
min         0.000000     100.000000
25%         0.750000     196.000000
50%         1.500000     232.000000
75%         2.250000     266.000000
max         3.000000    1012.000000

In [59]:
class NEWS_DS(Dataset):
    def __init__(self, df):
        self.data = df['text']

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        data = self.data.iloc[idx]
        return data

In [60]:
news_ds = NEWS_DS(df)

In [61]:
len(news_ds)

127600

In [62]:
news_ds[2]

"Oil and Economy Cloud Stocks' Outlook (Reuters) Reuters - Soaring crude prices plus worries\\about the economy and the outlook for earnings are expected to\\hang over the stock market next week during the depth of the\\summer doldrums."

In [63]:
news_tokenizer.encode(news_tokenizer.mask_token)

[2, 4, 3]

In [64]:
orig_tokenizer.encode(news_tokenizer.mask_token)

[101, 103, 102]

In [65]:
def bernoulli_true_false(p):
    # Create a Bernoulli distribution with probability p
    bernoulli_dist = torch.distributions.Bernoulli(torch.tensor([p]))
    # Sample from this distribution and convert 1 to True and 0 to False
    return bernoulli_dist.sample().item() == 1

In [66]:
torch.randint(0, 9000, size=(1,)).item() #.squeeze().item()

3843

In [67]:
def Masking(token, vocab_size):
    # Decide whether to mask this token (15% chance)
    mask = bernoulli_true_false(0.15)

    # If mask is False, immediately return with '[PAD]' label
    if not mask:
        status = "nomask"
        return token, '[PAD]', status

    # If mask is True, proceed with further operations
    # Randomly decide on an operation (10% chance each)
    replace_random = bernoulli_true_false(0.1)
    leave_as_is = bernoulli_true_false(0.1)
    if replace_random:
        _token = torch.randint(0, vocab_size, size=(1,)).item()
        label = token
        status = "random"
    elif leave_as_is:
        _token = token
        label = token
        status = "asis"
    else:
        _token = '[MASK]'
        label = token
        status = "masked"
        
    return _token, label, status

In [68]:
vocab_size = news_tokenizer.vocab_size
vocab_size

9000

In [69]:
text_list[3]

'Iraq Halts Oil Exports from Main Southern Pipeline (Reuters) Reuters - Authorities have halted oil export\\flows from the main pipeline in southern Iraq after\\intelligence showed a rebel militia could strike\\infrastructure, an oil official said on Saturday.'

In [70]:
news_tokenizer(text_list[3], max_length=256, truncation=True)

{'input_ids': [2, 366, 4363, 70, 426, 4198, 241, 1459, 1823, 5900, 11, 231, 12, 231, 15, 2474, 310, 4363, 104, 426, 5669, 32, 7206, 70, 241, 102, 1459, 5900, 108, 1823, 366, 264, 32, 3596, 2189, 34, 2280, 5430, 592, 1746, 32, 6156, 14, 117, 426, 560, 221, 131, 696, 16, 3], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [71]:
inp = news_tokenizer(text_list[:8]).input_ids
inp

[[2,
  1405,
  134,
  16,
  3934,
  267,
  1104,
  523,
  469,
  102,
  1741,
  11,
  231,
  12,
  231,
  15,
  1551,
  15,
  1066,
  148,
  14,
  1405,
  1456,
  10,
  52,
  6859,
  1187,
  900,
  32,
  4083,
  115,
  5665,
  161,
  15,
  1997,
  6516,
  70,
  14,
  318,
  7661,
  1900,
  381,
  16,
  3],
 [2,
  3668,
  3199,
  2858,
  2057,
  2990,
  8081,
  11,
  231,
  12,
  231,
  15,
  2587,
  2364,
  1286,
  3668,
  3199,
  563,
  14,
  32,
  637,
  230,
  34,
  8389,
  135,
  1739,
  1570,
  15,
  552,
  74,
  132,
  3492,
  5278,
  702,
  32,
  3692,
  4694,
  108,
  102,
  1785,
  1076,
  14,
  230,
  7555,
  4970,
  32,
  209,
  1291,
  70,
  131,
  1009,
  581,
  115,
  102,
  667,
  16,
  3],
 [2,
  426,
  132,
  1414,
  7159,
  605,
  10,
  2279,
  11,
  231,
  12,
  231,
  15,
  5225,
  1647,
  607,
  4322,
  3287,
  32,
  488,
  102,
  1414,
  132,
  102,
  2279,
  135,
  1197,
  318,
  947,
  111,
  32,
  5097,
  275,
  102,
  1089,
  667,
  598,
  458,
  1050,
  102,
  869,
  158,
  115,
  102,
  32,
  3041,
  680,
  193,
  8317,
  70,
  16,
  3],
 [2,
  366,
  4363,
  70,
  426,
  4198,
  241,
  1459,
  1823,
  5900,
  11,
  231,
  12,
  231,
  15,
  2474,
  310,
  4363,
  104,
  426,
  5669,
  32,
  7206,
  70,
  241,
  102,
  1459,
  5900,
  108,
  1823,
  366,
  264,
  32,
  3596,
  2189,
  34,
  2280,
  5430,
  592,
  1746,
  32,
  6156,
  14,
  117,
  426,
  560,
  221,
  131,
  696,
  16,
  3],
 [2,
  426,
  607,
  8241,
  111,
  434,
  15,
  552,
  646,
  14,
  1596,
  109,
  186,
  1499,
  297,
  111,
  219,
  1414,
  11,
  641,
  12,
  641,
  15,
  7637,
  6929,
  361,
  426,
  607,
  14,
  8138,
  900,
  4182,
  132,
  1375,
  5292,
  1405,
  401,
  14,
  5702,
  34,
  186,
  1438,
  1499,
  297,
  6806,
  514,
  1269,
  868,
  102,
  219,
  1509,
  1874,
  16,
  3],
 [2,
  605,
  515,
  252,
  14,
  357,
  742,
  271,
  4891,
  11,
  231,
  12,
  231,
  15,
  605,
  2344,
  3441,
  1163,
  131,
  462,
  32,
  357,
  8213,
  742,
  4891,
  135,
  102,
  271,
  162,
  426,
  607,
  5060,
  1401,
  7,
  1466,
  29,
  5153,
  32,
  34,
  2115,
  14,
  5629,
  611,
  34,
  3910,
  2279,
  241,
  857,
  1023,
  32,
  2409,
  283,
  16,
  11,
  2409,
  16,
  48,
  12,
  3],
 [2,
  1979,
  3131,
  1458,
  108,
  1330,
  458,
  11,
  189,
  12,
  189,
  15,
  4159,
  115,
  102,
  1313,
  10,
  52,
  1229,
  1979,
  667,
  4583,
  3131,
  1458,
  217,
  7,
  1466,
  29,
  19,
  16,
  1514,
  734,
  108,
  102,
  1330,
  458,
  111,
  7,
  1466,
  29,
  5850,
  95,
  16,
  8548,
  715,
  2446,
  120,
  14,
  102,
  2364,
  417,
  6292,
  221,
  438,
  16,
  3],
 [2,
  712,
  3246,
  878,
  6204,
  133,
  275,
  3375,
  11,
  4833,
  16,
  160,
  12,
  4833,
  16,
  160,
  15,
  1229,
  727,
  8745,
  74,
  523,
  34,
  2812,
  108,
  3231,
  14,
  132,
  186,
  1916,
  135,
  5377,
  4103,
  1458,
  472,
  458,
  14,
  102,
  587,
  221,
  438,
  14,
  3918,
  602,
  102,
  1414,
  174,
  5464,
  241,
  34,
  8636,
  223,
  454,
  6672,
  16,
  3]]

In [72]:
inp_mask  = [Masking(i, vocab_size) for il in inp for i in il]
len(inp_mask)

429

In [73]:
no_mask = 0
masked = 0
random = 0
asis = 0
for i, t, s in inp_mask:
    if s == "nomask":
        no_mask+=1
    elif s == 'masked':
        masked+=1
    elif s == "random":
        random+=1
    else:
        asis+=1

In [74]:
no_mask, masked, random, asis

(366, 53, 3, 7)

In [75]:
429*0.15

64.35

In [76]:
429*0.15*0.8

51.48

In [77]:
429*0.15*0.1

6.435

In [78]:
#so masking is woring good

In [79]:
class NEWS_DS(Dataset):
    def __init__(self, df):
        self.data = df['text']

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text = self.data.iloc[idx]
        return text

In [80]:
news_tokenizer.vocab['[MASK]'], news_tokenizer.vocab['[PAD]']

(4, 0)

In [81]:
def Masking(token, vocab_size):
    # Decide whether to mask this token (15% chance)
    mask = bernoulli_true_false(0.15)

    # If mask is False, immediately return with '[PAD]' label
    if not mask:
        return token, -100

    # If mask is True, proceed with further operations
    # Randomly decide on an operation (10% chance each)
    replace_random = bernoulli_true_false(0.1)
    leave_as_is = bernoulli_true_false(0.1)
    label = token
    if replace_random:
        _token = torch.randint(0, vocab_size, size=(1,)).item()
    elif leave_as_is:
        _token = token
    else:
        _token = 4

    return _token, label

In [82]:
news_tokenizer.vocab[news_tokenizer.pad_token], news_tokenizer.vocab[news_tokenizer.mask_token]

(0, 4)

In [83]:
pad_tokenid = [news_tokenizer.vocab[news_tokenizer.pad_token]]
type(pad_tokenid[0])

int

In [84]:
def collate_fn(batch, tokenizer):
    vocab_size = tokenizer.vocab_size
    pad_tokenid = [tokenizer.vocab[news_tokenizer.pad_token]]
    ignore_loss_id = [-100]  #ignore loss
    ignore_token_id = [0]   #attention mask filler
    x_input_ids, x_am = [], []
    lab_list = []

    for x in batch:
        tokenized = tokenizer(x, max_length=256, truncation=True)
        inp_ids = []
        label_list = []
        for x in tokenized.input_ids:
            tok, lbl = Masking(x, vocab_size)
            inp_ids.append(tok)
            label_list.append(lbl)
        am = tokenized.attention_mask
        x_input_ids.append(inp_ids)
        x_am.append(am)
        lab_list.append(label_list)

    len_enc = [len(l) for l in x_input_ids]
    max_len = max(len_enc)

    def pad_tokens_stack(in_list, max_len, padding):
        list_tensor = []
        for item in in_list:
            len_item = len(item)
            deficit = max_len - len_item
            if deficit > 0:
                item = item + padding*deficit
            list_tensor.append(torch.tensor(item))
        item_ids = torch.vstack(list_tensor)
        return item_ids

    input_ids = pad_tokens_stack(x_input_ids, max_len, pad_tokenid)
    attention_mask = pad_tokens_stack(x_am, max_len, ignore_token_id)
    labels =  pad_tokens_stack(lab_list, max_len, ignore_loss_id)

    return {'input_ids': input_ids, 'attention_mask': attention_mask}, labels

In [85]:
train_ds = NEWS_DS(df_train)
test_ds = NEWS_DS(df_test)

In [86]:
len(train_ds), len(test_ds)

(120000, 7600)

In [87]:
torch.cuda.empty_cache()

In [88]:
from functools import partial
import os
wrapper_collate_fn = partial(
    collate_fn,
    tokenizer=news_tokenizer,
    )

train_dl = DataLoader(train_ds, shuffle=False, batch_size=128,
                      num_workers=os.cpu_count(), collate_fn=wrapper_collate_fn)
test_dl = DataLoader(test_ds, shuffle=False, batch_size=128,
                      num_workers=os.cpu_count(), collate_fn=wrapper_collate_fn)

In [89]:
train_iter = iter(train_dl)

In [90]:
i, l = next(train_iter)

In [91]:
unravel = [t for i in l.tolist() for t in i]

In [92]:
len(unravel)

16256

In [93]:
valid_items = [i for i in unravel if i > -100]
valid_items

[16,
 267,
 1066,
 1405,
 32,
 1997,
 7661,
 1900,
 381,
 2858,
 3668,
 563,
 8389,
 16,
 2,
 132,
 231,
 5225,
 1647,
 16,
 2,
 231,
 32,
 70,
 16,
 607,
 111,
 15,
 1375,
 5702,
 1269,
 1509,
 1874,
 2344,
 742,
 271,
 2409,
 3,
 1313,
 217,
 1330,
 712,
 160,
 727,
 108,
 186,
 135,
 221,
 6672,
 160,
 34,
 16,
 37,
 16,
 51,
 102,
 1356,
 6529,
 1286,
 14,
 34,
 6016,
 265,
 2310,
 357,
 3346,
 2310,
 102,
 2165,
 241,
 16,
 3,
 11,
 14,
 4083,
 6516,
 70,
 1900,
 426,
 275,
 193,
 135,
 3474,
 1233,
 12,
 2246,
 16,
 660,
 8229,
 221,
 696,
 607,
 3266,
 3776,
 69,
 4265,
 14,
 1384,
 769,
 102,
 981,
 283,
 2186,
 240,
 462,
 264,
 102,
 5942,
 5197,
 496,
 11,
 102,
 6862,
 131,
 34,
 54,
 16,
 108,
 6678,
 5534,
 111,
 1014,
 2624,
 1312,
 7996,
 325,
 1587,
 168,
 15,
 15,
 34,
 581,
 115,
 523,
 410,
 1038,
 667,
 1263,
 357,
 4583,
 3131,
 484,
 10,
 504,
 1642,
 175,
 3,
 102,
 219,
 646,
 8,
 3081,
 162,
 1843,
 14,
 1510,
 34,
 892,
 4045,
 102,
 723,
 10,
 209,
 3292,
 1313,
 207,
 108,
 271,
 3,
 3938,
 3,
 2,
 3582,
 1885,
 14,
 357,
 2038,
 4258,
 923,
 1583,
 52,
 2015,
 34,
 34,
 2,
 981,
 462,
 981,
 1466,
 1824,
 131,
 2,
 146,
 4244,
 264,
 505,
 14,
 3021,
 884,
 1887,
 403,
 1014,
 159,
 1355,
 458,
 2172,
 436,
 829,
 3823,
 15,
 1503,
 102,
 1156,
 34,
 111,
 363,
 16,
 101,
 14,
 102,
 102,
 107,
 535,
 3783,
 2341,
 34,
 54,
 19,
 4115,
 3023,
 3783,
 6019,
 5972,
 111,
 1459,
 34,
 1818,
 7945,
 16,
 3,
 2,
 162,
 253,
 4508,
 147,
 4294,
 1845,
 286,
 1784,
 960,
 115,
 102,
 417,
 52,
 4770,
 3135,
 592,
 593,
 102,
 16,
 34,
 5757,
 202,
 132,
 1398,
 10,
 132,
 2657,
 102,
 15,
 1484,
 2590,
 1689,
 16,
 10,
 1097,
 16,
 2590,
 108,
 1920,
 1419,
 1689,
 52,
 1082,
 15,
 52,
 16,
 34,
 96,
 34,
 518,
 74,
 111,
 2519,
 110,
 618,
 8815,
 3338,
 2408,
 3460,
 6039,
 5566,
 11,
 10,
 1841,
 14,
 52,
 3077,
 70,
 5176,
 14,
 132,
 15,
 425,
 182,
 102,
 230,
 10,
 311,
 29,
 1509,
 3566,
 575,
 207,
 238,
 2,
 204,
 8716,
 923,
 786,
 135,
 96,
 16,
 2,
 1728,
 34,
 96,
 14,
 14,
 2742,
 1226,
 5637,
 8,
 14,
 108,
 1979,
 5787,
 168,
 16,
 14,
 88,
 5787,
 16,
 2,
 14,
 786,
 5003,
 6516,
 52,
 8460,
 31,
 174,
 15,
 3327,
 230,
 1939,
 175,
 3,
 2,
 109,
 368,
 70,
 4961,
 16,
 4470,
 3766,
 135,
 28,
 218,
 2018,
 7371,
 4267,
 3498,
 6196,
 34,
 2571,
 135,
 597,
 505,
 16,
 7007,
 889,
 889,
 8929,
 52,
 52,
 1542,
 361,
 16,
 733,
 10,
 53,
 337,
 3254,
 6594,
 2303,
 367,
 321,
 1691,
 115,
 129,
 566,
 2718,
 67,
 10,
 409,
 174,
 5662,
 16,
 318,
 201,
 5942,
 1088,
 265,
 102,
 8711,
 28,
 1724,
 2,
 186,
 625,
 6462,
 6311,
 102,
 625,
 667,
 2756,
 251,
 310,
 1614,
 10,
 1008,
 102,
 2222,
 1420,
 484,
 325,
 2035,
 3440,
 3470,
 8804,
 434,
 252,
 2047,
 2389,
 68,
 34,
 14,
 257,
 579,
 70,
 6732,
 3314,
 1413,
 67,
 15,
 10,
 102,
 132,
 2838,
 7019,
 109,
 5198,
 14,
 8262,
 2138,
 70,
 174,
 1570,
 108,
 162,
 3279,
 14,
 104,
 34,
 8362,
 5166,
 629,
 387,
 1124,
 15,
 8725,
 102,
 189,
 2930,
 207,
 52,
 157,
 108,
 3352,
 410,
 108,
 115,
 132,
 1951,
 16,
 102,
 2534,
 8696,
 16,
 34,
 1263,
 2730,
 1176,
 642,
 2930,
 207,
 6797,
 7900,
 99,
 6797,
 819,
 4070,
 5977,
 1655,
 1097,
 67,
 23,
 1412,
 31,
 301,
 5733,
 5733,
 1024,
 131,
 98,
 16,
 2,
 5701,
 5080,
 2129,
 230,
 6247,
 16,
 1787,
 111,
 10,
 2487,
 563,
 3332,
 70,
 2772,
 165,
 6092,
 7453,
 1702,
 104,
 5795,
 132,
 16,
 70,
 14,
 4362,
 15,
 5875,
 1561,
 115,
 34,
 3332,
 54,
 44,
 10,
 5745,
 207,
 6178,
 44,
 52,
 881,
 47,
 12,
 1132,
 1299,
 8952,
 32,
 2069,
 440,
 981,
 1212,
 1938,
 981,
 8636,
 209,
 14,
 286,
 4436,
 102,
 5645,
 573,
 367,
 3292,
 3829,
 15,
 108,
 417,
 7525,
 4354,
 1245,
 612,
 28,
 508,
 2662,
 5946,
 28,
 1801,
 2509,
 16,
 2176,
 3943,
 14,
 1940,
 102,
 14,
 1801,
 73,
 3,
 1136,
 34,
 16,
 102,
 2772,
 10,
 207,
 4458,
 8563,
 31,
 2228,
 115,
 12,
 1325,
 1817,
 601,
 3620,
 2723,
 2297,
 14,
 2513,
 32,
 740,
 8501,
 440,
 2,
 1732,
 563,
 283,
 16,
 12,
 134,
 65,
 16,
 1473,
 1305,
 48,
 5335,
 111,
 2952,
 111,
 111,
 4809,
 207,
 15,
 3957,
 271,
 563,
 34,
 70,
 2135,
 1137,
 2513,
 1033,
 34,
 6,
 492,
 1022,
 4305,
 2315,
 2611,
 102,
 52,
 11,
 12,
 8911,
 7793,
 3294,
 70,
 1044,
 12,
 231,
 16,
 3,
 4689,
 7546,
 727,
 2125,
 1392,
 727,
 637,
 70,
 1955,
 1017,
 15,
 2967,
 135,
 1079,
 1227,
 16,
 3,
 16,
 6933,
 52,
 12,
 2189,
 111,
 397,
 190,
 81,
 189,
 102,
 238,
 6090,
 111,
 5592,
 102,
 166,
 2275,
 189,
 15,
 1314,
 783,
 2275,
 1838,
 845,
 872,
 14,
 560,
 2964,
 1104,
 12,
 15,
 102,
 1786,
 801,
 7458,
 217,
 7733,
 16,
 2,
 1136,
 231,
 69,
 5156,
 1703,
 4059,
 5073,
 6,
 14,
 6,
 131,
 2071,
 469,
 5222,
 15,
 1681,
 231,
 649,
 1226,
 32,
 8363,
 16,
 2590,
 310,
 231,
 32,
 1629,
 492,
 108,
 34,
 5426,
 221,
 750,
 1646,
 231,
 12,
 1646,
 131,
 267,
 111,
 168,
 7143,
 106,
 3201,
 117,
 554,
 2590,
 182,
 4899,
 111,
 1825,
 32,
 217,
 34,
 2,
 886,
 16,
 16,
 15,
 1427,
 2068,
 5580,
 4579,
 2124,
 592,
 162,
 395,
 7896,
 7540,
 160,
 15,
 469,
 438,
 1930,
 878,
 168,
 115,
 16,
 2365,
 12,
 160,
 1056,
 115,
 7487,
 3648,
 6200,
 47,
 2222,
 16,
 131,
 70,
 400,
 14,
 230,
 779,
 332,
 224,
 2381,
 10,
 183,
 104,
 3,
 803,
 28,
 10,
 7382,
 886,
 7993,
 5766,
 7382,
 34,
 139,
 151,
 963,
 886,
 12,
 886,
 15,
 139,
 70,
 444,
 14,
 325,
 140,
 168,
 1763,
 1741,
 6555,
 115,
 975,
 1282,
 3626,
 3348,
 4867,
 886,
 16,
 160,
 15,
 102,
 2172,
 111,
 7435,
 3,
 2,
 104,
 189,
 12,
 4652,
 1867,
 14,
 16,
 1201,
 637,
 1995,
 4641,
 7098,
 168,
 127,
 131,
 207,
 2,
 186,
 4499,
 726,
 132,
 310,
 6240,
 2696,
 182,
 2987,
 52,
 1513,
 16,
 1193,
 659,
 189,
 1431,
 3088,
 270,
 70,
 1067,
 108,
 1377,
 3626,
 6084,
 8098,
 1608,
 81,
 4231,
 10,
 878,
 7540,
 70,
 12,
 15,
 318,
 1595,
 2693,
 7896,
 14,
 4391,
 188,
 108,
 189,
 8813,
 108,
 34,
 7086,
 131,
 221,
 438,
 16,
 2,
 627,
 1086,
 5250,
 108,
 15,
 1086,
 104,
 552,
 913,
 68,
 111,
 52,
 832,
 16,
 16,
 160,
 16,
 160,
 3541,
 318,
 3427,
 81,
 15,
 34,
 1886,
 313,
 7,
 592,
 174,
 3,
 70,
 ...]

In [94]:
len(valid_items)

1116

In [95]:
16256*.15

2438.4

In [96]:
# so this is all good. next we need to train hte model

In [97]:
from torch.optim import AdamW

In [114]:
def train_model(num_epochs, lrate, model, dl, device, vocab_size):
    epochs = num_epochs
    lr = lrate
    fn_loss = nn.CrossEntropyLoss()
    optimizer = AdamW(model.parameters(), lr=lr)
    grad_accum_steps = 1 #args.grad_accum_steps # 4 - previous static value
    model = model.to(device)

    for i in range(epochs):
        loss_epoch = 0
        n_step = 0
        grad_accum_counter = 1

        for inputs in dl:
            data = inputs[0]
            label = inputs[1]
            batch_size = label.shape[0]
            ctx_size = label.shape[1]
            data = {i: k.to(device) for i, k in data.items()}
            label = label.to(device)
            out = model(**data)
            out = out.view(batch_size * ctx_size, vocab_size)
            label = label.view(batch_size * ctx_size)
            loss = fn_loss(out, label)
            loss = loss / grad_accum_steps
            loss.backward()
            if grad_accum_counter == grad_accum_steps:
                #logger.info(f'Steps: {grad_accum_counter}, adjusting learnable params now')
                optimizer.step()
                optimizer.zero_grad()
                grad_accum_counter = 0
            loss_epoch = loss_epoch + (loss.item() * batch_size * grad_accum_steps)
            if n_step % 100 == 0:
                print(f'Step: {n_step}, Loss: {loss.item()}')
            grad_accum_counter += 1
            n_step += 1
            ##update so that if remaining dataloader runs are less than grad accum steps then at the last run i should
            #gradient update
            #print(f'Completed minibatch loop')
        average_loss = loss_epoch/len(dl.dataset)
        perplexity = math.exp(average_loss) 
        print(f'Epoch: {i} -- Average loss: {average_loss}')
        print(f'Epoch: {i} -- Perplexity: {perplexity}')

    return model, optimizer, average_loss, perplexity

In [99]:
vocab_size = news_tokenizer.vocab_size
vocab_size

9000

In [100]:
BroEncoder = Encoder(num_layers=6, num_heads=8, vocab_size=vocab_size, 
                     embed_dim=256, k_dim=32, ctx_len=256, do=0.1, device=device)

In [101]:
BroEncoder

Encoder(
  (emb): Embed(
    (tok_layer): Embedding(9000, 256)
    (pos_layer): PositionalEncoding(
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (norm_do): Sequential(
      (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (1): Dropout(p=0.1, inplace=False)
    )
  )
  (layers): Sequential(
    (0): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-7): 8 x Attention(
            (query): Linear(in_features=256, out_features=32, bias=True)
            (key): Linear(in_features=256, out_features=32, bias=True)
            (value): Linear(in_features=256, out_features=32, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=256, out_features=1024, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=1024, out_features=256, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
    (1): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-7): 8 x Attention(
            (query): Linear(in_features=256, out_features=32, bias=True)
            (key): Linear(in_features=256, out_features=32, bias=True)
            (value): Linear(in_features=256, out_features=32, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=256, out_features=1024, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=1024, out_features=256, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
    (2): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-7): 8 x Attention(
            (query): Linear(in_features=256, out_features=32, bias=True)
            (key): Linear(in_features=256, out_features=32, bias=True)
            (value): Linear(in_features=256, out_features=32, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=256, out_features=1024, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=1024, out_features=256, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
    (3): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-7): 8 x Attention(
            (query): Linear(in_features=256, out_features=32, bias=True)
            (key): Linear(in_features=256, out_features=32, bias=True)
            (value): Linear(in_features=256, out_features=32, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=256, out_features=1024, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=1024, out_features=256, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
    (4): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-7): 8 x Attention(
            (query): Linear(in_features=256, out_features=32, bias=True)
            (key): Linear(in_features=256, out_features=32, bias=True)
            (value): Linear(in_features=256, out_features=32, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=256, out_features=1024, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=1024, out_features=256, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
    (5): Encoder_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-7): 8 x Attention(
            (query): Linear(in_features=256, out_features=32, bias=True)
            (key): Linear(in_features=256, out_features=32, bias=True)
            (value): Linear(in_features=256, out_features=32, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=256, out_features=1024, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=1024, out_features=256, bias=True)
        (3): Dropout(p=0.1, inplace=False)
      )
      (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
  )
)

In [102]:
summary(BroEncoder)

======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
Encoder                                       --
├─Embed: 1-1                                  --
│    └─Embedding: 2-1                         2,304,000
│    └─PositionalEncoding: 2-2                --
│    │    └─Dropout: 3-1                      --
│    └─Sequential: 2-3                        --
│    │    └─LayerNorm: 3-2                    512
│    │    └─Dropout: 3-3                      --
├─Sequential: 1-2                             --
│    └─Encoder_Block: 2-4                     --
│    │    └─Attention_Block: 3-4              263,168
│    │    └─LayerNorm: 3-5                    512
│    │    └─Sequential: 3-6                   525,568
│    │    └─LayerNorm: 3-7                    512
│    └─Encoder_Block: 2-5                     --
│    │    └─Attention_Block: 3-8              263,168
│    │    └─LayerNorm: 3-9                    512
│    │    └─Sequential: 3-10                  525,568
│    │    └─LayerNorm: 3-11                   512
│    └─Encoder_Block: 2-6                     --
│    │    └─Attention_Block: 3-12             263,168
│    │    └─LayerNorm: 3-13                   512
│    │    └─Sequential: 3-14                  525,568
│    │    └─LayerNorm: 3-15                   512
│    └─Encoder_Block: 2-7                     --
│    │    └─Attention_Block: 3-16             263,168
│    │    └─LayerNorm: 3-17                   512
│    │    └─Sequential: 3-18                  525,568
│    │    └─LayerNorm: 3-19                   512
│    └─Encoder_Block: 2-8                     --
│    │    └─Attention_Block: 3-20             263,168
│    │    └─LayerNorm: 3-21                   512
│    │    └─Sequential: 3-22                  525,568
│    │    └─LayerNorm: 3-23                   512
│    └─Encoder_Block: 2-9                     --
│    │    └─Attention_Block: 3-24             263,168
│    │    └─LayerNorm: 3-25                   512
│    │    └─Sequential: 3-26                  525,568
│    │    └─LayerNorm: 3-27                   512
======================================================================
Total params: 7,043,072
Trainable params: 7,043,072
Non-trainable params: 0
======================================================================

In [103]:
Bro_MLM = MLM(BroEncoder, 256, vocab_size)
Bro_MLM

MLM(
  (encoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(9000, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (mlm_layer): Linear(in_features=256, out_features=9000, bias=True)
)

In [104]:
summary(Bro_MLM)

===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
MLM                                                --
├─Encoder: 1-1                                     --
│    └─Embed: 2-1                                  --
│    │    └─Embedding: 3-1                         2,304,000
│    │    └─PositionalEncoding: 3-2                --
│    │    └─Sequential: 3-3                        512
│    └─Sequential: 2-2                             --
│    │    └─Encoder_Block: 3-4                     789,760
│    │    └─Encoder_Block: 3-5                     789,760
│    │    └─Encoder_Block: 3-6                     789,760
│    │    └─Encoder_Block: 3-7                     789,760
│    │    └─Encoder_Block: 3-8                     789,760
│    │    └─Encoder_Block: 3-9                     789,760
├─Linear: 1-2                                      2,313,000
===========================================================================
Total params: 9,356,072
Trainable params: 9,356,072
Non-trainable params: 0
===========================================================================

In [ ]:
%%time
model, optimizer, average_loss, perplexity = train_model(10, 0.0004, Bro_MLM, train_dl, device, vocab_size)

Step: 0, Loss: 9.216163635253906

In [106]:
model

MLM(
  (encoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(9000, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (mlm_layer): Linear(in_features=256, out_features=9000, bias=True)
)

In [107]:
torch.save({
        'epoch': 10,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss': average_loss,
        'device': device
        }, './mlmckpt')

In [108]:
average_loss

3.4532971148173015

In [109]:
%pwd

'/home/ec2-user/SageMaker/EncoderTasks'

In [110]:
!ls -ltrh

total 138M
-rw-rw-r-- 1 ec2-user ec2-user  28M Mar 22 10:51 agnews_train
-rw-rw-r-- 1 ec2-user ec2-user 1.8M Mar 22 10:51 agnews_test
-rw-rw-r-- 1 ec2-user ec2-user 108M Mar 22 13:45 mlmckpt
-rw-rw-r-- 1 ec2-user ec2-user 133K Mar 22 13:48 Encoder_MLM.ipynb

In [112]:
device, perplexity

('cuda', 31.60442412716105)

In [115]:
model.eval()
fn_loss = nn.CrossEntropyLoss()
model = model.to(device)
loss_epoch = 0
for inputs in train_dl:
    data = inputs[0]
    label = inputs[1]
    batch_size = label.shape[0]
    ctx_size = label.shape[1]
    data = {i: k.to(device) for i, k in data.items()}
    label = label.to(device)
    with torch.no_grad():
        out = model(**data)
    out = out.view(batch_size * ctx_size, vocab_size)
    label = label.view(batch_size * ctx_size)
    loss = fn_loss(out, label)
    loss_epoch = loss_epoch + (loss.item() * batch_size)
average_loss = loss_epoch/len(train_dl.dataset)
perplexity = math.exp(average_loss) 
print(f'Epoch: {i} -- Average loss: {average_loss}')
print(f'Epoch: {i} -- Perplexity: {perplexity}')

Epoch: {'input_ids': tensor([[   2, 1405,  134,  ...,    0,    0,    0],
        [   2, 3668, 3199,  ...,    0,    0,    0],
        [   4,  426,    4,  ...,    0,    0,    0],
        ...,
        [   2, 1759, 4627,  ...,    0,    0,    0],
        [   4,  102,  598,  ...,    0,    0,    0],
        [   4, 1136,   14,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])} -- Average loss: 3.151042181523641
Epoch: {'input_ids': tensor([[   2, 1405,  134,  ...,    0,    0,    0],
        [   2, 3668, 3199,  ...,    0,    0,    0],
        [   4,  426,    4,  ...,    0,    0,    0],
        ...,
        [   2, 1759, 4627,  ...,    0,    0,    0],
        [   4,  102,  598,  ...,    0,    0,    0],
        [   4, 1136,   14,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])} -- Perplexity: 23.360397673830942

In [116]:
model.eval()
fn_loss = nn.CrossEntropyLoss()
model = model.to(device)
loss_epoch = 0
for inputs in test_dl:
    data = inputs[0]
    label = inputs[1]
    batch_size = label.shape[0]
    ctx_size = label.shape[1]
    data = {i: k.to(device) for i, k in data.items()}
    label = label.to(device)
    with torch.no_grad():
        out = model(**data)
    out = out.view(batch_size * ctx_size, vocab_size)
    label = label.view(batch_size * ctx_size)
    loss = fn_loss(out, label)
    loss_epoch = loss_epoch + (loss.item() * batch_size)
average_loss = loss_epoch/len(train_dl.dataset)
perplexity = math.exp(average_loss) 
print(f'Test Average loss: {average_loss}')
print(f'Test Perplexity: {perplexity}')

Test Average loss: 0.20677252238591512
Test Perplexity: 1.2297028101009242

In [146]:
train_ds[12]

'Non-OPEC Nations Should Up Output-Purnomo  JAKARTA (Reuters) - Non-OPEC oil exporters should consider  increasing output to cool record crude prices, OPEC President  Purnomo Yusgiantoro said on Sunday.'

In [120]:
text = "There is so much of the [MASK] pollution nowadays"
tok = news_tokenizer(text, return_tensors='pt')
input_ids = tok.input_ids.to(device)
attention_mask = tok.attention_mask.to(device)
input_ids.shape, attention_mask.shape
with torch.no_grad():
    out = model(input_ids=input_ids, attention_mask=attention_mask)

In [125]:
input_ids

tensor([[   2, 1038,  174,  492, 1420,  115,  102,    4, 7094,  902, 3273, 2051,
            3]], device='cuda:0')

In [121]:
out.shape

torch.Size([1, 13, 9000])

In [122]:
out_max = torch.argmax(out, dim=-1)
out_max

tensor([[   2, 1038,  174,  492, 1420,  115,  102,  186,  115,  902, 1427, 2051,
            3]], device='cuda:0')

In [129]:
news_tokenizer.decode([out_max[0][7].item()])

'new'

In [130]:
text = "I saw a [MASK] building today"
tok = news_tokenizer(text, return_tensors='pt')
input_ids = tok.input_ids.to(device)
attention_mask = tok.attention_mask.to(device)
input_ids.shape, attention_mask.shape
with torch.no_grad():
    out = model(input_ids=input_ids, attention_mask=attention_mask)

In [131]:
input_ids

tensor([[   2,   42, 3740,   34,    4, 2900,  625,    3]], device='cuda:0')

In [133]:
out_max = torch.argmax(out, dim=-1)
news_tokenizer.decode([out_max[0][4].item()])

'whole'

In [143]:
text = "Oil prices [MASK] to all-time record"
tok = news_tokenizer(text, return_tensors='pt')
input_ids = tok.input_ids.to(device)
mask_index = input_ids[0].tolist().index(4)
attention_mask = tok.attention_mask.to(device)
input_ids.shape, attention_mask.shape
with torch.no_grad():
    out = model(input_ids=input_ids, attention_mask=attention_mask)
out_max = torch.argmax(out, dim=-1)
news_tokenizer.decode([out_max[0][mask_index].item()])

'fall'

In [144]:
text = "Calif. Aims to [MASK] Farm-Related Smog"
tok = news_tokenizer(text, return_tensors='pt')
input_ids = tok.input_ids.to(device)
mask_index = input_ids[0].tolist().index(4)
attention_mask = tok.attention_mask.to(device)
input_ids.shape, attention_mask.shape
with torch.no_grad():
    out = model(input_ids=input_ids, attention_mask=attention_mask)
out_max = torch.argmax(out, dim=-1)
news_tokenizer.decode([out_max[0][mask_index].item()])

'buy'

In [147]:
text = "Non-OPEC oil exporters should consider  [MASK] output to cool record crude prices"
tok = news_tokenizer(text, return_tensors='pt')
input_ids = tok.input_ids.to(device)
mask_index = input_ids[0].tolist().index(4)
attention_mask = tok.attention_mask.to(device)
input_ids.shape, attention_mask.shape
with torch.no_grad():
    out = model(input_ids=input_ids, attention_mask=attention_mask)
out_max = torch.argmax(out, dim=-1)
news_tokenizer.decode([out_max[0][mask_index].item()])

'oil'

##### MLM on imdb ds

In [33]:
ds_name_2 = 'stanfordnlp/imdb'
ds_imdb = load_dataset(ds_name_2)

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

unsupervised-00000-of-00001.parquet:   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [34]:
ds_imdb

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [35]:
tokenizer = AutoTokenizer.from_pretrained('./agnews_tokenizer')
tokenizer

BertTokenizerFast(name_or_path='./agnews_tokenizer', vocab_size=9000, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [36]:
df_train = ds_imdb['train'].to_pandas()
df_train

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [37]:
df_test = ds_imdb['test'].shuffle(seed=42).select(range(5000)).to_pandas()

In [38]:
df_test['label'].value_counts()

label
1    2506
0    2494
Name: count, dtype: int64

In [39]:
df = pd.concat([df_train, df_test], axis=0)
df

                                                   text  label
0     I rented I AM CURIOUS-YELLOW from my video sto...      0
1     "I Am Curious: Yellow" is a risible and preten...      0
2     If only to avoid making this type of film in t...      0
3     This film was probably inspired by Godard's Ma...      0
4     Oh, brother...after hearing about this ridicul...      0
...                                                 ...    ...
4995  This was a pleasant musical about the creation...      1
4996  OK, I saw this film through Mystery Science Th...      0
4997  It's painfully clear that all effort in this f...      0
4998  The Vietnam War era is certainly far before my...      1
4999  Duncan Roy's writing and direction is really, ...      0

[30000 rows x 2 columns]

In [40]:
imdb_list = df['text'].tolist()
len(imdb_list)

30000

In [41]:
imdb_list[:4]

['I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.',
 '"I Am Curious: Yellow" is a risible and pretentious steaming pile. It doesn\'t matter what one\'s political views are because this film can hardly be taken seriously on any level. As for the claim that frontal male nudity is an automatic NC-17, that isn\'t true. I\'ve seen R-rated films with male nudity. Granted, they only offer some fleeting views, but where are the R-rated films with gaping vulvas and flapping labia? Nowhere, because they don\'t exist. The same goes for those crappy cable shows: schlongs swinging in the breeze but not a clitoris in sight. And those pretentious indie movies like The Brown Bunny, in which we\'re treated to the site of Vincent Gallo\'s throbbing johnson, but not a trace of pink visible on Chloe Sevigny. Before crying (or implying) "double-standard" in matters of nudity, the mentally obtuse should take into account one unavoidably obvious anatomical difference between men and women: there are no genitals on display when actresses appears nude, and the same cannot be said for a man. In fact, you generally won\'t see female genitals in an American film in anything short of porn or explicit erotica. This alleged double-standard is less a double standard than an admittedly depressing ability to come to terms culturally with the insides of women\'s bodies.',
 "If only to avoid making this type of film in the future. This film is interesting as an experiment but tells no cogent story.<br /><br />One might feel virtuous for sitting thru it because it touches on so many IMPORTANT issues but it does so without any discernable motive. The viewer comes away with no new perspectives (unless one comes up with one while one's mind wanders, as it will invariably do during this pointless film).<br /><br />One might better spend one's time staring out a window at a tree growing.<br /><br />",
 "This film was probably inspired by Godard's Masculin, féminin and I urge you to see that film instead.<br /><br />The film has two strong elements and those are, (1) the realistic acting (2) the impressive, undeservedly good, photo. Apart from that, what strikes me most is the endless stream of silliness. Lena Nyman has to be most annoying actress in the world. She acts so stupid and with all the nudity in this film,...it's unattractive. Comparing to Godard's film, intellectuality has been replaced with stupidity. Without going too far on this subject, I would say that follows from the difference in ideals between the French and the Swedish society.<br /><br />A movie of its time, and place. 2/10."]

In [42]:
len_items = [len(tokenizer(i).input_ids) for i in imdb_list]

Token indices sequence length is longer than the specified maximum sequence length for this model (559 > 512). Running this sequence through the model will result in indexing errors

In [68]:
max(len_items)

3660

In [69]:
len_items[:3]

[412, 362, 147]

In [71]:
df['tok_len'] = df['text'].apply(lambda x: len(tokenizer(x).input_ids))

In [72]:
df.describe()

              label       tok_len
count  26000.000000  26000.000000
mean       0.499538    360.043269
std        0.500009    271.187799
min        0.000000     14.000000
25%        0.000000    190.000000
50%        0.000000    266.000000
75%        1.000000    438.250000
max        1.000000   3660.000000

In [73]:
class IMDB_DS(Dataset):
    def __init__(self, df):
        self.data = df['text']

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text = self.data.iloc[idx]
        return text

In [75]:
imdb_ds = IMDB_DS(df)

In [77]:
imdb_ds[2]

"If only to avoid making this type of film in the future. This film is interesting as an experiment but tells no cogent story.<br /><br />One might feel virtuous for sitting thru it because it touches on so many IMPORTANT issues but it does so without any discernable motive. The viewer comes away with no new perspectives (unless one comes up with one while one's mind wanders, as it will invariably do during this pointless film).<br /><br />One might better spend one's time staring out a window at a tree growing.<br /><br />"

In [78]:
len(imdb_ds)

26000

In [79]:
tokenizer.encode(tokenizer.mask_token)

[2, 4, 3]

In [81]:
tokenizer.vocab['[MASK]'], tokenizer.vocab['[PAD]']

(4, 0)

In [80]:
def bernoulli_true_false(p):
    # Create a Bernoulli distribution with probability p
    bernoulli_dist = torch.distributions.Bernoulli(torch.tensor([p]))
    # Sample from this distribution and convert 1 to True and 0 to False
    return bernoulli_dist.sample().item() == 1

In [82]:
def Masking(token, vocab_size):
    # Decide whether to mask this token (15% chance)
    mask = bernoulli_true_false(0.15)

    # If mask is False, immediately return with '[PAD]' label
    if not mask:
        return token, -100

    # If mask is True, proceed with further operations
    # Randomly decide on an operation (10% chance each)
    replace_random = bernoulli_true_false(0.1)
    leave_as_is = bernoulli_true_false(0.1)
    label = token
    if replace_random:
        _token = torch.randint(0, vocab_size, size=(1,)).item()
    elif leave_as_is:
        _token = token
    else:
        _token = 4

    return _token, label

In [83]:
def collate_fn(batch, tokenizer):
    vocab_size = tokenizer.vocab_size
    pad_tokenid = [tokenizer.vocab[tokenizer.pad_token]]
    ignore_loss_id = [-100]  #ignore loss
    ignore_token_id = [0]   #attention mask filler
    x_input_ids, x_am = [], []
    lab_list = []

    for x in batch:
        tokenized = tokenizer(x, max_length=256, truncation=True)
        inp_ids = []
        label_list = []
        for x in tokenized.input_ids:
            tok, lbl = Masking(x, vocab_size)
            inp_ids.append(tok)
            label_list.append(lbl)
        am = tokenized.attention_mask
        x_input_ids.append(inp_ids)
        x_am.append(am)
        lab_list.append(label_list)

    len_enc = [len(l) for l in x_input_ids]
    max_len = max(len_enc)

    def pad_tokens_stack(in_list, max_len, padding):
        list_tensor = []
        for item in in_list:
            len_item = len(item)
            deficit = max_len - len_item
            if deficit > 0:
                item = item + padding*deficit
            list_tensor.append(torch.tensor(item))
        item_ids = torch.vstack(list_tensor)
        return item_ids

    input_ids = pad_tokens_stack(x_input_ids, max_len, pad_tokenid)
    attention_mask = pad_tokens_stack(x_am, max_len, ignore_token_id)
    labels =  pad_tokens_stack(lab_list, max_len, ignore_loss_id)

    return {'input_ids': input_ids, 'attention_mask': attention_mask}, labels

In [84]:
train_ds = IMDB_DS(df_train)
test_ds = IMDB_DS(df_test)

In [85]:
len(train_ds), len(test_ds)

(25000, 1000)

In [86]:
torch.cuda.empty_cache()

In [88]:
tokenizer

BertTokenizerFast(name_or_path='./agnews_tokenizer', vocab_size=9000, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [92]:
from functools import partial
import os
wrapper_collate_fn = partial(
    collate_fn,
    tokenizer=tokenizer,
    )

train_dl = DataLoader(train_ds, shuffle=True, batch_size=128,
                      num_workers=os.cpu_count(), collate_fn=wrapper_collate_fn)
test_dl = DataLoader(test_ds, shuffle=False, batch_size=128,
                      num_workers=os.cpu_count(), collate_fn=wrapper_collate_fn)

In [93]:
train_iter = iter(train_dl)

In [94]:
i, l = next(train_iter)

In [95]:
unravel = [t for i in l.tolist() for t in i]

In [96]:
len(unravel)

32768

In [97]:
valid_items = [i for i in unravel if i > -100]
valid_items

[14,
 115,
 3535,
 115,
 4984,
 16,
 3065,
 3124,
 2546,
 109,
 3748,
 333,
 7833,
 306,
 29,
 1510,
 42,
 7354,
 238,
 787,
 6846,
 241,
 174,
 1091,
 112,
 313,
 3017,
 310,
 2423,
 46,
 175,
 387,
 168,
 375,
 16,
 1,
 4809,
 16,
 102,
 14,
 67,
 12,
 434,
 1056,
 321,
 14,
 102,
 207,
 1232,
 29,
 1951,
 7626,
 102,
 16,
 3994,
 6146,
 102,
 3,
 1224,
 109,
 1665,
 16,
 102,
 245,
 4435,
 552,
 951,
 52,
 6161,
 824,
 1587,
 53,
 111,
 42,
 16,
 102,
 2624,
 99,
 207,
 895,
 488,
 7128,
 1432,
 102,
 2274,
 115,
 52,
 65,
 34,
 182,
 7479,
 182,
 102,
 102,
 351,
 693,
 310,
 159,
 4930,
 158,
 7932,
 102,
 2904,
 658,
 241,
 8007,
 1697,
 2790,
 230,
 1338,
 504,
 64,
 672,
 2948,
 5491,
 2314,
 8,
 23,
 108,
 1471,
 403,
 4771,
 252,
 7113,
 111,
 132,
 4918,
 68,
 421,
 115,
 6896,
 2339,
 1082,
 109,
 3314,
 1241,
 378,
 102,
 109,
 152,
 271,
 238,
 34,
 271,
 102,
 7031,
 16,
 182,
 5342,
 3035,
 132,
 313,
 1224,
 1923,
 1843,
 1852,
 14,
 733,
 3869,
 3597,
 14,
 115,
 3792,
 62,
 570,
 4967,
 14,
 1570,
 449,
 1692,
 252,
 217,
 675,
 3353,
 64,
 2953,
 789,
 71,
 14,
 484,
 1519,
 34,
 1090,
 34,
 14,
 77,
 7179,
 68,
 1165,
 29,
 115,
 102,
 1244,
 14,
 1424,
 2260,
 60,
 77,
 1,
 333,
 17,
 52,
 7744,
 7031,
 1259,
 411,
 174,
 115,
 16,
 104,
 343,
 115,
 2225,
 16,
 68,
 368,
 817,
 102,
 729,
 102,
 490,
 6,
 1577,
 3815,
 3022,
 1428,
 1165,
 2419,
 1178,
 131,
 102,
 96,
 8240,
 478,
 63,
 434,
 777,
 2838,
 627,
 3022,
 241,
 4452,
 6164,
 523,
 2975,
 156,
 492,
 240,
 111,
 278,
 53,
 68,
 3477,
 11,
 2513,
 1587,
 2445,
 350,
 34,
 951,
 3272,
 3530,
 34,
 16,
 5659,
 102,
 6896,
 15,
 2359,
 187,
 3003,
 175,
 3912,
 16,
 1,
 2,
 343,
 434,
 1272,
 1658,
 66,
 174,
 42,
 310,
 5990,
 34,
 1828,
 12,
 111,
 3925,
 5125,
 102,
 72,
 1266,
 16,
 6569,
 1714,
 1145,
 2531,
 6960,
 312,
 169,
 3597,
 42,
 217,
 10,
 52,
 758,
 8076,
 102,
 102,
 3302,
 758,
 2887,
 1897,
 6,
 977,
 6689,
 1,
 637,
 1510,
 761,
 397,
 723,
 113,
 1238,
 2887,
 1407,
 175,
 7479,
 1512,
 3589,
 372,
 1,
 333,
 397,
 135,
 102,
 115,
 504,
 34,
 3022,
 4890,
 6,
 2191,
 5772,
 1384,
 3036,
 132,
 318,
 115,
 7791,
 34,
 984,
 3036,
 805,
 492,
 1818,
 135,
 951,
 16,
 2222,
 16,
 3713,
 999,
 371,
 6484,
 837,
 111,
 1082,
 440,
 16,
 227,
 241,
 207,
 1459,
 724,
 207,
 14,
 2,
 5985,
 357,
 2070,
 3116,
 552,
 264,
 552,
 7030,
 102,
 515,
 515,
 4950,
 14,
 8769,
 3621,
 693,
 1939,
 14,
 4915,
 14,
 4554,
 182,
 4915,
 1859,
 174,
 102,
 135,
 506,
 332,
 102,
 16,
 397,
 3,
 67,
 73,
 16,
 329,
 34,
 102,
 16,
 175,
 1118,
 75,
 134,
 16,
 102,
 123,
 132,
 1692,
 306,
 4384,
 168,
 3,
 175,
 3022,
 1024,
 11,
 166,
 3757,
 14,
 42,
 1024,
 6794,
 3170,
 1356,
 3343,
 269,
 2365,
 180,
 16,
 626,
 10,
 16,
 14,
 34,
 397,
 1470,
 839,
 1692,
 403,
 1881,
 1692,
 34,
 630,
 104,
 387,
 162,
 207,
 111,
 117,
 215,
 6336,
 4972,
 1692,
 14,
 111,
 42,
 343,
 15,
 102,
 4361,
 7263,
 169,
 2486,
 3745,
 1090,
 102,
 159,
 230,
 550,
 4390,
 182,
 265,
 64,
 11,
 171,
 174,
 217,
 8276,
 434,
 1079,
 951,
 115,
 1241,
 135,
 68,
 333,
 17,
 3022,
 171,
 3022,
 2085,
 7354,
 5434,
 8128,
 315,
 436,
 15,
 238,
 6128,
 123,
 108,
 8177,
 115,
 4693,
 2013,
 440,
 616,
 3923,
 132,
 17,
 1,
 34,
 53,
 16,
 368,
 175,
 102,
 2363,
 111,
 153,
 740,
 11,
 3445,
 331,
 15,
 108,
 16,
 6034,
 53,
 115,
 2593,
 115,
 3022,
 42,
 182,
 230,
 2775,
 42,
 207,
 616,
 135,
 2887,
 96,
 4983,
 8017,
 4017,
 8286,
 3,
 2315,
 117,
 4251,
 59,
 8589,
 115,
 6644,
 16,
 397,
 592,
 115,
 1218,
 1066,
 344,
 16,
 592,
 2070,
 3894,
 175,
 6391,
 1019,
 16,
 4454,
 1212,
 207,
 1428,
 174,
 66,
 3246,
 6,
 4558,
 4706,
 14,
 357,
 104,
 2042,
 42,
 488,
 517,
 75,
 1019,
 3551,
 14,
 8831,
 3807,
 14,
 680,
 534,
 62,
 34,
 169,
 1,
 14,
 1844,
 4956,
 11,
 450,
 12,
 632,
 534,
 12,
 570,
 2405,
 115,
 6648,
 12,
 12,
 2658,
 62,
 427,
 1826,
 34,
 259,
 109,
 162,
 8999,
 336,
 16,
 34,
 89,
 16,
 3,
 3648,
 16,
 3252,
 14,
 1082,
 135,
 453,
 14,
 14,
 238,
 108,
 132,
 4694,
 102,
 102,
 2735,
 16,
 77,
 102,
 1,
 4330,
 34,
 70,
 397,
 65,
 3498,
 723,
 111,
 397,
 174,
 3713,
 16,
 135,
 1665,
 2777,
 132,
 6036,
 174,
 132,
 166,
 938,
 251,
 1331,
 1995,
 460,
 102,
 1568,
 16,
 5168,
 397,
 1541,
 132,
 2086,
 1,
 2604,
 275,
 8385,
 96,
 7443,
 440,
 6628,
 115,
 14,
 938,
 16,
 1541,
 102,
 1029,
 824,
 400,
 8950,
 132,
 3,
 16,
 1831,
 7612,
 440,
 1430,
 29,
 6653,
 1420,
 13,
 16,
 333,
 318,
 285,
 5947,
 2862,
 14,
 102,
 824,
 7862,
 109,
 5,
 6034,
 1282,
 7030,
 42,
 6,
 115,
 4330,
 1,
 510,
 3297,
 169,
 4554,
 7401,
 6607,
 2775,
 318,
 693,
 17,
 1,
 496,
 2181,
 1089,
 102,
 2812,
 8362,
 3597,
 1859,
 14,
 3251,
 2981,
 1,
 1,
 77,
 17,
 1665,
 4501,
 1019,
 1349,
 863,
 12,
 403,
 5988,
 2219,
 14,
 162,
 14,
 523,
 5398,
 6,
 1782,
 397,
 17,
 17,
 5256,
 1241,
 999,
 111,
 15,
 773,
 1778,
 4828,
 34,
 405,
 102,
 102,
 332,
 6436,
 31,
 403,
 14,
 404,
 12,
 601,
 4390,
 3339,
 793,
 693,
 4890,
 102,
 169,
 42,
 515,
 42,
 102,
 412,
 2068,
 1,
 17,
 480,
 11,
 8349,
 6931,
 132,
 102,
 6322,
 1,
 397,
 679,
 135,
 2604,
 313,
 275,
 504,
 16,
 1241,
 326,
 265,
 246,
 6754,
 2659,
 207,
 174,
 14,
 16,
 16,
 68,
 132,
 102,
 367,
 357,
 1241,
 1844,
 5092,
 436,
 207,
 3,
 4998,
 5399,
 1,
 1,
 4753,
 900,
 11,
 77,
 3421,
 3478,
 658,
 4593,
 334,
 102,
 3596,
 3588,
 165,
 64,
 611,
 114,
 205,
 631,
 175,
 182,
 144,
 114,
 1715,
 1,
 333,
 64,
 1038,
 2124,
 656,
 77,
 872,
 313,
 592,
 16,
 17,
 1,
 4237,
 6551,
 1019,
 3,
 310,
 357,
 758,
 16,
 34,
 1817,
 2812,
 174,
 3065,
 3074,
 3040,
 14,
 132,
 367,
 111,
 108,
 115,
 207,
 34,
 4118,
 253,
 102,
 1653,
 4976,
 14,
 81,
 8484,
 368,
 2657,
 8300,
 397,
 14,
 397,
 4473,
 16,
 2405,
 1929,
 397,
 1020,
 2,
 3339,
 2186,
 4945,
 175,
 109,
 6793,
 132,
 97,
 5,
 6,
 112,
 16,
 469,
 109,
 34,
 3339,
 10,
 523,
 132,
 34,
 716,
 8420,
 2381,
 81,
 5965,
 2968,
 663,
 132,
 7632,
 108,
 1452,
 856,
 207,
 2986,
 1212,
 102,
 72,
 1019,
 132,
 132,
 1,
 1,
 333,
 4057,
 343,
 ...]

In [98]:
len(valid_items)

4154

In [99]:
len(unravel)*0.15

4915.2

In [100]:
from torch.optim import AdamW

In [102]:
model_dict = torch.load('./mlmckpt')
model_dict.keys()

dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'loss', 'device'])

In [103]:
for keys in ['epoch', 'loss', 'device']:
    print(model_dict[keys])

10
3.4532971148173015
cuda

In [104]:
vocab_size = tokenizer.vocab_size
vocab_size

9000

In [105]:
BroEncoder = Encoder(num_layers=6, num_heads=8, vocab_size=vocab_size, 
                     embed_dim=256, k_dim=32, ctx_len=256, do=0.1, device=device)

In [106]:
Bro_MLM = MLM(BroEncoder, 256, vocab_size)
Bro_MLM

MLM(
  (encoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(9000, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (mlm_layer): Linear(in_features=256, out_features=9000, bias=True)
)

In [107]:
summary(Bro_MLM)

===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
MLM                                                --
├─Encoder: 1-1                                     --
│    └─Embed: 2-1                                  --
│    │    └─Embedding: 3-1                         2,304,000
│    │    └─PositionalEncoding: 3-2                --
│    │    └─Sequential: 3-3                        512
│    └─Sequential: 2-2                             --
│    │    └─Encoder_Block: 3-4                     789,760
│    │    └─Encoder_Block: 3-5                     789,760
│    │    └─Encoder_Block: 3-6                     789,760
│    │    └─Encoder_Block: 3-7                     789,760
│    │    └─Encoder_Block: 3-8                     789,760
│    │    └─Encoder_Block: 3-9                     789,760
├─Linear: 1-2                                      2,313,000
===========================================================================
Total params: 9,356,072
Trainable params: 9,356,072
Non-trainable params: 0
===========================================================================

In [108]:
model_dict.keys()

dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'loss', 'device'])

In [110]:
Bro_MLM.load_state_dict(model_dict['model_state_dict'])

In [111]:
model = Bro_MLM

In [112]:
model.eval()
fn_loss = nn.CrossEntropyLoss()
model = model.to(device)
loss_epoch = 0
for inputs in train_dl:
    data = inputs[0]
    label = inputs[1]
    batch_size = label.shape[0]
    ctx_size = label.shape[1]
    data = {i: k.to(device) for i, k in data.items()}
    label = label.to(device)
    with torch.no_grad():
        out = model(**data)
    out = out.view(batch_size * ctx_size, vocab_size)
    label = label.view(batch_size * ctx_size)
    loss = fn_loss(out, label)
    loss_epoch = loss_epoch + (loss.item() * batch_size)
average_loss = loss_epoch/len(train_dl.dataset)
perplexity = math.exp(average_loss) 
print(f'Training Average loss: {average_loss}')
print(f'Training Perplexity: {perplexity}')

Training Average loss: 5.883202411651611
Training Perplexity: 358.95693089933525

Training Average loss: 0.23519211776733398
Training Perplexity: 1.2651518035263254

In [116]:
model, optimizer, average_loss, perplexity = train_model(10, 0.0004, Bro_MLM, train_dl, device, vocab_size)

Step: 0, Loss: 5.840501308441162
Step: 100, Loss: 4.1548991203308105
Epoch: 0 -- Average loss: 4.228756598434448
Epoch: 0 -- Perplexity: 68.63184215782235
Step: 0, Loss: 3.7393600940704346
Step: 100, Loss: 3.5682082176208496
Epoch: 1 -- Average loss: 3.629689563140869
Epoch: 1 -- Perplexity: 37.701110985865846
Step: 0, Loss: 3.553816080093384
Step: 100, Loss: 3.3739774227142334
Epoch: 2 -- Average loss: 3.395516984024048
Epoch: 2 -- Perplexity: 29.830071159472038
Step: 0, Loss: 3.2187609672546387
Step: 100, Loss: 3.213336706161499
Epoch: 3 -- Average loss: 3.2408977336120603
Epoch: 3 -- Perplexity: 25.556654519825276
Step: 0, Loss: 3.1452534198760986
Step: 100, Loss: 3.119072437286377
Epoch: 4 -- Average loss: 3.1306783029937746
Epoch: 4 -- Perplexity: 22.889500294535207
Step: 0, Loss: 2.9917099475860596
Step: 100, Loss: 3.0777344703674316
Epoch: 5 -- Average loss: 3.0353518660736083
Epoch: 5 -- Perplexity: 20.808298345729206
Step: 0, Loss: 2.9388041496276855
Step: 100, Loss: 3.0187602043151855
Epoch: 6 -- Average loss: 2.9537916438293457
Epoch: 6 -- Perplexity: 19.17853421250692
Step: 0, Loss: 2.8562769889831543
Step: 100, Loss: 2.8724799156188965
Epoch: 7 -- Average loss: 2.9022250284576416
Epoch: 7 -- Perplexity: 18.214628381308337
Step: 0, Loss: 2.9279849529266357
Step: 100, Loss: 2.984524726867676
Epoch: 8 -- Average loss: 2.8421047959899903
Epoch: 8 -- Perplexity: 17.151828671270316
Step: 0, Loss: 2.788547992706299
Step: 100, Loss: 2.864069938659668
Epoch: 9 -- Average loss: 2.79384552696228
Epoch: 9 -- Perplexity: 16.343749439361723

In [120]:
model.eval()
fn_loss = nn.CrossEntropyLoss()
model = model.to(device)
loss_epoch = 0
for inputs in test_dl:
    data = inputs[0]
    label = inputs[1]
    batch_size = label.shape[0]
    ctx_size = label.shape[1]
    data = {i: k.to(device) for i, k in data.items()}
    label = label.to(device)
    with torch.no_grad():
        out = model(**data)
    out = out.view(batch_size * ctx_size, vocab_size)
    label = label.view(batch_size * ctx_size)
    loss = fn_loss(out, label)
    loss_epoch = loss_epoch + (loss.item() * batch_size)
average_loss = loss_epoch/len(test_dl.dataset)
perplexity = math.exp(average_loss) 
print(f'Test Average loss: {average_loss}')
print(f'Test Perplexity: {perplexity}')

Test Average loss: 2.885202169418335
Test Perplexity: 17.907187515273186

In [122]:
#test loss and perplexity is in line with training dataset
#Let us bake the model for 5 more epochs

In [123]:
model, optimizer, average_loss, perplexity = train_model(5, 0.0004, model, train_dl, device, vocab_size)

Step: 0, Loss: 2.8169198036193848
Step: 100, Loss: 2.7115659713745117
Epoch: 0 -- Average loss: 2.759156516799927
Epoch: 0 -- Perplexity: 15.786521665098821
Step: 0, Loss: 2.763066530227661
Step: 100, Loss: 2.70294189453125
Epoch: 1 -- Average loss: 2.714950934295654
Epoch: 1 -- Perplexity: 15.103868971744802
Step: 0, Loss: 2.7801594734191895
Step: 100, Loss: 2.627650737762451
Epoch: 2 -- Average loss: 2.6722273762512208
Epoch: 2 -- Perplexity: 14.47216828368427
Step: 0, Loss: 2.7393577098846436
Step: 100, Loss: 2.5838873386383057
Epoch: 3 -- Average loss: 2.6409716455078125
Epoch: 3 -- Perplexity: 14.026826091109776
Step: 0, Loss: 2.6095361709594727
Step: 100, Loss: 2.6043498516082764
Epoch: 4 -- Average loss: 2.615363771820068
Epoch: 4 -- Perplexity: 13.67218903047144

In [124]:
model.eval()
fn_loss = nn.CrossEntropyLoss()
model = model.to(device)
loss_epoch = 0
for inputs in test_dl:
    data = inputs[0]
    label = inputs[1]
    batch_size = label.shape[0]
    ctx_size = label.shape[1]
    data = {i: k.to(device) for i, k in data.items()}
    label = label.to(device)
    with torch.no_grad():
        out = model(**data)
    out = out.view(batch_size * ctx_size, vocab_size)
    label = label.view(batch_size * ctx_size)
    loss = fn_loss(out, label)
    loss_epoch = loss_epoch + (loss.item() * batch_size)
average_loss = loss_epoch/len(test_dl.dataset)
perplexity = math.exp(average_loss) 
print(f'Test Average loss: {average_loss}')
print(f'Test Perplexity: {perplexity}')

Test Average loss: 2.760401731491089
Test Perplexity: 15.806191517851754

In [125]:
torch.save({
        'epoch': 15,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss': average_loss,
        'device': device
        }, './news_imdb_mlm.pt')

In [43]:
df_train

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [44]:
df_train['label'].value_counts()

label
0    12500
1    12500
Name: count, dtype: int64

In [45]:
df_test['label'].value_counts()

label
1    2506
0    2494
Name: count, dtype: int64

In [46]:
import math

class LoRALayer(torch.nn.Module):
    def __init__(self, in_dim, out_dim, rank, alpha):
        super().__init__()
        self.A = torch.nn.Parameter(torch.empty(in_dim, rank))
        torch.nn.init.kaiming_uniform_(self.A, a=math.sqrt(5))    #1
        self.B = torch.nn.Parameter(torch.zeros(rank, out_dim))
        self.alpha = alpha

    def forward(self, x):
        x = self.alpha * (x @ self.A @ self.B)
        return x

In [47]:
class LinearWithLoRA(torch.nn.Module):
    def __init__(self, linear, rank, alpha):
        super().__init__()
        self.linear = linear
        self.lora = LoRALayer(
            linear.in_features, linear.out_features, rank, alpha
        )

    def forward(self, x):
        return self.linear(x) + self.lora(x)

In [48]:
def replace_linear_with_lora(model, rank, alpha):
    for name, module in model.named_children():
        if isinstance(module, torch.nn.Linear):     #1
            setattr(model, name, LinearWithLoRA(module, rank, alpha))
        else:    #2
            replace_linear_with_lora(module, rank, alpha)
#1 Replaces the Linear layer with LinearWithLoRA

In [49]:
#summary(model)

In [50]:
#replace_linear_with_lora(model, rank=16, alpha=16)
#total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
#print(f"Total trainable LoRA parameters: {total_params:,}")

In [51]:
#summary(model)

In [52]:
#model

In [53]:
#device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#model.to(device)
#print(model)

In [54]:
#model.mlm_layer

In [132]:
class Bro_Classification_Model(nn.Module):
    def __init__(self, max_length, vocab_size, device):
        super().__init__()
        self.BroEncoder = Encoder(num_layers=6, num_heads=8, vocab_size=vocab_size,
                                  embed_dim=256, k_dim=32, ctx_len=256, do=0.1, device=device)
        self.Bro_MLM = MLM(self.BroEncoder, 256, vocab_size)
        model_dict = torch.load('./news_imdb_mlm.pt')
        self.Bro_MLM.load_state_dict(model_dict['model_state_dict'])
        print("Model loaded from checkpoint successfully")

        self.Bro_MLM.mlm_layer = nn.Sequential(
            nn.Linear(max_length, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(inplace=True),
            nn.Dropout(0.1),
            nn.Linear(128, 2)
        )
        total_params = sum(p.numel() for p in self.Bro_MLM.parameters() if p.requires_grad)
        print(f"Total trainable LoRA and classification parameters: {total_params:,}")


    def forward(self, input_ids, attention_mask):
        x = self.BroEncoder(input_ids, attention_mask)
        x = x.mean(dim=1)
        x = self.Bro_MLM.mlm_layer(x)
        return x

In [103]:
class Bro_Classification_Model_skip(nn.Module):
    def __init__(self, max_length, vocab_size, device):
        super().__init__()
        self.BroEncoder = Encoder(num_layers=6, num_heads=8, vocab_size=vocab_size,
                                  embed_dim=256, k_dim=32, ctx_len=256, do=0.1, device=device)
        self.Bro_MLM = MLM(self.BroEncoder, 256, vocab_size)
        model_dict = torch.load('./news_imdb_mlm.pt')
        self.Bro_MLM.load_state_dict(model_dict['model_state_dict'])
        print("Model loaded from checkpoint successfully")
        #total_params = sum(p.numel() for p in self.Bro_MLM.parameters() if p.requires_grad)
        #print(f"Total trainable parameters before freezing: {total_params:,}")
        #for param in self.Bro_MLM.parameters():
        #    param.requires_grad = False
        #total_params = sum(p.numel() for p in self.Bro_MLM.parameters() if p.requires_grad)
        #print(f"Total trainable parameters after freezing: {total_params:,}")
        #replace_linear_with_lora(self.Bro_MLM, rank=16, alpha=32)
        self.Bro_MLM.mlm_layer = nn.Sequential(
            nn.Linear(256, 64),
            nn.LayerNorm(64),
            nn.GELU(),
            nn.Dropout(0.05),
            nn.Linear(64, 1)
        )
        self.gen_layer = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(inplace=True),
            nn.Dropout(0.05),
            )
        self.classifier = nn.Linear(64, 2)
        total_params = sum(p.numel() for p in self.Bro_MLM.parameters() if p.requires_grad)
        print(f"Total trainable LoRA and classification parameters: {total_params:,}")


    def forward(self, input_ids, attention_mask):
        x = self.BroEncoder(input_ids, attention_mask)
        #x = x.mean(dim=1)
        x = self.Bro_MLM.mlm_layer(x)
        #print(x.shape)
        x = self.gen_layer(x)
        #print(x.shape)
        #x = x + y
        x = self.classifier(x)
        return x

In [133]:
vocab_size = tokenizer.vocab_size
vocab_size

9000

In [134]:
bro_model = Bro_Classification_Model(256, vocab_size, device)

Model loaded from checkpoint successfully
Total trainable LoRA and classification parameters: 7,076,482

In [135]:
summary(bro_model)

================================================================================
Layer (type:depth-idx)                                  Param #
================================================================================
Bro_Classification_Model                                --
├─Encoder: 1-1                                          --
│    └─Embed: 2-1                                       --
│    │    └─Embedding: 3-1                              2,304,000
│    │    └─PositionalEncoding: 3-2                     --
│    │    └─Sequential: 3-3                             512
│    └─Sequential: 2-2                                  --
│    │    └─Encoder_Block: 3-4                          789,760
│    │    └─Encoder_Block: 3-5                          789,760
│    │    └─Encoder_Block: 3-6                          789,760
│    │    └─Encoder_Block: 3-7                          789,760
│    │    └─Encoder_Block: 3-8                          789,760
│    │    └─Encoder_Block: 3-9                          789,760
├─MLM: 1-2                                              7,043,072
│    └─Encoder: 2-3                                     (recursive)
│    │    └─Embed: 3-10                                 (recursive)
│    │    └─Sequential: 3-11                            (recursive)
│    └─Sequential: 2-4                                  --
│    │    └─Linear: 3-12                                32,896
│    │    └─BatchNorm1d: 3-13                           256
│    │    └─ReLU: 3-14                                  --
│    │    └─Dropout: 3-15                               --
│    │    └─Linear: 3-16                                258
================================================================================
Total params: 14,119,554
Trainable params: 14,119,554
Non-trainable params: 0
================================================================================

In [137]:
bro_model

Bro_Classification_Model(
  (BroEncoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(9000, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (Bro_MLM): MLM(
    (encoder): Encoder(
      (emb): Embed(
        (tok_layer): Embedding(9000, 256)
        (pos_layer): PositionalEncoding(
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (norm_do): Sequential(
          (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (layers): Sequential(
        (0): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (1): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (2): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (3): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (4): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (5): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
    (mlm_layer): Sequential(
      (0): Linear(in_features=256, out_features=128, bias=True)
      (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=128, out_features=2, bias=True)
    )
  )
)

In [138]:
t = torch.randint(0, 100, (2,256))
t

tensor([[82, 99, 21, 10, 93, 17, 65, 38,  3, 71, 35, 39, 76, 73, 75, 57, 50, 32,
         42, 49, 58, 70, 68, 12, 62, 59, 91, 99, 17,  0, 57, 93, 46, 30, 24, 69,
         84, 16, 90, 14, 92, 94, 97,  5, 45, 68, 93, 26, 42, 67, 54, 92, 37, 44,
         84, 63, 76, 57, 14, 63, 98, 45, 94, 69, 18, 22, 90, 44, 66, 20, 18, 32,
         30,  2, 83, 67, 34, 69, 61, 92, 28, 83,  3,  8, 26, 42, 41, 93, 11, 13,
          2, 60, 68, 58, 25, 75, 79, 71, 40, 88, 37, 77, 91, 42, 10, 81, 79, 74,
         27, 21, 62, 61, 89, 23, 89, 53, 91, 86, 75, 97, 14, 44, 15, 14, 94, 44,
         90,  8, 40, 72, 91, 44, 73, 61, 88,  9, 34, 74, 11, 10, 57, 77, 15, 63,
         43, 47, 54, 28, 72, 57, 12, 45, 37, 19, 56, 72, 10, 16, 92, 19, 51, 82,
         96, 53, 56, 79, 47, 46, 84, 46, 79, 54,  9, 33, 47, 25, 93, 94, 31, 90,
         69, 94, 60, 16, 12, 70, 92, 53,  8, 36, 14, 84, 26, 46, 27,  1, 75, 88,
         15, 93, 86, 38, 56,  7, 87, 61, 33, 50, 53,  2, 15, 96, 85, 92, 53,  7,
         44, 25, 65, 42, 30, 99, 44, 16, 98, 76, 61, 54,  3, 67,  9, 85, 58, 62,
         76, 85, 33,  9, 26, 88, 52, 43, 45, 64, 81, 37, 52, 22, 31, 39, 31, 83,
         26, 14, 71, 63],
        [88, 20, 14, 39, 95, 34, 24, 25, 77, 92, 49, 29, 44, 45, 36, 11, 21,  8,
         49, 41, 14, 19,  8,  2, 22,  6, 82, 83, 98, 95, 94, 10, 34, 77, 23, 75,
         51, 62, 11, 80, 72,  8, 13, 15, 93, 96, 46,  8, 22, 44, 81, 58, 92, 27,
         31, 34, 82, 10, 20, 59, 45,  2, 40, 35, 44, 19, 94, 80, 41, 19, 64, 20,
         66, 95, 33, 80, 47, 59, 25, 84, 72, 88, 66, 85, 93, 42, 95, 88, 22, 29,
         82, 87, 23, 93, 16, 83, 24, 48, 15, 82, 39, 38, 99, 96, 20, 15, 83, 48,
         21, 58, 96, 31, 46, 51,  7, 25, 45, 77, 76, 60, 41, 69, 35, 74, 55, 34,
          6, 58, 70, 36, 47,  9, 40, 24, 47,  1, 87, 11, 10, 30, 38, 78, 72, 55,
         56, 86, 91,  2,  0, 91, 46, 64, 35, 27, 14, 63, 91,  6, 71, 50, 90, 94,
         19, 43, 42, 88, 36, 98, 26, 81, 55, 48, 26,  8, 34, 42, 77, 52, 73, 72,
         88, 42,  6, 16,  8, 64, 84, 73, 14, 90, 23, 46, 14, 27,  2, 64, 64, 53,
         52, 96, 75, 47, 33,  9, 82, 92, 91, 21, 71, 87, 97, 31, 29, 70, 10, 62,
         72,  3, 39, 46,  1, 74,  0, 70, 36, 87,  8,  7, 66, 49, 17, 55, 37, 77,
         10, 61, 17,  1, 62, 96, 45,  3, 20, 93, 35, 38, 43, 62,  0, 61, 99, 79,
         66, 95, 63, 69]])

In [139]:
am = torch.randint(1, 2, (2,256))
am

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [140]:
t.shape

torch.Size([2, 256])

In [141]:
t, am= t.to(device), am.to(device)

In [142]:
bro_model.to(device)

Bro_Classification_Model(
  (BroEncoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(9000, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (Bro_MLM): MLM(
    (encoder): Encoder(
      (emb): Embed(
        (tok_layer): Embedding(9000, 256)
        (pos_layer): PositionalEncoding(
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (norm_do): Sequential(
          (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (layers): Sequential(
        (0): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (1): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (2): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (3): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (4): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (5): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
    (mlm_layer): Sequential(
      (0): Linear(in_features=256, out_features=128, bias=True)
      (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=128, out_features=2, bias=True)
    )
  )
)

In [143]:
out = bro_model(t, am)
out, out.shape

(tensor([[ 0.3597,  0.1926],
         [-0.2961, -0.2147]], device='cuda:0', grad_fn=<AddmmBackward0>),
 torch.Size([2, 2]))

In [144]:
tokenizer = AutoTokenizer.from_pretrained('./agnews_tokenizer/')
tokenizer

BertTokenizerFast(name_or_path='./agnews_tokenizer/', vocab_size=9000, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [145]:
df_train

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [146]:
df_train['label'].value_counts()

label
0    12500
1    12500
Name: count, dtype: int64

In [147]:
df_test['label'].value_counts()

label
1    2506
0    2494
Name: count, dtype: int64

In [148]:
class IMDB_DS(Dataset):
    def __init__(self, df, max_len):
        self.data = df['text']
        self.label = df['label']
        self.max_len = max_len

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        x = self.data.iloc[idx]
        y = torch.tensor(self.label.iloc[idx])
        tokenized = tokenizer(x, truncation=True, max_length=self.max_len, padding='max_length', return_tensors='pt')
        input_ids = tokenized.input_ids.squeeze()
        attention_mask = tokenized.attention_mask.squeeze()
        return {'input_ids': input_ids, 'attention_mask': attention_mask}, y

In [149]:
train_ds = IMDB_DS(df_train, 256)
test_ds = IMDB_DS(df_test, 256)

In [150]:
train_ds[0]

({'input_ids': tensor([   2,   42, 7870,  104,   42,  285, 3341,  839,   15, 7698,  241, 1428,
          1471, 2135, 1282,  115,  434,  102, 5938,  182, 5583,  104,  207,  591,
           207,  238,  343, 1392,  108, 7942,   95,   16,   42, 1653, 5820,  182,
           166,  343,  207,  238, 5374,  217,   54,   16,   52,   16, 1406,   68,
           838,  207, 1025, 4288,  111, 1176,  397,  890,   14, 1038, 2676,   65,
          1227,   34, 4203,  115, 8245, 5635,    6, 3692,    6,   42, 4330,  566,
           111, 1929,  397,  135, 7744, 1664,   16,    1,  333,   17,    1,    1,
           333,   17,    1,  102, 3787,  174, 1682,  104, 1545,   34, 2658, 6730,
          8366, 7092, 2648, 6060,   70,  504, 2250,  111, 6823, 5544, 1541,  400,
           488, 1561,   16,  108, 6642, 1541, 2250,  111, 2301,  951, 4958,   68,
           111, 1739,  693, 8031,  115, 6699,  427,  131,  938,  102, 3053, 3724,
            65, 3460,  488, 3564, 1788, 2777, 1897,  162,  102, 5408,  453,  132,
          1635, 2777,  108,  102,  583,  855,   16,  108, 1065, 7392, 7505,  132,
          6535,  537,  278, 1751, 1134, 2133,  115, 7777,  488,  325, 7175,   68,
           131, 5721,   14, 1541,  230, 2684,  175,  951, 8366, 7802,   96,   14,
          1990, 3182, 5943,   68,   14,  132, 5872,  104, 1499,   16,    1,  333,
            17,    1,    1,  333,   17,    1,  938, 2644,  517,  488,   42,  285,
          3341,  839,   15, 7698,  174,  182, 2568,  621, 1377,   14,  397,  238,
          5635, 5253, 8686,   16, 4330,   14,  102, 2684,  132,   47, 3520, 1110,
          7030,   68,  318, 1869,  132, 1512, 1065,   14, 1208, 2521,  207,   10,
            52,  368, 1819, 1241,  693, 7038,  169, 1017, 5253,   74,   16, 1056,
          1428,  890, 2579,    3]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])},
 tensor(0))

In [151]:
test_ds[0]

({'input_ids': tensor([   2,    1,  333,   17,    1,    1,  333,   17,    1,  591,   42, 4633,
           155, 1733,  816,  104,  169, 7870,  104,   34, 2019,  187,  263, 2039,
            14,   42, 3460,   42,  238,  108,  135,  117, 3074,  109, 2731, 3433,
          3894,  132,  115, 3121, 7980,  146, 4989,   65, 6112,   71,  238,  108,
           207,   14,  492,  938,  592,  312, 3759,   31,    1,  333,   17,    1,
             1,  333,   17,    1, 3065, 4602,   14, 6034,   14,   42, 1356, 1553,
           182,  397, 3894,  238,  488,   34, 2019,  187,  845, 3795, 4432, 1901,
           733,  263, 2039,   16,   42, 3312, 5488,  109,  132, 6190,   10,   53,
          1810, 2464,  779,  264,  102, 3339, 2344,   16,  436,   73,  824, 2175,
            65,   14, 6436,   70,  132,  777, 2944, 5844,   14,  135, 4705,  219,
          1897,   34, 6664, 7310, 1091,  576,  132,  224, 5283, 2134, 5943, 3339,
             5,  436,   73,  824, 3421,   14,  135, 1227, 4945,  132, 1564,  161,
          4836,  102, 1165, 7479,   68,  175, 1897,  869,  158,  132,  655,  576,
          1692,    5,    1,  333,   17,    1,    1,  333,   17,    1,   42, 5169,
          1553,  102, 6960, 3446, 1831,   29,  102,  663, 6929, 3446, 1831,  132,
           102, 3446, 1831,  108, 1751,  261,   16,   42, 5169, 1553,  102, 3478,
            68,  270, 8024,  132, 3095,  246,  238, 1038,  132, 2521,  102, 5501,
            14, 3032, 3032,  102, 5501,   16,   16,   16,  434, 1608, 6183,   77,
          3302,   16,   42, 1653, 5169, 1553, 7744, 1664,  132,  397, 3339,  238,
           117, 3866,   15, 4073,   14,   34, 3573,   14,   34, 2741,  111, 1287,
          1428, 1090,  334, 6830,  132, 2516, 4906, 3923,  488,  207,   16,   42,
           334,  183,   77,    3]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])},
 tensor(1))

In [152]:
train_dl = DataLoader(train_ds, shuffle=True, batch_size=32, num_workers=os.cpu_count())
test_dl = DataLoader(test_ds, shuffle=False, batch_size=32, num_workers=os.cpu_count())

In [153]:
len(train_dl.dataset), len(test_dl.dataset)

(25000, 5000)

In [154]:
i, l = next(iter(train_dl))
i.keys, i['input_ids'].shape, i['attention_mask'].shape, l.shape

(<function dict.keys>,
 torch.Size([32, 256]),
 torch.Size([32, 256]),
 torch.Size([32]))

In [155]:
i = {k: v.to(device) for k, v in i.items()}
i

{'input_ids': tensor([[   2,  135,  621,  ...,   52, 1315,    3],
         [   2, 1510, 5988,  ...,  132, 1356,    3],
         [   2, 3077, 1925,  ...,    0,    0,    0],
         ...,
         [   2,   42,  400,  ...,    0,    0,    0],
         [   2, 6477, 6441,  ...,  397,  174,    3],
         [   2,  397,  174,  ...,    0,    0,    0]], device='cuda:0'),
 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0')}

In [156]:
out = bro_model(**i)
out.shape

torch.Size([32, 2])

In [157]:
torch.cuda.empty_cache()

In [170]:
def test(model, dl, device, vocab_size):
    model.eval()
    fn_loss = nn.CrossEntropyLoss()
    model = model.to(device)

    loss_epoch = 0
    accuracy = 0
    for inputs in dl:
        data = inputs[0]
        label = inputs[1]
        batch_size = data['input_ids'].shape[0]
        ctx_size = data['input_ids'].shape[1]
        data = {i: k.to(device) for i, k in data.items()}
        label = label.to(device)
        with torch.no_grad():
            out = model(**data)
        #out = out.view(batch_size * ctx_size, vocab_size)
        #label = label.view(batch_size * ctx_size)
        loss = fn_loss(out, label)
        loss_epoch = loss_epoch + (loss.item() * batch_size)
        accuracy += (torch.argmax(out, dim=1) == label).sum().item()
    average_loss = loss_epoch/len(dl.dataset)
    average_acc = accuracy/len(dl.dataset)
    print(f'Average Test loss: {average_loss}')
    print(f'Average Test Accuracy: {average_acc}')
    return average_loss, average_acc

In [171]:
def train_model(num_epochs, lrate, model, dl, test_dl, device, vocab_size):
    epochs = num_epochs
    lr = lrate
    fn_loss = nn.CrossEntropyLoss()
    optimizer = AdamW(model.parameters(), lr=lr)
    grad_accum_steps = 1 #args.grad_accum_steps # 4 - previous static value
    model = model.to(device)
    base_test_acc = 0.84

    for i in range(epochs):
        loss_epoch = 0
        n_step = 0
        grad_accum_counter = 1
        accuracy = 0
        model.train()
        

        for inputs in dl:
            data = inputs[0]
            label = inputs[1]
            batch_size = data['input_ids'].shape[0]
            ctx_size = data['input_ids'].shape[1]
            data = {i: k.to(device) for i, k in data.items()}
            label = label.to(device)
            out = model(**data)
            #out = out.view(batch_size * ctx_size, vocab_size)
            #label = label.view(batch_size * ctx_size)
            loss = fn_loss(out, label)
            loss = loss / grad_accum_steps
            loss.backward()
            if grad_accum_counter == grad_accum_steps:
                optimizer.step()
                optimizer.zero_grad()
                grad_accum_counter = 0
            loss_epoch = loss_epoch + (loss.item() * batch_size * grad_accum_steps)
            accuracy += (torch.argmax(out, dim=1) == label).sum().item()
            if n_step % 200 == 0:
                print(f'Step: {n_step}, Loss: {loss.item()}')
            grad_accum_counter += 1
            n_step += 1

        average_loss = loss_epoch/len(dl.dataset)
        average_acc = accuracy/len(dl.dataset)
        print(f'Epoch: {i} -- Average training Loss: {average_loss}')
        print(f'Epoch: {i} -- Average training Accuracy: {average_acc}')
        avg_test_loss, avg_test_acc = test(model, test_dl, device, vocab_size)
        if avg_test_acc > base_test_acc:
            base_test_acc = avg_test_acc
            print("saving model")
            torch.save({
                'epoch': i,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'loss': avg_test_loss,
                'accuracy': avg_test_acc,
                'device': device
                }, './imdb_class_model.pt')

    return model, optimizer, average_loss, average_acc

In [172]:
torch.cuda.empty_cache()

In [173]:
bro_model

Bro_Classification_Model(
  (BroEncoder): Encoder(
    (emb): Embed(
      (tok_layer): Embedding(9000, 256)
      (pos_layer): PositionalEncoding(
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (norm_do): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Dropout(p=0.1, inplace=False)
      )
    )
    (layers): Sequential(
      (0): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (1): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (2): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (3): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (4): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
      (5): Encoder_Block(
        (MHA): Attention_Block(
          (heads): ModuleList(
            (0-7): 8 x Attention(
              (query): Linear(in_features=256, out_features=32, bias=True)
              (key): Linear(in_features=256, out_features=32, bias=True)
              (value): Linear(in_features=256, out_features=32, bias=True)
              (att_do): Dropout(p=0.1, inplace=False)
            )
          )
          (lin_do): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): Dropout(p=0.1, inplace=False)
          )
        )
        (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (ff): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
        (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (Bro_MLM): MLM(
    (encoder): Encoder(
      (emb): Embed(
        (tok_layer): Embedding(9000, 256)
        (pos_layer): PositionalEncoding(
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (norm_do): Sequential(
          (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (layers): Sequential(
        (0): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (1): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (2): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (3): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (4): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (5): Encoder_Block(
          (MHA): Attention_Block(
            (heads): ModuleList(
              (0-7): 8 x Attention(
                (query): Linear(in_features=256, out_features=32, bias=True)
                (key): Linear(in_features=256, out_features=32, bias=True)
                (value): Linear(in_features=256, out_features=32, bias=True)
                (att_do): Dropout(p=0.1, inplace=False)
              )
            )
            (lin_do): Sequential(
              (0): Linear(in_features=256, out_features=256, bias=True)
              (1): Dropout(p=0.1, inplace=False)
            )
          )
          (mha_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (ff): Sequential(
            (0): Linear(in_features=256, out_features=1024, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1024, out_features=256, bias=True)
            (3): Dropout(p=0.1, inplace=False)
          )
          (enc_blk_end_layernorm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
    (mlm_layer): Sequential(
      (0): Linear(in_features=256, out_features=128, bias=True)
      (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=128, out_features=2, bias=True)
    )
  )
)

In [163]:
model, optimizer, average_loss, average_acc = train_model(num_epochs=10, lrate=0.0003,
                                                          model=bro_model, dl=train_dl,
                                                          test_dl=test_dl, device=device,
                                                          vocab_size=2)

Step: 0, Loss: 0.8127052783966064
Step: 200, Loss: 0.46270430088043213
Step: 400, Loss: 0.5631912350654602
Step: 600, Loss: 0.6299863457679749
Epoch: 0 -- Average training Loss: 0.4378236967277527
Epoch: 0 -- Average training Accuracy: 0.79732
Average Test loss: 0.3767437571048737
Average Test Accuracy: 0.8342
saving model
Step: 0, Loss: 0.3684602975845337
Step: 200, Loss: 0.7427643537521362
Step: 400, Loss: 0.2368483990430832
Step: 600, Loss: 0.3925231993198395
Epoch: 1 -- Average training Loss: 0.355702325425148
Epoch: 1 -- Average training Accuracy: 0.84464
Average Test loss: 0.36056462383270266
Average Test Accuracy: 0.8436
saving model
Step: 0, Loss: 0.15949581563472748
Step: 200, Loss: 0.2605215311050415
Step: 400, Loss: 0.2404199242591858
Step: 600, Loss: 0.26854878664016724
Epoch: 2 -- Average training Loss: 0.30536746253013614
Epoch: 2 -- Average training Accuracy: 0.86952
Average Test loss: 0.3376775577545166
Average Test Accuracy: 0.8464
saving model
Step: 0, Loss: 0.2564046382904053
Step: 200, Loss: 0.2504136562347412
Step: 400, Loss: 0.26359823346138
Step: 600, Loss: 0.5447407960891724
Epoch: 3 -- Average training Loss: 0.2636064229488373
Epoch: 3 -- Average training Accuracy: 0.8898
Average Test loss: 0.482204753780365
Average Test Accuracy: 0.8192
saving model
Step: 0, Loss: 0.1854097843170166
Step: 200, Loss: 0.17713160812854767
Step: 400, Loss: 0.25141969323158264
Step: 600, Loss: 0.14756712317466736
Epoch: 4 -- Average training Loss: 0.225672662358284
Epoch: 4 -- Average training Accuracy: 0.9082
Average Test loss: 0.3919127082824707
Average Test Accuracy: 0.8436
saving model
Step: 0, Loss: 0.20966599881649017
Step: 200, Loss: 0.15425564348697662
Step: 400, Loss: 0.2943136394023895
Step: 600, Loss: 0.21428363025188446
Epoch: 5 -- Average training Loss: 0.1908082795715332
Epoch: 5 -- Average training Accuracy: 0.9238
Average Test loss: 0.4100700105190277
Average Test Accuracy: 0.8384
saving model
Step: 0, Loss: 0.08878149092197418
Step: 200, Loss: 0.24627555906772614
Step: 400, Loss: 0.11736893653869629
Step: 600, Loss: 0.29486504197120667
Epoch: 6 -- Average training Loss: 0.15598008499383925
Epoch: 6 -- Average training Accuracy: 0.93736
Average Test loss: 0.653476789188385
Average Test Accuracy: 0.7664
saving model
Step: 0, Loss: 0.15986987948417664
Step: 200, Loss: 0.09366267174482346
Step: 400, Loss: 0.11651524156332016
Step: 600, Loss: 0.14526082575321198
Epoch: 7 -- Average training Loss: 0.1301131991958618
Epoch: 7 -- Average training Accuracy: 0.94948
Average Test loss: 0.6609454664826393
Average Test Accuracy: 0.8004
saving model
Step: 0, Loss: 0.04842755198478699
Step: 200, Loss: 0.055491186678409576
Step: 400, Loss: 0.19065380096435547
Step: 600, Loss: 0.16166409850120544
Epoch: 8 -- Average training Loss: 0.12126808844923972
Epoch: 8 -- Average training Accuracy: 0.95372
Average Test loss: 0.5579345310211181
Average Test Accuracy: 0.8292
saving model
Step: 0, Loss: 0.02343270182609558
Step: 200, Loss: 0.25414422154426575
Step: 400, Loss: 0.045777834951877594
Step: 600, Loss: 0.1463678628206253
Epoch: 9 -- Average training Loss: 0.10081201140224934
Epoch: 9 -- Average training Accuracy: 0.9612
Average Test loss: 0.5978612891316414
Average Test Accuracy: 0.84
saving model

In [174]:
model, optimizer, average_loss, average_acc = train_model(num_epochs=6, lrate=0.0003,
                                                          model=model, dl=train_dl,
                                                          test_dl=test_dl, device=device,
                                                          vocab_size=2)

Step: 0, Loss: 0.16213944554328918
Step: 200, Loss: 0.041101571172475815
Step: 400, Loss: 0.16001741588115692
Step: 600, Loss: 0.1139909103512764
Epoch: 0 -- Average training Loss: 0.09906813566178084
Epoch: 0 -- Average training Accuracy: 0.96152
Average Test loss: 0.5858877855777741
Average Test Accuracy: 0.83
Step: 0, Loss: 0.027473606169223785
Step: 200, Loss: 0.09507177770137787
Step: 400, Loss: 0.01149538904428482
Step: 600, Loss: 0.01848793774843216
Epoch: 1 -- Average training Loss: 0.08543457690298557
Epoch: 1 -- Average training Accuracy: 0.96728
Average Test loss: 0.695128291913867
Average Test Accuracy: 0.8346
Step: 0, Loss: 0.06963293999433517
Step: 200, Loss: 0.08692055195569992
Step: 400, Loss: 0.15298910439014435
Step: 600, Loss: 0.267459899187088
Epoch: 2 -- Average training Loss: 0.08575014843076467
Epoch: 2 -- Average training Accuracy: 0.9678
Average Test loss: 0.6013309459447861
Average Test Accuracy: 0.8286
Step: 0, Loss: 0.05309141427278519
Step: 200, Loss: 0.059357672929763794
Step: 400, Loss: 0.23786628246307373
Step: 600, Loss: 0.07486899942159653
Epoch: 3 -- Average training Loss: 0.13583593867719174
Epoch: 3 -- Average training Accuracy: 0.94748
Average Test loss: 0.4929994691133499
Average Test Accuracy: 0.8248
Step: 0, Loss: 0.13154026865959167
Step: 200, Loss: 0.0714273750782013
Step: 400, Loss: 0.05313697084784508
Step: 600, Loss: 0.021232150495052338
Epoch: 4 -- Average training Loss: 0.08222282081156969
Epoch: 4 -- Average training Accuracy: 0.96884
Average Test loss: 1.0721453122138977
Average Test Accuracy: 0.7726
Step: 0, Loss: 0.10671444237232208
Step: 200, Loss: 0.0452834852039814
Step: 400, Loss: 0.007746260613203049
Step: 600, Loss: 0.03068339265882969
Epoch: 5 -- Average training Loss: 0.06386764709949494
Epoch: 5 -- Average training Accuracy: 0.97588
Average Test loss: 0.6803093467235565
Average Test Accuracy: 0.7744

## following experiment gave best results. original bro model using single classification sequential and 0.1 dropout
#tomorrow try out once again using 0.05 dropout, no dropout and then 0.1 save each of the model
#model is learning well and very good rsults on test but kind of overfitting. we tried skip connections. it did not
#help. So perhaps it is more of an issue with model to originally trained on more data than we are using riggt now
#perhaps merge validation dataset with train and then use test data for validation but it will take lot of time 
#to train. Worth trying thought to rule out data hungriness.. see you tomorrow

In [115]:
model, optimizer, average_loss, average_acc = train_model(num_epochs=10, lrate=0.0003,
                                                          model=bro_model, dl=train_dl,
                                                          test_dl=test_dl, device=device,
                                                          vocab_size=2)

Step: 0, Loss: 0.29630622267723083
Step: 200, Loss: 0.3767191767692566
Step: 400, Loss: 0.27117452025413513
Step: 600, Loss: 0.4704580008983612
Epoch: 0 -- Average training Loss: 0.3578528818130493
Epoch: 0 -- Average training Accuracy: 0.84368
Average Test loss: 0.3778113238811493
Average Test Accuracy: 0.823
Step: 0, Loss: 0.41369813680648804
Step: 200, Loss: 0.24925951659679413
Step: 400, Loss: 0.22235561907291412
Step: 600, Loss: 0.221827894449234
Epoch: 1 -- Average training Loss: 0.3090490364646912
Epoch: 1 -- Average training Accuracy: 0.86836
Average Test loss: 0.34620957720279694
Average Test Accuracy: 0.838
Step: 0, Loss: 0.2785033881664276
Step: 200, Loss: 0.29370978474617004
Step: 400, Loss: 0.38096505403518677
Step: 600, Loss: 0.235026016831398
Epoch: 2 -- Average training Loss: 0.2738749547481537
Epoch: 2 -- Average training Accuracy: 0.88496
Average Test loss: 0.8523226054310798
Average Test Accuracy: 0.769
Step: 0, Loss: 0.2896747291088104
Step: 200, Loss: 0.2927595376968384
Step: 400, Loss: 0.215032160282135
Step: 600, Loss: 0.3201240301132202
Epoch: 3 -- Average training Loss: 0.2373767029285431
Epoch: 3 -- Average training Accuracy: 0.9036
Average Test loss: 0.4424243823885918
Average Test Accuracy: 0.832
Step: 0, Loss: 0.08524270355701447
Step: 200, Loss: 0.133751779794693
Step: 400, Loss: 0.3697534501552582
Step: 600, Loss: 0.2575252950191498
Epoch: 4 -- Average training Loss: 0.2009182875585556
Epoch: 4 -- Average training Accuracy: 0.91984
Average Test loss: 0.5238840489685536
Average Test Accuracy: 0.807
Step: 0, Loss: 0.10727711766958237
Step: 200, Loss: 0.14937514066696167
Step: 400, Loss: 0.1745268553495407
Step: 600, Loss: 0.10508449375629425
Epoch: 5 -- Average training Loss: 0.1768575390803814
Epoch: 5 -- Average training Accuracy: 0.92936
Average Test loss: 0.4089618592560291
Average Test Accuracy: 0.843
Step: 0, Loss: 0.1729506552219391
Step: 200, Loss: 0.18591630458831787
Step: 400, Loss: 0.20421409606933594
Step: 600, Loss: 0.07232651114463806
Epoch: 6 -- Average training Loss: 0.14809373423576355
Epoch: 6 -- Average training Accuracy: 0.94192
Average Test loss: 0.5516150118410588
Average Test Accuracy: 0.83
Step: 0, Loss: 0.2489282190799713
Step: 200, Loss: 0.1728333830833435
Step: 400, Loss: 0.05476202070713043
Step: 600, Loss: 0.048858143389225006
Epoch: 7 -- Average training Loss: 0.12965908619999886
Epoch: 7 -- Average training Accuracy: 0.94964
Average Test loss: 0.43639251539111135
Average Test Accuracy: 0.856
Step: 0, Loss: 0.07189951092004776
Step: 200, Loss: 0.053781285881996155
Step: 400, Loss: 0.07158251106739044
Step: 600, Loss: 0.2925528883934021
Epoch: 8 -- Average training Loss: 0.11451082803852856
Epoch: 8 -- Average training Accuracy: 0.95508
Average Test loss: 0.5975204569101333
Average Test Accuracy: 0.817
Step: 0, Loss: 0.1026744619011879
Step: 200, Loss: 0.17165930569171906
Step: 400, Loss: 0.01737024262547493
Step: 600, Loss: 0.04824908822774887
Epoch: 9 -- Average training Loss: 0.10073565234422684
Epoch: 9 -- Average training Accuracy: 0.96148
Average Test loss: 0.5192772985156625
Average Test Accuracy: 0.857

In [116]:
torch.cuda.empty_cache()

In [148]:
model, optimizer, average_loss, average_acc = train_model(num_epochs=10, lrate=0.0003,
                                                          model=bro_model, dl=train_dl,
                                                          test_dl=test_dl, device=device,
                                                          vocab_size=2)

Step: 0, Loss: 0.7909785509109497
Step: 200, Loss: 0.3639296591281891
Step: 400, Loss: 0.38096943497657776
Step: 600, Loss: 0.555366575717926
Epoch: 0 -- Average training Loss: 0.4390769592189789
Epoch: 0 -- Average training Accuracy: 0.79572
Average Test loss: 0.40017609858512876
Average Test Accuracy: 0.8188
Step: 0, Loss: 0.49086111783981323
Step: 200, Loss: 0.30750951170921326
Step: 400, Loss: 0.3301372230052948
Step: 600, Loss: 0.32998254895210266
Epoch: 1 -- Average training Loss: 0.34987502027511597
Epoch: 1 -- Average training Accuracy: 0.84496
Average Test loss: 0.4015485887050629
Average Test Accuracy: 0.8232
Step: 0, Loss: 0.32598480582237244
Step: 200, Loss: 0.1787509322166443
Step: 400, Loss: 0.5574291944503784
Step: 600, Loss: 0.2652207314968109
Epoch: 2 -- Average training Loss: 0.3022260072517395
Epoch: 2 -- Average training Accuracy: 0.86988
Average Test loss: 0.446350325012207
Average Test Accuracy: 0.8174
Step: 0, Loss: 0.3133648633956909
Step: 200, Loss: 0.2811741828918457
Step: 400, Loss: 0.2610442340373993
Step: 600, Loss: 0.1721968650817871
Epoch: 3 -- Average training Loss: 0.2611819619369507
Epoch: 3 -- Average training Accuracy: 0.88976
Average Test loss: 0.3937518024921417
Average Test Accuracy: 0.831
Step: 0, Loss: 0.16468867659568787
Step: 200, Loss: 0.11772476136684418
Step: 400, Loss: 0.23694463074207306
Step: 600, Loss: 0.07723212242126465
Epoch: 4 -- Average training Loss: 0.22074767621994018
Epoch: 4 -- Average training Accuracy: 0.9082
Average Test loss: 0.4806199743270874
Average Test Accuracy: 0.8226
Step: 0, Loss: 0.11092401295900345
Step: 200, Loss: 0.17200976610183716
Step: 400, Loss: 0.1757943481206894
Step: 600, Loss: 0.28604185581207275
Epoch: 5 -- Average training Loss: 0.19229676252841948
Epoch: 5 -- Average training Accuracy: 0.92164
Average Test loss: 0.40012535367012025
Average Test Accuracy: 0.8442
Step: 0, Loss: 0.12253236025571823
Step: 200, Loss: 0.05657171085476875
Step: 400, Loss: 0.181181862950325
Step: 600, Loss: 0.07516424357891083
Epoch: 6 -- Average training Loss: 0.16283301619052887
Epoch: 6 -- Average training Accuracy: 0.93392
Average Test loss: 0.4590791714668274
Average Test Accuracy: 0.839
Step: 0, Loss: 0.15699784457683563
Step: 200, Loss: 0.19325609505176544
Step: 400, Loss: 0.27181488275527954
Step: 600, Loss: 0.15726405382156372
Epoch: 7 -- Average training Loss: 0.1341096802508831
Epoch: 7 -- Average training Accuracy: 0.9474
Average Test loss: 0.5240277880072594
Average Test Accuracy: 0.8464
Step: 0, Loss: 0.11214596778154373
Step: 200, Loss: 0.057254962623119354
Step: 400, Loss: 0.03971730172634125
Step: 600, Loss: 0.06429865211248398
Epoch: 8 -- Average training Loss: 0.1186546756708622
Epoch: 8 -- Average training Accuracy: 0.95516
Average Test loss: 0.6738898951053619
Average Test Accuracy: 0.7974
Step: 0, Loss: 0.030905475839972496
Step: 200, Loss: 0.03679613769054413
Step: 400, Loss: 0.09242668747901917
Step: 600, Loss: 0.09470407664775848
Epoch: 9 -- Average training Loss: 0.10990277182459832
Epoch: 9 -- Average training Accuracy: 0.959
Average Test loss: 0.6581226485729218
Average Test Accuracy: 0.832

In [191]:
#thrd run

In [193]:
model, optimizer, average_loss, average_acc = train_model(num_epochs=10, lrate=0.0003,
                                                          model=bro_model, dl=train_dl,
                                                          test_dl=test_dl, device=device,
                                                          vocab_size=2)

Step: 0, Loss: 0.8423508405685425
Step: 200, Loss: 0.6513998508453369
Step: 400, Loss: 0.5072464942932129
Step: 600, Loss: 0.4617939293384552
Epoch: 0 -- Average training Loss: 0.44616307553291323
Epoch: 0 -- Average training Accuracy: 0.79076
Average Test loss: 0.660544674873352
Average Test Accuracy: 0.7104
Step: 0, Loss: 0.3452816307544708
Step: 200, Loss: 0.38347098231315613
Step: 400, Loss: 0.4230605959892273
Step: 600, Loss: 0.40187007188796997
Epoch: 1 -- Average training Loss: 0.351481398563385
Epoch: 1 -- Average training Accuracy: 0.84268
Average Test loss: 0.4341929154396057
Average Test Accuracy: 0.8034
Step: 0, Loss: 0.2827933132648468
Step: 200, Loss: 0.22288374602794647
Step: 400, Loss: 0.414408802986145
Step: 600, Loss: 0.2525902986526489
Epoch: 2 -- Average training Loss: 0.3034148890638351
Epoch: 2 -- Average training Accuracy: 0.86924
Average Test loss: 0.35769237060546877
Average Test Accuracy: 0.8422
Step: 0, Loss: 0.10430754721164703
Step: 200, Loss: 0.12726598978042603
Step: 400, Loss: 0.2371678352355957
Step: 600, Loss: 0.1475566327571869
Epoch: 3 -- Average training Loss: 0.2687581581401825
Epoch: 3 -- Average training Accuracy: 0.88688
Average Test loss: 0.3332943400859833
Average Test Accuracy: 0.8496
Step: 0, Loss: 0.13917304575443268
Step: 200, Loss: 0.3556936979293823
Step: 400, Loss: 0.28913551568984985
Step: 600, Loss: 0.17653381824493408
Epoch: 4 -- Average training Loss: 0.23373100769519806
Epoch: 4 -- Average training Accuracy: 0.90228
Average Test loss: 0.36490974650382996
Average Test Accuracy: 0.8482
Step: 0, Loss: 0.28593894839286804
Step: 200, Loss: 0.07741794735193253
Step: 400, Loss: 0.11871963739395142
Step: 600, Loss: 0.29114919900894165
Epoch: 5 -- Average training Loss: 0.19953856142044069
Epoch: 5 -- Average training Accuracy: 0.91796
Average Test loss: 0.5377678734302521
Average Test Accuracy: 0.7792
Step: 0, Loss: 0.15038561820983887
Step: 200, Loss: 0.08850003778934479
Step: 400, Loss: 0.03043234720826149
Step: 600, Loss: 0.2993123233318329
Epoch: 6 -- Average training Loss: 0.16943737461805344
Epoch: 6 -- Average training Accuracy: 0.93136
Average Test loss: 0.45967926993370056
Average Test Accuracy: 0.8264
Step: 0, Loss: 0.12111272662878036
Step: 200, Loss: 0.0562196783721447
Step: 400, Loss: 0.09832233190536499
Step: 600, Loss: 0.3211735486984253
Epoch: 7 -- Average training Loss: 0.14673544239282607
Epoch: 7 -- Average training Accuracy: 0.94332
Average Test loss: 0.5968518186092376
Average Test Accuracy: 0.8218
Step: 0, Loss: 0.07581734657287598
Step: 200, Loss: 0.101437047123909
Step: 400, Loss: 0.11893945932388306
Step: 600, Loss: 0.06518437713384628
Epoch: 8 -- Average training Loss: 0.1316652869206667
Epoch: 8 -- Average training Accuracy: 0.947
Average Test loss: 0.4868341685295105
Average Test Accuracy: 0.843
Step: 0, Loss: 0.07376399636268616
Step: 200, Loss: 0.09386174380779266
Step: 400, Loss: 0.15848849713802338
Step: 600, Loss: 0.04973665624856949
Epoch: 9 -- Average training Loss: 0.12687828743994237
Epoch: 9 -- Average training Accuracy: 0.94932
Average Test loss: 0.5616742713928222
Average Test Accuracy: 0.8232

In [194]:
torch.save({
        'epoch': 10,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss': average_loss,
        'device': device
        }, './imdb_skip_bro.pt')

In [195]:
model, optimizer, average_loss, average_acc = train_model(num_epochs=5, lrate=0.001,
                                                          model=model, dl=train_dl,
                                                          test_dl=test_dl, device=device,
                                                          vocab_size=2)

Step: 0, Loss: 0.08310122042894363
Step: 200, Loss: 0.39325278997421265
Step: 400, Loss: 0.3325696885585785
Step: 600, Loss: 0.2620108425617218
Epoch: 0 -- Average training Loss: 0.3049830710029602
Epoch: 0 -- Average training Accuracy: 0.86716
Average Test loss: 1.6374860614776612
Average Test Accuracy: 0.5826
Step: 0, Loss: 0.2888806164264679
Step: 200, Loss: 0.3544050455093384
Step: 400, Loss: 0.3804762363433838
Step: 600, Loss: 0.30437350273132324
Epoch: 1 -- Average training Loss: 0.2651524244403839
Epoch: 1 -- Average training Accuracy: 0.88664
Average Test loss: 0.8935859023094177
Average Test Accuracy: 0.6756
Step: 0, Loss: 0.14580285549163818
Step: 200, Loss: 0.1806003600358963
Step: 400, Loss: 0.20146822929382324
Step: 600, Loss: 0.5246925354003906
Epoch: 2 -- Average training Loss: 0.2551437360107899
Epoch: 2 -- Average training Accuracy: 0.89432
Average Test loss: 0.5087716403961182
Average Test Accuracy: 0.8106
Step: 0, Loss: 0.17919081449508667
Step: 200, Loss: 0.1668112874031067
Step: 400, Loss: 0.36898142099380493
Step: 600, Loss: 0.4444487988948822
Epoch: 3 -- Average training Loss: 0.24005168176651
Epoch: 3 -- Average training Accuracy: 0.89936
Average Test loss: 0.6269377774238586
Average Test Accuracy: 0.7698
Step: 0, Loss: 0.12490175664424896
Step: 200, Loss: 0.22068563103675842
Step: 400, Loss: 0.10019145160913467
Step: 600, Loss: 0.21117570996284485
Epoch: 4 -- Average training Loss: 0.23207562485218047
Epoch: 4 -- Average training Accuracy: 0.90332
Average Test loss: 0.4419543561935425
Average Test Accuracy: 0.8108