To implement decoder model architecture, we will need to accomplish following tasks:

1) Text needs to be converted into tokens

2) For step 1, we will need to implement a tokenizer

3) For step 2, we will create a character based tokenizer and train it on data corpus

4) tokenizer should be able to convert text into numbers(encode) and convert numbers back to characters(decode)

5) tokenizer will have its own vocab and dictionaries to perform forward and reverse lookups

6) We will need a dataset which will be converted into iterator and dataloader be created after it. 
Dataloader should create inputs and labels such that labels are 1 position behind the input(DataCollator for Language Modeling in hugging face).

7) We need to create decoder model now

8) First step is to create embedding layer whose input size is equal to vocabulary size and output size is equal to number of dimensions we want to create for each input.

9) Second step is to create positional embeddings whose input size is equal to context length and output isze is equal to model dimension(same as in step 8)

10) add 8+9 and then feed it to decoder block

11) Decoder --> layer norm --> Attention head --> concat attention heads--> add linear layer--> feed forward layer - expand and squeeze with gelu in between (add dropout and layer norm as required)

12) Create decoder layers

13) Finally put linear layer which converts model dimension to vocab dimension for each position

14) train the model

## Let us implement character tokenizer

Steps in implementing chracter tokenizer:
1) Reading the text and creating a vocabulary
2) Mapping vocab tokens to ids and then from ids to vocab tokens
3) Encode function that takes text; convert it into tokens and then into token ids
4) Decode function that takes tokenids, converts into tokens and then joins tokens to form a coherent text

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from pathlib import Path
import sys
from torch.utils.data import Dataset, DataLoader, RandomSampler

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu

In [3]:
try:
    from datasets import load_dataset
except:
    print("datasets package is not installed. installing it now. Please remember to start kernel once installation is complete")
    !pip install datasets==3.3.2
    print("Please restart your kernel now")

In [4]:
ds = load_dataset("Trelis/tiny-shakespeare")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/497 [00:00<?, ?B/s]

train.csv: 0.00B [00:00, ?B/s]

test.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/472 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/49 [00:00<?, ? examples/s]

In [5]:
ds

DatasetDict({
    train: Dataset({
        features: ['Text'],
        num_rows: 472
    })
    test: Dataset({
        features: ['Text'],
        num_rows: 49
    })
})

In [6]:
len(ds['train'][0]['Text'])

3131

In [7]:
len_train = len(ds['train'])

In [8]:
for i in range(len_train):
    print(len(ds['train'][i]['Text']))

3131
1703
1614
3199
3159
2872
2969
2847
1930
2451
2507
3046
3122
3081
2701
3265
2478
2750
2796
2550
2863
2410
3173
2218
2813
2562
1264
1708
3239
2945
2417
2488
2554
2601
1802
2767
2743
1029
2009
2165
3295
2541
2435
3013
3128
2843
2930
2428
2502
2964
1997
3116
2622
2794
2849
2636
3142
2763
2656
3038
3090
2896
3239
3070
2438
3158
2773
2050
3261
2886
3234
3076
1406
2902
3065
225
2923
3075
3186
1667
3050
3157
2912
1437
1632
2189
3068
1158
2014
2688
3059
1558
1556
3042
3103
1966
2683
1448
1637
3003
3255
2337
2970
3267
593
2232
2508
3135
3143
2472
2963
3114
3202
3324
3209
3396
2109
2848
2965
3007
2111
2931
3114
3020
3125
2947
2986
3362
2688
1986
2961
1184
2012
3137
2372
2918
2003
3266
1361
1853
2707
3081
3283
3304
2679
3286
1377
1857
3171
3313
3035
3107
1897
3301
3352
3185
1572
1676
2705
3076
2458
3103
2193
3025
2403
1387
1842
3251
3146
905
2399
3387
623
2674
3281
3318
255
3141
3349
3422
3009
2986
3156
3057
3027
3307
2477
2894
62
3238
3228
3113
1558
2635
1339
1676
2985
40
2942
2923
2056
3311
1239
1985
3168
2025
3079
2177
2816
3295
2874
2736
2132
2873
2227
2542
2382
2062
2521
2912
2636
2671
3139
3207
2995
2060
2712
2623
2314
3047
74
3165
3160
2248
2200
1945
2894
2473
1628
1495
2864
1282
1770
3002
2553
3221
1726
2962
2734
1850
2368
2908
176
2750
2904
3311
2239
3129
2100
1868
2051
3185
943
2167
2790
2508
2859
1632
3104
2780
3131
847
2495
3246
225
2834
3047
2254
2880
2683
1308
1898
3042
199
2929
3040
3116
3260
3104
3179
3290
196
3104
3290
3224
3109
3140
3332
3190
124
3180
3193
1863
3094
3138
2680
2419
3323
3156
3254
3286
3190
3281
2360
3223
3189
3162
3342
3174
3071
3047
2837
3069
2273
3420
3019
2679
3027
3254
3283
2222
2713
2622
2698
2205
3148
2964
3061
1868
2739
2925
1892
2724
2998
3073
2055
2866
3091
3094
3060
972
2274
3050
2766
2726
3105
2816
2527
3039
2376
2759
2169
2900
2316
2389
1397
1699
2726
2054
2749
2102
2785
2806
3038
3026
2658
2742
3063
2821
2454
3053
2802
3130
3472
3586
2679
2453
2835
3096
3337
2430
2702
2768
3105
1899
2700
2921
1314
1840
2726
2860
2420
2969
2522
2950
2972
3010
2171
1820
3197
2903
2286
2587
2674
3206
3189
2986
2104
2896
2359
3234
2785
2805
1936
2873
2661
3205
1975
2528
2943
2913
2841
2909
2536
1742
2675
1407
1862
2756
2879
1532
3173
2914
1994
992
2099
3200
18
3363
3362
130
3222
3222
1911
3450
2494
1922
2946
3076
2714
2847
2021
2982
1424
1397
3018
2941
1552
1771
3148
2607
2983

In [9]:
#lets combine all the data together train+test together

In [10]:
ds

DatasetDict({
    train: Dataset({
        features: ['Text'],
        num_rows: 472
    })
    test: Dataset({
        features: ['Text'],
        num_rows: 49
    })
})

In [11]:
df_train = ds['train'].to_pandas()
df_train

                                                  Text
0    First Citizen:\nBefore we proceed any further,...
1    Alack,\nYou are transported by calamity\nThith...
2    With a kind of smile,\nWhich ne'er came from t...
3    With a kind of smile,\nWhich ne'er came from t...
4    Your virtue is\nTo make him worthy whose offen...
..                                                 ...
467  To express the like kindness, myself,\nthat ha...
468  You are passing welcome,\nAnd so I pray you al...
469  You are passing welcome,\nAnd so I pray you al...
470  Good morrow, Kate; for that's your name, I hea...
471  Well aim'd of such a young one.\n\nPETRUCHIO:\...

[472 rows x 1 columns]

In [12]:
df_test = ds['test'].to_pandas()
df_test

                                                 Text
0   TRANIO:\nIs this your speeding? nay, then, goo...
1   Sir, list to me:\nI am my father's heir and on...
2   And, to cut off all strife, here sit we down:\...
3   Now, Licio, to you:\nGood masters, take it not...
4   TRANIO:\nPatience, good Katharina, and Baptist...
5   And yet I come not well.\n\nBAPTISTA:\nAnd yet...
6   we'll fit him to our turn,--\nAnd he shall be ...
7   But that his beard grew thin and hungerly\nAnd...
8   Grumio,\nDraw forth thy weapon, we are beset w...
9   But wilt thou make a\nfire, or shall I complai...
10  But what talk I of this?\nCall forth Nathaniel...
11  Some water, here; what, ho!\nWhere's my spanie...
12  He that knows better how to tame a shrew,\nNow...
13  TRANIO:\nWhat is he, Biondello?\n\nBIONDELLO:\...
14  Know you not the cause?\nYour ships are stay'd...
15  Know you not the cause?\nYour ships are stay'd...
16  That feed'st me with the very name of meat:\nS...
17  PETRUCHIO:\nO monstrous arrogance! Thou liest,...
18  I say unto\nthee, I bid thy master cut out the...
19  I say unto\nthee, I bid thy master cut out the...
20  Sirs, let't alone:\nI will not go to-day; and ...
21  Biondello, hie you home,\nAnd bid Bianca make ...
22  My master hath appointed me to go to Saint\nLu...
23  As those two eyes become that heavenly face?\n...
24  Wonder not,\nNor be grieved: she is of good es...
25  Wonder not,\nNor be grieved: she is of good es...
26  What, have you forgot me?\n\nBIONDELLO:\nForgo...
27  Father Baptista,\nI charge you see that he be ...
28  Bianca's love\nMade me exchange my state with ...
29  Pray you, sit down;\nFor now we sit to chat as...
30  Here, Signior Tranio.\nThis bird you aim'd at,...
31  What is the wager?\n\nLUCENTIO:\nTwenty crowns...
32  PETRUCHIO:\nThe fouler fortune mine, and there...
33  Why are our bodies soft and weak and smooth,\n...
34  If he be not\nborn to be hanged, our case is m...
35  Poor souls, they perish'd.\nHad I been any god...
36  But how is it\nThat this lives in thy mind? Wh...
37  He being thus lorded,\nNot only with what my r...
38  Thou didst smile.\nInfused with a fortitude fr...
39  All but mariners\nPlunged in the foaming brine...
40  This damn'd witch Sycorax,\nFor mischiefs mani...
41  What, ho! slave! Caliban!\nThou earth, thou! s...
42  The red plague rid you\nFor learning me your l...
43  He does hear me;\nAnd that he does I weep: mys...
44  What!\nAn advocate for an imposter! hush!\nTho...
45  Our hint of woe\nIs common; every day some sai...
46  The wager?\n\nANTONIO:\nA laughter.\n\nSEBASTI...
47  GONZALO:\nI assure you, Carthage.\n\nSEBASTIAN...
48  We have lost your\nson,\nI fear, for ever: Mil...

In [13]:
len(df_train), len(df_test)

(472, 49)

In [14]:
df_train.columns, df_test.columns

(Index(['Text'], dtype='object'), Index(['Text'], dtype='object'))

In [15]:
#let us mrge the two datasets together
df = pd.concat([df_train, df_test], axis=0)
df.reset_index(inplace=True, drop=True)
len(df)

521

In [16]:
df

                                                  Text
0    First Citizen:\nBefore we proceed any further,...
1    Alack,\nYou are transported by calamity\nThith...
2    With a kind of smile,\nWhich ne'er came from t...
3    With a kind of smile,\nWhich ne'er came from t...
4    Your virtue is\nTo make him worthy whose offen...
..                                                 ...
516  What!\nAn advocate for an imposter! hush!\nTho...
517  Our hint of woe\nIs common; every day some sai...
518  The wager?\n\nANTONIO:\nA laughter.\n\nSEBASTI...
519  GONZALO:\nI assure you, Carthage.\n\nSEBASTIAN...
520  We have lost your\nson,\nI fear, for ever: Mil...

[521 rows x 1 columns]

In [17]:
shakes_ds = './shakes_ds.csv'
df.to_csv(shakes_ds, index=False)
!ls -ltr

total 169596
drwxrwxr-x  3 ec2-user ec2-user      4096 Feb 22  2025 scripts
-rw-rw-r--  1 ec2-user ec2-user 135751680 Mar 16  2025 brogpt.tar
-rw-rw-r--  1 ec2-user ec2-user  28924927 Mar 22  2025 agnews_train
-rw-rw-r--  1 ec2-user ec2-user   1822708 Mar 22  2025 agnews_test
-rw-rw-r--  1 ec2-user ec2-user    292466 Apr 25 06:48 BroGPT.ipynb
-rw-rw-r--  1 ec2-user ec2-user   1890137 Apr 25 07:35 BroGPT-GPT2TOK.ipynb
drwxrwxr-x  3 ec2-user ec2-user      4096 Apr 25 08:44 model_ckpts
-rw-rw-r--  1 ec2-user ec2-user    129719 Apr 25 11:44 Encoder_MLM.ipynb
-rw-rw-r--  1 ec2-user ec2-user   1341374 Apr 25 15:56 shakes_ds.txt
-rw-rw-r--  1 ec2-user ec2-user   1871240 Apr 25 16:10 BroGPT-GPT2Pretrained.ipynb
drwxrwxr-x 10 ec2-user ec2-user      4096 Apr 26 17:06 encoder-decoder
-rw-rw-r--  1 ec2-user ec2-user    269166 May 21 03:32 BroGPT-v1.ipynb
-rw-rw-r--  1 ec2-user ec2-user   1342940 May 21 03:36 shakes_ds.csv

In [18]:
df['txt_len'] = df['Text'].apply(lambda x: len(x))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Text     521 non-null    object
 1   txt_len  521 non-null    int64
dtypes: int64(1), object(1)
memory usage: 8.3+ KB

In [19]:
df.describe()

           txt_len
count   521.000000
mean   2574.614203
std     693.507375
min      18.000000
25%    2218.000000
50%    2796.000000
75%    3076.000000
max    3586.000000

In [20]:
#While we can read directly from df/csv to create dataset, we will need to break it as irregular intervals
#as we see there is a huge variation in length of indiviual texts
#let us now write the entire text in normal text file. This will help us batch things better without wasting
#on padding tokens

In [21]:
len(df['Text'].to_list())

521

In [22]:
shakes_txt = './shakes_ds.txt'
with open(shakes_txt, 'w') as f:
    for i in range(len(df)):
        f.write(df['Text'].iloc[i])

In [23]:
!head ./shakes_ds.txt

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:

In [24]:
!tail -50  ./shakes_ds.txt

Execute all things; for no kind of traffic
Would I admit; no name of magistrate;
Letters should not be known; riches, poverty,
And use of service, none; contract, succession,
Bourn, bound of land, tilth, vineyard, none;
No use of metal, corn, or wine, or oil;
No occupation; all men idle, all;
And women too, but innocent and pure;
No sovereignty;--

SEBASTIAN:
Yet he would be king on't.

ANTONIO:
The latter end of his commonwealth forgets the
beginning.

GONZALO:
All things in common nature should produce
Without sweat or endeavour: treason, felony,
Sword, pike, knife, gun, or need of any engine,
Would I not have; but nature should bring forth,
Of its own kind, all foison, all abundance,
To feed my innocent people.

SEBASTIAN:
No marrying 'mong his subjects?

ANTONIO:
None, man; all idle: whores and knaves.

GONZALO:
I would with such perfection govern, sir,
To excel the golden age.

SEBASTIAN:
God save his majesty!

ANTONIO:
Long live Gonzalo!

GONZALO:
And,--do you mark me, sir?

ALONSO:
Prithee, no more: thou dost talk nothing to me.

GONZALO:
I do well believe your highness; and
did it to minister occasion to these gentlemen,

In [25]:
vocab_text = Path('./shakes_ds.txt').read_text()

In [26]:
#lets try reading from text file in pythonic way
print(vocab_text[0:200])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you

In [27]:
set(vocab_text)

{'\n',
 ' ',
 '!',
 '$',
 '&',
 "'",
 ',',
 '-',
 '.',
 '3',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [28]:
class Char_Tokenizer:
    def __init__(self, text):
        super().__init__()
        self.text = text
        self.vocab = None
        self.tok_list = None
        self.t2i = None
        self.i2t = None
        self.len_vocab = None

    def create_vocab(self):
        self.vocab = set(self.text)
        return sorted(list(self.vocab))

    def train_tokenizer(self):
        self.tok_list = self.create_vocab()
        # tokens created . lets create forwrd and reverse mapping
        self.t2i = {token: index for index, token in enumerate(self.tok_list)}
        self.i2t = {index: token for index, token in enumerate(self.tok_list)}
        self.len_vocab = self.vocab_size()

    def vocab_size(self):
        if self.tok_list is None:
            print("errrrrr Error dude.. you should train the tokenizer first")
        else:
            return len(self.tok_list)

    def encode(self, text, return_tensors=False):
        inputs = [self.t2i[c] for c in text]
        if return_tensors:
            inputs = torch.tensor(inputs)
        return inputs

    def decode(self, inputs, tensors=False):
        if tensors:
            inputs = inputs.squeeze().tolist()
        toks = [self.i2t[i] for i in inputs]
        join_toks = ''.join(toks)
        #right now support is only for one sentence
        return join_toks

    def __str__(self):
        return f"token2index: {self.t2i},\
                index2token: {self.i2t},\
                vocab_len: {self.len_vocab}"

    def __repr__(self):
        return f"token2index: {self.t2i},\
                index2token: {self.i2t},\
                vocab_len: {self.len_vocab}"

In [29]:
tokenizer = Char_Tokenizer(vocab_text)

In [30]:
tokenizer.vocab #Vocab is empty

In [31]:
tokenizer.vocab is None

True

In [32]:
#let us train our tokenizer
tokenizer.train_tokenizer()

In [33]:
tokenizer.vocab is None

False

In [34]:
tokenizer.vocab

{'\n',
 ' ',
 '!',
 '$',
 '&',
 "'",
 ',',
 '-',
 '.',
 '3',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [35]:
tokenizer.i2t

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [36]:
tokenizer.t2i

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [37]:
toks = tokenizer.encode("Shaheer")

In [38]:
print(toks)

[31, 46, 39, 46, 43, 43, 56]

In [39]:
tokenizer.decode(toks) 
# Can it really decode me lol!
# Dude dont take it on heart. Its just converting integers to text thats it bro

'Shaheer'

In [40]:
text = "This is a beautiful day"
text

'This is a beautiful day'

In [41]:
enc = tokenizer.encode(text, return_tensors=True)
enc, enc.shape

(tensor([32, 46, 47, 57,  1, 47, 57,  1, 39,  1, 40, 43, 39, 59, 58, 47, 44, 59,
         50,  1, 42, 39, 63]),
 torch.Size([23]))

In [42]:
dec = tokenizer.decode(enc, tensors=True)
dec

'This is a beautiful day'

In [43]:
tokenizer.len_vocab

65

In [44]:
tokenizer

token2index: {'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64},                index2token: {0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i', 48: 'j', 49: 'k', 50: 'l', 51: 'm', 52: 'n', 53: 'o', 54: 'p', 55: 'q', 56: 'r', 57: 's', 58: 't', 59: 'u', 60: 'v', 61: 'w', 62: 'x', 63: 'y', 64: 'z'},                vocab_len: 65

In [45]:
print(tokenizer)

token2index: {'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64},                index2token: {0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i', 48: 'j', 49: 'k', 50: 'l', 51: 'm', 52: 'n', 53: 'o', 54: 'p', 55: 'q', 56: 'r', 57: 's', 58: 't', 59: 'u', 60: 'v', 61: 'w', 62: 'x', 63: 'y', 64: 'z'},                vocab_len: 65

In [46]:
class Embed(nn.Module):
    def __init__(self, vocab_size, embed_dim, ctx_len, do, device):
        super().__init__()
        self.tok_layer = nn.Embedding(vocab_size, embed_dim)
        self.pos_layer = nn.Embedding(ctx_len, embed_dim)
        self.norm_do = nn.Sequential(
            nn.LayerNorm(embed_dim),
            nn.Dropout(do)
            )
        self.device = device
        self.ctx_len = ctx_len

    def forward(self, inp):
        inp = inp.to(self.device)
        tok_embed = self.tok_layer(inp)
        len_inp = inp.shape[-1]
        try:
            assert len_inp <= self.ctx_len
        except:
            print("Err..Errr. Error...Bro..Length of supplied text exceeds context length defined.Exiting the program now")
            sys.exit(1)
        pos_range = torch.arange(0, len_inp).unsqueeze(0)
        pos_range = pos_range.to(self.device)
        pos_embed = self.pos_layer(pos_range)
        embed_tok_pos = tok_embed + pos_embed
        embed_out = self.norm_do(embed_tok_pos)
        return embed_out

In [47]:
device

'cpu'

In [48]:
embed_mod = Embed(vocab_size=65, embed_dim=768, ctx_len=64, do=0.1, device=device)
embed_mod

Embed(
  (tok_layer): Embedding(65, 768)
  (pos_layer): Embedding(64, 768)
  (norm_do): Sequential(
    (0): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (1): Dropout(p=0.1, inplace=False)
  )
)

In [49]:
#this is just a song that popped in my head from movie named "Amar Akbar Anthony"
text_1 = "My name is Anthony Gonsalvez. Main duniya mein akela hoon."
text_1

'My name is Anthony Gonsalvez. Main duniya mein akela hoon.'

In [50]:
text_2 = "My name is Anthony Gonsalvez. Main duniya mein akela hoon. Dil bhi hai khaali"
text_2, len(text_2)

('My name is Anthony Gonsalvez. Main duniya mein akela hoon. Dil bhi hai khaali',
 77)

In [51]:
toks_1 = tokenizer.encode(text_1, return_tensors=True)
toks_1, toks_1.shape

(tensor([25, 63,  1, 52, 39, 51, 43,  1, 47, 57,  1, 13, 52, 58, 46, 53, 52, 63,
          1, 19, 53, 52, 57, 39, 50, 60, 43, 64,  8,  1, 25, 39, 47, 52,  1, 42,
         59, 52, 47, 63, 39,  1, 51, 43, 47, 52,  1, 39, 49, 43, 50, 39,  1, 46,
         53, 53, 52,  8]),
 torch.Size([58]))

In [52]:
toks_1_embed = embed_mod(toks_1)
toks_1_embed, toks_1_embed.shape

(tensor([[[ 1.4306, -0.8432, -0.2262,  ...,  0.4541, -0.0868,  0.4184],
          [ 0.5810, -0.5322, -0.2585,  ...,  0.5928, -0.8726,  1.8925],
          [ 0.0000, -1.2712, -1.7825,  ...,  0.5603,  0.3001, -1.7606],
          ...,
          [ 1.7750,  1.3187,  0.4860,  ..., -0.0794, -0.6084, -1.2465],
          [-0.2925, -0.3224, -0.7986,  ..., -0.0885,  1.5241, -0.3266],
          [ 0.3488,  0.3298,  0.1780,  ..., -0.6603, -0.5312, -0.0941]]],
        grad_fn=<MulBackward0>),
 torch.Size([1, 58, 768]))

In [53]:
toks_2 = tokenizer.encode(text_2, return_tensors=True)
toks_2, toks_2.shape

(tensor([25, 63,  1, 52, 39, 51, 43,  1, 47, 57,  1, 13, 52, 58, 46, 53, 52, 63,
          1, 19, 53, 52, 57, 39, 50, 60, 43, 64,  8,  1, 25, 39, 47, 52,  1, 42,
         59, 52, 47, 63, 39,  1, 51, 43, 47, 52,  1, 39, 49, 43, 50, 39,  1, 46,
         53, 53, 52,  8,  1, 16, 47, 50,  1, 40, 46, 47,  1, 46, 39, 47,  1, 49,
         46, 39, 39, 50, 47]),
 torch.Size([77]))

In [54]:
#This should error out as tokenized length is greater than context length
toks_2_embed = embed_mod(toks_2)
toks_2_embed, toks_2_embed.shape

Err..Errr. Error...Bro..Length of supplied text exceeds context length defined.Exiting the program now

SystemExit: 1

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3587: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [55]:
class Attention(nn.Module):
    def __init__(self, embed_dim, k_dim, do, device):
        super().__init__()
        self.embed_dim = embed_dim
        self.k_dim = k_dim
        self.query = nn.Linear(embed_dim, k_dim)
        self.key = nn.Linear(embed_dim, k_dim)
        self.value = nn.Linear(embed_dim, k_dim)
        self.att_do = nn.Dropout(do)
        self.device = device

    def forward(self, inputs):
        bs = inputs.shape[0]
        num_toks = inputs.shape[1]
        q = self.query(inputs)
        k = self.key(inputs)
        v = self.value(inputs)
        qk = (q@k.transpose(1, 2))/(self.k_dim**0.5)
        t1 = torch.tril(torch.ones(bs, num_toks, num_toks))
        mask = torch.where(t1 == 0, -torch.inf, 0.0)
        mask = mask.to(self.device)
        qk_m = qk + mask
        qk_m_smax = torch.softmax(qk_m, dim=-1)
        qk_m_smax_do = self.att_do(qk_m_smax)
        qkv = qk_m_smax_do@v
        return qkv

In [56]:
att_mod = Attention(embed_dim=768, k_dim=64, do=0.1, device=device)
att_mod

Attention(
  (query): Linear(in_features=768, out_features=64, bias=True)
  (key): Linear(in_features=768, out_features=64, bias=True)
  (value): Linear(in_features=768, out_features=64, bias=True)
  (att_do): Dropout(p=0.1, inplace=False)
)

In [57]:
att_mod_out = att_mod(toks_1_embed)
att_mod_out, att_mod_out.shape

(tensor([[[-0.5319,  0.4052,  0.2823,  ..., -0.4058, -0.7279,  1.0703],
          [ 0.3243,  0.4037,  0.3709,  ..., -0.6666,  0.5148,  0.0898],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.1628,  0.0562,  0.2255,  ...,  0.0436,  0.2667, -0.0176],
          [ 0.1820,  0.0776,  0.2298,  ..., -0.0915,  0.3680,  0.0294],
          [ 0.1981,  0.0363,  0.2718,  ...,  0.0047,  0.4347, -0.0966]]],
        grad_fn=<UnsafeViewBackward0>),
 torch.Size([1, 58, 64]))

In [58]:
#so things are working good

In [59]:
class Attention_Block(nn.Module):
    def __init__(self, num_heads, embed_dim, k_dim, do, device):
        super().__init__()
        self.num_heads = num_heads
        self.heads_list = [Attention(embed_dim, k_dim, do, device) for i in range(num_heads)]
        self.heads = nn.ModuleList(self.heads_list)
        self.lin_do = nn.Sequential(
            nn.Linear(embed_dim, embed_dim),
            nn.Dropout(do)
        )

    def forward(self, inputs):
        heads_list_out = [head(inputs) for head in self.heads]
        att_head = torch.cat(heads_list_out, dim=-1)
        att_head_out = self.lin_do(att_head)
        return att_head_out

In [60]:
att_blk = Attention_Block(num_heads=12, embed_dim=768, k_dim=64, do=0.1, device=device)
att_blk

Attention_Block(
  (heads): ModuleList(
    (0-11): 12 x Attention(
      (query): Linear(in_features=768, out_features=64, bias=True)
      (key): Linear(in_features=768, out_features=64, bias=True)
      (value): Linear(in_features=768, out_features=64, bias=True)
      (att_do): Dropout(p=0.1, inplace=False)
    )
  )
  (lin_do): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): Dropout(p=0.1, inplace=False)
  )
)

In [61]:
att_blk_out = att_blk(toks_1_embed)
att_blk_out, att_blk_out.shape

(tensor([[[-0.0808,  0.4469, -0.0000,  ...,  0.0997, -0.1565, -0.3163],
          [-0.2909,  0.0000,  0.1310,  ...,  0.3251,  0.1751, -0.2239],
          [ 0.2008, -0.1257,  0.0000,  ...,  0.0550, -0.1467, -0.1425],
          ...,
          [-0.0242, -0.1637,  0.2700,  ..., -0.1017, -0.0825,  0.0303],
          [-0.0595, -0.1436,  0.1996,  ..., -0.1212, -0.0000,  0.0317],
          [-0.1042, -0.1791,  0.2302,  ..., -0.0000, -0.1155,  0.0756]]],
        grad_fn=<MulBackward0>),
 torch.Size([1, 58, 768]))

In [62]:
class Transformer_Block(nn.Module):
    def __init__(self, num_heads, embed_dim, k_dim, do, device):
        super().__init__()
        self.MHA = Attention_Block(num_heads, embed_dim, k_dim, do, device)
        self.ff = nn.Sequential(
            nn.LayerNorm(embed_dim),
            nn.Linear(embed_dim, embed_dim*4),
            nn.GELU(),
            nn.Linear(embed_dim*4, embed_dim),
            nn.LayerNorm(embed_dim),
            nn.Dropout(do)
            )

    def forward(self, inputs):
        inp_start_att_block = inputs
        x = self.MHA(inputs)
        x = x + inp_start_att_block

        inp_start_ff_block = x
        x = self.ff(x)
        x = x + inp_start_ff_block
        return x

In [63]:
trans_blk = Transformer_Block(num_heads=12, embed_dim=768, k_dim=64, do=0.1, device=device)
trans_blk

Transformer_Block(
  (MHA): Attention_Block(
    (heads): ModuleList(
      (0-11): 12 x Attention(
        (query): Linear(in_features=768, out_features=64, bias=True)
        (key): Linear(in_features=768, out_features=64, bias=True)
        (value): Linear(in_features=768, out_features=64, bias=True)
        (att_do): Dropout(p=0.1, inplace=False)
      )
    )
    (lin_do): Sequential(
      (0): Linear(in_features=768, out_features=768, bias=True)
      (1): Dropout(p=0.1, inplace=False)
    )
  )
  (ff): Sequential(
    (0): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (1): Linear(in_features=768, out_features=3072, bias=True)
    (2): GELU(approximate='none')
    (3): Linear(in_features=3072, out_features=768, bias=True)
    (4): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (5): Dropout(p=0.1, inplace=False)
  )
)

In [64]:
trans_blk_out = trans_blk(toks_1_embed)
trans_blk_out, trans_blk_out.shape

(tensor([[[ 1.8007, -2.7185,  0.4421,  ..., -1.0782, -0.9855,  0.9289],
          [ 0.0046, -2.5920, -1.1998,  ...,  0.1726, -0.2326,  2.7460],
          [-1.3917,  0.1591, -0.4456,  ..., -0.0085, -0.8037, -3.2188],
          ...,
          [ 2.4030,  0.9573,  0.3795,  ...,  0.2760,  0.0877, -4.0321],
          [-0.2188, -0.3821, -0.6747,  ..., -0.0890,  0.5931,  0.4964],
          [ 1.4304, -0.1049,  2.6136,  ..., -1.4658, -2.4244, -1.7292]]],
        grad_fn=<AddBackward0>),
 torch.Size([1, 58, 768]))

In [65]:
class BroGPT(nn.Module):
    def __init__(self, num_layers, num_heads, vocab_size, embed_dim, k_dim, ctx_len, do, device):
        super().__init__()
        self.emb = Embed(vocab_size, embed_dim, ctx_len, do, device)
        self.layer_list = [Transformer_Block(num_heads, embed_dim, k_dim, do, device) for i in range(num_layers)]
        self.layers = nn.Sequential(*self.layer_list)
        self.embed_vocab = nn.Linear(embed_dim, vocab_size)

    def forward(self, inputs):
        x = self.emb(inputs)
        x = self.layers(x)
        x = self.embed_vocab(x)
        return x

In [66]:
tokenizer.len_vocab

65

In [67]:
num_layers = 6
num_heads = 4
vocab_size = tokenizer.len_vocab
embed_dim = 256
k_dim = 64
ctx_len = 1024
do = 0.1

In [68]:
brogpt = BroGPT(num_layers, num_heads, vocab_size, embed_dim, k_dim, ctx_len, do, device)
brogpt

BroGPT(
  (emb): Embed(
    (tok_layer): Embedding(65, 256)
    (pos_layer): Embedding(1024, 256)
    (norm_do): Sequential(
      (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (1): Dropout(p=0.1, inplace=False)
    )
  )
  (layers): Sequential(
    (0): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (1): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (2): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (3): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (4): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (5): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (embed_vocab): Linear(in_features=256, out_features=65, bias=True)
)

In [69]:
sum([p.numel() for p in brogpt.parameters()])

5034561

In [70]:
brogpt_out = brogpt(toks_1)
brogpt_out, brogpt_out.shape

(tensor([[[-3.6893,  1.1022,  2.8884,  ...,  4.8646,  2.8707, -0.7234],
          [-0.3063,  0.1199, -0.2190,  ..., -1.5600,  1.7158, -0.6233],
          [-1.4267,  1.8815, -2.1876,  ...,  0.2109, -0.1398, -3.0105],
          ...,
          [ 1.1674, -0.4640, -0.0942,  ...,  1.6564,  1.5582,  0.9019],
          [-0.5147,  0.7005, -0.1355,  ...,  1.2647, -2.5363,  0.3225],
          [-2.1878,  0.7145,  0.8740,  ...,  4.2228, -0.1239, -2.9479]]],
        grad_fn=<ViewBackward0>),
 torch.Size([1, 58, 65]))

In [71]:
# let us test it out again
text = "Its a nice soft morning breeze. I wish I could "
input_ids = tokenizer.encode(text, return_tensors=True)
input_ids, input_ids.shape

(tensor([21, 58, 57,  1, 39,  1, 52, 47, 41, 43,  1, 57, 53, 44, 58,  1, 51, 53,
         56, 52, 47, 52, 45,  1, 40, 56, 43, 43, 64, 43,  8,  1, 21,  1, 61, 47,
         57, 46,  1, 21,  1, 41, 53, 59, 50, 42,  1]),
 torch.Size([47]))

In [72]:
input_ids = input_ids.to(device)
brogpt.to(device)

BroGPT(
  (emb): Embed(
    (tok_layer): Embedding(65, 256)
    (pos_layer): Embedding(1024, 256)
    (norm_do): Sequential(
      (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (1): Dropout(p=0.1, inplace=False)
    )
  )
  (layers): Sequential(
    (0): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (1): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (2): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (3): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (4): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
    (5): Transformer_Block(
      (MHA): Attention_Block(
        (heads): ModuleList(
          (0-3): 4 x Attention(
            (query): Linear(in_features=256, out_features=64, bias=True)
            (key): Linear(in_features=256, out_features=64, bias=True)
            (value): Linear(in_features=256, out_features=64, bias=True)
            (att_do): Dropout(p=0.1, inplace=False)
          )
        )
        (lin_do): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Dropout(p=0.1, inplace=False)
        )
      )
      (ff): Sequential(
        (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (1): Linear(in_features=256, out_features=1024, bias=True)
        (2): GELU(approximate='none')
        (3): Linear(in_features=1024, out_features=256, bias=True)
        (4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (5): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (embed_vocab): Linear(in_features=256, out_features=65, bias=True)
)

In [73]:
out = brogpt(input_ids)
out, out.shape

(tensor([[[ 0.6338,  0.5104, -2.6060,  ...,  0.4931,  2.2608, -5.4191],
          [ 0.9668, -2.7311, -3.4659,  ..., -0.1851, -1.3860, -0.8669],
          [-0.5903,  4.3381, -1.7488,  ..., -0.5452, -1.7325,  1.4413],
          ...,
          [ 2.3041, -2.1744, -2.4656,  ..., -1.5775,  1.4606, -0.9726],
          [ 2.3398, -0.9986, -1.6803,  ..., -0.8883, -0.4601,  0.3251],
          [-0.0942,  0.3166, -1.3716,  ..., -0.4516,  1.3988, -1.6015]]],
        grad_fn=<ViewBackward0>),
 torch.Size([1, 47, 65]))

In [74]:
ids = torch.argmax(out, dim=-1)
dec = tokenizer.decode(ids, tensors=True)
print(dec)

gl WRWC.SaWaa.:kr.y3Ar
Wra
DaaWWsWlNmx..WaRlDCQ

In [75]:
len(dec)

47

In [76]:
#lets simulate this in batch format

In [77]:
inp = torch.randint(low=0, high=64, size=(4, 8))
inp = inp.to(device)

In [78]:
inp.shape

torch.Size([4, 8])

In [79]:
out = brogpt(inp)
out, out.shape

(tensor([[[ 7.0003e-01, -4.1778e+00, -2.0065e+00,  ...,  1.8798e+00,
            1.3132e+00,  1.5852e+00],
          [ 3.7273e-01, -4.7624e+00, -1.5738e+00,  ..., -6.9278e-01,
            7.6950e-02,  2.2376e-01],
          [-1.1739e+00, -1.3942e-01, -2.3091e-01,  ...,  3.4995e+00,
           -8.8729e-01,  1.6839e-01],
          ...,
          [-1.4995e+00, -1.0422e+00,  1.2169e+00,  ...,  7.3108e-01,
           -1.9771e+00, -2.5335e+00],
          [-1.8401e+00, -2.0639e+00,  2.0968e+00,  ...,  5.2496e-02,
            1.0045e+00, -7.7444e-01],
          [-1.2866e-01,  1.2120e+00, -2.0230e+00,  ..., -1.2168e+00,
           -8.1566e-01, -3.1295e-01]],

         [[-1.1308e+00, -2.2710e+00,  3.9410e-01,  ...,  9.6986e-01,
            1.2013e+00, -1.9438e+00],
          [-1.6328e+00, -2.1161e+00, -1.0897e+00,  ...,  2.4948e+00,
           -3.8506e+00,  8.0914e-01],
          [-6.8692e-02,  1.3553e-01, -1.6297e+00,  ..., -8.5210e-01,
           -8.2406e-01, -1.4418e+00],
          ...,
          [ 1.7235e+00, -1.5640e+00, -2.1361e+00,  ..., -3.1434e+00,
            2.0607e+00, -7.6224e-01],
          [-1.7252e+00, -3.6071e+00, -1.1861e+00,  ...,  6.3072e-01,
            1.2225e+00, -2.4577e-01],
          [ 8.7252e-01, -2.8376e+00, -2.3476e+00,  ...,  1.8090e+00,
            2.6296e+00,  2.4390e+00]],

         [[-1.2476e-01, -2.8967e+00, -1.0984e+00,  ..., -3.5350e+00,
           -1.1905e-02, -4.6700e+00],
          [-1.4376e-01, -3.3744e+00, -3.8357e+00,  ..., -5.5877e-01,
            2.1942e-02, -2.2426e+00],
          [-4.5424e-04,  9.0203e-01, -1.3542e+00,  ..., -7.2104e-01,
           -5.7827e-01, -1.9071e+00],
          ...,
          [-6.3982e-01, -2.6045e+00, -1.6729e+00,  ...,  5.2852e-01,
            6.6877e-02, -3.2809e+00],
          [-1.4068e+00,  1.8259e+00, -1.5685e+00,  ..., -8.1577e-01,
            1.0844e+00, -1.7720e+00],
          [-8.7371e-01, -1.2032e+00, -3.2559e+00,  ...,  8.6061e-01,
            1.1396e+00,  3.9149e-01]],

         [[-5.1673e-01, -9.1468e-01,  9.5063e-01,  ..., -9.7841e-01,
            2.2107e-01, -9.0246e-02],
          [-2.6070e+00, -6.3611e-01, -2.2972e-02,  ..., -1.0983e-01,
            2.7491e-01,  7.7302e-01],
          [-4.6606e-01,  2.9601e+00,  4.0855e-01,  ..., -6.5060e-01,
           -1.7091e+00, -2.2420e+00],
          ...,
          [ 9.0008e-01, -1.8809e+00, -1.0003e+00,  ..., -1.5153e+00,
           -2.8428e+00, -1.5975e-01],
          [-1.9005e+00,  1.4972e+00,  2.2365e+00,  ...,  1.0964e+00,
            1.7333e+00,  8.3383e-01],
          [-2.1667e+00,  8.7885e-01,  1.0856e+00,  ...,  1.7511e+00,
            1.1481e+00,  1.4493e+00]]], grad_fn=<ViewBackward0>),
 torch.Size([4, 8, 65]))

In [80]:
#so this is working in batch format

In [81]:
ids = torch.argmax(out, dim=-1)
ids, ids.shape

(tensor([[57, 45, 34, 39, 19, 40, 37, 46],
         [45, 56,  8, 48, 59, 42,  8, 21],
         [38, 17, 11, 31, 31, 38, 42, 54],
         [57, 50, 34, 61,  7, 47, 45, 35]]),
 torch.Size([4, 8]))

In [82]:
for i in ids:
    dec = tokenizer.decode(i, tensors=True)
    print(dec)

sgVaGbYh
gr.jud.I
ZE;SSZdp
slVw-igW

### Next tasks:
1) Create dataloader
2) Implement training loop and train the model(Use AWS if required)
3) Create a probabilistic decoding mechanism

In [83]:
class Bro_Shake_DS(Dataset):
    def __init__(self, vocab_text, bs=256):
        super().__init__()
        self.data = vocab_text
        self.bs = bs

    def __len__(self):
        return int((len(self.data) - self.bs)/self.bs)

    def __getitem__(self, idx):
        assert idx < len(self.data) - self.bs
        x = tokenizer.encode(self.data[idx:idx+self.bs], return_tensors=True)
        y = tokenizer.encode(self.data[idx+1:idx+1+self.bs], return_tensors=True)

        return x, y

In [84]:
len(vocab_text)

1341374

In [85]:
ds = Bro_Shake_DS(vocab_text[:65536])
ds

In [86]:
len(ds)

255

In [87]:
dl = DataLoader(ds, shuffle=True, batch_size=32)

In [88]:
len(dl)

8

In [89]:
len(dl.dataset)

255

In [90]:
n=1
for t, l in dl:
    print(f'Sample no: {n}')
    print(f'Text: {t}\n')
    print(f'Label: {l}\n')
    print(t.shape, l.shape)
    n += 1

Sample no: 1
Text: tensor([[43, 44, 53,  ...,  1, 49, 52],
        [31, 54, 43,  ...,  1, 46, 39],
        [41, 43, 43,  ..., 56, 57, 58],
        ...,
        [37, 53, 59,  ..., 57,  5, 58],
        [43,  1, 39,  ..., 60, 43, 56],
        [ 1, 58, 53,  ..., 43,  1, 58]])

Label: tensor([[44, 53, 56,  ..., 49, 52, 53],
        [54, 43, 39,  ..., 46, 39, 60],
        [43, 43, 42,  ..., 57, 58,  1],
        ...,
        [53, 59,  1,  ...,  5, 58,  1],
        [ 1, 39, 50,  ..., 43, 56, 42],
        [58, 53,  1,  ...,  1, 58, 39]])

torch.Size([32, 256]) torch.Size([32, 256])
Sample no: 2
Text: tensor([[43,  8,  0,  ...,  1, 41, 47],
        [ 8,  1, 56,  ..., 39, 61, 39],
        [64, 43, 52,  ..., 41, 43,  8],
        ...,
        [39, 56, 43,  ..., 39,  1, 60],
        [43,  1, 61,  ..., 61,  5, 58],
        [59,  1, 39,  ..., 58,  1, 39]])

Label: tensor([[ 8,  0,  0,  ..., 41, 47, 58],
        [ 1, 56, 43,  ..., 61, 39, 63],
        [43, 52, 10,  ..., 43,  8,  0],
        ...,
        [56, 43,  1,  ...,  1, 60, 43],
        [ 1, 61, 43,  ...,  5, 58,  8],
        [ 1, 39, 56,  ...,  1, 39,  1]])

torch.Size([32, 256]) torch.Size([32, 256])
Sample no: 3
Text: tensor([[56, 43,  1,  ...,  1, 60, 43],
        [50, 60, 43,  ..., 13, 50, 50],
        [ 6,  1, 63,  ..., 45, 53, 53],
        ...,
        [58, 46, 39,  ..., 45,  1, 53],
        [ 1, 58, 46,  ..., 52, 45,  1],
        [ 1, 58, 53,  ..., 41, 41, 53]])

Label: tensor([[43,  1, 39,  ..., 60, 43, 56],
        [60, 43, 42,  ..., 50, 50, 10],
        [ 1, 63, 53,  ..., 53, 53, 42],
        ...,
        [46, 39, 52,  ...,  1, 53, 52],
        [58, 46, 39,  ..., 45,  1, 53],
        [58, 53,  1,  ..., 41, 53, 59]])

torch.Size([32, 256]) torch.Size([32, 256])
Sample no: 4
Text: tensor([[47, 59, 57,  ...,  1, 15, 47],
        [56, 58, 46,  ..., 10,  0, 24],
        [42, 47, 43,  ..., 50, 49, 47],
        ...,
        [56, 57, 58,  ...,  1, 53, 61],
        [ 1, 51, 43,  ..., 50, 50,  1],
        [ 8,  0,  0,  ..., 52, 42,  1]])

Label: tensor([[59, 57,  1,  ..., 15, 47, 58],
        [58, 46, 43,  ...,  0, 24, 43],
        [47, 43,  1,  ..., 49, 47, 52],
        ...,
        [57, 58,  1,  ..., 53, 61, 52],
        [51, 43,  1,  ..., 50,  1, 46],
        [ 0,  0, 13,  ..., 42,  1, 61]])

torch.Size([32, 256]) torch.Size([32, 256])
Sample no: 5
Text: tensor([[49, 52, 53,  ..., 47, 58, 47],
        [52, 10,  0,  ...,  8,  0, 21],
        [57, 46, 12,  ..., 47, 58,  1],
        ...,
        [ 0, 13, 50,  ...,  1, 61, 43],
        [56, 43, 57,  ..., 39, 63,  2],
        [47, 43,  1,  ..., 49, 47, 52]])

Label: tensor([[52, 53, 61,  ..., 58, 47, 64],
        [10,  0, 37,  ...,  0, 21, 57],
        [46, 12,  0,  ..., 58,  1, 40],
        ...,
        [13, 50, 50,  ..., 61, 43,  5],
        [43, 57, 53,  ..., 63,  2,  0],
        [43,  1, 58,  ..., 47, 52, 45]])

torch.Size([32, 256]) torch.Size([32, 256])
Sample no: 6
Text: tensor([[43, 39, 49,  ..., 39, 60, 43],
        [47, 56, 57,  ..., 15, 47, 58],
        [56,  1, 58,  ..., 56, 43,  1],
        ...,
        [50, 50, 10,  ..., 42, 53, 52],
        [53, 59,  1,  ..., 42,  1, 41],
        [56, 43,  1,  ..., 53, 61,  5]])

Label: tensor([[39, 49,  6,  ..., 60, 43,  1],
        [56, 57, 58,  ..., 47, 58, 47],
        [ 1, 58, 53,  ..., 43,  1, 58],
        ...,
        [50, 10,  0,  ..., 53, 52, 43],
        [59,  1, 49,  ...,  1, 41, 47],
        [43,  1, 61,  ..., 61,  5, 58]])

torch.Size([32, 256]) torch.Size([32, 256])
Sample no: 7
Text: tensor([[63, 53, 59,  ..., 53, 42,  1],
        [ 1, 63, 53,  ..., 53, 53, 42],
        [57, 54, 43,  ..., 53, 56, 52],
        ...,
        [ 1, 15, 47,  ..., 52,  1, 54],
        [56, 57, 58,  ...,  0, 35, 43],
        [59, 57,  1,  ...,  0,  0, 18]])

Label: tensor([[53, 59,  1,  ..., 42,  1, 41],
        [63, 53, 59,  ..., 53, 42,  1],
        [54, 43, 39,  ..., 56, 52,  1],
        ...,
        [15, 47, 58,  ...,  1, 54, 56],
        [57, 58,  1,  ..., 35, 43,  1],
        [57,  1, 25,  ...,  0, 18, 47]])

torch.Size([32, 256]) torch.Size([32, 256])
Sample no: 8
Text: tensor([[ 1, 57, 54,  ..., 41, 53, 56],
        [52,  1, 58,  ..., 52,  5, 58],
        [10,  0, 31,  ..., 50, 50,  1],
        ...,
        [52, 43, 51,  ..., 56, 43,  1],
        [50,  1, 56,  ..., 47, 41, 58],
        [18, 47, 56,  ...,  1, 15, 47]])

Label: tensor([[57, 54, 43,  ..., 53, 56, 52],
        [ 1, 58, 53,  ...,  5, 58, 11],
        [ 0, 31, 54,  ..., 50,  1, 46],
        ...,
        [43, 51, 63,  ..., 43,  1, 39],
        [ 1, 56, 43,  ..., 41, 58, 12],
        [47, 56, 57,  ..., 15, 47, 58]])

torch.Size([31, 256]) torch.Size([31, 256])

In [91]:
t, l = t.to(device), l.to(device)
t.shape, l.shape

(torch.Size([31, 256]), torch.Size([31, 256]))

In [92]:
embed = Embed(vocab_size, embed_dim, ctx_len, do, device)
embed.to(device)

Embed(
  (tok_layer): Embedding(65, 256)
  (pos_layer): Embedding(1024, 256)
  (norm_do): Sequential(
    (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (1): Dropout(p=0.1, inplace=False)
  )
)

In [93]:
e_t = embed(t)
e_t.shape

torch.Size([31, 256, 256])

In [94]:
epochs = 1
lr = 0.0006
fn_loss = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(brogpt.parameters(), lr=lr)

In [95]:
sum([p.numel() for p in brogpt.parameters()])

5034561

In [96]:
#we will not train in cpu. we will train in gpu using sagemaker

In [97]:
# TODO: Import any packages that you might need
#importing the "King" library :P
import sagemaker
import boto3
from sagemaker.inputs import TrainingInput

#sagemaker pytorch container estimator related libraries
from sagemaker.pytorch import PyTorch
from sagemaker.pytorch import PyTorchModel


from sagemaker.estimator import Estimator
from sagemaker.model import Model
from sagemaker.predictor import Predictor

#general utility imports
import os
import glob
import pandas as pd
import numpy as np
import random

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/ec2-user/.config/sagemaker/config.yaml

In [98]:
#Sagemaker related commands
sess = sagemaker.Session()
role = sagemaker.get_execution_role()
region = sess.boto_region_name
bucket = sess.default_bucket()
sess, role, region, bucket

(<sagemaker.session.Session at 0x7f4bae9590c0>,
 'arn:aws:iam::191013407134:role/service-role/AmazonSageMaker-ExecutionRole-20250124T222384',
 'us-east-1',
 'sagemaker-us-east-1-191013407134')

In [99]:
%pwd

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/broGPT'

In [100]:
S3_LOC = f's3://{bucket}/gpt_train/dataset/'
S3_LOC

's3://sagemaker-us-east-1-191013407134/gpt_train/dataset/'

In [101]:
#!aws s3 cp ./shakes_ds.txt {S3_LOC}

In [102]:
!aws s3 ls --recursive {S3_LOC}

2025-02-26 05:00:50   27728622 gpt_train/dataset/reuters/reuters_ds.csv
2025-02-20 18:20:57    1341374 gpt_train/dataset/shakes_ds.txt

In [103]:
# let us get image uri
training_image_uri = sagemaker.image_uris.retrieve(
    framework='pytorch', 
    version='2.0',
    instance_type='ml.g4dn.xlarge',
    region=region,
    py_version='py310',
    image_scope='training'
)
print(training_image_uri)

763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.0-gpu-py310

In [104]:
train_uri = f'{S3_LOC}'
train_uri

's3://sagemaker-us-east-1-191013407134/gpt_train/dataset/'

In [105]:
s3_inp_tr = TrainingInput(
    s3_data = train_uri
    )
s3_inp_tr

In [106]:
data_channels = {
    'train': s3_inp_tr
    }
data_channels

{'train': <sagemaker.inputs.TrainingInput at 0x7f4be02bd600>}

In [107]:
objective_metric_name = "average training loss"
objective_type = "Minimize"
metric_definitions = [{"Name": "average training loss", "Regex": "Average loss: ([0-9\\.]+)"},
                      {"Name": "Perplexity", "Regex": "Perplexity: ([0-9\\.]+)"}]
objective_metric_name, objective_type, metric_definitions

('average training loss',
 'Minimize',
 [{'Name': 'average training loss', 'Regex': 'Average loss: ([0-9\\.]+)'},
  {'Name': 'Perplexity', 'Regex': 'Perplexity: ([0-9\\.]+)'}])

In [108]:
ic=1
i_type = "ml.g4dn.xlarge"
ic, i_type

(1, 'ml.g4dn.xlarge')

In [109]:
%pwd

'/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/broGPT'

In [110]:
hparams = {
    'bs': 128,
    'lrate': 0.0006,
    'num_epochs': 100,
    'do': 0.1,
    'block_size': 256,
    'environ': 'aws',
    'num_layers': 6,
    'num_heads': 4,
    'embed_dim': 256,
    'k_dim': 64,
    'ctx_len': 256
}
hparams

{'bs': 128,
 'lrate': 0.0006,
 'num_epochs': 100,
 'do': 0.1,
 'block_size': 256,
 'environ': 'aws',
 'num_layers': 6,
 'num_heads': 4,
 'embed_dim': 256,
 'k_dim': 64,
 'ctx_len': 256}

In [111]:
est_brogpt = Estimator(
    image_uri=training_image_uri,
    role=role,
    source_dir='./scripts',
    entry_point='train.py',
    instance_count=ic,
    instance_type=i_type,
    base_job_name='brogpt-train',
    hyperparameters=hparams,
    metric_definitions=metric_definitions,
    objective_type=objective_type,
    objective_metric_name=objective_metric_name
)

est_brogpt.fit(
    inputs=data_channels,
    wait=True
)

INFO:sagemaker:Creating training-job with name: brogpt-train-2026-05-21-03-40-03-927

2026-05-21 03:40:06 Starting - Starting the training job...
2026-05-21 03:40:20 Starting - Preparing the instances for training...
2026-05-21 03:40:49 Downloading - Downloading input data...
2026-05-21 03:41:20 Downloading - Downloading the training image.........
2026-05-21 03:43:06 Training - Training image download completed. Training in progress..bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2026-05-21 03:43:08,778 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2026-05-21 03:43:08,801 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-05-21 03:43:08,812 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2026-05-21 03:43:08,819 sagemaker_pytorch_container.training INFO     Invoking user training script.
2026-05-21 03:43:10,825 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-05-21 03:43:10,860 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-05-21 03:43:10,895 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-05-21 03:43:10,910 sagemaker-training-toolkit INFO     Invoking user script

Training Env:

{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.g4dn.xlarge",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "block_size": 256,
        "bs": 128,
        "ctx_len": 256,
        "do": 0.1,
        "embed_dim": 256,
        "environ": "aws",
        "k_dim": 64,
        "lrate": 0.0006,
        "num_epochs": 100,
        "num_heads": 4,
        "num_layers": 6
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "train": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "instance_groups": [
        "homogeneousCluster"
    ],
    "instance_groups_dict": {
        "homogeneousCluster": {
            "instance_group_name": "homogeneousCluster",
            "instance_type": "ml.g4dn.xlarge",
            "hosts": [
                "algo-1"
            ]
        }
    },
    "is_hetero": false,
    "is_master": true,
    "is_modelparallel_enabled": null,
    "is_smddpmprun_installed": false,
    "is_smddprun_installed": true,
    "job_name": "brogpt-train-2026-05-21-03-40-03-927",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://sagemaker-us-east-1-191013407134/brogpt-train-2026-05-21-03-40-03-927/source/sourcedir.tar.gz",
    "module_name": "train",
    "network_interface_name": "eth0",
    "num_cpus": 4,
    "num_gpus": 1,
    "num_neurons": 0,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "current_instance_type": "ml.g4dn.xlarge",
        "current_group_name": "homogeneousCluster",
        "hosts": [
            "algo-1"
        ],
        "instance_groups": [
            {
                "instance_group_name": "homogeneousCluster",
                "instance_type": "ml.g4dn.xlarge",
                "hosts": [
                    "algo-1"
                ]
            }
        ],
        "network_interface_name": "eth0",
        "topology": null
    },
    "user_entry_point": "train.py"
}

Environment variables:

SM_HOSTS=["algo-1"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={"block_size":256,"bs":128,"ctx_len":256,"do":0.1,"embed_dim":256,"environ":"aws","k_dim":64,"lrate":0.0006,"num_epochs":100,"num_heads":4,"num_layers":6}
SM_USER_ENTRY_POINT=train.py
SM_FRAMEWORK_PARAMS={}
SM_RESOURCE_CONFIG={"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.g4dn.xlarge","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.g4dn.xlarge"}],"network_interface_name":"eth0","topology":null}
SM_INPUT_DATA_CONFIG={"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["train"]
SM_CURRENT_HOST=algo-1
SM_CURRENT_INSTANCE_TYPE=ml.g4dn.xlarge
SM_CURRENT_INSTANCE_GROUP=homogeneousCluster
SM_CURRENT_INSTANCE_GROUP_HOSTS=["algo-1"]
SM_INSTANCE_GROUPS=["homogeneousCluster"]
SM_INSTANCE_GROUPS_DICT={"homogeneousCluster":{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.g4dn.xlarge"}}
SM_DISTRIBUTION_INSTANCE_GROUPS=[]
SM_IS_HETERO=false
SM_MODULE_NAME=train
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_pytorch_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=4
SM_NUM_GPUS=1
SM_NUM_NEURONS=0
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://sagemaker-us-east-1-191013407134/brogpt-train-2026-05-21-03-40-03-927/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{"train":"/opt/ml/input/data/train"},"current_host":"algo-1","current_instance_group":"homogeneousCluster","current_instance_group_hosts":["algo-1"],"current_instance_type":"ml.g4dn.xlarge","distribution_hosts":[],"distribution_instance_groups":[],"framework_module":"sagemaker_pytorch_container.training:main","hosts":["algo-1"],"hyperparameters":{"block_size":256,"bs":128,"ctx_len":256,"do":0.1,"embed_dim":256,"environ":"aws","k_dim":64,"lrate":0.0006,"num_epochs":100,"num_heads":4,"num_layers":6},"input_config_dir":"/opt/ml/input/config","input_data_config":{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","instance_groups":["homogeneousCluster"],"instance_groups_dict":{"homogeneousCluster":{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.g4dn.xlarge"}},"is_hetero":false,"is_master":true,"is_modelparallel_enabled":null,"is_smddpmprun_installed":false,"is_smddprun_installed":true,"job_name":"brogpt-train-2026-05-21-03-40-03-927","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-east-1-191013407134/brogpt-train-2026-05-21-03-40-03-927/source/sourcedir.tar.gz","module_name":"train","network_interface_name":"eth0","num_cpus":4,"num_gpus":1,"num_neurons":0,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.g4dn.xlarge","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.g4dn.xlarge"}],"network_interface_name":"eth0","topology":null},"user_entry_point":"train.py"}
SM_USER_ARGS=["--block_size","256","--bs","128","--ctx_len","256","--do","0.1","--embed_dim","256","--environ","aws","--k_dim","64","--lrate","0.0006","--num_epochs","100","--num_heads","4","--num_layers","6"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TRAIN=/opt/ml/input/data/train
SM_HP_BLOCK_SIZE=256
SM_HP_BS=128
SM_HP_CTX_LEN=256
SM_HP_DO=0.1
SM_HP_EMBED_DIM=256
SM_HP_ENVIRON=aws
SM_HP_K_DIM=64
SM_HP_LRATE=0.0006
SM_HP_NUM_EPOCHS=100
SM_HP_NUM_HEADS=4
SM_HP_NUM_LAYERS=6
PYTHONPATH=/opt/ml/code:/opt/conda/bin:/opt/conda/lib/python310.zip:/opt/conda/lib/python3.10:/opt/conda/lib/python3.10/lib-dynload:/opt/conda/lib/python3.10/site-packages

Invoking script with the following command:

/opt/conda/bin/python3.10 train.py --block_size 256 --bs 128 --ctx_len 256 --do 0.1 --embed_dim 256 --environ aws --k_dim 64 --lrate 0.0006 --num_epochs 100 --num_heads 4 --num_layers 6


2026-05-21 03:43:10,948 sagemaker-training-toolkit INFO     Exceptions not imported for SageMaker TF as Tensorflow is not installed.
Processing arguments now
Starting training job with parameters: Namespace(bs=128, lrate=0.0006, num_epochs=100, do=0.1, block_size=256, environ='aws', num_layers=6, num_heads=4, embed_dim=256, k_dim=64, ctx_len=256)
Parsed arguments are Namespace(bs=128, lrate=0.0006, num_epochs=100, do=0.1, block_size=256, environ='aws', num_layers=6, num_heads=4, embed_dim=256, k_dim=64, ctx_len=256)
Invoking main function with parsed arguments
data_path is /opt/ml/input/data/
batch_size is 128
Training Device is cuda
STEP 1: Creating training dataloaders...
STEP 1 completed successfully...
STEP 2: Initializing and loading model for training
STEP 2 completed successfully
STEP 3: Initiating model training
Model will be trained for 100 Epochs
There are 4837953 parameters in our model
Step: 0, Loss: 5.456735610961914
Step: 1, Loss: 8.376721382141113
Step: 2, Loss: 8.483153343200684
Step: 3, Loss: 8.17534065246582
Step: 4, Loss: 6.095426082611084
Step: 5, Loss: 6.057554244995117
Step: 6, Loss: 5.758411407470703
Step: 7, Loss: 5.776252746582031
Step: 8, Loss: 5.055408477783203
Step: 9, Loss: 4.282759189605713
Step: 10, Loss: 4.095144271850586
Step: 11, Loss: 3.8365275859832764
Step: 12, Loss: 3.7690813541412354
Step: 13, Loss: 3.6084489822387695
Step: 14, Loss: 3.4938509464263916
Step: 15, Loss: 3.304133892059326
Step: 16, Loss: 3.2016496658325195
Step: 17, Loss: 3.1648941040039062
Step: 18, Loss: 3.1571686267852783
Step: 19, Loss: 3.136594533920288
Step: 20, Loss: 3.1114261150360107
Step: 21, Loss: 3.088226318359375
Step: 22, Loss: 3.095939874649048
Step: 23, Loss: 3.0074703693389893
Step: 24, Loss: 2.970937967300415
Step: 25, Loss: 2.9531784057617188
Step: 26, Loss: 2.9563536643981934
Step: 27, Loss: 2.930523633956909
Step: 28, Loss: 2.903733730316162
Step: 29, Loss: 2.8933980464935303
Step: 30, Loss: 2.872309684753418
Step: 31, Loss: 2.8741507530212402
Step: 32, Loss: 2.879549503326416
Step: 33, Loss: 2.8344578742980957
Step: 34, Loss: 2.8363535404205322
Step: 35, Loss: 2.827631950378418
Step: 36, Loss: 2.7968697547912598
Step: 37, Loss: 2.8093979358673096
Step: 38, Loss: 2.7940673828125
Step: 39, Loss: 2.796478748321533
Step: 40, Loss: 2.7910139560699463
Epoch: 0 -- Average loss: 0.030414037096359293
Epoch: 0 -- Perplexity: 1.0308812686925952
Step: 0, Loss: 2.7763402462005615
Step: 1, Loss: 2.768421173095703
Step: 2, Loss: 2.7801737785339355
Step: 3, Loss: 2.7494826316833496
Step: 4, Loss: 2.723008394241333
Step: 5, Loss: 2.7782881259918213
Step: 6, Loss: 2.735297441482544
Step: 7, Loss: 2.724400758743286
Step: 8, Loss: 2.730497121810913
Step: 9, Loss: 2.7038135528564453
Step: 10, Loss: 2.7177841663360596
Step: 11, Loss: 2.704926013946533
Step: 12, Loss: 2.7040672302246094
Step: 13, Loss: 2.704231023788452
Step: 14, Loss: 2.7162554264068604
Step: 15, Loss: 2.7047317028045654
Step: 16, Loss: 2.6912307739257812
Step: 17, Loss: 2.6825265884399414
Step: 18, Loss: 2.7022688388824463
Step: 19, Loss: 2.67880916595459
Step: 20, Loss: 2.6713852882385254
Step: 21, Loss: 2.690208673477173
Step: 22, Loss: 2.663245677947998
Step: 23, Loss: 2.67579984664917
Step: 24, Loss: 2.6657536029815674
Step: 25, Loss: 2.6667017936706543
Step: 26, Loss: 2.665435552597046
Step: 27, Loss: 2.654642105102539
Step: 28, Loss: 2.6573429107666016
Step: 29, Loss: 2.6523022651672363
Step: 30, Loss: 2.654878616333008
Step: 31, Loss: 2.647819757461548
Step: 32, Loss: 2.653438091278076
Step: 33, Loss: 2.647611379623413
Step: 34, Loss: 2.6383838653564453
Step: 35, Loss: 2.6588962078094482
Step: 36, Loss: 2.640881299972534
Step: 37, Loss: 2.6473228931427
Step: 38, Loss: 2.6215286254882812
Step: 39, Loss: 2.6389787197113037
Step: 40, Loss: 2.6262500286102295
Epoch: 1 -- Average loss: 0.021041497013504246
Epoch: 1 -- Perplexity: 1.0212644301820817
Step: 0, Loss: 2.60659122467041
Step: 1, Loss: 2.6251444816589355
Step: 2, Loss: 2.618892192840576
Step: 3, Loss: 2.639040470123291
Step: 4, Loss: 2.6254515647888184
Step: 5, Loss: 2.6129937171936035
Step: 6, Loss: 2.623325824737549
Step: 7, Loss: 2.610628604888916
Step: 8, Loss: 2.6162755489349365
Step: 9, Loss: 2.6122822761535645
Step: 10, Loss: 2.6139981746673584
Step: 11, Loss: 2.611527442932129
Step: 12, Loss: 2.608278751373291
Step: 13, Loss: 2.608602285385132
Step: 14, Loss: 2.606975793838501
Step: 15, Loss: 2.615739583969116
Step: 16, Loss: 2.609043598175049
Step: 17, Loss: 2.6018195152282715
Step: 18, Loss: 2.603325843811035
Step: 19, Loss: 2.6091856956481934
Step: 20, Loss: 2.6159839630126953
Step: 21, Loss: 2.601975917816162
Step: 22, Loss: 2.6052908897399902
Step: 23, Loss: 2.5952184200286865
Step: 24, Loss: 2.6044647693634033
Step: 25, Loss: 2.605384349822998
Step: 26, Loss: 2.601667881011963
Step: 27, Loss: 2.6030783653259277
Step: 28, Loss: 2.5832507610321045
Step: 29, Loss: 2.578793525695801
Step: 30, Loss: 2.583918333053589
Step: 31, Loss: 2.5905637741088867
Step: 32, Loss: 2.5794920921325684
Step: 33, Loss: 2.5714197158813477
Step: 34, Loss: 2.5760490894317627
Step: 35, Loss: 2.583416700363159
Step: 36, Loss: 2.5791738033294678
Step: 37, Loss: 2.5823793411254883
Step: 38, Loss: 2.5780036449432373
Step: 39, Loss: 2.575953722000122
Step: 40, Loss: 2.5967068672180176
Epoch: 2 -- Average loss: 0.02036489280592899
Epoch: 2 -- Perplexity: 1.0205736720828438
Step: 0, Loss: 2.5747671127319336
Step: 1, Loss: 2.5862162113189697
Step: 2, Loss: 2.5745866298675537
Step: 3, Loss: 2.5771613121032715
Step: 4, Loss: 2.5791358947753906
Step: 5, Loss: 2.5587804317474365
Step: 6, Loss: 2.5660719871520996
Step: 7, Loss: 2.571507692337036
Step: 8, Loss: 2.5688650608062744
Step: 9, Loss: 2.5681252479553223
Step: 10, Loss: 2.564749240875244
Step: 11, Loss: 2.5705349445343018
Step: 12, Loss: 2.5549728870391846
Step: 13, Loss: 2.5498263835906982
Step: 14, Loss: 2.5760340690612793
Step: 15, Loss: 2.563847541809082
Step: 16, Loss: 2.562293767929077
Step: 17, Loss: 2.553443193435669
Step: 18, Loss: 2.5689642429351807
Step: 19, Loss: 2.5520455837249756
Step: 20, Loss: 2.5687572956085205
Step: 21, Loss: 2.575770139694214
Step: 22, Loss: 2.557457447052002
Step: 23, Loss: 2.5510566234588623
Step: 24, Loss: 2.556043863296509
Step: 25, Loss: 2.554530620574951
Step: 26, Loss: 2.5524003505706787
Step: 27, Loss: 2.5566623210906982
Step: 28, Loss: 2.561082601547241
Step: 29, Loss: 2.548356056213379
Step: 30, Loss: 2.554287910461426
Step: 31, Loss: 2.553696632385254
Step: 32, Loss: 2.5442354679107666
Step: 33, Loss: 2.5463244915008545
Step: 34, Loss: 2.5521061420440674
Step: 35, Loss: 2.5570645332336426
Step: 36, Loss: 2.5459861755371094
Step: 37, Loss: 2.5303001403808594
Step: 38, Loss: 2.560554027557373
Step: 39, Loss: 2.548380136489868
Step: 40, Loss: 2.541454315185547
Epoch: 3 -- Average loss: 0.020037884064055708
Epoch: 3 -- Perplexity: 1.020239990131778
Step: 0, Loss: 2.5360636711120605
Step: 1, Loss: 2.5402932167053223
Step: 2, Loss: 2.539159059524536
Step: 3, Loss: 2.5348973274230957
Step: 4, Loss: 2.54233717918396
Step: 5, Loss: 2.5321691036224365
Step: 6, Loss: 2.542257785797119
Step: 7, Loss: 2.54375958442688
Step: 8, Loss: 2.5233309268951416
Step: 9, Loss: 2.552938222885132
Step: 10, Loss: 2.5407023429870605
Step: 11, Loss: 2.526837110519409
Step: 12, Loss: 2.5371339321136475
Step: 13, Loss: 2.537076473236084
Step: 14, Loss: 2.5221707820892334
Step: 15, Loss: 2.526700019836426
Step: 16, Loss: 2.534762144088745
Step: 17, Loss: 2.5347256660461426
Step: 18, Loss: 2.535855531692505
Step: 19, Loss: 2.5342655181884766
Step: 20, Loss: 2.5235376358032227
Step: 21, Loss: 2.5277976989746094
Step: 22, Loss: 2.518195152282715
Step: 23, Loss: 2.5352041721343994
Step: 24, Loss: 2.5400021076202393
Step: 25, Loss: 2.515080451965332
Step: 26, Loss: 2.5237655639648438
Step: 27, Loss: 2.5225963592529297
Step: 28, Loss: 2.538964033126831
Step: 29, Loss: 2.5360512733459473
Step: 30, Loss: 2.522789239883423
Step: 31, Loss: 2.519277572631836
Step: 32, Loss: 2.5301644802093506
Step: 33, Loss: 2.525688409805298
Step: 34, Loss: 2.5160727500915527
Step: 35, Loss: 2.525815010070801
Step: 36, Loss: 2.520733118057251
Step: 37, Loss: 2.532531976699829
Step: 38, Loss: 2.5110459327697754
Step: 39, Loss: 2.537299633026123
Step: 40, Loss: 2.5166099071502686
Epoch: 4 -- Average loss: 0.01980844942291714
Epoch: 4 -- Perplexity: 1.0200059385865599
Step: 0, Loss: 2.5181162357330322
Step: 1, Loss: 2.532200813293457
Step: 2, Loss: 2.517159938812256
Step: 3, Loss: 2.523247003555298
Step: 4, Loss: 2.518359422683716
Step: 5, Loss: 2.496846914291382
Step: 6, Loss: 2.5158231258392334
Step: 7, Loss: 2.5091559886932373
Step: 8, Loss: 2.5124731063842773
Step: 9, Loss: 2.51658034324646
Step: 10, Loss: 2.506957769393921
Step: 11, Loss: 2.504707098007202
Step: 12, Loss: 2.5139243602752686
Step: 13, Loss: 2.51731538772583
Step: 14, Loss: 2.5216662883758545
Step: 15, Loss: 2.524121046066284
Step: 16, Loss: 2.510641574859619
Step: 17, Loss: 2.5077104568481445
Step: 18, Loss: 2.513359308242798
Step: 19, Loss: 2.504561185836792
Step: 20, Loss: 2.4994428157806396
Step: 21, Loss: 2.488318681716919
Step: 22, Loss: 2.499849796295166
Step: 23, Loss: 2.5045571327209473
Step: 24, Loss: 2.498783588409424
Step: 25, Loss: 2.4980759620666504
Step: 26, Loss: 2.502948760986328
Step: 27, Loss: 2.5147085189819336
Step: 28, Loss: 2.4968795776367188
Step: 29, Loss: 2.5005242824554443
Step: 30, Loss: 2.51237416267395
Step: 31, Loss: 2.504939317703247
Step: 32, Loss: 2.507460594177246
Step: 33, Loss: 2.4930951595306396
Step: 34, Loss: 2.5170745849609375
Step: 35, Loss: 2.491173267364502
Step: 36, Loss: 2.49462890625
Step: 37, Loss: 2.4965896606445312
Step: 38, Loss: 2.4907946586608887
Step: 39, Loss: 2.4983270168304443
Step: 40, Loss: 2.498711109161377
Epoch: 5 -- Average loss: 0.019624701207172968
Epoch: 5 -- Perplexity: 1.0198185315336792
Step: 0, Loss: 2.4923095703125
Step: 1, Loss: 2.496307134628296
Step: 2, Loss: 2.4871249198913574
Step: 3, Loss: 2.4931929111480713
Step: 4, Loss: 2.481275796890259
Step: 5, Loss: 2.4904937744140625
Step: 6, Loss: 2.488450288772583
Step: 7, Loss: 2.482318639755249
Step: 8, Loss: 2.491213798522949
Step: 9, Loss: 2.4962172508239746
Step: 10, Loss: 2.50161075592041
Step: 11, Loss: 2.488076686859131
Step: 12, Loss: 2.4952898025512695
Step: 13, Loss: 2.489914894104004
Step: 14, Loss: 2.4886183738708496
Step: 15, Loss: 2.4903202056884766
Step: 16, Loss: 2.473452568054199
Step: 17, Loss: 2.4927287101745605
Step: 18, Loss: 2.499880075454712
Step: 19, Loss: 2.4820168018341064
Step: 20, Loss: 2.480478048324585
Step: 21, Loss: 2.471421003341675
Step: 22, Loss: 2.481508731842041
Step: 23, Loss: 2.485269546508789
Step: 24, Loss: 2.4798905849456787
Step: 25, Loss: 2.4687623977661133
Step: 26, Loss: 2.470977306365967
Step: 27, Loss: 2.4849822521209717
Step: 28, Loss: 2.465325117111206
Step: 29, Loss: 2.489593267440796
Step: 30, Loss: 2.487122058868408
Step: 31, Loss: 2.484175205230713
Step: 32, Loss: 2.4758074283599854
Step: 33, Loss: 2.485455274581909
Step: 34, Loss: 2.471069812774658
Step: 35, Loss: 2.47465181350708
Step: 36, Loss: 2.4829440116882324
Step: 37, Loss: 2.4779744148254395
Step: 38, Loss: 2.4818718433380127
Step: 39, Loss: 2.471405029296875
Step: 40, Loss: 2.4824440479278564
Epoch: 6 -- Average loss: 0.019445197051515466
Epoch: 6 -- Perplexity: 1.019635486298434
Step: 0, Loss: 2.4676730632781982
Step: 1, Loss: 2.47501277923584
Step: 2, Loss: 2.4822704792022705
Step: 3, Loss: 2.4763665199279785
Step: 4, Loss: 2.471545457839966
Step: 5, Loss: 2.46323561668396
Step: 6, Loss: 2.473784923553467
Step: 7, Loss: 2.4747936725616455
Step: 8, Loss: 2.4690234661102295

In [113]:
est_brogpt.model_data

's3://sagemaker-us-east-1-191013407134/brogpt-train-2026-05-21-03-40-03-927/output/model.tar.gz'

In [114]:
est_brogpt.latest_training_job.describe()['FinalMetricDataList']

[{'MetricName': 'Perplexity',
  'Value': 1.0083860158920288,
  'Timestamp': datetime.datetime(2026, 5, 21, 5, 18, 1, tzinfo=tzlocal())},
 {'MetricName': 'average training loss',
  'Value': 0.008351005613803864,
  'Timestamp': datetime.datetime(2026, 5, 21, 5, 18, 1, tzinfo=tzlocal())}]

In [115]:
CKPT_DIR = './model_ckpts'

In [116]:
os.makedirs(CKPT_DIR, exist_ok=True)

In [117]:
!aws s3 cp {est_brogpt.model_data} {CKPT_DIR}/

download: s3://sagemaker-us-east-1-191013407134/brogpt-train-2026-05-21-03-40-03-927/output/model.tar.gz to model_ckpts/model.tar.gz

In [118]:
!aws s3 ls {est_brogpt.model_data}

2026-05-21 05:18:19   53148638 model.tar.gz

In [119]:
%cd {CKPT_DIR}

/home/ec2-user/SageMaker/CURRENTFOCUS/LLMS_transformers_WIP/LLMfromScratch/broGPT/model_ckpts

In [120]:
%pwd
!ls -ltrh

total 2.0G
-rw-r--r-- 1 ec2-user ec2-user  56M Feb 23  2025 ckpt_Epoch_100_Prplxty_1.0083447968191865.pt
-rw-rw-r-- 1 ec2-user ec2-user  51M Feb 23  2025 model_old.tar.gz
-rw-r--r-- 1 ec2-user ec2-user  56M Apr 25 06:31 ckpt_Epoch_50_Prplxty_1.010824581177966.pt
-rw-r--r-- 1 ec2-user ec2-user 351M Apr 25 07:18 ckpt_Epoch_40_Prplxty_1.0619401693860067.pt
-rw-r--r-- 1 ec2-user ec2-user 1.4G Apr 25 08:13 ckpt_Epoch_20_Prplxty_1.0012009449952726.pt
-rw-rw-r-- 1 ec2-user ec2-user  51M May 21 05:18 model.tar.gz

In [121]:
!gunzip -dc model.tar.gz |tar xvf -

tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
ckpt_Epoch_100_Prplxty_1.0083859726932272.pt

In [122]:
!ls -ltrh

total 2.0G
-rw-r--r-- 1 ec2-user ec2-user  56M Feb 23  2025 ckpt_Epoch_100_Prplxty_1.0083447968191865.pt
-rw-rw-r-- 1 ec2-user ec2-user  51M Feb 23  2025 model_old.tar.gz
-rw-r--r-- 1 ec2-user ec2-user  56M Apr 25 06:31 ckpt_Epoch_50_Prplxty_1.010824581177966.pt
-rw-r--r-- 1 ec2-user ec2-user 351M Apr 25 07:18 ckpt_Epoch_40_Prplxty_1.0619401693860067.pt
-rw-r--r-- 1 ec2-user ec2-user 1.4G Apr 25 08:13 ckpt_Epoch_20_Prplxty_1.0012009449952726.pt
-rw-r--r-- 1 ec2-user ec2-user  56M May 21 05:18 ckpt_Epoch_100_Prplxty_1.0083859726932272.pt
-rw-rw-r-- 1 ec2-user ec2-user  51M May 21 05:18 model.tar.gz

In [123]:
hparams

{'bs': 128,
 'lrate': 0.0006,
 'num_epochs': 100,
 'do': 0.1,
 'block_size': 256,
 'environ': 'aws',
 'num_layers': 6,
 'num_heads': 4,
 'embed_dim': 256,
 'k_dim': 64,
 'ctx_len': 256}

In [124]:
device

'cpu'

BroGPT(num_layers, num_heads, vocab_size, embed_dim, k_dim, ctx_len, do, device)

In [125]:
model = BroGPT(6, 4, 65, 256, 64, 256, 0.1, device)

In [126]:
with open("./ckpt_Epoch_100_Prplxty_1.0083859726932272.pt", 'rb') as f:
    checkpoint = torch.load(f, map_location=torch.device(device))
    print(f'checkpoint keys: {checkpoint.keys()}')
    model.load_state_dict(checkpoint['model_state_dict'])
    print("completed success")

checkpoint keys: dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'loss', 'device'])
completed success

In [127]:
print(vocab_text[1024:1224])

u proceed especially against Caius Marcius?

All:
Against him first: he's a very dog to the commonalty.

Second Citizen:
Consider you what services he has done for his country?

First Citizen:
Very we

In [128]:
def generate_toks(model, tokenizer, device, prompt, num_toks):
    orig_prompt = prompt
    model.to(device)
    model.eval()
    input_ids = tokenizer.encode(prompt, return_tensors=True)
    for i in range(num_toks):
        input_ids = input_ids.to(device)
        with torch.no_grad():
            out = model(input_ids)
        ids = torch.argmax(out, dim=-1)
        gen_tok = ids[:,-1]
        input_ids = torch.hstack([input_ids, gen_tok])
    dec = tokenizer.decode(input_ids, tensors=True)
    print(f"Original Prompt: {orig_prompt}")
    print("########################################################")
    print("########################################################")
    print(f"Generated Prompt: {dec}")

In [129]:
prompt = vocab_text[1024:1224]
print(prompt)

u proceed especially against Caius Marcius?

All:
Against him first: he's a very dog to the commonalty.

Second Citizen:
Consider you what services he has done for his country?

First Citizen:
Very we

In [130]:
generate_toks(model, tokenizer, device, prompt, num_toks=57)

Original Prompt: u proceed especially against Caius Marcius?

All:
Against him first: he's a very dog to the commonalty.

Second Citizen:
Consider you what services he has done for his country?

First Citizen:
Very we
########################################################
########################################################
Generated Prompt: u proceed especially against Caius Marcius?

All:
Against him first: he's a very dog to the commonalty.

Second Citizen:
Consider you what services he has done for his country?

First Citizen:
Very well: they are not so be conduct to the crown.

Third Citiz

In [141]:
prompt = vocab_text[1323:1400]
print(prompt)

Second Citizen:
Nay, but speak not maliciously.

First Citizen:
I say unto yo

In [145]:
generate_toks(model, tokenizer, device, prompt, num_toks=178)

Original Prompt: Second Citizen:
Nay, but speak not maliciously.

First Citizen:
I say unto yo
########################################################
########################################################
Generated Prompt: Second Citizen:
Nay, but speak not maliciously.

First Citizen:
I say unto your grace is a man to make of me.

CORIOLANUS:
I would they are a man thou art a man.

Second Citizen:
Ay, ay, ay, if you come to the commonwealth.

Third Citizen:
Now, I will not